### ISSUE TITLE
RFE - Argument for switch/port group unused uplink

### ISSUE THREAD

**Issue by rfitzhugh** [hashicorp/terraform-provider-vsphere#1007]
### Terraform Version

Terraform v0.12.8

### vSphere Provider Version

provider.vsphere v1.16.2

### Affected Resource(s)

Please list the resources as a list, for example:

* `vsphere_distributed_virtual_switch`
* `vsphere_distributed_port_group`
* `vsphere_host_virtual_switch`
* `vsphere_host_port_group`

### Terraform Configuration Files

Currently, the supported arguments for uplink configuration are active or standby. Resembling something like the following:

```
resource "vsphere_distributed_port_group" "pg-iscsi-b" {
  name                            = "Storage_iSCSI_B"
  vlan_id                         = 101
  distributed_virtual_switch_uuid = vsphere_distributed_virtual_switch.dvs.id

  active_uplinks  = ["Uplink 2"]
  standby_uplinks = ["Uplink 1"]
}
```

The other resource types have similar arguments for uplink configuration. 

### Expected Behavior
It is not uncommon in multi-path software iSCSI configurations to use port binding, requiring the use of unused uplinks. 

![Screen Shot 2020-03-22 at 8 26 12 PM](https://user-images.githubusercontent.com/29388592/77278035-823c7980-6c7b-11ea-9a1c-bf810ced5c68.png)

The argument could resemble something like the following to allow override (from what is inherited from the distributed switch) behavior at the port group:

```
resource "vsphere_distributed_port_group" "pg-iscsi-b" {
  name                            = "Storage_iSCSI_B-2"
  vlan_id                         = 101
  distributed_virtual_switch_uuid = vsphere_distributed_virtual_switch.dvs.id

  active_uplinks  = ["Uplink 2"]
  unused_uplinks = ["Uplink 1"]
}
```

Similarly, but secondarily, this argument should also be allowed on the distributed switch and host switch resource. 

### Actual Behavior

Currently these arguments do not exist.

**Comment by bill-rich** [comment]
This seems like a reasonable ask. I'll need to look a little more into if unused ports are configured any differently on the API side to be able to tell for sure what this would entail.

**Comment by codeopen1** [comment]
The `VMwareUplinkPortOrderPolicy` Data Object in the API only has arrays of `activeUplinkPort` and `standbyUplinkPort`. It seems like you set an uplink to unused by leaving it out of these lists.
So in the Terraform, to ensure an uplink is unused, you specify the `active_uplinks` and `standby_uplinks` lists and leave out the names of the unused uplinks. There could be an explicit unused_uplinks argument but there would have to be extra logic to make it work with the API that only allows you to pass it the active and standby lists.

**Comment by tenthirtyam** [comment]
As @codeopen1 mentions above, the method to achieve this configuration would be similar to the following:

```hcl
data "vsphere_distributed_virtual_switch" "vds" {
  depends_on = [
    vsphere_distributed_virtual_switch.vds
  ]
  name          = "foo"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_distributed_virtual_switch" "vds" {
  name            = "foo"
  description     = "foo"
  datacenter_id   = data.vsphere_datacenter.datacenter.id
  version         = "7.0.2"
  teaming_policy  = "loadbalance_srcid"
  uplinks         = ["uplink1", "uplink2", "uplink3", "uplink4"]
  active_uplinks  = ["uplink1", "uplink2"]
  standby_uplinks = ["uplink3", "uplink4"]
}

resource "vsphere_distributed_port_group" "pg-iscsi-b" {
  name                            = "Storage_iSCSI_B-2"
  vlan_id                         = 101
  distributed_virtual_switch_uuid = data.vsphere_distributed_virtual_switch.vds.id
  active_uplinks                  = ["uplink2"]
}
```

Which would result in the following:

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/7771363/139498677-b1379e6f-7f23-4ac8-bbd1-687f628d0943.png">

I suggest that the documentation for the the resources should be updated to reflect the logic instead of introducing an explicit `unused_uplinks` argument.

Thoughts @rfitzhugh?

Ryan

**Comment by rfitzhugh** [comment]
Hey @tenthirtyam, thanks for reaching out. I filed this on behalf of my former team; unfortunately, I haven't used VMware products in years and have no way of testing at this point. Thus, closing the issue.

**Comment by tenthirtyam** [comment]
Thanks for the update, Rebecca! Good to hear from you!

Ryan
