### ISSUE TITLE
distributed port_group resource does not support "trunk"

### ISSUE THREAD

**Issue by nvpnathan** [hashicorp/terraform-provider-vsphere#1009]
### Terraform Version                                                                                                                           
Terraform v0.12.23

### vSphere Provider Version
+ provider.vsphere v1.16.1

### Affected Resource(s)
- `vsphere_distributed_port_group`

Please list the resources as a list, for example:
- `vsphere_distributed_port_group`

### Terraform Configuration Files

```hcl
resource "vsphere_distributed_port_group" "pg-1" {
  name                            = "tf-edge-tunnel"
  distributed_virtual_switch_uuid = vsphere_distributed_virtual_switch.dvs.id

  vlan_id = 4095
}
```

### Debug Output
Error: expected vlan_id to be in the range (0 - 4094), got 4095

  on network.tf line 24, in resource "vsphere_distributed_port_group" "pg-1":
  24: resource "vsphere_distributed_port_group" "pg-1" {

### Expected Behavior
Create a trunk port_group

1. `terraform apply`

### Important Factoids

Are there anything atypical about your infrastructure that we should know about
that could be causing an edge case or something not necessarily obvious? If so,
please state it here.

### References
https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/website/docs/r/distributed_port_group.html.markdown

https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/website/docs/r/host_port_group.html.markdown

Could follow the same logic here for "vlan_id"
vlan_id - (Optional) The VLAN ID/trunk mode for this port group. An ID of 0 denotes no tagging, an ID of 1-4094 tags with the specific ID, and an ID of 4095 enables trunk mode, allowing the guest to manage its own tagging. Default: 0.

Are there any other GitHub issues (open or closed) or Pull Requests that should
be linked here? For example:
- GH-1234

**Comment by bill-rich** [comment]
This seems like a reasonable ask. I'll need to look a little more into if trunks are configured any differently on the API side to be able to tell for sure what this would entail

**Comment by nvpnathan** [comment]
Would it be possible to add the ability to create untagged or "no vlan" portgroups a long with trunk with ```
vland_id = 0
```

**Comment by codeopen1** [comment]
I came across this and wondered if this is fixed now? The `vlan_range` attribute implements trunking for the `VMwareDVSPortSetting` and the host virtual switch/host port group seem to support the `HostPortGroupSpec` `vlanId` attribute with the 0-4095 values as described.

**Comment by bill-rich** [comment]
This should be covered with `vlan_range` let me know if thats not the case and I'll reopen the issue.
