### ISSUE TITLE
Ability to add a wildcard range of hosts to DVS

### ISSUE THREAD

**Issue by nvpnathan** [hashicorp/terraform-provider-vsphere#1010]
Instead of specifying individual hosts in the resource for a dvs, allow a wildcard range of hosts like you can with the cluster resource.

### Terraform Version
Terraform v0.12.23

### vSphere Provider Version
+ provider.vsphere v1.16.1

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_distributed_virtual_switch`

### Terraform Configuration Files

```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
  name          = "tf-tkg"
  datacenter_id = data.vsphere_datacenter.dc.id

  uplinks         = ["uplink1", "uplink2"]
  active_uplinks  = ["uplink1"]
  standby_uplinks = ["uplink2"]
  max_mtu         = "1600"
  host {
    host_system_id = data.vsphere_host.hosts.0.id
    devices        = var.network_interfaces
  }
  host {
    host_system_id = data.vsphere_host.hosts.1.id
    devices        = var.network_interfaces
  }
  host {
    host_system_id = data.vsphere_host.hosts.2.id
    devices        = var.network_interfaces
  }
}
```

### Could look like this
```hcl
resource "vsphere_compute_cluster" "compute_cluster" {
  name            = "tf-vlab-tkg"
  datacenter_id   = data.vsphere_datacenter.dc.id
  host_system_ids = data.vsphere_host.hosts.*.id
  devices        = var.network_interfaces
```

**Comment by bill-rich** [comment]
This seems like a good enhancement suggestion. I'll get this added to the backlog.

**Comment by bill-rich** [comment]
I think it would be best to try and keep the existing structure, but expand on it a bit. Rather than adding multiple ways to accomplish adding hosts, lets go with adding a `host_system_ids` to the `host sub resource. Then only one host entry can be put in that will cover adding an entire list.

**Comment by qiangtang** [comment]
Maybe you can use dynamic here, it works on my local site  
dynamic "host" {
    for_each = toset(var.cell_hosts)
    content {
      host_system_id = data.vsphere_host.cell-hosts[host.value].id
      devices        = "${var.network_interfaces}"
    }
  }

**Comment by tenthirtyam** [comment]
I agree with @qiangtang in the [previous comment](https://github.com/hashicorp/terraform-provider-vsphere/issues/1010#issuecomment-1003239632).

The ideal method would be to use a dynamic block.

```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
  name          = "tf-tkg"
  datacenter_id = data.vsphere_datacenter.dc.id

  uplinks         = ["uplink1", "uplink2"]
  active_uplinks  = ["uplink1"]
  standby_uplinks = ["uplink2"]
  max_mtu         = "1600"
  dynamic "host" {
    for_each = toset(var.host_names)
    content {
      host_system_id = data.vsphere_host.hosts[host.value].id
      devices        = var.network_interfaces
    }
  }
}
```

Ryan
