### ISSUE TITLE
Adding a host to a cluster without thumbprint verification

### ISSUE THREAD

**Issue by rydss** [hashicorp/terraform-provider-vsphere#1034]
It would be very useful for labs deployment to be able to add hosts to a cluster without the certificate thumbprint verification. 

It is possible to do so with govmomi with the "-noverify" parameter: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#clusteradd

**Comment by bill-rich** [comment]
Hi @rydss! A solution to this was recently merged in #1142. Rather than adding a `noverify` option, we opted for a thumbprint data source which can be used to retrieve the thumbprint.
