### ISSUE TITLE
Host jumps out of compute_cluster and back in

### ISSUE THREAD

**Issue by a666** [hashicorp/terraform-provider-vsphere#1041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.24
+ provider.vsphere v1.17.2 && v1.18.1
```

### vSphere Provider Version
```
Terraform v0.12.24
+ provider.vsphere v1.17.2 && v1.18.1

.
└── provider.vsphere
```

### Affected Resource(s)

- `vsphere_host`
- `vsphere_compute_cluster`

### Terraform Configuration Files

```hcl
variable "esxi_user" {}
variable "esxi_pass" {}
variable "esxi_license" {}

resource "vsphere_license" "esxi_license1" {
  license_key = var.esxi_license
}

resource "vsphere_datacenter" "s1" {
  name = "s1"
}

resource "vsphere_compute_cluster" "s1c" {
  name          = "s1c"
  datacenter_id = vsphere_datacenter.s1.moid
  # host_system_ids = [
  #   vsphere_host.esxi1.id,
  #   # vsphere_host.esxi2.id,
  # ]
}

resource "vsphere_host" "esxi1" {
  hostname   = "10.0.0.22"
  thumbprint = "Sh:aO:ne"
  username   = var.esxi_user
  password   = var.esxi_pass
  license    = var.esxi_license
  # datacenter = vsphere_datacenter.s1.moid
  cluster = vsphere_compute_cluster.s1c.id
}

```

### Debug Output

First apply:
```
Terraform will perform the following actions:

  # vsphere_host.esxi1 will be updated in-place
  ~ resource "vsphere_host" "esxi1" {
      + cluster     = "domain-c54"
        ...
```
Second apply:
```
Terraform will perform the following actions:

 # vsphere_compute_cluster.s1c will be updated in-place
  ~ resource "vsphere_compute_cluster" "s1c" {
        ...
      ~ host_system_ids                                       = [
          - "host-59",
        ]
```

### Expected Behavior

Host remains in the cluster it is declared in.

### Actual Behavior

Host keeps jumping between in cluster to out of cluster.

### Steps to Reproduce

1. Have vcenter 6.7
1. Have esxi 6.5/6.7
1. `terraform apply`
1. `terraform apply`

### Important Factoids

I'm trying to do a vcenter deployment never touching the UI.

### References

None that I could find...

**Comment by broestls** [comment]
fwiw, I've seen this issue using code similar to this when utilizing the `vsphere_compute_cluster` resource or if I use the `cluster` parameter of the `vsphere_host` resource. Adding hosts seems to work fine, but removing hosts from the cluster is a recipe for a broken cluster.

In my case, I am combining the `vsphere_host` with a terraform `for_each` like so:

```
resource "vsphere_host" "dc_host" {
  for_each = var.esxi_hosts
  hostname   = "${each.key}.${var.dns_suffix}"
  username   = var.esxi_username
  password   = var.esxi_password
  datacenter = var.datacenter_id
  thumbprint = data.external.esxi_hosts.result["${each.value["ip_address"]}"]
  depends_on = [infoblox_record_a.esxi_ib_a]
}
```
I am using an external script to generate SHA1 thumbprints, hence the `data.external` variable.

**Comment by craqs** [comment]
I have exactly the same problem. It looks like you can add host to compute cluster using two separate methods: 
- `cluster` attribute in `vsphere_host` 
- `host_system_ids` attribute in `vsphere_compute_cluster`. 

Both methods are changing the same state, but terraform doesn't allow to use them together at the same time (complaining about cycle `Error: Cycle: vsphere_host.xxx, vsphere_compute_cluster.yyy`). 

In your case @a666 terraform thinks that host `esxi1` should be a member of `s1c` cluster, but cluster `s1c` doesn't have proper host system id defined in `host_system_ids` attribute, so terraform is trying to remove this host from cluster.

I'm using Terraform v0.12.24 with provider.vsphere v1.18.1, vSphere 7 and waiting for fix too ;-)

**Comment by a666** [comment]
@craqs Thank you. 
As you can see in my commented code, I proceeded exactly as you did. 
Only to be rebuffed by that cycle error.

Right now I'm manually adding hosts to the cluster and reading it as datasource...

**Comment by bill-rich** [comment]
This can be resolved by either setting `host_managed` on the cluster, or `cluster_managed` on the hosts. The issue comes about because both resources manage cluster membership, so one must be disabled if both resources are used.
