### ISSUE TITLE
Content library vm deployment should allow thin provisioning.

### ISSUE THREAD

**Issue by axelrtgs** [hashicorp/terraform-provider-vsphere#1042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Thank you for the content library support. I was not sure whether to file this as a bug or a feature request.

When trying to use it with Thin provisioned templates since we hardcode the storage mapping and storage provisioning [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/d18d4f04c4535839d640ad391dd90179b0a6905d/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go#L491) by default it always created the VMs with thick provisioned storage.

Specifying thin provisioned on the disk resource results in an error that it cannot change the type from thick to thin since the VM is already created when it does the post-clone tasks.

I also noticed while digging through git that the code to do the storage mappings was already implemented [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/e8706139f03843d07fa8d19256e04f13f1bc64fe/vsphere/internal/helper/contentlibrary/content_library_helper.go#L226). it may be as simple as adding 2 more properties `storage_mapping` that works similar to the network one and `storage_provisioning` which can map to thick or thin provisioning types and using those values instead of the hardcoded ones.

I noticed the MapNetworkDevices function seems to include information about storage policies that I think should not be there.

There is some good information [here](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html) on the values possible for these mappings.

To note, since the disks in the template are configured already using this mapping/setting we should not need to specify a disk in the terraform config and it should just skip the disk step if there are no disks specified and this is a content library template. This is a minor issue and is worked around by specifying the disks anyway in the TF file and results in usable VMs.

### Potential Terraform Configuration
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://github.com/terraform-providers/terraform-provider-vsphere/blob/d18d4f04c4535839d640ad391dd90179b0a6905d/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go#L491

https://github.com/terraform-providers/terraform-provider-vsphere/blob/e8706139f03843d07fa8d19256e04f13f1bc64fe/vsphere/internal/helper/contentlibrary/content_library_helper.go#L226

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html

**Comment by leemachine** [comment]
Worked on testing Content Library deployment and after I resolved a few extra permissions needed I hit this blocker. 

I'll revisit this again in a few months :)

**Comment by djpbessems** [comment]
I'm really blocked by this issue; we have templates with 400GB thin provisioned disks that need to be deployed to our staging environment which has limited capacity (they will be migrated to a dedicated environment with sufficient datastore capacity later during the course of respective projects and then changed to thick disks).
I tried working around this by doing a vMotion through PowerCLI to change to thin-provisioned disks; but without succes (probably because of https://kb.vmware.com/s/article/2004155).

Is there any estimation on when this bug/feature-request could be resolved? Is there anything I can do to assist with that?

**Comment by bill-rich** [comment]
We were waiting on upstream support for this originally. There have been Content Library improvements in govmomi since support was added to the provider. This week I'll be looking into what can be done with the improvements.

**Comment by bill-rich** [comment]
Added in #1183
