### ISSUE TITLE
Error: duplicate name orphaned_disk_0 for terraform plan/apply

### ISSUE THREAD

**Issue by pkqsun** [hashicorp/terraform-provider-vsphere#1044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.17

### vSphere Provider Version

+ provider.vsphere v1.17.0
{
  "vsphere": "e784f64f18ea92e5892d26d469eb06c69bad2ca9b6baf635a9986b9a0c6d0b44"
}

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

https://gist.github.com/pkqsun/b51454172a228d9fed9f03d1c5883961#file-0-main-tf 

### Debug Output

https://gist.github.com/pkqsun/b51454172a228d9fed9f03d1c5883961#file-terraform-apply-debug-log 

### Expected Behavior

After the dynamic vsphere volumes number changed, terraform need also update the orphaned_disk name and label

### Actual Behavior

duplicate name orphaned_disk_0 error happened and block further terraform cmd.

### Steps to Reproduce

1. terraform apply to create target instances.
2. installed k8s and enabled dynamic volume.
3. install app to request k8s dynamic volumes, set replicas to N (my case is 6)
4. do terraform init/plan/apply, then the tfstate file will be update with orphaned_disks.
5. set app replicas to M (larger than N, my case is 11)
    https://gist.github.com/pkqsun/b51454172a228d9fed9f03d1c5883961#file-replicas-changed-from-6-to-11-log
6. do terraform init/plan/apply, then the issue will happen.

**Comment by pkqsun** [comment]
Related with #1005 
Kindly ping @Fodoj

**Comment by Fodoj** [comment]
@pkqsun unlikely I will have time to work on this in the near future, neither I have the same issue :) But if there is one, it's in the same code area as #1005, should be relatively easy to fix.

**Comment by pkqsun** [comment]
Tested with terraform-provider-vsphere_v1.17.2_x4 and issue resolved.
