### ISSUE TITLE
Validate Terraform 0.13 Compatibility

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-provider-vsphere#1065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When Terraform 0.13 is released, we need to validate provider compatibility and make any associated fixes.
### References
* https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md

**Comment by bill-rich** [comment]
Didn't come across any problems.
