### ISSUE TITLE
OVF (vApp) Properties are not correctly applied after OVF import

### ISSUE THREAD

**Issue by lamw** [hashicorp/terraform-provider-vsphere#1074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.vsphere v1.18.0
```

### vSphere Provider Version
```
v1.18.0
```

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files
```hcl
provider "vsphere" {
  user           = "administrator@vsphere.local"
  password       = "VMware1!"
  vsphere_server = "192.168.30.200"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "Primp-Datacenter"
}

data "vsphere_datastore" "datastore" {
  name          = "sm-vsanDatastore"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "Supermicro-Cluster/Resources"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_host" "host" {
  name          = "192.168.30.14"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

resource "vsphere_virtual_machine" "vmFromLocalOvf" {
  name = "Nested-ESXi-7.0-From-Terraform"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id = "${data.vsphere_datastore.datastore.id}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
  host_system_id = "${data.vsphere_host.host.id}"
  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
  }

  ovf_deploy {
    local_ovf_path = "/Volumes/Storage/Software/Nested_ESXi7.0_Appliance_Template_v1.ovf"
  }

  vapp {
    properties = {
      "guestinfo.hostname" = "tf-nested-esxi.primp-industries.com",
      "guestinfo.ipaddress" = "192.168.30.180",
      "guestinfo.netmask" = "255.255.255.0",
      "guestinfo.gateway" = "192.168.30.1",
      "guestinfo.dns" = "192.168.30.1",
      "guestinfo.domain" = "primp-industries.com",
      "guestinfo.ntp" = "pool.ntp.org",
      "guestinfo.password" = "VMware1!"
    }
  }
}
```

### Debug Output

https://gist.github.com/lamw/4769a59dabaa41f789950aaa1c7fab2b

### Expected Behavior
Successfully deploy OVF with correctly applied OVF properties 

### Steps to Reproduce

`terraform apply`

It looks like the OVF is imported but when/how the vApp properties are applied was not done correctly or in a way that vSphere does not actually even get configured. See screenshot below and you can see only the default values (which were encoded in the OVF) were applied but all vApp properties specified within the TF file was not. 

<img width="1182" alt="Screen Shot 2020-05-08 at 8 45 32 AM" src="https://user-images.githubusercontent.com/602199/81422981-a27ba700-9108-11ea-9847-8c7cfcde1e57.png">

### Important Factoids

OVF (vApp Properties) should be applied prior to powering on the VM as these are normally used to customize the application running within the appliance. Feel free to download and test with https://download3.vmware.com/software/vmw-tools/nested-esxi/Nested_ESXi7.0_Appliance_Template_v1.ova 

If you wish to see the desired behavior, simply import the OVA via vSphere HTML UI and notice the vApp properties are configured properly prior to powering on (which is needed as these properties are read in only during the initial boot)

**Comment by sumitAgrawal007** [comment]
Thanks for the feedback, I will look into this.

**Comment by jacobludriks** [comment]
I'm having this same issue when trying to deploy an Ubuntu cloudimg and using the cloud-init user-data attribute via vapp properties. I'm also on vSphere 7.0.

**Comment by k3nny0ne** [comment]
I'm not a Go expert, but seems that currently there is no code implemented for handling custom parameters for `ovf_deploy`.
https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine.go#L1344

**Comment by sumitAgrawal007** [comment]
yes currently there is no support for vapp properties while deploying ovf, I am planning to add it in the next release in the following week.

**Comment by lamw** [comment]
@sumitAgrawal007 If vApp properties aren't supported, the docs feel a bit miss-leading ... as I read `Cloning from an OVF/OVA-created template with vApp properties` as an example and since it references `vapp` section and there was no complaint in deploy, I figured this was supported.

**Comment by tezzigator** [comment]
> 
> 
> yes currently there is no support for vapp properties while deploying ovf, I am planning to add it in the next release in the following week.

Thanks - its sorely needed.  Also please work it such that Deployment/Configuration selection is supported.  For example, when an OVF contains multiple choices to pick from. (with powershell, its DeploymentOption.Value that is used for this selection)

**Comment by jacobludriks** [comment]
any update?

**Comment by sumitAgrawal007** [comment]
Pull request has been raised for this https://github.com/terraform-providers/terraform-provider-vsphere/pull/1082

**Comment by jacobludriks** [comment]
this works beautifully now. thank you all so much!
