### ISSUE TITLE
Virtual disks not destroyed with VM when ovf_deploy from local file

### ISSUE THREAD

**Issue by bryantbunderson** [hashicorp/terraform-provider-vsphere#1089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.25

### vSphere Provider Version
provider.vsphere v1.18.2

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files

```
resource "vsphere_virtual_machine" "vm_from_ovf" {
    name             = "vm1 (Terraform)"
    resource_pool_id = data.vsphere_host.host.resource_pool_id
    datastore_id     = data.vsphere_datastore.datastore.id
    host_system_id   = data.vsphere_host.host.id
    datacenter_id    = data.vsphere_datacenter.dc.id

    wait_for_guest_net_timeout = 0

    ovf_deploy {
        local_ovf_path  = "./ovf_files/my-vm.ovf"
        ovf_network_map = {
            "ESX-port-1" = data.vsphere_network.network.id
            "ESX-port-2" = data.vsphere_network.network.id
        }
    }
}
```

### Expected Behavior
The virtual disks created in the datastore when the OVF is deployed should have been deleted when the VM was destroyed. 

### Actual Behavior
The virtual disks created in the datastore are left behind after the VM is destroyed.

### Steps to Reproduce
1. `terraform apply` verify that the .vmdk files are created in the specified datastore
2. `terraform destroy` notice that the .vmdk files remain and were not destroyed

### Important Factoids
Deploying from a local OVF file that contains two virtual disks.

### References

* #0000

**Comment by bill-rich** [comment]
Resolved in #1106
