### ISSUE TITLE
vsphere_content_library_item completes successfully but item is always size zero (possibly timeout)

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-vsphere#1098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
v0.12.26
```

### vSphere Provider Version

```
v1.18.3
```

### Affected Resource(s)

- `vsphere_content_library`
- `vsphere_content_library_item`

### Terraform Configuration Files

```hcl

data "vsphere_datacenter" "this" {
  name = var.datacenter_name
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore_name
  datacenter_id = data.vsphere_datacenter.this.id
}

resource "vsphere_content_library" "this" {
  name            = var.content_library_name
  storage_backing = toset([data.vsphere_datastore.datastore.id])
  description     = "Content Library"
}

resource "vsphere_content_library_item" "this" {
  name        = var.template_name
  description = "VM template"
  library_id  = vsphere_content_library.this.id
  file_url = [
    "file://${path.module}/../stage3_export/output_vsphere/${var.template_name}.ovf",
    "file://${path.module}/../stage3_export/output_vsphere/${var.template_name}.mf",
    "file://${path.module}/../stage3_export/output_vsphere/${var.template_name}-disk-0.vmdk"
  ]
}
```

### Debug Output
`TF_LOG=TRACE`

https://gist.github.com/dkirrane/2a4dfd764c9cbbcdbc73fa6a073e2b33

### Panic Output

No crash.

### Expected Behavior

OVF should be correctly uploaded to the Content Library.

### Actual Behavior

Terraform completes successfully after ~5mins but upload hasn't completed.

I can see upload in vSphere UI Recent Tasks window that upload has only completed about 10%.
After ~5mins Terraform completes. It disappears form the vSphere UI Recent Tasks window. 
It does not show up in the UI under running, completed or a failed tasks.
OVF appears in Content Library but it's size is 0:

![image](https://user-images.githubusercontent.com/1280116/83944364-e2fb3d00-a7fa-11ea-9e68-077e25bc7d9f.png)

### Steps to Reproduce

```
export TF_LOG=TRACE
export TF_LOG_PATH=./terraform.log
terraform init
terraform validate
terraform plan -out terraform.tfplan
terraform apply terraform.tfplan
```

### Important Factoids

The OVF I'm trying to upload to the Content Library was created and exported with packer `vsphere-clone`.

When I manually upload the OVF to the Content Library with the vSphere Web UI it is successful.

**Comment by arizvisa** [comment]
@dkirrane, just a member of the community here, but what if you use govmomi's `govc` client?

I think the command is `govc library.import`.

**Comment by bill-rich** [comment]
Hi @dkirrane! I wasn't able to reproduce the issue. If you're still having this problem, please try with `govc`, and let me know the results.
