### ISSUE TITLE
error loading default device list: NoPermission (works with gui)

### ISSUE THREAD

**Issue by macau23** [hashicorp/terraform-provider-vsphere#1109]
### Terraform Version
Terraform version: 0.12.26

### vSphere Provider Version
terraform-provider-vsphere_v1.18.3_x4

### Affected Resource(s)

`vsphere_virtual_machine`

### Terraform Configuration Files

```
main.cf:
provider "vsphere" {
  user           = "X"
# VSPHERE_PASSWORD is set
  vsphere_server = "X"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "X"
}

data "vsphere_resource_pool" "pool" {
  name          = "X"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = "X"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "X"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terra-test1"
  folder           = "X"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  scsi_type = "lsilogic"
  num_cpus  = 2
  memory    = 1024
  guest_id  = "rhel6_64Guest"
  firmware  = "bios"
  hardware_version = 15

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label            = "disk0"
    size             = 20
    thin_provisioned = true
  }
}
```

### Debug Output

`$ terraform plan -out=deployvm`
https://gist.github.com/macau23/51475663907127f50f147b8d0967817d

`$ terraform apply "deployvm"`
https://gist.github.com/macau23/cc9c22b74a792bde3bf75fb13d8d1bff

### Expected Behavior

I can create a VM in my pool using the vSphere web interface, but not using Terraform.

### Actual Behavior

The plan is successful. The apply of the plan is not.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Hi @macau23! The way we go about creating VMs in Terraform differs a bit from how they are created through the GUI. The issue looks like it is coming about when we are querying the resource pool and cluster for default configuration information. 

I don't know exactly which permission that is utilizing though. If you'd like to send which permissions you have enabled, I could take a look and see if anything stands out.

**Comment by macau23** [comment]
Hi @bill-rich thanks just a heads up, I tried to create a VM in govc directly but got a similar error (see https://github.com/vmware/govmomi/issues/2024). Should I try to resolve that first, before updating this ticket?

**Comment by bill-rich** [comment]
Sorry about the delay @macau23. It does sound like there is a required permission missing from the user. In some cases, we're having to make API calls (which need additional permissions), which are not required through the UI. Specifically this seems to be happening when acquiring the environment browser for the resource pool and cluster. You should be able to resolve this by opening up additional permissions.
