### ISSUE TITLE
Could not find SystemId

### ISSUE THREAD

**Issue by thepiger** [hashicorp/terraform-provider-vsphere#1110]
With Terraform v0.11.14 and provider.vspher 1.19.0 i can create new vm resources but i can't edit them.
I retrieve this error:

Error: Error applying plan:

1 error occurred:
        * module.vm-etcd.vsphere_virtual_machine.k8s_node: 1 error occurred:
        * vsphere_virtual_machine.k8s_node: could not find SystemId

After downgrading to provider.vsphere v1.18.3 everything goes fine

**Comment by bill-rich** [comment]
Thanks for the report on this. I've looked into it and found the problem. I'll have the bug fix in the Monday release. Also, I'm going to close this issue so I can keep everything related to the SystemId problem in one place (#1111).
