### ISSUE TITLE
Can't edit existing virtual_machine resources after updating to v1.19.0 (Error: could not find SystemId)

### ISSUE THREAD

**Issue by jschoewe** [hashicorp/terraform-provider-vsphere#1111]
### Terraform Version
v0.12.26
### vSphere Provider Version
v1.19.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

main.tf
```
# Configure the vSphere provider
provider "vsphere" {
  user           = var.vsphere_username
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

# Get the vsphere datacenter
data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "import_vm" {
  name          = var.vm_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Define a resource to import an existing VM into
resource "vsphere_virtual_machine" "destroy_vm" {
  name = var.vm_name

  # NIC definition
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.import_vm.network_interface_types[0]
  }

  guest_id  = data.vsphere_virtual_machine.import_vm.guest_id

  resource_pool_id = var.vsphere_resource_pool_id

  datastore_id = data.vsphere_datastore.datastore.id

  scsi_type = data.vsphere_virtual_machine.import_vm.scsi_type

  # Disk information
  dynamic "disk" {
    for_each = data.vsphere_virtual_machine.import_vm.disks

    content {
      label            = "disk${disk.key}"
      size             = disk.value.size
      eagerly_scrub    = disk.value.eagerly_scrub
      thin_provisioned = disk.value.thin_provisioned
      unit_number      = disk.key
    }
  }
}
```

variables.tf
```
# vSphere login credentials
variable "vsphere_server" {}
variable "vsphere_username" {}
variable "vsphere_password" {}

# vSphere datacenter name
variable "vsphere_datacenter" {}

# vSphere datastore name (must NOT be a datastore cluster)
variable "vsphere_datastore" {}

# vSphere vlan name
variable "vsphere_network" {}

# vSphere resource pool MOID
variable "vsphere_resource_pool_id" {}

# Name of the VM in vCenter
variable "vm_name" {}
```

### Debug Output

`terraform plan`
https://gist.github.com/jschoewe/0b8762c1a5aec1e880840da6a97beed2

`terraform apply`
https://gist.github.com/jschoewe/2fc38c91eff511f8a89b85d0cf426d71

### Expected Behavior

Running `terraform plan` succeeds, I expect `terraform apply` to succeed as well and change the keep_on_remove variable on disks to false

### Actual Behavior

`terraform apply` fails with error:
`Error: could not find SystemId`

### Steps to Reproduce

1. Import a VM into a virtual_machine resource
2. Run `terraform plan`
3. Run `terraform apply`

### Important Factoids

* This still works as expected if I revert the provider version back to 1.18.3.
* Creating new VMs still works as expected in version 1.19.0.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Thanks for the report. I've looked into it and will have a bug fix ready for the release on Monday.

**Comment by mtaumike** [comment]
Ha! Right on, just this this issue this morning!
