### ISSUE TITLE
Different ipv4_gateway for multiple "network_interface"

### ISSUE THREAD

**Issue by basic39** [hashicorp/terraform-provider-vsphere#1114]
Hello,

I dont't have a lot of experience on terraform, but how I can see, there is no way to set different ipv4_gateway for multiple network_interfaces. Sometimes I need to create VMs with multiple different network interfaces for different subnets.

ipv4_gateway cannot be placed in the "network_interface"-block without this error:
`Error: Unsupported argument
  on main.tf line 124, in resource "vsphere_virtual_machine" "vm":
 124:         ipv4_gateway = "xxx.xxx.xxx.xxx"
An argument named "ipv4_gateway" is not expected here`

Do I understand it right, what there is no option to set different ipv4_gateways for multiple networks?

```
clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
       windows_options {
...
      network_interface {
        ipv4_address = "172.1.1.1"
        ipv4_netmask = 24
        ipv4_gateway = "172.1.1.254"
        dns_server_list = ...
        dns_domain = ...
      }
       network_interface {
        ipv4_address = "172.1.2.1"
        ipv4_netmask = 24
        ipv4_gateway = "172.1.2.254"
        dns_server_list = ...
        dns_domain = ...
      }
    }
```

Terraform v0.12.26 + provider.vsphere v1.20.0

**Comment by bill-rich** [comment]
Hi @basic39! Unfortunately there is not support for additional routes in the [vSphere API](https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.customization.IPSettings.html). If you need to add routes beyond the default gateway, I'd recommend using a provisioner to add them after the VM created.

For example:
```
resource "vsphere_virtual_machine" {
...
  provisioner "remote_exec" {
    inline = [
       "ip route add 192.168.100.0/24 via 192.168.100.1"
    ]
  }
...
}
```
