### ISSUE TITLE
Adding Tags to VM fails - provider v1.19.0 or higher - vSphere 6.0.0

### ISSUE THREAD

**Issue by bhadrim** [hashicorp/terraform-provider-vsphere#1115]
I am unable to set tags on VMware VMs when I use provider v1.19.0 or higher. The template is working fine if I use provider v1.18.3 or lower. I have this issue on vSphere vCenter Server version 6.0.0 Build 3018524 (vSphere vCenter client version 6.0.0 Build 3016447). Works fine on vSphere vCenter Server version 6.7.0

Error Message: 

error attaching tags to object ID "vm-22700": 400 Bad Request: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.invalid_argument"}
  on main.tf line 26, in resource "vsphere_virtual_machine" "vm":
  26: resource "vsphere_virtual_machine" "vm" {

### Affected Resource(s)

- `vsphere_virtual_machine`
- `vsphere_tag_category` (probable root cause)

### Terraform Configuration Files

https://github.com/bhadrim/Samples/tree/master/VMwaretag/main.tf
https://github.com/bhadrim/Samples/tree/master/VMwaretag/variables.tf

### Debug Output

Plan/Apply with TF_LOGS set to TRACE. Also includes tfstate file

[trace.zip](https://github.com/hashicorp/terraform-provider-vsphere/files/4835007/trace.zip)

### Expected Behavior

Tag Category, Tag must be created. VM must be created and the created Tag must be set on the VM 

### Actual Behavior

Tag Category, Tag are created. VM gets created but the created Tag is not set on the VM. Instead following error is thrown

error attaching tags to object ID "vm-22700": 400 Bad Request: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.invalid_argument"}
  on main.tf line 26, in resource "vsphere_virtual_machine" "vm":
  26: resource "vsphere_virtual_machine" "vm" {

### Steps to Reproduce

Execute the following on vSphere vCenter Server version 6.0.0 

1. Get the templates from

https://github.com/bhadrim/Samples/tree/master/VMwaretag/main.tf
https://github.com/bhadrim/Samples/tree/master/VMwaretag/variables.tf

2. Add your tfvar files to fill the variables. 

3. terraform apply

### Important Factoids

On vSphere vCenter Server version 6.0.0 , when I use provider v1.19.0 or higher, the created tag category does not have associable object types set to VirtualMachine (as specified in template https://github.com/bhadrim/Samples/blob/master/VMwaretag/main.tf#L12). See image below.

![vmware_category](https://user-images.githubusercontent.com/17169839/85819322-52e94d00-b741-11ea-9ee0-0a420d363d99.JPG)

If I use v1.18.3 or lower on vSphere vCenter Server version 6.0.0 I can see the association types set or 
If I use v1.19.0 or higher on vCenter Server version 6.7.0 I can see the association types set

Root issue could be in this commit 

https://github.com/hashicorp/terraform-provider-vsphere/commit/4971a0d855284d23c5d932d0667aa6383fdca103#diff-f13c81fb03a154075e243936c9b9f1e2

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Hi @bhadrim! Unfortunately we're no longer supporting vSphere 6.0. We match our support to VMware's General Support period. Please upgrade to a newer version of vSphere to use tagging.
