### ISSUE TITLE
Clone a CentOS_8 template, but the VM boot with "Operating System not Found"

### ISSUE THREAD

**Issue by garethhk** [hashicorp/terraform-provider-vsphere#1122]
### Terraform Version
v0.12.28

### vSphere Provider Version
v6.7

### Affected Resource(s)

====variables.tf====
variable "vsphere_server" {}
variable "vsphere_user" {}
variable "vsphere_password" {}

====terraform.tfvars====
vsphere_server = "172.4.1.10"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "XXXXXX"

====vcenter.tf====
## Configure the vSphere Provider
provider "vsphere" {
    version = "1.21"
    vsphere_server = var.vsphere_server
    user = var.vsphere_user
    password = var.vsphere_password
    allow_unverified_ssl = true
}

## Build VM
data "vsphere_datacenter" "dc" {
  name = "XXX-DC"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore2"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = "XXX-ResourcePool"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "mgmt_lan" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = "CentOS_8_Template_1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "terraform-test1" {
  name             = "terraform-test1"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus   = 1
  memory     = 2048
  wait_for_guest_net_timeout = 0
  guest_id = data.vsphere_virtual_machine.template.guest_id
  scsi_type = data.vsphere_virtual_machine.template.scsi_type
  ##nested_hv_enabled =true
  ##fireware="efi"
  network_interface {
   network_id     = data.vsphere_network.mgmt_lan.id
   #adapter_type   = "vmxnet3"
  }

  disk {
   size             = data.vsphere_virtual_machine.template.disks.0.size
   label             = "disk0"
   ##eagerly_scrub    = false
   thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

##    }
  }
}

### Expected Behavior
VM boot with CentOS 8 installed.

### Actual Behavior
VM boot with 
-----------------------------------------
PXE-M0F: Exiting Intel PXE ROM.
Operating System not found
------------------------------------------

### Steps to Reproduce
1. terraform init
2. terraform plan
3. terraform apply

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bkresoja** [comment]
For me the issue was with firmware. You can try with following: 
firmware = data.vsphere_virtual_machine.template.firmware

**Comment by rsysadmin-com** [comment]
@bkresoja  thanks for the hint!

FYI --

For CentOS8 there was also an issue: the process showed this error message:
---] START OF PASTED TEXT
Error:
Virtual machine customization failed on "/foo/bar/myvm02":

An error occurred while customizing VM myvm02. For details reference the log file /var/log/vmware-imc/toolsDeployPkg.log in the guest OS.
---] END OF PASTED TEXT

A quick look at the log file mentioned above showed that Perl's module File::Temp was not installed on the base CentOS8 template. After installing it and rebuilding the template, terraform was able to complete the whole deployment flawlessly. 

HTH

**Comment by bill-rich** [comment]
Hi @garethhk! Were you able to resolve the issue by setting the `firmware`?

**Comment by redgryphon** [comment]
I had the very same issue and it happens that it just uses the default firmware (bios) when nothing is specified. Once specified the option as already stated the build runs as expected.
I would say that if ever there is a bug is the fact that the default firmware could be set as the same as the source machine of the clone which is the expected behavior of a **clone**.

**Comment by akulbe** [comment]
I have this issue, and I've tried the firmware fix. I even converted my template back to a VM and installed the Perl module for File::Temp. After that, converted it back into a template and retried. No luck.

Cloning the VM right from vSphere works fine. It's only when I try to do this from Terraform that it doesn't work.

**Comment by rsysadmin-com** [comment]
> I have this issue, and I've tried the firmware fix. I even converted my template back to a VM and installed the Perl module for File::Temp. After that, converted it back into a template and retried. No luck.
> 
> Cloning the VM right from vSphere works fine. It's only when I try to do this from Terraform that it doesn't work.

can you please share your Terraform code to roll out a new VM from your CentOS 8 template?

**Comment by xqSupersonic** [comment]
me too , anyone have fix?

**Comment by jimdevops19** [comment]
@akulbe I still experience the same issue, from UI it works just as expected. But when I template this Centos8 (Or leave it as a machine) and try to use `clone {}` it does not look good.

**Comment by jimdevops19** [comment]
> For me the issue was with firmware. You can try with following:
> firmware = data.vsphere_virtual_machine.template.firmware

This comment is gold. Thanks

**Comment by tenthirtyam** [comment]
Hi folks,

In order for guest customizations (**_not_** `cloud-init`-based) to work with CentOS you **must** install Perl. I recommend doing this as part of the build kickstart process if you are using Packer. Here [you can see an example](https://github.com/rainpole/packer-vsphere/blob/f6a5aac4232dcbc4d8c4e0410f8d090c6f6c2fbc/builds/linux/centos-stream-8/data/ks.pkrtpl.hcl#L106) in my project where it's installed during the first phase.

![image](https://user-images.githubusercontent.com/7771363/140442672-9a5b461a-6240-4473-96e2-2b470b0f2495.png)

From there you can use the following example:

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = var.vm_hostname
        domain    = var.vm_domain
      }
      network_interface {
        ipv4_address = var.vm_ipv4_address
        ipv4_netmask = var.vm_ipv4_netmask
      }

      ipv4_gateway    = var.vm_ipv4_gateway
      dns_suffix_list = var.vm_dns_suffix_list
      dns_server_list = var.vm_dns_server_list
    }
  }
  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
}
```

You can grab the [complete example](https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine/clone-template-linux-guest-customization) on my repo.

Hope this helps,
Ryan
@tenthirtyam

Recommend: `close/not-a-bug`

**Comment by tenthirtyam** [comment]
Hi @garethhk - could you review [my previous comment](https://github.com/hashicorp/terraform-provider-vsphere/issues/1122#issuecomment-961556326) and update the status of the issue?

Ryan

**Comment by tenthirtyam** [comment]
Hi @iBrandyJackson and @appilon, I suggest that this issue can be closed based on solution provided in the thread to return the firmware from the template using the `vsphere_virtual_machine` data source of the template since the default is BIOS.

```hcl
Resource "vsphere_virtual_machine" "terraform-test1" {
 # ... other config ...
 firmware = data.vsphere_virtual_machine.template.firmware
 # ... other config ...
}
```

Ryan
