### ISSUE TITLE
Disable pxe boot for some network adapters

### ISSUE THREAD

**Issue by skydion** [hashicorp/terraform-provider-vsphere#1123]
### Description

It is possible add feature to disable PXE boot for network interface?

### Potential Terraform Configuration

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = data.vsphere_network.network.id

    pxe_boot = false
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
This enhancement request has been posted for ~2 years with no +1 reactions to date or additional comments on the use case. 

Close: `not planned`

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
