### ISSUE TITLE
`guestinfo.userdata` in `extra_config` not passed to resource configuration

### ISSUE THREAD

**Issue by authsec** [hashicorp/terraform-provider-vsphere#1124]
### Terraform Version

Terraform v0.12.28

### vSphere Provider Version

1.21.0

Deployment target is ESXi 7.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

**metadata.tpl:**
```yaml
instance-id: cloud-vm
local-hostname: cloud-vm
network:
  version: 2
  ethernets:
    nics:
      match:
        name: ens*
      dhcp4: yes
```

**userdata.tpl:**
```yaml
#cloud-config

bootcmd:
  # Password is "kevin.is.dead" (no quotes)
  - /bin/sed -E -i 's#^root:([^:]+):.*$#root:$6$noSeaSaltAndNoPe$ahaWZDtt2EFso57ADBL4Uoa71hsNPB3DX27tZM//hy2GrduH9hzbebjcZTOiwq8szzY3NmXzXUiOADXVGSVMb/:18448:0:99999:0:::#' /etc/shadow
users:
  - name: pihole
    groups: wheel,sudo
    passwd: $6$noSeaSaltAndNoPe$ahaWZDtt2EFso57ADBL4Uoa71hsNPB3DX27tZM//hy2GrduH9hzbebjcZTOiwq8szzY3NmXzXUiOADXVGSVMb/
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
     
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: yes
```

```hcl
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
  version              = "~> 1.21"
}

// Virtual machines
variable "datacenter" {
  default = "tlab-dc"
}

variable "cluster" {
  default = "tlab-cc"
}

data "vsphere_datacenter" "tlab_dc" {
  name = "${var.datacenter}"
}

data "vsphere_compute_cluster" "tlab_cc" {
  name          = "${var.cluster}"
  datacenter_id = "${data.vsphere_datacenter.tlab_dc.id}"
}

data "vsphere_host" "bones" {
  name          = "bones.example.com"
  datacenter_id = "${data.vsphere_datacenter.tlab_dc.id}"
}

data "template_file" "meta_init" {
  template = file("./metadata.tpl")
}

data "template_file" "cloud_init" {
  template = file("./userdata.tpl")
}

resource "vsphere_virtual_machine" "vmFromRemoteOvf" {
  name                       = "testvm"
  resource_pool_id           = data.vsphere_compute_cluster.tlab_cc.resource_pool_id
  datastore_id               = data.vsphere_datastore.bones_local_ds.id
  host_system_id             = data.vsphere_host.bones.id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  datacenter_id              = data.vsphere_datacenter.tlab_dc.id

  num_cpus = 2
  memory   = 1024

  ovf_deploy {
    remote_ovf_url = "https://packages.vmware.com/photon/3.0/Rev2/ova/Update1/photon-hw11-3.0-0a85037c.ova"
  }

  extra_config = {
    "guestinfo.metadata"          = "${base64gzip(data.template_file.meta_init.rendered)}"
    "guestinfo.metadata.encoding" = "gzip+base64"
    "guestinfo.userdata"          = "${base64encode(data.template_file.cloud_init.rendered)}"
    "guestinfo.userdata.encoding" = "gzip+base64"
  }
}
```

### Debug Output

[terraform init](https://gist.github.com/authsec/39712fcdb8e8a1b4454341ba60baf045)
[terraform apply -auto-approve](https://gist.github.com/authsec/d343446d5711834861df24f2ae251bc4)

### Panic Output

No Panic.

### Expected Behavior

Photon OS 3.0 should have been configured using the cloud-init data passed through the guestinfo `extra_config`

### Actual Behavior

Photon OS is not getting configured with cloud-init data.

### Steps to Reproduce

Put above configurations in a folder and run `terraform init && terraform apply -auto-approve`

### Important Factoids

The ESXi/vCenter deployment target is ESXi/vCenter 7.0

When using `govc` the virtual machine gets configured correctly:

```shell
#> govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      7.0.0
Build:        16189207
OS type:      linux-x64
API type:     VirtualCenter
API version:  7.0.0.0
Product ID:   vpx
UUID:         87b89166-0f8c-47e9-b0da-640649932079
#> govc version
govc 0.23.0
#> export METADATA=$(gzip -c9 <metadata.tpl | { base64 -w0 2>/dev/null || base64; }) USERDATA=$(gzip -c9 <userdata.tpl | { base64 -w0 2>/dev/null || base64; })
#> govc vm.change -vm "testvm" -e guestinfo.metadata="${METADATA}"   -e guestinfo.metadata.encoding="gzip+base64"   -e guestinfo.userdata="${USERDATA}"   -e guestinfo.userdata.encoding="gzip+base64"
#> govc vm.power -vm "testvm" -on
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by isometry** [comment]
In your sample config, I can’t help noticing the discrepancy in encoding between metadata (`base64gzip()` + `gzip+base64`) and userdata (`base64encode()` + `gzip+base64`… but the data was never gzip’d). Does the issue persist if you correct this discrepancy?

```hcl
extra_config = {
    "guestinfo.metadata"          = base64gzip(data.template_file.meta_init.rendered)
    "guestinfo.metadata.encoding" = "gzip+base64"
    "guestinfo.userdata"          = base64gzip(data.template_file.cloud_init.rendered)
    "guestinfo.userdata.encoding" = "gzip+base64"
  }

```

**Comment by authsec** [comment]
Thank you for looking into it. Changing to `base64gzip` unfortunately doesn't fix it for me (although this probably would have led to other problems further down the road).

If you start from a "clean plate" (like an initial checkout) it doesn't set the parameters for me:
```
#> terraform destroy -auto-approve; rm -rf terraform.tfstate* .terraform && terraform init && terraform apply -auto-approve
```
However, I figured out that if I run `terraform apply -auto-approve` again after the initial setup it sets the data correctly.

So if I'm running these commands the data is propagated properly.

```
#> terraform destroy -auto-approve; rm -rf terraform.tfstate* .terraform && terraform init && terraform apply -auto-approve && terraform apply -auto-approve
```

**Comment by tmashos** [comment]
I ran into some similar issues getting terraform to pass data into cloud init and took me a bit to figure this out and get it working, so maybe this will help you out too.

First, it's important to understand that there's multiple parts in play here. 

1. Terraform is sending the data to vsphere, but not into the virtual machine
2. Cloud init providers read data (eg. userdata) from various locations (in this instance, vsphere)
2. Cloud init reads data from a set of configured providers
(Cloud init is not reading the userdata directly from vsphere, it's reading it from the provider, which is reading it from vsphere)

While these multiple parts can be confusing, it also helps in troubleshooting. Inside your VM, you can see if the data is getting passed from terraform to the VM correctly by running

`vmware-rpctool "info-get guestinfo.userdata"`

If the data is getting passed from terraform correctly then it should print out the data in the encoding format you've specified (in your case, gzip+base64), which you should be able to decode to see your actual data. I'm only encoding mine base64, so I can see it by running.

`vmware-rpctool "info-get guestinfo.userdata" | base64 -d`

If that prints out the data you expect, your issue is on the cloud-init side (which is where my issue was). It turns out that the cloud init provider for vmware is written by vmware, not the cloud init people. So it's not installed by default in your VM image (assuming you built your image and didn't download it from somewhere).

Here's the info on installing it  https://github.com/vmware/cloud-init-vmware-guestinfo

Once installed in your image you'll need to configure cloudinit to use the plugin, which I'd have to dig up exactly what needs done but there's a config file that you need to add the plugin to. If you find this is the issue and can't figure out the config I'll try to dig mine up.

**Comment by authsec** [comment]
Thank you for that information. I am using [Photon OS](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/deploy_photon_with_cloud-init.html) where cloud-init is already baked in.

Cloud-init is working fine when the data is actually accessible to cloud-init inside Photon OS. 

I managed to get it running by executing `terraform apply` twice in the end, which I kind of discovered by accident. However, I do think this is a bug, as I expect the virtual machine to be running properly after a first`terraform apply` when running from a clean slate, or am I wrong?

**Comment by bill-rich** [comment]
Hi @authsec! To help troubleshoot, can you please run `terraform apply` once and then check the VM settings in the web client to see if the `guestinfo` is set? You should be able to find it under `VM Options` -> `Advanced` -> `Edit Configuration`.

**Comment by authsec** [comment]
Hi @bill-rich! Thanks for looking into it. If I run `terraform apply` once, then I cannot find the `guestinfo` information there. Applying `terraform` a second time, will set the information in the VM Configuration parameters  correctly. 

<img width="831" alt="Screenshot 2020-07-28 at 17 41 27" src="https://user-images.githubusercontent.com/7973409/88689166-74e83d80-d0fa-11ea-8d44-9d4147d6f4b2.png">

**Comment by bill-rich** [comment]
Thanks for the additional info @authsec. It sounds like the extra_config is not being applied when the VM is created, but is applied when it is being updated. I will look into what could be causing that and keep you updated.

**Comment by neurostream** [comment]
> terraform apply -auto-approve

Ran into this issue as well.  It hadn't occurred to me to run terraform apply again as a troubleshooting system.  Thank you.


`terraform version`
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/vsphere v1.24.0


terraform plan shows it building the correct extra_config block for the vm resource that only gets applied when running apply a second time.

**Comment by neurostream** [comment]
I tried updating to:
`terraform version`
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/vsphere v1.24.2

terraform base binary from v0.13.3 to v0.13.4
tf vsphere provider from v1.24.0 to v1.24.2

but it just crashes now, before writing to tfstate ( so a subsequent apply sees the partially provisioned vm resource already running and exits )

**Comment by neurostream** [comment]
> Hi @bill-rich! Thanks for looking into it. If I run `terraform apply` once, then I cannot find the `guestinfo` information there. Applying `terraform` a second time, will set the information in the VM Configuration parameters correctly.
> 

Was this working as expected in a previous combination of Terraform version + VSphere provider version?  

I'm using Packer to build my immutable Cloud-Init OVA runtime artifacts ( i.e. a Consul Server node image ) and Terraform to orchestrate the deployment.

This dream workflow seemed finally possible in a VMWare datacenter with with the vSphere provider and  **_ovf_deploy_** **+**  **_vmFromLocalOvf_** **+** **_extra_config_** ( for guestinfo cloud-init user/meta data ) - then encountered this issue.

Is using vmFromLocalOvf with extra_config just recently a possibility with the Terraform and vSphere provider versions cited in this issue or could I start developing this workflow on a previously working Terraform/provider version ?

**Comment by authsec** [comment]
@neurostream Unfortunately I do not know if this was working prior to v0.12.28, as I started doing this with that version.

I hope this issue can somehow be fixed.

**Comment by sqqqrly** [comment]
I have found that changing the open-vm-tools.service so it starts after the dbus service fixed my network. Otherwise, just installing cloud-init broke the VM's network (no carrier).

Using ansible (because I did):
```
      21 - name: Start after dbus.service
      22   lineinfile:
      23     path: /lib/systemd/system/open-vm-tools.service
      24     insertafter: "After=apparmor.service"
      25     line: "After=dbus.service"

**Comment by neurostream** [comment]
@sqqrly I tried this and found that I still had to apply this twice before the local tf state is mostly updated, which affects cloud init directives that are intended to run differently on first boot than subsequent boots ( we're trying to avoid subsequent boots, preferring a re-deploy of images over rebooting existing instances to fix stuff).

**Comment by sspreitzer** [comment]
The provider documentation at https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#extra_config states:
>Do not use extra_config when working with a template imported from OVF or OVA as more than likely your settings will be ignored. Use the vapp block's properties section as outlined in Using vApp properties to supply OVF/OVA configuration.


Maybe this explains the behaviour.

**Comment by luoymu** [comment]
Can you elaborate this a little bit more?  I am having the same issue


> The provider documentation at https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#extra_config states:
> 
> > Do not use extra_config when working with a template imported from OVF or OVA as more than likely your settings will be ignored. Use the vapp block's properties section as outlined in Using vApp properties to supply OVF/OVA configuration.
> 
> Maybe this explains the behaviour.

**Comment by luoymu** [comment]
BTW, I use extra_config to pass guestinfo.userdata into vm. I have to run terraform apply twice before it is attached to the VM 

> Can you elaborate this a little bit more? I am having the same issue
> 
> > The provider documentation at https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#extra_config states:
> > > Do not use extra_config when working with a template imported from OVF or OVA as more than likely your settings will be ignored. Use the vapp block's properties section as outlined in Using vApp properties to supply OVF/OVA configuration.
> > 
> > 
> > Maybe this explains the behaviour.

**Comment by christheradioguy** [comment]
Just wanted to chime in that I have the same issue with needing to run terraform apply twice when using the extra_config and deploying from an OVF.

When using vsphere-clone (rather then OVF as a source) I only have to run terraform apply once and the guestinfo is correctly applied.

**Comment by tenthirtyam** [comment]
Using an example Ubuntu 20.04 LTS image with cloud-init 21.3 and the upstream `VMware` data source as seen in [vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere), I was able to sucessfully use the following to pass the `guestinfo.*` configurations on the **_first_** apply.

`metadata`

```yml
instance-id: foo
local-hostname: foo
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - 172.16.11.192/24
      gateway4: 172.16.11.1
      nameservers:
        addresses:
          - 172.16.11.11
          - 172.16.11.12
```

`userdata`

```yml
#cloud-config

users:
  - default
  - name: ryan
    primary_group: ryan
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, wheel
    ssh_import_id: None
    passed: $6$noSeaSaltAndNoPe$ahaWZDtt2EFso57ADBL4Uoa71hsNPB3DX27tZM//hy2GrduH9hzbebjcZTOiwq8szzY3NmXzXUiOADXVGSVMb/
```

`main.tf`

```hcl

terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.2"
    }
  }
  required_version = ">= 1.1.5"
}

provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}


data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  memory_hot_add_enabled  = true
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = "ubuntu64Guest"
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  cdrom {
    client_device = true
  }
  disk {
    label        = "disk0"
    size         = var.vm_disk_size
    datastore_id = data.vsphere_datastore.datastore.id
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
      extra_config,
    ]
  }
  extra_config = {
    "guestinfo.metadata"          = base64encode(file("${path.module}/metadata.yml"))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("${path.module}/userdata.yml"))
    "guestinfo.userdata.encoding" = "base64"
  }
}
```

If the issue persists with [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please comment on this issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the [previous recommendations](https://github.com/hashicorp/terraform-provider-vsphere/issues/1124#issuecomment-1032020312)

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
