### ISSUE TITLE
Unable to set VM memory during OVA deployment, or by re-running script

### ISSUE THREAD

**Issue by saintdle** [hashicorp/terraform-provider-vsphere#1130]
### Terraform Version
0.12.18

### vSphere Provider Version
1.21

### Affected Resource(s)

In the below terraform config, I set the vsphere_virtual_machine resource parameters for depoying the VM based on an OVA. 

I set "memory" and "num_cpus". 

### Terraform Configuration Files

https://github.com/saintdle/Terraform/tree/master/Deploy-FAH

In particular this file is the problematic config file.

https://github.com/saintdle/Terraform/blob/master/Deploy-FAH/FAH_appliance/main.tf

### Debug Output
![image](https://user-images.githubusercontent.com/22192242/87147689-f6d80a00-c2a4-11ea-9796-eddaae7323bc.png)

### Expected Behavior

Virtual Machine is created and the correct CPU and Memory is set. 

### Actual Behavior

Virtual Machine is built and CPU is set correct, but memory is ignored, see below image for the terraform plan, memory is not considered as an attribute to be changed. 

### Important notes

I understand that this may not be supported reading the documentation, however setting the CPU does work. 

### Steps to Reproduce

Run the files to deploy an OVA and set the CPU and Memory parameter, run with "terraform apply"

Tested against on-prem vSphere 7.0 and VMC environment SDDC 1.10v3

### References

It's mentioned in the documentation;
 

> While deploying, the VM properties like name, datacenter_id, resource_pool_id, datastore_id, host_system_id, folder, scsi_controller_count, sata_controller_count, ide_controller_count, and vapp can only be set. All other VM properties are taken from the ovf template and setting them in the configuration file is redundant.

[Source](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#deploying-vm-from-an-ovf-ova-template)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vinaykumar-c** [comment]
@saintdle I am also facing the same issue
