### ISSUE TITLE
Add support to manage ntpd setting on ESXi hosts

### ISSUE THREAD

**Issue by waquidvp** [hashicorp/terraform-provider-vsphere#1131]
### Description

We are trying configure ntp on all of our ESXi hosts. This is currently available in the `govc` cli, see [this](https://github.com/vmware/govmomi/blob/master/govc/host/date/change.go#L65). We want to have the ability to both enable the `ntpd` service and later configure it.

We had a look at the provider source code and adding this feature doesn't look trivial. I am happy to create a PR for this feature but I am unsure about where to start. Since it involves both exposing the [`ServiceSystem`](https://github.com/vmware/govmomi/blob/master/object/host_config_manager.go#L149) for controlling the different services (in our case, `ntpd`) and the [`DateTimeSystem`](https://github.com/vmware/govmomi/blob/master/object/host_config_manager.go#L165) for configuring the `ntpd` service, could we add these under the [`vsphere_host`](https://www.terraform.io/docs/providers/vsphere/r/host.html) resource or in a new resource, eg. `vsphere_host_services` and `vsphere_host_ntp`?

We can see some examples of how [`ConfigManager`](https://github.com/vmware/govmomi/blob/master/object/host_config_manager.go) is used in [`vsphere/resource_vsphere_host.go`](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_host.go#L287) but we can't find any uses of [`ServiceSystem`](https://github.com/vmware/govmomi/blob/master/object/host_config_manager.go#L149) so some guidance would be much appreciated.

For now we are using `govc` and could potentially have it as a `null_resource`.

### Potential Terraform Configuration

```hcl
data "vsphere_datacenter" "dc" {
  name = "my-datacenter"
}

resource "vsphere_host" "h1" {
  hostname   = "10.10.10.1"
  username   = "root"
  password   = "password"
  license    = "00000-00000-00000-00000i-00000"
  datacenter = data.vsphere_datacenter.dc.id
  services   = {
    ntpd = {
      enabled     = true
      policy      = "on"
      ntp_servers = [
        "0.pool.ntp.org",
        "1.pool.ntp.org"
      ]
    }
  }
}
```
or
```hcl
data "vsphere_datacenter" "dc" {
  name = "my-datacenter"
}

resource "vsphere_host" "h1" {
  hostname   = "10.10.10.1"
  username   = "root"
  password   = "password"
  license    = "00000-00000-00000-00000i-00000"
  datacenter = data.vsphere_datacenter.dc.id
}

resource "vsphere_host_service" "ntp" {
  service = "ntpd"
  enabled = true
  policy = "on"
  ntp_servers = [
     "0.pool.ntp.org",
     "1.pool.ntp.org"
  ]
}
```

### References

This feature is available in Ansible, but we prefer to use Terraform ❤️:
- https://docs.ansible.com/ansible/latest/modules/vmware_host_ntp_module.html#vmware-host-ntp-module
- https://docs.ansible.com/ansible/latest/modules/vmware_host_service_manager_module.html#vmware-host-service-manager-module

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by burnsjared0415** [comment]
can pick this one up also
