### ISSUE TITLE
Upgrade to SDKv2 and deprecate Terraform 0.11

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-provider-vsphere#1132]
### Description

Follow the [upgrade guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html) and [deprecate Terraform 0.11 support](https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers/) in the provider.
### References
* https://github.com/hashicorp/terraform-plugin-sdk/blob/master/CHANGELOG.md

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Wasn't this addressed in https://github.com/hashicorp/terraform-provider-vsphere/pull/1379 and therefore shipped in [v2.0.0](https://github.com/hashicorp/terraform-provider-vsphere/releases/tag/v2.0.0) and later? 

cc @bill-rich 

Ryan

**Comment by tenthirtyam** [comment]
@redeux - Can you review and confirm if this was resolved in the above?

- @tenthirtyam

**Comment by tenthirtyam** [comment]
cc @appilon and @iBrandyJackson to review.

Ryan

**Comment by redeux** [comment]
Sorry I missed your first ping @tenthirtyam. Yes, this issue is resolved.
