### ISSUE TITLE
Error: Virtual machine customization failed on <vm>

### ISSUE THREAD

**Issue by varun2677** [hashicorp/terraform-provider-vsphere#1133]
### Terraform Version
0.12.25

### vSphere Provider Version
terraform-provider-vsphere_v1.21.0_x4 

### Affected Resource(s)

<!--- Please list the resources as a list, for example:
- `vsphere_virtual_machine`

hi, 

we are getting below error while applying customization. however, there is no enough log to figure out why customization failed (though TRACE is enabled). Is there a specific log file get created that we can look to figure out?

Error: Virtual machine customization failed on "../<vm-name>":

An error occurred while customizing VM <vm-name>. For details reference the log file <No Log> in the guest OS.

The virtual machine has not been deleted to assist with troubleshooting. If
corrective steps are taken without modifying the "customize" block of the
resource configuration, the resource will need to be tainted before trying
again. For more information on how to do this, see the following page:
https://www.terraform.io/docs/commands/taint.html

  on vm.tf line 29, in resource "vsphere_virtual_machine" "vm":
  29: resource "vsphere_virtual_machine" "vm" {

thanks,
Varun

**Comment by varun2677** [comment]
hi, 

we are getting below error while applying customization. however, there is no enough log to figure out why customization failed (though TRACE is enabled). Is there a specific log file get created that we can look to figure out?

Error: Virtual machine customization failed on "../<vm-name>":

An error occurred while customizing VM <vm-name>. For details reference the log file <No Log> in the guest OS.

The virtual machine has not been deleted to assist with troubleshooting. If
corrective steps are taken without modifying the "customize" block of the
resource configuration, the resource will need to be tainted before trying
again. For more information on how to do this, see the following page:
https://www.terraform.io/docs/commands/taint.html


  on vm.tf line 29, in resource "vsphere_virtual_machine" "vm":
  29: resource "vsphere_virtual_machine" "vm" {


thanks,
Varun

**Comment by bill-rich** [comment]
Hi @varun2677! 

The first thing to check is that your source VM meets the [requirements](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) for guest OS customization on vSphere. The next would be to run through some customization [troubleshooting](https://kb.vmware.com/s/article/1026317). If everything looks ok on both of those, you can also try [manually setting up customization](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) through the vCenter client. Please note though that the vCenter client will not report failed customization, so you will need to compare the logs on the guest OS.
