### ISSUE TITLE
Cannot create VM we're destroying as the name already exists

### ISSUE THREAD

**Issue by bish0polis** [hashicorp/terraform-provider-vsphere#1141]
### Terraform Version
terraform-0.12.28-1.el7.harbottle.x86_64

### vSphere Provider Version
golang-github-terraform-provider-vsphere-1.13.0-0.1.x86_64

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

I have two nearly-identical TF configs, because I'm a noob and can't figure a better way to differentiate vLANs on my setup in the time I have.

They each feed constructs like:

```hcl
resource "vsphere_virtual_machine" "prd908mischosts" {

  provider = vsphere.prod
  for_each = var.prd908miscmap

  name = each.key
  num_cpus = each.value.num_cpus
  num_cores_per_socket = each.value.corespercpu
  memory   = each.value.ram * 1024
#:
#:
}
```

Moving a host from the 908misc to the 808misc caused the expected 
```
   # vsphere_virtual_machine.prd808mischosts["tstwiki01"] will be destroyed
   # vsphere_virtual_machine.prd908mischosts["tstwiki01"] will be created
```
.. and it happily got to work on the apply phase, where it abruptly died.

You see, it did it in *parallel*, so it was trying the create as it was destroying it.  `VM "tstwiki01" already exists` of course, and it errored out (while still destroying the old VM).

The problem is simple: we know that VM names are unique to a given VC and we can't have two named the same at the same time.  

Can we hook in a check to ensure a resources conflict if their names match, and decide from there whether to modify or delete-before-create ?  

### workaround

After it errors out, plan and apply again.  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Hi @bish0polis! Unfortunately, with your current configuration, there isn't a way to ensure the VM is destroyed before a new one is created. The reason is that since the VM is being moved into a different `vsphere_virtual_machine` name, Terraform is not able to track that they are the same. If possible, I'd recommend trying to find a way to change the configuration so that `vsphere_virtual_machine` (prd808mischosts/prd908mischosts) doesn't change. If you're able to do that, Terraform's lifecycle management will ensure the VM is destroyed first.

**Comment by bish0polis** [comment]
Coincidentally the only thing different between those two TFs is the vLAN settings, or I could merge the configs;  the vLAN, though, became the hardest thing to set in my variables.

Yeah, I understand the reasoning.  Coordinating around that kind of a change is a bit far to go.  

Thanks for the assessment and the easy explanation.
