### ISSUE TITLE
Add support for additional features in `vsphere_distributed_virtual_switch` resource

### ISSUE THREAD

**Issue by codeopen1** [hashicorp/terraform-provider-vsphere#1145]
### Description

Hi. First of all thanks for the plugin.
I would like to implement some functionality in the `distributed_virtual_switch` resource and I just wanted to give notice while I prepare the code for a PR.

Features include:

- PVLAN mappings
- VSPAN (port mirroring) sessions
- Filter policies (maybe)

So far, I have implemented PVLANs but the code is not quite ready for a PR yet.

### Potential Terraform Configuration

Example pvlan mappings:

```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
  # ...

  # VMwareDVSPvlanMapEntry
  pvlan_mapping {
    primary_vlan_id   = 100
    secondary_vlan_id = 100
    pvlan_type        = "promiscuous"
  }

  pvlan_mapping {
    primary_vlan_id   = 100
    secondary_vlan_id = 101
    pvlan_type        = "community"
  }

  pvlan_mapping {
    primary_vlan_id   = 100
    secondary_vlan_id = 102
    pvlan_type        = "isolated"
  }
  
  # Defaults to false
  # ignore_other_pvlan_mappings = true
}
```

It works how you would expect. The `ignore_other_pvlan_mappings` allows you to have unmanaged mappings that won't get overwritten. It also allows you to use the standalone mapping resources which I have implemented (`vsphere_distributed_virtual_switch_pvlan_mapping`). The standalone resource works in a similar way to the AWS provider route_table/route and security_group/security_group_rule. In order to get that to work I have added a global MutexKV object so that the DVS doesn't get reconfigured concurrently.

Feedback is welcome. At this stage, I just wanted to let people know that I've got some code I plan on sharing if possible.

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Hi @codeopen1! That looks like a good method of implementing this feature. Thanks for working on this, and let me know if you run into any problems or questions.

**Comment by tenthirtyam** [comment]
PVLANs added in PR #1146.

If additional enhancements are required for `r/vsphere_distributed_virtual_switch`, please file separate enhancement requests.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
