### ISSUE TITLE
It should be possible to deploy OVF/OVA on direct ESXi connections

### ISSUE THREAD

**Issue by gif30** [hashicorp/terraform-provider-vsphere#1150]
https://github.com/hashicorp/terraform-provider-vsphere/issues/1096
https://stackoverflow.com/questions/38796466/is-vmware-vcenter-server-necessary-for-esxi-terraform

There is a lot of people who would like to see that

**Comment by saintdle** [comment]
This is not possible as terraform uses the API which is not available on ESXi free.
