### ISSUE TITLE
Inconsistent final plan: guest_id other-64 / rhel7_64Guest mismatch

### ISSUE THREAD

**Issue by cloudbustinguk** [hashicorp/terraform-provider-vsphere#1154]
### Terraform Version

0.12.29

### vSphere Provider Version

1.21.1

### Affected Resource(s)

`vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "clone" {
  count            = length(var.vm_data)
  name             = var.machine_config.hostname[count.index]
  folder           = var.folder
  resource_pool_id = var.resource_pool_id
  host_system_id   = var.host_system_id
  datastore_id     = var.datastore_id
  enable_disk_uuid = true
  wait_for_guest_net_timeout = -1
  wait_for_guest_net_routable = false

  num_cpus = var.machine_config.cpu
  memory   = var.machine_config.memory
  guest_id = var.guest_id
. . . 

```

### Debug Output

[Debug output](https://gist.github.com/cloudbustinguk/f5ccc9e0b8984f875caaf0f2f2aa381b)

### Expected Behavior

VM template (well, OVA in a Content Library) is actually cloned, and powered-on. Terraform should exit gracefully.

### Actual Behavior

Terraform dies prematurely. I am unsure as to why this is a showstopper.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I'm using a special/beta build of vCenter (7.0.1) which also support Kubernetes. However, I don't believe this is the culprit.

UPDATE: Have confirmed this is also present when pointing at vCenter 6.7

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mrlesmithjr** [comment]
Just adding that I am seeing this as well...

Terraform version: `0.13.0`
vSphere provider version: `1.22.0`

```bash
Error: Provider produced inconsistent final plan

When expanding the plan for
module.management.vsphere_virtual_machine.gitlab_runner[2] to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/vsphere" produced an invalid new value for
.guest_id: was cty.StringVal("other-64"), but now
cty.StringVal("ubuntu64Guest").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
