### ISSUE TITLE
Add support to attach multiple CD-ROM devices on a virtual machine

### ISSUE THREAD

**Issue by qhua948** [hashicorp/terraform-provider-vsphere#1164]
### Description

Currently, the provider only allows a single `cdrom` block in resource 
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#cdrom-options

I wonder if it is possible to allow for more CDROM block to be declared in Terraform? Similar to the `network` or `disk` block

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "vsphere_virtual_machine" "example" {
  name = ...
  resource_pool = ...

  memory = 2048
  num_cpus = 1
  sata_controller_count = 1

  guest_id = "centos8_64Guest"


  cdrom {
    datastore_id = ...
    path = pathA
    unit_number = 0
  }

  cdrom {
    datastore_id = ...
    path = pathB
    unit_number = 1
  }
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
ℹ️ Supporting context from duplicate / related issue #1624 and the need for >1 CD-ROM support for some OVF/OVA deployments.

> _"Some appliance OVAs (like the cisco 8000v) utilize an ISO for installation and an ISO for initial one-touch configuration._
> 
> _Because the vsphere provider can only attach one CDROM (https://github.com/hashicorp/terraform-provider-vsphere/issues/1164), terraform vm deployments from OVA do not work for these appliances."_

cc: @ckhordiasma
