### ISSUE TITLE
host_system_id is not optional when creating VM from OVA/OVF

### ISSUE THREAD

**Issue by idoob** [hashicorp/terraform-provider-vsphere#1165]
### Terraform Version
Terraform v0.13.0

### vSphere Provider Version
vsphere v1.22.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
...

resource "vsphere_virtual_machine" "vm_from_ovf" {
  name                       = "example_vm_name"
  resource_pool_id           = data.vsphere_compute_cluster.compute_cluster.resource_pool_id
  datastore_id               = data.vsphere_datastore.datastore.id
  datacenter_id              = data.vsphere_datacenter.dc.id
  folder = var.vm_target_folder
  ovf_deploy {
    local_ovf_path       = var.vm_ovf_path
  }
...
}
```

### Debug Output

https://gist.github.com/idoob/3da1a3e8abc607b2841d1c7c91053394

### Expected Behavior

The documentation explains that ```host_system_id``` is optional. Additionally, that if the option is not supplied, then a host from the resource pool will be selected. I tried deploying a vm from an ovf where my resource pool was from a cluster of esxi hosts. I did not want to explicitly define a host within the cluster to put the new VM on. My goal is to have the cluster policy select a host.

Source from documentation: 
```
host_system_id - (Optional) An optional managed object reference ID of a host to put this virtual machine on. See the section on virtual machine migration for details on changing this value. If a host_system_id is not supplied, vSphere will select a host in the resource pool to place the virtual machine, according to any defaults or DRS policies in place.
```

### Actual Behavior

The provider errors out when created a vm if ```host_sysem_id``` is not strictly defined. In ```func resourceVsphereMachineDeployOvfAndOva``` of ```resource_vsphere_virtual_machine.go``` if the hid is not supplied then the function exits with the error: ```host system ID is required for ovf deployment```. 

### Steps to Reproduce
Deploy a vm resource using from an ovf without strictly defining the host_system_id but with a resource_pool defined.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Unfortunately, `host_system_id` is required when deploying an OVA/OVF using the API. If this changes in the future, we can revisit it. In the meantime, you'll need to rely on DRS to relocate the VMs once they're deployed.

**Comment by nmarus** [comment]
I am having the same issue. @bill-rich, are you sure about the requirement of host_system_id? I can this without specifying a individual host with other automation tools if i specify the cluster and if the cluster has drs enabled. 

Not sure if I am looking at the same API you use in the backend but check this out:
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html

> If unset, the server will automatically select a target host from the resource pool if vcenter.ovf.library_item.deployment_target.resource_pool_id is a stand-alone host or a cluster with Distributed Resource Scheduling (DRS) enabled.When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: HostSystem. When operations return a value of this structure as a result, the field will be an identifier for the resource type: HostSystem.
