### ISSUE TITLE
terraform import can't follow variable references in the vsphere provider block 

### ISSUE THREAD

**Issue by darracott** [hashicorp/terraform-provider-vsphere#1169]
### Terraform Version
v0.12.24

### vSphere Provider Version
1.17.4

### Affected Resource(s)
None

This issue affects the provider "vsphere".
```
provider "vsphere" {
  allow_unverified_ssl = var.vsphere_allow_insecure
  password             = var.vsphere_password
  user                 = var.vsphere_username
  vsphere_server       = var.vsphere_server
  version              = "~> 1.17.4"
}
```

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
`terraform import` should start running.

### Actual Behavior
`terraform import` states that the var.<variable>s from the vsphere provider block are not defined.
```
 provider "vsphere" {
  allow_unverified_ssl = var.vsphere_allow_insecure
  password             = var.vsphere_password
  user                 = var.vsphere_username
  vsphere_server       = var.vsphere_server
  version              = "~> 1.17.4"
}
```
However running `terraform validate` passes which shows that these variables are defined. (And in fact we already used the files to create VMs.) 

Rerunning `terraform import`, after explicitly filling in the values, successfully created tfstate for an existing vSphere VM. 
The variables shouldn't need to be explicitly filled in.
```
 provider "vsphere" {
  allow_unverified_ssl = foo
  password             = bar
  user                 = baz
  vsphere_server       = foo2
  version              = "~> 1.17.4"
}
```
Rerunning `terraform import`, after explicitly filling in the values, successfully created tfstate for an existing vSphere VM. 
The variables shouldn't need to be explicitly filled in.

### Steps to Reproduce
1. Create a `variables.tf.json` file which defines say `vsphere_username`.
2. Create another .tf.json file with the values for the variables.
3. Create a main.tf with a vsphere provider block.
4. Run `terraform validate` to check your configuration is valid. (We also ran `terraform apply` and successfully created vSphere VMs).
5. Run `terraform import <args>` with args filled out and see it bail out.
6. Fill in the variable's values straight into the vSphere provider block.
7. Now run `terraform import <args>` with args filled out and it works.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Hi @darracott! I wasn't able to reproduce this issue, but I think you may be able to get some more help at the core terraform repo. It sounds like there must be something conflicting with the two variable files, but I'm not familiar enough to be able to recommend best practices there.
