### ISSUE TITLE
Error: Incorrect attribute value type

### ISSUE THREAD

**Issue by gowthamakanthan** [hashicorp/terraform-provider-vsphere#1170]
### Terraform Version
Terraform v0.12.24

### vSphere Provider Version
+ provider.vsphere v1.22.0

### Affected Resource(s)

- `vsphere provider`

--->

multiple resources are getting affected

### Terraform Configuration Files
In the Module: 

```
provider "vsphere" {
  version              = "~> 1.10"
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}

#In variable.conf

variable "vsphere_user" {
  default = {}
}
variable "vsphere_password" {
  default = {}
}
variable "vsphere_server" {
  default = {}
}
```
While calling the module 
```
module "test-server" {
    source = "../../modules/generic-vm"
}

#In variable.conf 
variable "vsphere_server" {}
variable "vsphere_user" {}
variable "vsphere_password" {}
```
### Panic Output
```
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Incorrect attribute value type

  on ../../modules/generic-vm/provider.tf line 3, in provider "vsphere":
   3:   user                 = var.vsphere_user
    |----------------
    | var.vsphere_user is object with no attributes

Inappropriate value for attribute "user": string required.


Error: Incorrect attribute value type

  on ../../modules/generic-vm/provider.tf line 4, in provider "vsphere":
   4:   password             = var.vsphere_password
    |----------------
    | var.vsphere_password is object with no attributes

Inappropriate value for attribute "password": string required.


Error: Incorrect attribute value type

  on ../../modules/generic-vm/provider.tf line 5, in provider "vsphere":
   5:   vsphere_server       = var.vsphere_server
    |----------------
    | var.vsphere_server is object with no attributes

Inappropriate value for attribute "vsphere_server": string required.
```

### Expected Behavior

Terraform plan should get executed

### Actual Behavior

Throwing the above error

### Steps to Reproduce
Create a module with all variable. Provide the value for the variable using tfvars while calling the module.
Have tried to provide the empty/ null value in the variable block (Module level).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by isometry** [comment]
By setting `default = {}` you are implicitly setting the variable type to `map`. Since the provider expects strings, it generates the errors you see. Change your defaults to `default = ""` or (`type = string` and `default = null`). `null` has the advantage that it leaves you open to providing credentials via either Terraform variable or [standard govmomi environment variable](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs#argument-reference).

**Comment by gowthamakanthan** [comment]
@isometry  Thanks for the explanation. I have tried to set the ```default = ""``` in the root module variable and in the child module as well.  Facing the following error.

Scenerio 1: 
In root module variable.tf :
```
variable "vsphere_user" {
  default = ""
}

variable "vsphere_password" {
   default = ""
}

variable "vsphere_server" {
  default = ""
}
```
In Child module : 

```
module "test-server" {
    source = "../../modules/generic-vm"
    vsphere_server = var.vsphere_server
}
```
in child module variable.tf 
```
variable "vsphere_user" {
  default = ""
}
variable "vsphere_password" {
  default = ""
}

variable "vsphere_server" {
  default = ""
}
```

Error : 

```
Error: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.

  on ../../modules/generic-vm/provider.tf line 1, in provider "vsphere":
   1: provider "vsphere" {
```

Scenario 2:

In root module variable.tf :

```
variable "vsphere_server" {
  default = ""
}

variable "vsphere_user" {
  default = null
}
variable "vsphere_password" {
  default = null
}
```
In child module variable.tf:
```
 variable "vsphere_server" {
  default = ""
}

variable "vsphere_user" {
  default = null
}
variable "vsphere_password" {
  default = null
}
```

Still getting the above error. Vsphere server value passed from tfvar file and trying to pass the credentials as runtime(even tested passing through tfvars).  Any suggestion?

**Comment by isometry** [comment]
Your `provider "vsphere"` block should only be in the root module, and as such you can remove all the current `vsphere_*` variables from the child module.

See the [Provider Configuration](https://www.terraform.io/docs/configuration/providers.html) documentation.

**Comment by gowthamakanthan** [comment]
When i remove the variable for vsphere_* from child, am getting the following error.

```

**Comment by gowthamakanthan** [comment]
When am removing the ```vsphere_*``` from the child variable.tf am getting the following error (Am passing the values in run time).
```
Error: Value for undeclared variable

A variable named "vsphere_user" was assigned on the command line, but the root
module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration.


Error: Value for undeclared variable

A variable named "vsphere_password" was assigned on the command line, but the
root module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration.


Error: Value for undeclared variable

A variable named "vsphere_server" was assigned on the command line, but the
root module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration.

```

**Comment by gowthamakanthan** [comment]
This has been tested successfully by moving the provider details from the root module to the child module. 

Child module having the provider definition along with the other variable details of root module.  please close this.
