### ISSUE TITLE
Dynamic disks added to a `vsphere_virtual_machine` resource should be ignored

### ISSUE THREAD

**Issue by gricuk** [hashicorp/terraform-provider-vsphere#1171]
### Terraform Version
0.12.26
### vSphere Provider Version
1.21.1

### Affected Resource(s)

`vsphere_virtual_machine`

```
      ~ disk {
            attach            = false
            controller_type   = "scsi"
            datastore_id      = "datastore"
            device_address    = "scsi:0:2"
            disk_mode         = "persistent"
            disk_sharing      = "sharingNone"
            eagerly_scrub     = false
            io_limit          = -1
            io_reservation    = 0
            io_share_count    = 1000
            io_share_level    = "normal"
            keep_on_remove    = true
          ~ label             = "orphaned_disk_0" -> "<remove, keep disk>"
        }
```

### Expected Behavior

Terraform should ignore dynamic k8s disks

### Actual Behavior

Terraform was detached disks from vm.

### Steps to Reproduce
1. Create pvc and attach to pod
2. terraform plan

**Comment by pjamenaja** [comment]
Hi,

Not sure if "lifecycle" block as mentioned here https://www.terraform.io/docs/language/meta-arguments/lifecycle.html can solve your issue? Also here https://www.hashicorp.com/blog/detecting-and-managing-drift-with-terraform. I'm facing the same issue on my own K8S cluster using GCE as worker nodes.

Regards,
Seub

**Comment by tenthirtyam** [comment]
As @pjamenaja[ mentions above](https://github.com/hashicorp/terraform-provider-vsphere/issues/1171#issuecomment-886177415), to ignore the dynamic disks added to the virtual machine, use the lifecycle meta-argument in the `vsphere_virtual_machine` resource.

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ...
  lifecycle {
    ignore_changes = [ 
     disk,
   ]
  }
  # ...
}
```

Marking the issue as closed. If the solution (and the latest version of the provider) do not resolve your issue,  please open a new issue and reference this issue for added context.

Ryan
