### ISSUE TITLE
Add support for vCenter Server object permissions

### ISSUE THREAD

**Issue by eshanks16** [hashicorp/terraform-provider-vsphere#1172]
### Description

We want to be able to apply permissions to our vSphere environment through the Terraform provider but there doesn't appear to be a way to attach permissions to the vCenter managed object. DataCenter, Folders, etc are all fine, but the vCenter object is missing.

### References

We were using this as the starting point.
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/vsphere_entity_permissions

Navigating here to find the managed objects.
https://code.vmware.com/apis/968/vsphere

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sumitAgrawal007** [comment]
Help me understand here, which vcenter object type is missing ?

**Comment by isometry** [comment]
@broestls : this is definitely useful, but unless I'm mistaken there's still a case for being able to manage [Global Permissions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-C7702E31-1623-4189-89CB-E1136AA27972.html), for example for controlling permissions on tags and content libraries.

**Comment by dhoeld** [comment]
I'd like to manage Global Permissions as well (for gaining access to the Content Library) via the terraform-provider-vsphere. Is there any possiblity to manage these permissions?

**Comment by tenthirtyam** [comment]
@sumitAgrawal007, do you know if there are plans to add this enhancement?

**Comment by sumitAgrawal007** [comment]
Its on our to-do list, targeted for next month.

**Comment by andyanfieldroad** [comment]
This solved the issue for me also, great response @broestls

**Comment by tenthirtyam** [comment]
The provider support added in in https://github.com/hashicorp/terraform-provider-vsphere/pull/1144; however, there are open issues (#1517) on the implementation and an open enhancement for global permissions. (#1102).

Previous https://github.com/hashicorp/terraform-provider-vsphere/issues/1172#issuecomment-678529987 above shares the solution for the vCenter Server root-level.

Ryan
