### ISSUE TITLE
(0.13) Error on disk provisioning while creating VMs

### ISSUE THREAD

**Issue by mrrandrade** [hashicorp/terraform-provider-vsphere#1182]
### Terraform Version

0.13. Programs run on 0.12 just fine.

### vSphere Provider Version

1.23, but also tried up to 1.20, no difference.

### Affected Resource(s)

* vsphere_virtual_machine

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {
  for_each  = local.vms
  name      = each.value.hostname

  # Configuração do cluster
  resource_pool_id = data.vsphere_compute_cluster.compute_cluster.resource_pool_id
  datastore_cluster_id = data.vsphere_datastore_cluster.cluster_datastore.id
  folder = vsphere_folder.folder.path

  # Configuração comum a todas as máquinas
  # boot_delay = 300000
  cpu_hot_add_enabled = true
  cpu_hot_remove_enabled = true
  guest_id = "coreos64Guest"
  wait_for_guest_net_timeout = 0
  # wait_for_guest_net_routable = false

  num_cpus = 4
  memory   = 8192
  disk {
    label = "${each.value.hostname}-disk"
    # tried with both string and numeric types, same error.
    # size = 100
    size  = "100"
  }

  dynamic "network_interface" {

    for_each = each.value.network

    content {
      network_id = lookup(lookup(data.vsphere_network.networks, network_interface.key), "id")
    }

  }


  # Backups colocam annotations nas VMs
  lifecycle {
    ignore_changes= [
      annotation,
      # "vapp.0.properties",
    ]
  }
}

```

### Debug Output

https://gist.github.com/mrrandrade/02037e6cd4e7cb6c81758084aaa7291f

### Expected Behavior

VM with a disk created and powered up.

### Actual Behavior

Program error. VMware displays the Virtual machine as if its disk is created having 0 as size; some default values ignored (it's thick provisioned, for instance).

Error isn't very helpful:

```
Error: error powering on virtual machine: powerOn task for vm "/DEVSRES-SPO/vm/Kubernetes/lab2/lab2km" failed: Unable to enumerate all disks.
```

### Steps to Reproduce

1. `terraform apply`--->

### Important Factoids

don't think of anything relevant, since it used to work with 0.12.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
Hi @mrrandrade! Are you able to clone the VM manually through the web UI? If so, are you using snapshots on the template VM? It is possible something has gone with the snapshots and the VM being migrated to a different storage device.

**Comment by bill-rich** [comment]
I haven't heard back in a while. If this is still an issue, please let me know and I'll reopen it.
