### ISSUE TITLE
Add support for a flag to force replace of vsphere_virtual_machine

### ISSUE THREAD

**Issue by gmintoco** [hashicorp/terraform-provider-vsphere#1190]
### Description

I am using cloud-init with vsphere and terraform to automatically deploy VMs and bootstrap them. The issue I am facing is that when a modification is made to the cloud init metadata/config after deployment the VM is not replaced and the changes will not take effect (which makes sense as there is no way the provider knows that those 'guestinfo' parameters require a replacement)

You can see below an example configuration for passing data from 'extra_config' into the VM. I realise that this might not be the best way to do this - possibly puppet might work better, but in our use case it doesn't make sense to have the additional infrastructure for something like puppet.

My idea would be to have a boolean flag like 'replace_on_extra_config_modify: true/false' that would force a replacement if anything under extra_config changed. I am open to any other thoughts and suggestions. I think this might also be relevant for general OVF configuration (as only modification to the clone block will force replacement) along with vapp configuration through the vapp block possibly.

### Potential Terraform Configuration

```hcl
resource vsphere_virtual_machine "gitlab_runner" {
  name             = "gitlab-runner-${local.init_hash}.${local.domain_name}"
  resource_pool_id = data.vsphere_compute_cluster.this.resource_pool_id
  datastore_id     = data.vsphere_datastore.this.id

  enable_disk_uuid = true

  num_cpus = 2
  memory   = 4096
  guest_id = data.vsphere_virtual_machine.template.guest_id

  cdrom {
    client_device = true
  }

  network_interface {
    network_id = data.vsphere_network.management.id
  }

  network_interface {
    network_id = data.vsphere_network.aux.id
  }

  wait_for_guest_net_timeout = 0

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  extra_config = {
    "guestinfo.metadata" = base64encode(templatefile("./files/metadata.yaml.template", {
      management_ip      = var.Management_IP
      management_gateway = var.Management_Gateway
      management_subnet  = "24"
      aux_ip         = var.Aux_IP
      aux_gateway    = var.Aux_IP
      aux_subnet     = "24"
      node_hostname      = "gitlab-runner.${local.domain_name}"
    }))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = data.cloudinit_config.runner.rendered
    "guestinfo.userdata.encoding" = "gzip+base64"
  }

  provisioner "remote-exec" {
    inline = [
      "cloud-init status --wait"
    ]

    connection {
      type        = "ssh"
      host        = var.Aux_IP
      user        = var.node_username
      private_key = tls_private_key.ssh.private_key_pem
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Resolved in #1360 with `replace_trigger` in the `vsphere_virtual_machine` resource.

> `replace_trigger` - (Optional) Triggers replacement of resource whenever it changes. replace_trigger = sha256(format("%s-%s",data.template_file.cloud_init_metadata.rendered,data.template_file.cloud_init_userdata.rendered)) will fingerprint the changes in cloud_init metadata and userdata templates. This will enable a replacement of the resource whenever the dependant template renders a new configuration. (Forces a replacement)

Marking as resolved/closed.
