### ISSUE TITLE
Non-inclusive language changes

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-provider-vsphere#1192]
### Description
In line with the company-wide inclusive language changes, conduct a search for non-inclusive language usage in the provider and make the necessary updates.

### References
* https://discuss.hashicorp.com/t/inclusive-language-changes/12797

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment]
There were only a few instances in the code that needed fixing. The last thing we need to do is switch over to using `main`. @aareet, can you please do that? I don't have access to those repo settings.

**Comment by aareet** [comment]
@bill-rich EngServ is building a tool to do them all in one go so just the code changes should be good to close this.
