### ISSUE TITLE
terraform can not delete disks

### ISSUE THREAD

**Issue by azharakbari** [hashicorp/terraform-provider-vsphere#1200]
HI,

I am creating VMs in GCP with primary and secondary disks. When I rerun the scripts, I see error message that the disk cannot be created as it already exists. When I try removing it by removing the relevant code from the script, it doesn't remove it. 

May I know how to deal with this? I can also put if then else type condition, if terraform support something like "if exists then". 

Thanks

**Comment by bill-rich** [comment]
Hi @azharakbari! It sounds like you may be in the wrong repo for this issue. If you're working with GCP, you'll want to report this on https://github.com/hashicorp/terraform-provider-google.
