### ISSUE TITLE
Intermittent non-boot-disk destroy failure due to `Invalid datastore path`

### ISSUE THREAD

**Issue by murrayrogers** [hashicorp/terraform-provider-vsphere#1213]
### Terraform Version
0.13.2

### vSphere Provider Version
1.22.0

### Affected Resource(s)
`vsphere_virtual_disk`

### Terraform Configuration Files

```hcl
provider "local" {
  version = "~> 1.4"
}

provider "vsphere" {
  allow_unverified_ssl = var.vsphere_allow_insecure
  password             = var.vsphere_password
  user                 = var.vsphere_username
  vsphere_server       = var.vsphere_server
  version              = "~> 1.22.0"
}


# Data sources

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  datacenter_id = data.vsphere_datacenter.dc.id
  name          = var.vsphere_datastore[count.index]
  count         = length(var.vsphere_datastore)
}

data "vsphere_network" "internet" {
  datacenter_id = data.vsphere_datacenter.dc.id
  name          = var.internet_net_id
}

data "vsphere_network" "management" {
  datacenter_id = data.vsphere_datacenter.dc.id
  name          = var.management_net_id
}

data "vsphere_resource_pool" "pool" {
  count         = length(var.vsphere_resource_pool_name)
  datacenter_id = data.vsphere_datacenter.dc.id
  name          = var.vsphere_resource_pool_name[count.index]
}

data "vsphere_virtual_machine" "template" {
  datacenter_id = data.vsphere_datacenter.dc.id
  name          = var.image
}

# Resource declarations

resource "local_file" "user_data_json" {
  content  = templatefile("${path.module}/foo_metadata_template.yaml",
    {
      TIMEZONE = trim(jsonencode(var.timezone), "\""),
    ...
    }
  )
  count    =  3
  filename = "${var.node_names[count.index]}_userdata.json"
}

resource "vsphere_virtual_disk" "foo_diags_disks" {
  size         = 2
  # vmdk_path should not contain a folder name unless using a vSAN datastore - this configuration is for non vSAN
  vmdk_path    = "${var.node_names[count.index]}_disk_diags.vmdk"
  datacenter   = var.vsphere_datacenter
  datastore    = data.vsphere_datastore.datastore[count.index].name
  count        = 3
  type         = "thin"
}

resource "vsphere_virtual_disk" "foo_etcd_disks" {
  size         = 2
  # vmdk_path should not contain a folder name unless using a vSAN datastore - this configuration is for non vSAN
  vmdk_path    = "${var.node_names[count.index]}_disk_etcd.vmdk"
  datacenter   = var.vsphere_datacenter
  datastore    = data.vsphere_datastore.datastore[count.index].name
  count        = 3
  type         = "thin"
}

resource "vsphere_virtual_machine" "foo_vms" {
  clone {
    template_uuid    = data.vsphere_virtual_machine.template.id
  }
  count              = 3
  datastore_id       = data.vsphere_datastore.datastore[count.index].id

  depends_on         = [local_file.user_data_json]
  disk {
    datastore_id     = data.vsphere_datastore.datastore[count.index].id
    label            = "disk0"
    keep_on_remove   = false
    size             = var.boot_disk_size
    thin_provisioned = true
  }
  disk {
    datastore_id     = data.vsphere_datastore.datastore[count.index].id
    label            = "disk1"
    unit_number      = 1
    attach           = true
    path             = vsphere_virtual_disk.foo_diags_disks[count.index].vmdk_path
  }
  disk {
    datastore_id     = data.vsphere_datastore.datastore[count.index].id
    label            = "disk2"
    unit_number      = 2
    attach           = true
    path             = vsphere_virtual_disk.foo_etcd_disks[count.index].vmdk_path
  }
  enable_logging     = true
  folder             = var.vsphere_folder[count.index]
  guest_id           = data.vsphere_virtual_machine.template.guest_id
  memory             = var.memory
  name               = var.node_names[count.index]
  network_interface {
    network_id       = data.vsphere_network.management.id
  }
  network_interface {
    network_id       = data.vsphere_network.internet.id
  }
  num_cpus           = var.cpu
  resource_pool_id   = data.vsphere_resource_pool.pool[count.index].id
  vapp {
    properties = {
      user-data = base64encode(local_file.user_data_json[count.index].content)
      public-keys = "ssh-rsa <snip>"
    }
  }
  wait_for_guest_net_timeout = 15
}
```

### Debug Output

https://gist.github.com/murrayrogers/7523a3779fda3c4c8d82eb7953f2668f

### Panic Output

n/a

### Expected Behavior

When running `terraform destroy`, all VMs and disks are destroyed.

### Actual Behavior

When running `terraform destroy`, VMs deleted OK, but then it fails with:

```
Error: Invalid datastore path '/vmfs/volumes/5c87e0ff-7ff91d1a-74e5-b8ca3a5cc000/foo-2_disk_etcd.vmdk'.
```

This disk corresponds to `module.foo.vsphere_virtual_disk.foo_etcd_disks[1]`, which is still present on vSphere.  Re-running the `terraform destroy` command later did work.

### Steps to Reproduce

1. `terraform apply` 
2. `terraform destroy` - though it doesn't hit this every time, it looks to be some kind of race/window condition (believed introduced between `v1.17.4` and `v1.22.0`.

### Important Factoids

This issue has been seen intermittently (about one time in three), but multiple times, using provider `v1.22.0`, having never been seen at `v1.17.4` (which we were using previously).  Changelog / git diffs suggest there are multiple disk-related changes in that window, but none immediately pointed me at a cause.

It's not been seen on VMs which have a boot disk only - it does seem specific to having additional non-boot disks.

I'm unclear where how the given path is built, as the disk (in vSphere UI terms) is simply '[Datastore]/foo-2_disk_etcd.vmdk' (i.e. the root of the datastore), not '/vmfs/volumes/5c87e0ff-7ff91d1a-74e5-b8ca3a5cc000/foo-2_disk_etcd.vmdk'.  See e.g. https://kb.vmware.com/s/article/2013832 which talks around the invalidity of the latter form.

### References

None

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
This can be addressed with a `depends_on` added to the resource mapped to the `vsphere_virtual_disk` resources.

During the destroy, the `vsphere_virtual_machine` would be destroyed first followed by the resources on which it had a dependency. This is why the second pass of the plan worked.

For example:

```hcl
resource "vsphere_virtual_machine" "foo_vms" {
  depends_on = [
    vsphere_virtual_disk.foo_diags_disk,
    vsphere_virtual_disk.foo_etcd_disk
  ]
  # ... other configuration ...
}

Marking as closed based on time since open and no reactions to the original issue.

Ryan
