### ISSUE TITLE
Provide the of necessary privileges for least-privileged user access

### ISSUE THREAD

**Issue by mayamamoto** [hashicorp/terraform-provider-vsphere#1216]
To whom it may concern,

This is a general question. We started to look into the vSphere provider, but we only have access to a non-privileged user. We can provision a virtual machine, but Terraform fails with an error afterwards (attached in Actual Behavior and Debug Output section). Is there a list of permissions I can provide to my VMware admins? They've mentioned that the "StorageProfile.View" permission is attached to my user already, despite the error.

I've reviewed [this link](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs#notes-on-required-privileges), however having a hard time coming up with a list of permissions. Any help is appreciated. Thank you.

### Terraform Version

v0.12.29

### vSphere Provider Version

v1.24.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

Any

### Debug Output

```
{
  "RuntimeFaultFault": {
    "@xsi:type": "vim25:NoPermission",
    "@xmlns": "urn:pbm",
    "@xmlns:pbm": "urn:pbm",
    "@xmlns:vim25": "urn:vim25",
    "vim25:object": {
      "@type": "Folder",
      "#text": "group-d1"
    },
    "vim25:privilegeId": "StorageProfile.View"
  }
}
```

### Panic Output

n/a

### Expected Behavior

n/a

### Actual Behavior

```
Error: ServerFaultCode: NoPermission: RESOURCE (vm-18863), ACTION (queryAssociatedProfile): RESOURCE (vm-18863), ACTION (PolicyIDByVirtualMachine)

  on main.tf line 1, in resource "vsphere_virtual_machine" "test":
   1: resource "vsphere_virtual_machine" "test" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

n/a

### References

n/a

**Comment by punsoong** [comment]
#1109 is a similar issue and the same error I have (error loading default device list: NoPermission)

**Comment by prk0ghy** [comment]
I had a similar issue. I fixed it by adding role permissions to my terraform unprivileged user.

P: Host profile
--> View

P: Profile-driven storage
--> Profile-driven storage view

P: Storage views
--> View

I do not know which one is the correct one but I can run some tests if you want.

**Comment by pascal-hofmann** [comment]
I had the same issue. Adding permission "Profile-driven storage view" solved the issue.

**Comment by tenthirtyam** [comment]
Per the debug:

```
{
  "RuntimeFaultFault": {
    "@xsi:type": "vim25:NoPermission",
    "@xmlns": "urn:pbm",
    "@xmlns:pbm": "urn:pbm",
    "@xmlns:vim25": "urn:vim25",
    "vim25:object": {
      "@type": "Folder",
      "#text": "group-d1"
    },
    "vim25:privilegeId": "StorageProfile.View"
  }
}
```

`StorageProfile.View` is `Profile-driven storage.Profile-driven storage view` in the UI.

Ryan

**Comment by betweenclouds** [comment]
We have the same issue, but because we practice Least-Privilege we don't want to get the user "StorageProfile.View" on top level.
Is it an option, that the provider just use the default, like the UI or govc? Both are working without "StorageProfile.View".

**Comment by tenthirtyam** [comment]
The provider implementation requires this privilege.
