### ISSUE TITLE
Need to Clone a VM add extra disks and the format them one by one

### ISSUE THREAD

**Issue by darthVikes** [hashicorp/terraform-provider-vsphere#1225]
### Terraform Version
Terraform v0.13.4

### vSphere Provider Version
+ provider registry.terraform.io/hashicorp/vsphere v1.24.0

### Terraform Configuration Files

--- adding just the resource section here that would be pertinent ----

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = var.ServerName

  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id = data.vsphere_datastore.datastore.id

  num_cpus = var.TypeCPU
  memory   = var.TypeMemory

  guest_id = data.vsphere_virtual_machine.template.guest_id
  #scsi_type = data.vsphere_virtual_machine.template.scsi_type
  scsi_type = "pvscsi"
  scsi_controller_count = 4

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
     label            = "disk0"
     size             = var.DriveC
     thin_provisioned = "true"
     unit_number      = 0
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      windows_options {
        computer_name  = var.ServerName
        workgroup      = "campus"
        admin_password = var.LocalAdminPW
        auto_logon = true
        auto_logon_count = 1
        time_zone = "020"
        run_once_command_list = [
          "winrm quickconfig -force",
          "winrm set winrm/config @{MaxEnvelopeSizekb=\"100000\"}",
          "winrm set winrm/config/Service @{AllowUnencrypted=\"true\"}",
          "winrm set winrm/config/Service/Auth @{Basic=\"true\"}",
          "netsh advfirewall set allprofiles state off",
        ]
      }

      network_interface {}

      ipv4_gateway = var.NetworkGateway
      dns_server_list =  [ var.NetworkDNS1, var.NetworkDNS2 ]
      dns_suffix_list =  [ var.NetworkSearch1, var.NetworkSearch2, var.NetworkSearch3, var.NetworkSearch4 ]

    }
   }

   provisioner "file" {
        source      =  "./scripts"
        destination = "c:/tech/scripts/"
   }

   connection {
        host      = vsphere_virtual_machine.vm.default_ip_address
        type     = "winrm"
        https    = false
        user     = "Administrator"
        password = var.LocalAdminPW
        agent    = false
        insecure = true
   }

   disk {
        label            = "disk1"
        size             = var.DriveD
        thin_provisioned = "true"
        unit_number      = 1
   }

   provisioner "remote-exec" {
     inline = [ "powershell.exe c:\\tech\\scripts\\setDiskOnlineSingleTF.ps1 -icDriveLetter D" ]
   }

   disk {
        label            = "disk2"
        size             = var.DriveE
        thin_provisioned = "true"
        unit_number      = 15
   }

   provisioner "remote-exec" {
     inline = [ "powershell.exe c:\\tech\\scripts\\setDiskOnlineSingleTF.ps1 -icDriveLetter E" ]
   }

   disk {
        label            = "disk3"
        size             = var.DriveL
        thin_provisioned = "true"
        unit_number      = 16
   }

   provisioner "remote-exec" {
     inline = [ "powershell.exe c:\\tech\\scripts\\setDiskOnlineSingleTF.ps1 -icDriveLetter L" ]
   }


}

```

### Expected Behavior

Wanting the disk to be created, and then the PowerShell to run to format the disk, and repeat for each new disk that is going to be added before the next disk actually is added.

### Actual Behavior

Seems like all of the disks are added and it doesn't wait for the PowerShell script to run before adding the next disk

Perhaps there is a better way to do this?  But its very important that the PowerShell runs before the next disk is added as that is the easiest way to find the disk on the windows side and get it onlined and formatted that I have found.

### Important Factoids

The powershell script basically looks for a new RAW disk that has been added and online's the disk, format's it, and gives it a drive letter that is specified and does work correctly when only one disk is added at a time.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @darthVikes,

This issue is rather stale but checking in to see if you were able to derive a solution for your use case. 

All disks would be added at the creation of the resource or with subsequent applies of the plan if the disks change vs one-by-one.

Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as closed as this use case is not addressable by Terraform or the provider.

**Ryan Johnson**
Staff II Solutions Architect, VMware
