### ISSUE TITLE
`vsphere_virtual_machine` resource fails when deployed synchronously with a subscribed `vsphere_content_library` resource

### ISSUE THREAD

**Issue by nvibert** [hashicorp/terraform-provider-vsphere#1228]
### Terraform Version
Terraform v0.13.0

### vSphere Provider Version
v1.24.1

### Affected Resource(s)

- `vsphere_virtual_machine`
- `vsphere_content_library_item`

### Terraform Configuration Files

```hcl
resource "vsphere_content_library" "subscribedlibrary_terraform" {
  name            = "New Subscribed Library by Terraform"
  storage_backing = [data.vsphere_datastore.datastore.id]
  description     = "Another new source of content"
  subscription {
      subscription_url = "https://s3-us-west-2.amazonaws.com/s3-vmc-iso/lib.json"
      authentication_method = "NONE"
      automatic_sync = true
      on_demand = false
  }
}

data "vsphere_content_library_item" "library_item_photon" {
  name       = "Photon"
  library_id = vsphere_content_library.subscribedlibrary_terraform.id
  type = "OVA"
}

resource "vsphere_virtual_machine" "vm_terraform_from_cl" {
  name             = "vm_terraform_from_cl"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = "Workloads"
  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"
  clone {
    template_uuid = data.vsphere_content_library_item.library_item_photon.id
    }
  }
}
```

### Expected Behavior

What I was expecting was:
1) Content Library is deployed
2) The Content Library subscribes to an existing remote one
3) The Content Library item UUID is extracted by Terraform
4) VM deployed based on UUID is created

Steps 1-3 worked perfectly when I did "terraform apply" but the VM deployment failed with the following error message:

vsphere_virtual_machine.vm_terraform_from_cl: Creating...
 
Error: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.invalid_argument","value":{"error_type":"INVALID_ARGUMENT","messages":[{"args":[],"default_message":"Specified library item is not an OVF.","id":"com.vmware.ovfs.ovfs-main.ovfs.invalid_library_item"}]}}
 
  on main.tf line 59, in resource "vsphere_virtual_machine" "vm_terraform_from_cl":
  59: resource "vsphere_virtual_machine" "vm_terraform_from_cl" {

When I waited a few seconds and tried again with a "terraform apply", the VM was successfully deployed:

vsphere_virtual_machine.vm_terraform_from_cl: Creating...
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [10s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [20s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [30s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [40s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [50s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm_terraform_from_cl: Creation complete after 1m22s [id=422acb3e-ad7a-727c-27bb-27835c9de895]

It seems to indicate an issue with timing with the subscription/library item being ready for use.

### Steps to Reproduce

As mentioned above, a first "terraform apply" will create the library and the library item successfully but the VM deploy will fail. 

When repeating "terraform apply" seconds/minutes later, the VM will be deployed as expected.

### References

I documented this issue on this blog post:
https://nicovibert.com/2020/10/12/terraform-for-vsphere-content-library-support/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gchek** [comment]
Seeing same behaviour with the fact that the Content Library is deployed but we try to read from it too quickly.
```
resource "vsphere_content_library" "S3CL" {
  name            = "S3CL"
  storage_backing = [data.vsphere_datastore.datastore.id]
  description     = "AWS S3 Content Library"
  subscription {
    subscription_url = "https://s3.eu-central-1.amazonaws.com/s3-cl-frankfurt/lib.json"
    authentication_method = "NONE"
    automatic_sync = false
    on_demand = true
  }
}
data "vsphere_content_library_item" "DSL" {
  depends_on = [vsphere_content_library.S3CL]
  name       = "DSL4-4-10"
  library_id = vsphere_content_library.S3CL.id
  type = "OVF"
}
```
I don't think  the `depends_on` is necessary and doesn't make any difference.
error message is on the "data "`vsphere_content_library_item" "DSL" {`" statement.

```
module.VMs.vsphere_tag_category.category: Creating...
module.VMs.vsphere_content_library.S3CL: Creating...
module.VMs.vsphere_tag_category.category: Creation complete after 0s [id=urn:vmomi:InventoryServiceCategory:6624399d-36dd-40b4-810d-b664e688d375:GLOBAL]
module.VMs.vsphere_tag.tag: Creating...
module.VMs.vsphere_tag.tag: Creation complete after 2s [id=urn:vmomi:InventoryServiceTag:bf53432c-d029-4c4b-acf8-189e63c5b703:GLOBAL]
module.VMs.vsphere_content_library.S3CL: Creation complete after 4s [id=b88001a4-10ed-4a84-80ac-f0eb49520e0a]
module.VMs.data.vsphere_content_library_item.DSL: Refreshing state...

Error: Unable to find content library item (DSL4-4-10): RESOURCE (DSL4-4-10), ACTION (dataSourceVSphereContentLibraryItemRead)

  on ../VMs/VMs.tf line 64, in data "vsphere_content_library_item" "DSL":
  64: data "vsphere_content_library_item" "DSL" {

```
doing a `terraform apply` after a min or so goes through OK

**Comment by gchek** [comment]
Update:
Deployed a VMC 1.12 SDDC today and this issue is gone. I guess it was a content lib  issue in VMC vCenter 1.11

**Comment by nvibert** [comment]
Update to the update:

I still see this issue with SDDC 1.12 :-D 
I think Gilles just got lucky ! 

I still think there's an issue with the timing.

**Comment by dkirrane** [comment]
hitting the same issue, What type should I use for OVA? 
Is OVA not supported? https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/content_library_item#type

```
data "vsphere_content_library_item" "item" {
  name       = "my-tmpl"
  library_id = data.vsphere_content_library.library.id
  type       = "vm-template"
}
```

**Comment by gchek** [comment]
OVA is supported use 
```
data "vsphere_content_library_item" "blue" {
  name       = "blue"
  library_id = vsphere_content_library.S3CL.id
  type = "OVA"
}
```

**Comment by rahul-padhee** [comment]
I am also trying to create a VM using a template which is already present in a content Library. I published the content library and used the subscription URL in the content library that I am creating using terraform. 
1. The ova template is not getting copied properly to the new content library that is subscribed to an old content library having the ova file
2. The size of the ova getting copied to the new content library is of 0 byte size and probably thats the reason I am getting the below error:

Error: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.invalid_argument","value":{"messages":[{"args":[],"default_message":"Specified library item is not an OVF.","id":"com.vmware.ovfs.ovfs-main.ovfs.invalid_library_item"}]}}

  on vmware.tf line 113, in resource "vsphere_virtual_machine" "cloned_virtual_machine":
 113: resource "vsphere_virtual_machine" "cloned_virtual_machine" {


TERRAFORM FILE:

## Specifying the provider in terraform file
provider "vsphere" {
  user           = "user@vsphere.local"
  password       = "xxxxxxx"
  vsphere_server = "10.2.1.10"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

# variable passed for esxi host name - already exists in vsphere
variable "esxihost" {
  description = "input your esxi host name"
  default = "10.25.112.19"
}

variable "contentLib" {
  description = "enter the name of the content library"
  default = "SIEM devices"
}

variable "templateUUID"{
  description = "input the template UUID"
  default = "urn:vapi:com.vmware.content.library.Item:b5dd245d-05ce-4252-aa1a-63e204c9f52b"
}

# specifying content library details for further use:

data "vsphere_content_library" "existing_library" {
#  name       = "${var.contentLib}"
  name        = "SIEM devices"
}

# specifying the datacenter - already exists in vsphere
data "vsphere_datacenter" "dc" {
  name = "SIEM"
}

# specifying the data store name - already exists in vsphere
data "vsphere_datastore" "datastore" {
  name          = "10.25.112.19 Local 1"
#  name          = "TrueNAS-HLO shared iscsi"
  datacenter_id = data.vsphere_datacenter.dc.id
}

# specifying the resource pool name - already exists in vsphere

data "vsphere_resource_pool" "pool" {
  name          = "TerraformTest"
  datacenter_id = data.vsphere_datacenter.dc.id
}

# specifying the network name - which already exists  in vsphere
data "vsphere_network" "network" {
#  name          = "10.25.112.0"
  name          = "10.25.126.0"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network13" {
  name          = "10.25.112.0"
  datacenter_id = data.vsphere_datacenter.dc.id
}

# specifying the host name - already exists in vsphere - passed through variable content
data "vsphere_host" "host" {
#  name          = "172.26.112.28"
  name          = "${var.esxihost}"
  datacenter_id = data.vsphere_datacenter.dc.id
}



resource "vsphere_content_library" "library" {
  name            = "TerraformTestLibrary"
  storage_backing = [data.vsphere_datastore.datastore.id]
  description     = "Test library for testing terraform"
}

resource "vsphere_content_library" "subscribedLib" {
  name            = "SubscribedLibByTerra123"
  storage_backing = [data.vsphere_datastore.datastore.id]
  description     = "Another new source of content"
  subscription {
      subscription_url = "https://vcenter.siem.corpzone.internalzone.com:443/cls/vcsp/lib/27676df1-585c-40e0-b273-87981e245c7a/lib.json"
      authentication_method = "NONE"
      automatic_sync = true
      on_demand = false
  }
}

data "vsphere_content_library_item" "library_template" {
  depends_on = [vsphere_content_library.subscribedLib]
  name       = "enmelm_8CPU_11.4.2_20210108232509"
  library_id = vsphere_content_library.subscribedLib.id
  type = "OVF"
}

resource "vsphere_virtual_machine" "cloned_virtual_machine" {
  name             = "VMTest-Terraform"
#  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
#  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  host_system_id   = data.vsphere_host.host.id
#  datacenter_id    = data.vsphere_datacenter.dc.id  


  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
#    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
    adapter_type = "vmxnet3" 
  }

  disk {
   size             = 16
   name             = "test2.vmdk"
   eagerly_scrub    = false
   thin_provisioned = true
  }

  clone {
#    template_uuid = "${data.vsphere_virtual_machine.template.id}"
     template_uuid = "${data.vsphere_content_library_item.library_template.id}"
#     template_uuid = "urn:vapi:com.vmware.content.library.Item:b5dd245d-05ce-4252-aa1a-63e204c9f52b"
#     template_uuid = "${var.templateUUID}"
  }
}

******************************** This is a production requirement where I need to automate the creation of vms using OVAs stored in remote artifactory. I started trying with remote OVA template url, then local OVA template but nothing worked. Finally I am trying to deploy using OVAs stored in content library but doesnt work either. 
CAN SOMEONE PLEASE HELP

**Comment by tenthirtyam** [comment]
@nvibert @gchek did you ever try this with the depends_on and hashicorp/time?

Ryan

**Comment by tenthirtyam** [comment]
Hi @nvibert and @gchek, below is a basic example that would address this use case. 

The example uses the following:
- Terraform v1.1.4
- Terraform Provider for VMware vSphere v2.0.2
- VMware vSphere v7.0.3c

### The basic plan.

`versions.tf`

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.2"
    }
    time = {
      source  = "hashicorp/time"
      version = "0.7.2"
    }

  }
  required_version = ">= 1.1.4"
}
```

`variables.tf`

```hcl
# Credentials

variable "vsphere_server" {
  type        = string
  description = "The fully qualified domain name or IP address of the vCenter Server instance. (e.g. sfo-w02-vc01.sfo.rainpole.io)"
}

variable "vsphere_username" {
  type        = string
  description = "The username to login to the vCenter Server instance."
  sensitive   = true
}

variable "vsphere_password" {
  type        = string
  description = "The password for the login to the vCenter Server instance."
  sensitive   = true
}

variable "vsphere_insecure" {
  type        = bool
  description = "Set to true for self-signed certificates."
  default     = false
}

# vSphere Settings

variable "vsphere_datacenter" {
  type = string
}

variable "vsphere_cluster" {
  type = string
}

variable "vsphere_datastore" {
  type = string
}

variable "vsphere_folder" {
  type = string
}

variable "vsphere_network" {
  type = string
}

variable "vsphere_content_library_ovf" {
  type = string
}

# Content Library Settings

variable "vsphere_content_library_name" {
  type = string
}

variable "vsphere_content_library_description" {
  type = string
}

variable "vsphere_content_library_subscription_url" {
  type = string
}

variable "vsphere_content_library_automatic_sync" {
  type    = bool
  default = "true"
}

variable "vsphere_content_library_on_demand" {
  type    = bool
  default = "false"
}

# Virtual Machine Settings

variable "vm_name" {
  type = string
}

variable "vm_cpus" {
  type = number
}

variable "vm_memory" {
  type = number
}

variable "vm_disk_size" {
  type = number
}

variable "vm_firmware" {
  type = string
}

variable "vm_guest_id" {
  type = string
}

variable "vm_thin_provisioned" {
  type = bool
}

variable "vm_efi_secure_boot_enabled" {
  type = bool
}

variable "vm_hostname" {
  type = string
}

variable "vm_domain" {
  type = string
}

variable "vm_ipv4_address" {
  type = string
}

variable "vm_ipv4_netmask" {
  type = string
}

variable "vm_ipv4_gateway" {
  type = string
}

variable "vm_dns_suffix_list" {
  type = list(string)
}

variable "vm_dns_server_list" {
  type = list(string)
}
```

`main.tf`

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

provider "time" {
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_content_library" "content_library" {
  depends_on = [
    vsphere_content_library.content_library
  ]
  name = var.vsphere_content_library_name
}

data "vsphere_content_library_item" "content_library_item" {
  depends_on = [
    vsphere_content_library.content_library,
    time_sleep.nap
  ]
  name       = var.vsphere_content_library_ovf
  type       = "ovf"
  library_id = data.vsphere_content_library.content_library.id
}

resource "vsphere_content_library" "content_library" {
  name            = var.vsphere_content_library_name
  description     = var.vsphere_content_library_description
  storage_backing = toset([data.vsphere_datastore.datastore.id])
  subscription {
    subscription_url = var.vsphere_content_library_subscription_url
    automatic_sync   = var.vsphere_content_library_automatic_sync
    on_demand        = var.vsphere_content_library_on_demand
  }
}

resource "time_sleep" "nap" {
  depends_on = [
    vsphere_content_library.content_library
  ]
  create_duration = "120s"
}

resource "vsphere_virtual_machine" "vm" {
  depends_on = [
    data.vsphere_content_library_item.content_library_item
  ]
  name                    = var.vm_name
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = var.vm_guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = var.vm_disk_size
    thin_provisioned = var.vm_thin_provisioned
    datastore_id     = data.vsphere_datastore.datastore.id
  }
  clone {
    template_uuid = data.vsphere_content_library_item.content_library_item.id
    customize {
      linux_options {
        host_name = var.vm_hostname
        domain    = var.vm_domain
      }
      network_interface {
        ipv4_address = var.vm_ipv4_address
        ipv4_netmask = var.vm_ipv4_netmask
      }

      ipv4_gateway    = var.vm_ipv4_gateway
      dns_suffix_list = var.vm_dns_suffix_list
      dns_server_list = var.vm_dns_server_list
    }
  }
  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
}
```

`terraform.tfvars`

```hcl
# Credentials

vsphere_server   = "m01-vc01.rainpole.io"
vsphere_username = "administrator@vsphere.local"
vsphere_password = "VMware1!"
vsphere_insecure = true

# vSphere Settings

vsphere_datacenter = "m01-dc01"
vsphere_datastore  = "remote-nfs"
vsphere_cluster    = "m01-cl01"
vsphere_folder     = "workloads"
vsphere_network    = "M - 172.16.11.0"

# Content Library Settings

vsphere_content_library_ovf              = "linux-ubuntu-18.04lts-v22.01"
vsphere_content_library_name             = "m01-lib02"
vsphere_content_library_description      = "Subscribed Content Library for sfo-w02."
vsphere_content_library_subscription_url = "https://m01-vc01.rainpole.io:443/cls/vcsp/lib/93feb9f7-2926-4cbd-9b61-d78369646e83/lib.json"
vsphere_content_library_automatic_sync   = true
vsphere_content_library_on_demand        = false

# Virtual Machine Settings

vm_name                    = "ubuntu-test"
vm_cpus                    = 2
vm_memory                  = 4096
vm_disk_size               = 40960
vm_firmware                = "efi"
vm_guest_id                = "ubuntu64Guest"
vm_efi_secure_boot_enabled = true
vm_thin_provisioned        = true
vm_hostname                = "ubuntu-test"
vm_domain                  = "rainpole.io"
vm_ipv4_address            = "172.16.11.110"
vm_ipv4_netmask            = "24"
vm_ipv4_gateway            = "172.16.11.1"
vm_dns_suffix_list         = ["rainpole.io"]
vm_dns_server_list         = ["172.16.11.11", "172.16.11.12"]
```

### The Results

```console
❯ terraform apply --auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.vsphere_content_library.content_library will be read during apply
  # (config refers to values not yet known)
 <= data "vsphere_content_library" "content_library"  {
      + id   = (known after apply)
      + name = "m01-lib02"
    }

  # data.vsphere_content_library_item.content_library_item will be read during apply
  # (config refers to values not yet known)
 <= data "vsphere_content_library_item" "content_library_item"  {
      + id         = (known after apply)
      + library_id = (known after apply)
      + name       = "linux-ubuntu-18.04lts-v22.01"
      + type       = "ovf"
    }

  # time_sleep.nap will be created
  + resource "time_sleep" "nap" {
      + create_duration = "120s"
      + id              = (known after apply)
    }

  # vsphere_content_library.content_library will be created
  + resource "vsphere_content_library" "content_library" {
      + description     = "Subscribed Content Library for sfo-w02."
      + id              = (known after apply)
      + name            = "m01-lib02"
      + storage_backing = [
          + "datastore-11",
        ]

      + publication {
          + authentication_method = (known after apply)
          + password              = (known after apply)
          + publish_url           = (known after apply)
          + published             = (known after apply)
          + username              = (known after apply)
        }

      + subscription {
          + authentication_method = "NONE"
          + automatic_sync        = true
          + on_demand             = false
          + password              = (known after apply)
          + subscription_url      = "https://m01-vc01.rainpole.io:443/cls/vcsp/lib/93feb9f7-2926-4cbd-9b61-d78369646e83/lib.json"
          + username              = (known after apply)
        }
    }

  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-11"
      + default_ip_address                      = (known after apply)
      + efi_secure_boot_enabled                 = true
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "efi"
      + folder                                  = "workloads"
      + force_power_off                         = true
      + guest_id                                = "ubuntu64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = (known after apply)
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 4096
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "ubuntu-test"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 2
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-6046"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = (known after apply)
          + timeout       = 30

          + customize {
              + dns_server_list = [
                  + "172.16.11.11",
                  + "172.16.11.12",
                ]
              + dns_suffix_list = [
                  + "rainpole.io",
                ]
              + ipv4_gateway    = "172.16.11.1"
              + timeout         = 10

              + linux_options {
                  + domain       = "rainpole.io"
                  + host_name    = "ubuntu-test"
                  + hw_clock_utc = true
                }

              + network_interface {
                  + ipv4_address = "172.16.11.110"
                  + ipv4_netmask = 24
                }
            }
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "datastore-11"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 40960
          + storage_policy_id = (known after apply)
          + thin_provisioned  = true
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-1001"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.
vsphere_content_library.content_library: Creating...
vsphere_content_library.content_library: Creation complete after 1s [id=9ddbef86-98e7-432f-95d9-23a1a68af197]
data.vsphere_content_library.content_library: Reading...
time_sleep.nap: Creating...
data.vsphere_content_library.content_library: Read complete after 0s [id=9ddbef86-98e7-432f-95d9-23a1a68af197]
time_sleep.nap: Still creating... [10s elapsed]
time_sleep.nap: Still creating... [20s elapsed]
time_sleep.nap: Still creating... [30s elapsed]
time_sleep.nap: Still creating... [40s elapsed]
time_sleep.nap: Still creating... [50s elapsed]
time_sleep.nap: Still creating... [1m0s elapsed]
time_sleep.nap: Still creating... [1m10s elapsed]
time_sleep.nap: Still creating... [1m20s elapsed]
time_sleep.nap: Still creating... [1m30s elapsed]
time_sleep.nap: Still creating... [1m40s elapsed]
time_sleep.nap: Still creating... [1m50s elapsed]
time_sleep.nap: Creation complete after 2m0s [id=2022-01-31T22:40:27Z]
data.vsphere_content_library_item.content_library_item: Reading...
data.vsphere_content_library_item.content_library_item: Read complete after 0s [id=6749253b-3c7b-44c8-86bb-b488e4866037]
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m30s elapsed]
vsphere_virtual_machine.vm: Creation complete after 1m31s [id=42023f76-c8b9-852c-2192-c8b1a57c75cd]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

As you can see above, using `hashicorp/time` I put I created a `time_sleep` resource in which the `vsphere_content_library_item` data source is dependent, and in turn, the `time_sleep` resource is dependent on the ``vsphere_content_library` resource.

This provided the ability to create the subscribed content library, pause for 120 seconds while OVF templates synced, and then deploy a virtual machine from one of the OVF templates.

Generally, I'd recommend that these are resources are managed separately; however, the solution above demonstrates that the use case is entirely possible.

Ryan Johnson
Staff II Solutions Architect, VMware, Inc.
VMware Validated Solutions Engineering          
[credly.com/users/tenthirtyam](https://credly.com/users/tenthirtyam)

cc @appilon for issue and solution review

**Comment by tenthirtyam** [comment]
Hi @nvibert and @gchek,

Marking this issue as resolved based on the detailed [solution example](https://github.com/hashicorp/terraform-provider-vsphere/issues/1228#issuecomment-1026292915) provided in the previous comment for this use case. Generally, I'd recommend that these are resources are managed separately; however, the solution above demonstrates that the use case is entirely possible.

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
