### ISSUE TITLE
Openshift 4.5.15 installation failed on vsphere 6.7, terraform version: 

### ISSUE THREAD

**Issue by yukselao** [hashicorp/terraform-provider-vsphere#1240]
### Terraform Version
Terraform v0.12.29 (I also tested with latest version it didn't work.)

### vSphere Provider Version
6.7

### Affected Resource(s)
DEBUG vsphereprivate_import_ova.import: Creating...

### Terraform Configuration Files
N/A

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

https://gist.github.com/yukselao/675d3784a0d4db58bfa746151b691fd5

### Panic Output
https://gist.github.com/yukselao/675d3784a0d4db58bfa746151b691fd5
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to com

### Expected Behavior

# openshift-install create cluster --dir=. --log-level=debug

Openshift installation should be completed successfully. Any workaround is acceptable.

### Actual Behavior

Installation failed with:

DEBUG vsphereprivate_import_ova.import: Creating...
ERROR
ERROR Error: rpc error: code = Unavailable desc = transport is closing
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change

### Steps to Reproduce

Try to install openshift 4.5 on vsphere 6.7.

### References

Looks like vSphere Provider for Terraform is not tested for vSphere 6.7, but plans are underway to add support. 

https://github.com/hashicorp/terraform-provider-vsphere

* #0000

**Comment by jcpowermac** [comment]
@yukselao this probably doesn't belong here.
Please open a issue on [github.com/openshift/installer](github.com/openshift/installer)

Either case based on the error I would guess where you are running the installer it does not have connectivity to the ESXi hosts.

**Comment by tenthirtyam** [comment]
@yukselao - any update on this issue?

**Comment by yukselao** [comment]
I faced with this issue 2 years ago. I didn't have a chance to try it again But  I am sure about I don't have connectivity problems with esxi hosts
