### ISSUE TITLE
vSphere multiple Custome attributes

### ISSUE THREAD

**Issue by sameh-Tawfiq** [hashicorp/terraform-provider-vsphere#1244]
Terraform v0.12.24
+ provider.vsphere v1.17.3

Refer to the below link
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/custom_attribute#using-custom-attributes-in-a-supported-resource

The below lines works fine with me to add only one custom attribute for the vm

resource "vpshere_virtual_machine" "web" {
  # ... other configuration ...

  custom_attributes = "${map(vsphere_custom_attribute.attribute.id, "value")}"
}

The question is what's the correct syntax to add 2 custom attribute to the vm?

**Comment by desertmoose706** [comment]
I also would like to know the syntax for multiple attributes.

**Comment by vdba73** [comment]
I am unable to set multiple custom attributes 
PZEZ-2VX13GHV2H:test vipul.parikh@cheetahdigital.com$ terraform plan

Error: Reference to undeclared resource

  on cm-modulestest.tf line 66, in module "vip-test-linuxvm-advanced":
  66:     data.vsphere_custom_attribute.environment.id = "Dev"

A data resource "vsphere_custom_attribute" "environment" has not been declared
in the root module.


Error: Reference to undeclared resource

  on cm-modulestest.tf line 67, in module "vip-test-linuxvm-advanced":
  67:     data.vsphere_custom_attribute.owner.id = "Vip"

A data resource "vsphere_custom_attribute" "owner" has not been declared in
the root module.

I am define the resource 
resource "vsphere_custom_attribute" "environment" {
  name                = "Environment"
  managed_object_type = "VirtualMachine"
}

resource "vsphere_custom_attribute" "owner" {
  name                = "Owner"
  managed_object_type = "VirtualMachine"
}

**Comment by vdba73** [comment]
Any help i appreciated

**Comment by tenthirtyam** [comment]
Hi @sameh-Tawfiq,

In older versions of Terraform (pre-v0.13) the syntax would be:

```hcl
resource "vsphere_virtual_machine" "web" {
 #... other config ...
  custom_attributes = {
    "${data.vsphere_custom_attribute.foo.id}" = "hello"
    "${data.vsphere_custom_attribute.bar.id}" = "world"
  }
```

In Terraform v0.13 and later, without the interpolation, the syntax should be updated to the following:

```hcl
resource "vsphere_virtual_machine" "web" {
 #... other config ...
  custom_attributes = {
    (data.vsphere_custom_attribute.foo.id) = "hello"
    (data.vsphere_custom_attribute.bar.id) = "world"
  }
```

/ / / / 

Hi @vdba73,

I would recommend the following assuming Terraform v0.13 and later:

```hcl
data "vsphere_custom_attribute" "environment" {
  name = "Environment"
}

data "vsphere_custom_attribute" "owner" {
  name  = "Owner"
}

resource "vsphere_custom_attribute" "environment" {
  name = "Environment"
  managed_object_type = "VirtualMachine"
}

resource "vsphere_custom_attribute" "owner" {
  name = "Owner"
  managed_object_type = "VirtualMachine"
}

resource "vsphere_virtual_machine" "this" {
 #... other config ...
  custom_attributes = {
    (data.vsphere_custom_attribute.environment.id) = "prod"
    (data.vsphere_custom_attribute.ownerr.id) = "J.Doe"
  }
``` 

Adding @appilon for review.

Ryan

**Comment by appilon** [comment]
Closing since examples have been provided
