### ISSUE TITLE
vsphere_content_library_item expecting undocumented argument

### ISSUE THREAD

**Issue by Sonic-Pancake** [hashicorp/terraform-provider-vsphere#1245]
### Terraform Version 

0.13.3

### vSphere Provider Version 

1.24.1 and 1.24.2

### Affected Resource(s)

- Data Source - vsphere_content_library_item

### Terraform Configuration Files

in 1.24.0 This worked
```
data "vsphere_content_library_item" "image" {
  name       = var.base_image
  library_id = data.vsphere_content_library.content_lib.id
}
```
In version 1.24.1 and 1.24.2 I now need to use this:
```
data "vsphere_content_library_item" "image" {
  name       = var.base_image
  library_id = data.vsphere_content_library.content_lib.id
  type = "VM-TEMPLATE"
}
```
### Expected Behavior

Terraform should run without complaining I'm missing an argument and I shouldn't need to add the type argument according to the documentation.

### Actual Behavior
```
Error: Missing required argument

  on main.tf line 86, in data "vsphere_content_library_item" "image":
  86: data "vsphere_content_library_item" "image" {

The argument "type" is required, but no definition was found.
```
### Steps to Reproduce

1. Create a terraform file with enough information to connect to vcenter that contains a content library and vm template
2. Fill in the appropriate name and library_id information.
3. Run Terraform apply

### References

* #1184 
* #1126 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
The `type` was added to the `vsphere_content_library_item` in https://github.com/hashicorp/terraform-provider-vsphere/commit/7d83a8acc5345f5231f5f200b620634a0afbdeec#diff-59360f584f8f07cd75690f835baf71576e2a064e091268f7d3364611cd75bea3. As such, when this was added there would have been design choice to set this a Required vs Optional and setting `vm-template` as the default.

The result was a good design choice for the data source to require; however, the data source documentation was not appropriately update.

I'll be happy to address the issues in thr documentation and update the example(s).

Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment]
Submitted https://github.com/hashicorp/terraform-provider-vsphere/pull/1507 to address the gap in the documentation for the `type` argument and updated the examples.

Ryan
@tenthirtyam
