### ISSUE TITLE
vSphere HA Cluster

### ISSUE THREAD

**Issue by afallucc** [hashicorp/terraform-provider-vsphere#1247]
### Description

Support configuration of vSphere HA Cluster
### References
https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-4BC60283-B638-472F-B1D2-1E4E57EAD213.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @afallucc - 

vSphere HA Options [are supported](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/compute_cluster#vsphere-ha-options). You can see this beginning [here](https://github.com/hashicorp/terraform-provider-vsphere/blob/ebb115de9c50c11c28f700b2d4ef3388d40e6695/vsphere/resource_vsphere_compute_cluster.go#L227) in the code.

Is there a specific vSphere HA enhancement desired for the `vsphere_compute_cluster` resource?

Ryan

**Comment by tenthirtyam** [comment]
@appilon, could you review this thread and the suggestion to close as the ability to create a cluster and enable vSphere HA settings on specific resources is already implemented?

**Comment by appilon** [comment]
It appears from git history that the HA settings have existed since [2018](https://github.com/hashicorp/terraform-provider-vsphere/commit/88b398a29d476a89339b544ee8f078f6c3955785). Closing issue, to the community, please file a new issue with the specific feature request and we will do our best to assess it.
