### ISSUE TITLE
Add support for a `vsphere_template` data source

### ISSUE THREAD

**Issue by patshuff** [hashicorp/terraform-provider-vsphere#1248]
### Description

Rather than referring to a template for a new vsphere_virtual_machine as a tag from another virtual machine it would be nice to have a data declaration for a vsphere_template that can be used. Templates can be created with a resource by cloning from an exiting VM or modified when the existing reference VM is modified. The existing vSphere CLI has a Get-Template command that pulls just templates and not VM lists. It seems logical that Terraform should treat templates differently from virtual machines since vSphere does with the command line and API calls. 

### current definition example
```hcl
data "vsphere_virtual_machine" "win_10_template" {
   name = "win_10_template"
   datacenter_id = data.vsphere_datacenter.dc.id
}
resource "vsphere_virtual_machine" "vm" {
   name = "terraform-test"
   resource_pool_id = data.vsphere_resource_pool.Resources-10_0_0_92.id
   host_system_id = data.vsphere_host.Host-10_0_0_92.id
   guest_id = "windows9_64Guest"
   network_interface {
     network_id = data.vsphere_network.VMNetwork.id
   }
   disk {
     label = "Disk0"
         size = 40
   }
   clone {
     template_uuid = data.vsphere_virtual_machine.win_10_template.id
   }
}
```

### proposed
```
data "vsphere_template" "win_10_template" {
   name = "win_10_template"
   datacenter_id = data.vsphere_datacenter.dc.id
}
resource "vsphere_virtual_machine" "vm" {
   name = "terraform-test"
   resource_pool_id = data.vsphere_resource_pool.Resources-10_0_0_92.id
   host_system_id = data.vsphere_host.Host-10_0_0_92.id
   guest_id = "windows9_64Guest"
   network_interface {
     network_id = data.vsphere_network.VMNetwork.id
   }
   disk {
     label = "Disk0"
         size = 40
   }
   clone {
     template_uuid = data.vsphere_template.win_10_template.id
   }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by burnsjared0415** [comment]
@patshuff  on this request are you just asking for us to copy the same output that "vsphere_virtual_machine"  provides for data, but just a new data resource?

**Comment by tenthirtyam** [comment]
A data source for just templates would be quite duplicative of the virtual machine data source, but adding a flag to the existing data source to filter only on templates may be a more suitable approach.

**Comment by burnsjared0415** [comment]
After looking at this, i am not sure this makes sense, the datacenter resource is going to pull all virtual machines no matter if they are Templates or virtual machines, the data source for virtual machine is going to pull the name specified, not sure it makes sense we need to filter this when we specify the template name or virtual machine name

**Comment by tenthirtyam** [comment]
Quite true. Let's mark this one as it planned given this and no upvote reactions in the time since opened.
