### ISSUE TITLE
Make creation of `vsphere_virtual_machine` not dependent on `resource_pool_id`

### ISSUE THREAD

**Issue by patshuff** [hashicorp/terraform-provider-vsphere#1249]
### Description

For many small vSphere installations no resource pool is declared and the default Resources resource pool is used. For multiple servers this becomes a problem because the default for the resource pool is "Resources" on all servers. If this tag is used in Terraform it throws an error since there are multiple names and the names must be unique. 

It would be so much simpler to allow for resource_pool_id or host_system_id to be used rather than having to synthetically name the multiple "Resources" as something else. Allowing a vsphere_virtual_machine to not require a resource_pool_id but accept a resource_pool_id or host_system_id and assume that the resource pool is Resources if none is declared. This removes the lines of code to define a virtual machine and makes virtual machine creation much simpler for smaller installations. 

### current
```hcl
data "vsphere_host" "Host-10_0_0_92" {
   name = "10.0.0.92"
   datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "Resources-10_0_0_92" {
   name = "10.0.0.92/Resources"
   datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "Host-10_0_0_3" {
   name = "10.0.0.3"
   datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "Resources-10_0_0_3" {
   name = "10.0.0.3/Resources"
   datacenter_id = data.vsphere_datacenter.dc.id
}
resource "vsphere_virtual_machine" "vm" {
   name = "terraform-test"
   resource_pool_id = data.vsphere_resource_pool.Resources-10_0_0_92.id
   host_system_id = data.vsphere_host.Host-10_0_0_92.id
   guest_id = "windows9_64Guest"
   network_interface {
     network_id = data.vsphere_network.VMNetwork.id
   }
   disk {
     label = "Disk0"
         size = 40
   }
   clone {
     template_uuid = data.vsphere_virtual_machine.win_10_template.id
   }
}
```

### proposed
```hcl
data "vsphere_host" "Host-prod" {
   name = "10.0.0.92"
   datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "Host-dev" {
   name = "10.0.0.3"
   datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
   name = "terraform-test"
   host_system_id = data.vsphere_host.Host-prod.id
   guest_id = "windows9_64Guest"
   network_interface {
     network_id = data.vsphere_network.VMNetwork.id
   }
   disk {
     label = "Disk0"
         size = 40
   }
   clone {
     template_uuid = data.vsphere_virtual_machine.win_10_template.id
   }
}
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@patshuff, an alternative approach is also:

```hcl
data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "resource_pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
```

Do you think this would be beneficial to add to the documentation?

Hope this helps,
Ryan

@tenthirtyam
