### ISSUE TITLE
customization for RHEL 6.10 is not working

### ISSUE THREAD

**Issue by podman2020** [hashicorp/terraform-provider-vsphere#1254]
### Terraform Version
V0.12.17
### vSphere Provider Version

v1.17.0
### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
resource "vsphere_virtual_machine" "vm" { 
name = "${var.hostname}" 
resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}" 
# datastore_cluster_id = "${data.vsphere_datastore_cluster.datastore_cluster.id}" 
datastore_id = "${data.vsphere_datastore.datastore.id}" 
num_cpus = "${var.num_cpus}" 
memory = "${var.total_memory}" 
guest_id = "${data.vsphere_virtual_machine.template.guest_id}" 
scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}" 
enable_disk_uuid = true 
network_interface { 
network_id = "${data.vsphere_network.network.id}" 
adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}" 
} 
disk { 
label = "disk0" 
size = "${data.vsphere_virtual_machine.template.disks.0.size}" 
unit_number = 0 
eagerly_scrub = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}" 
thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}" 
} 

clone 
template_uuid = "${data.vsphere_virtual_machine.template.id}" 
customize { 
linux_options { 
host_name = "${var.hostname}" 
domain = "${var.dnssearch}" 
} 
network_interface { 
ipv4_address = var.primary_ip 
ipv4_netmask = "${var.primary_bits}" 
} 
ipv4_gateway = var.default_gateway 
} 
} 

}

# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

We get below error:

Error: Virtual machine customization failed on "//vm/itestvm1 ": An error occurred while customizing VM testvm1. For details reference the log file <No Log> in the guest OS. The virtual machine has not been deleted to assist with troubleshooting. If corrective steps are taken without modifying the "customize" block of the resource configuration, the resource will need to be tainted before  

We have installed vmeare-tools and perl modules .

It works in rhel 7 and fails in rhel 6.

do you have any specific perl module or vmware-tools need to install.
### Expected Behavior

supposed to configure network

### Actual Behavior

it is failing with error 

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @podman2020, I know this issue is rather old but I'd like to respond.

Can you confirm if you are still having this issue or if you were able to resolve it since your original posting?

Generally, the only packages that are required for RHEL/CentOS for guest customizations are `open-vm-tools` and `perl`.

```console
yum install -y open-vm-tools perl
```

It wasn't mentioned in the issue, but generally, if the customization is not working using Terraform for a guest operating system, verify that the guest customization is or is not working using a guest customization specification using the UI or PowerCLI so troubleshooting can be narrowed.

I suspect that the cause would be specific to your image and not this provider since you mentioned RHEL7 had no issues.

cc @appilon

**Comment by tenthirtyam** [comment]
Hi @podman2020 

I'm marking this issue as closed based on the comments and information provided earlier in the thread.

Generally, the only packages that are required for RHEL/CentOS (and other RHEL derivatives) for guest customizations are `open-vm-tools` and `perl`.

```console
yum install -y open-vm-tools perl
```

If the issue persists, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
VMware Validated Solutions Engineering
