### ISSUE TITLE
Terraform is crashing while creating VMs from an OVA file using ovf_deploy option, Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by hjabeen** [hashicorp/terraform-provider-vsphere#1255]
Terraform is crashing while creating VMs from an OVA file using ovf_deploy option. 

I tried with terraform version 0.12.18 to 0.12.29, same crash occurs all the time.
Currently blocked with this issue. 

### Terraform Version
v0.12.29
### vSphere Provider Version
provider.vsphere v1.24.2

### Affected Resource(s)
'vsphere_virtual_machine'

### Terraform Configuration Files

panorama_esxi.tf 
resource "random_string" "password" {
  length  = 6
  upper   = false
  special = false
}

provider "vsphere" {
  user           = var.vcenter_user
  password       = var.vcenter_pasw
  vsphere_server = var.vcenter_ip
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.datacenter_name
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.cluster_name}/Resources"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "host" {
  name          = var.esxi_host
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.network_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vmFromRemoteOvf" {
  name                       = "Panorama-vm-${random_string.password.result}"
  resource_pool_id           = data.vsphere_resource_pool.pool.id
  datastore_id               = data.vsphere_datastore.datastore.id
  host_system_id             = data.vsphere_host.host.id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  datacenter_id              = data.vsphere_datacenter.dc.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  ovf_deploy {
    // Url to remote ovf/ova file
//    remote_ovf_url = var.remote_ovf_url
    local_ovf_path = var.remote_ovf_url
    ovf_network_map = {
        "VM Network" = data.vsphere_network.network.id
    }
}
}

### Panic Output

https://gist.github.com/hjabeen/703e891d5eb779a5ed793168e2c2f6f8

### Expected Behavior

The vm should have been successfully deployed and powered on and resource should be provided as output

### Actual Behavior

As soon as the vm is created in the vcenter host cluster using the ova, terraform crashes. The vm instance in vcenter host is in powered off state. after the import is complete but before powering on the VM, is when the terraform is crashing. 

### Steps to Reproduce
terraform init
terraform plan
terraform apply
 to reproduce the issue.

### References

https://github.com/hashicorp/terraform-provider-vsphere/issues/1252 

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FlorentFlament** [comment]
Hi, I have the same issue as well.

```
$ terraform -version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/vsphere v1.24.2
```

I think all of these issues are the same:
* https://github.com/hashicorp/terraform-provider-vsphere/issues/1260
* https://github.com/hashicorp/terraform-provider-vsphere/issues/1255
* https://github.com/hashicorp/terraform-provider-vsphere/issues/1252
* https://github.com/hashicorp/terraform-provider-vsphere/issues/1238

**Comment by aareet** [comment]
Thanks for your help @FlorentFlament - we're taking a look. I'm going to close duplicates in favour of #1252 so we can track it there.
