### ISSUE TITLE
Terraform takes a long time to detect a public ip

### ISSUE THREAD

**Issue by Aeinot** [hashicorp/terraform-provider-vsphere#1256]
### Terraform Version
Terraform v0.13.5

### vSphere Provider Version
 6.7.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl

resource "vsphere_virtual_machine" "vm_webserver" {
  name             = "DemoAlpine_WebServer"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = 1
  memory   = 512
  guest_id = data.vsphere_virtual_machine.template_generic_alpine.guest_id

  network_interface {
    network_id   = data.vsphere_network.vm_network.id
    adapter_type = data.vsphere_virtual_machine.template_generic_alpine.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template_generic_alpine.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template_generic_alpine.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template_generic_alpine.disks.0.thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template_generic_alpine.id
    linked_clone = true
  }
  
}

output "vm_ip" {
  value = vsphere_virtual_machine.vm_webserver.default_ip_address
}
```
### Expected Behavior
Terraform should detect the public IP of the VM as soon as it appears in the vSphere Client, and thus complete the execution.

### Actual Behavior

It takes between 30 and 45 seconds from the moment the public IP of the VM appears in the vSphere Client to the moment Terraform detects it and returns the output variable.

### Steps to Reproduce
`terraform apply`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by eliz-ol** [comment]
It looks like my providers are the same as yours, but in #1261 I don't get the IP reported at all. You get it. I find that curious.

**Comment by tenthirtyam** [comment]
Marking as closed based on the age of the reported issue and few reactions.

If the issue persists with [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect at VMware, Inc.
Cloud Infrastructure Business Group, Solutions Engineering
