### ISSUE TITLE
Timeout waiting for new IP on linux VM

### ISSUE THREAD

**Issue by eliz-ol** [hashicorp/terraform-provider-vsphere#1261]
### Terraform Version
Terraform v0.13.5

### vSphere Provider Version
+ provider registry.terraform.io/hashicorp/vsphere v1.24.2

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
    user = var.vcenter_user
    password = var.vcenter_password
    vsphere_server = [redacted]
    allow_unverified_ssl = true
    version = "~> 1.24.2"
}

data "vsphere_datacenter" "dc" {
    name = [redacted]
}

data "vsphere_datastore" "ds" {
    name = "Datastore2"
    datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "rp" {
    name = "TestResourcePool"
    datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
    name = var.template_name
    datacenter_id = data.vsphere_datacenter.dc.id 
}
resource "vsphere_virtual_machine" "vm" {
    name = "TfTest"
    resource_pool_id = data.vsphere_resource_pool.rp.id
    datastore_id = data.vsphere_datastore.ds.id

    num_cpus = 2
    memory = 4096
    #RancherOS uses an old VMWare tools which needs _ip_ instead of _net_. 
    wait_for_guest_net_timeout = (var.template_name == "RancherOS" ? 0 : 5)
    wait_for_guest_ip_timeout = 5 #(var.template_name == "RancherOS" ? 5 : 0)
    guest_id = data.vsphere_virtual_machine.template.guest_id

    disk {
        label = data.vsphere_virtual_machine.template.disks[0].label
        size = data.vsphere_virtual_machine.template.disks[0].size #multi-disk VMs wants a loop syntax, I think

    }

    network_interface {
        network_id = data.vsphere_network.network.id
    }

    clone {
        template_uuid = data.vsphere_virtual_machine.template.id
    }

}
```

### Debug Output
https://gist.github.com/eliz-ol/db7b3ca30ffb5254ee3ce25089aa0f74

### Expected Behavior

vCenter reports the IP of the VM right around the 3 minute mark. I expect that TF would be able to read that IP by the next 10 second interval or so

### Actual Behavior

TF reports a timeout waiting for the IP. If I do a `terraform refresh` immediately after, it populates the output and the state file with the correct IP, so it clearly can get the data from vCenter. I've also tried hardcoding 5 minute timeouts for both wait_for_guest_net_timeout and wait_for_guest_ip_timeout (during separate runs) and neither works. I also checked the mob of the VM and it has the IP address listed in all three places in rymdlego's comment in #0718, namely 

* guest.ipAddress
* summary.guest.ipAddress
* guest.net.{nic}.ipConfig.ipAddress

It's very possible that I'm doing something wrong, but I can't figure it out. I'm using newest versions of open-vm-tools on Ubuntu 20.04 and Centos 8.2, and an older version on RancherOS 1.5.6. 

### Important Factoids

1. terraform refresh immediately after the timeout reads the IP successfully.

### References

* #0718

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mike-sol** [comment]
Have you got GuestIPHack enabled? 

https://blog.ukotic.net/2019/03/05/configuring-esxi-prerequisites-for-packer/

**Comment by eliz-ol** [comment]
> Have you got GuestIPHack enabled?

These GuestIPHack scenarios involving Packer all seem to be using the vmware-iso builder, which connects directly to the ESXi host and requires modification using esxcli [ref](https://www.packer.io/docs/builders/vmware/iso). Packer using the vsphere-iso builder, which uses the vCenter API, explicitly says it doesn't need modification of the host[ (second bullet point at the top, links directly to the relevant vmware-iso section](https://www.packer.io/docs/builders/vmware/vsphere-iso).

So I don't believe enabling GuestIPHack is relevant in this situation just from a stated requirements standpoint. Additionally, since terraform refresh can successfully read the IP, the failure mode is different (i.e. it fails to read the IP in one circumstance but not the other rather than a complete failure), This appears to be something in how the terraform apply is trying to listen to vCenter rather than an ESXi thing that is not yet enabled.

**Comment by tenthirtyam** [comment]
Hi @eliz-ol - I realize that this issue is rather old and stale. Are you still experiencing this issue? I do quite a bit with Terraform and Packer (using `vsphere-iso`) and have not run into this issue yet.

Let me know, I'd be happy to help.

Ryan

**Comment by tenthirtyam** [comment]
Marking as closed based on the age of the reported issue.

If the issue persists with [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

If you need some examples for building Linux virtual machine images with Packer and the `vsphere-iso` builder, I recommend taking a look at [github.com/vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere) which I maintain. There you will find many up-to-date well-documented examples.

**Ryan Johnson**
Staff II Solutions Architect at VMware, Inc.
Cloud Infrastructure Business Group, Solutions Engineering
