### ISSUE TITLE
data vsphere_datastore resource doesn't list all the datastores available in a Datacenter

### ISSUE THREAD

**Issue by sandkum5** [hashicorp/terraform-provider-vsphere#1264]
### Terraform Version
Terraform v0.13.5

### vSphere Provider Version
+ provider registry.terraform.io/hashicorp/vsphere v1.24.2

### Affected Resource(s)
- data "vsphere_datastore"

### Terraform Configuration Files
```hcl
provider "vsphere" {
  version        = "1.24.2"
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {}

output "datacenter_id" {
  value = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = data.vsphere_datacenter.dc.id
}

output "datastore_list" {
  value = data.vsphere_datastore.datastore
}
```

### Expected Behavior
- I was expecting a list of all the datastores present under the Datacenter. 

When I am looking at the vcenter mob, I see 3 datastores(1 under each ESXi hosts). 

datastore | ManagedObjectReference:Datastore[] | 
datastore-13 (datastore1)
datastore-186 (datastore1 (1))
datastore-159 (Local)

But, I don't see all the datastores in the data output. 

### Actual Behavior

**terraform apply -auto-approve**
data.vsphere_datacenter.dc: Refreshing state... [id=datacenter-2]
data.vsphere_datastore.datastore: Refreshing state... [id=datastore-13]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

datacenter_id = datacenter-2
datastore_list = {
  "datacenter_id" = "datacenter-2"
  "id" = "datastore-13"
  "name" = "datastore1"
}

### Steps to Reproduce

-Add 2 ESXi hosts under a vCenter.
-The ESXi hosts should be added under 2 different clusters. 
-Create the data resource tf file as provided above and execute terraform apply. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jweigand** [comment]
This isn't a bug - this is how it's supposed to work. Looking up a data object for name "datastore1", that data object will only contain "datastore1", not a list of all datastores. The vpshere provider cannot return a list of all datastores.

**Comment by sandkum5** [comment]
The name argument is required in the data resource section. Hence, 
Do we have a way to pull all the datastores? 

Something like: 

data "vsphere_datacenter" "dc" {}

data "vsphere_datastore" "datastore" {
  datacenter_id = data.vsphere_datacenter.dc.id
}

output "datastore_list" {
  value = data.vsphere_datastore.datastore
}

**Comment by jweigand** [comment]
No, there's no way to accomplish what you're trying to do purely from terraform/vsphere provider. You have to look up existing datastores one at a time, specifying their name.

**Comment by tenthirtyam** [comment]
I concur with @jweigan's prior comments on how the provider operates.

@appilon, would you mind reviewing and confirming. I don't think there is a way to query and filter on the data sources.

Ryan

**Comment by appilon** [comment]
Unfortunately this is not a "plural" datasource, which in general providers have historically been hesitant to support. Apologies that we cannot provide that functionality at this time.
