### ISSUE TITLE
Field "tfplugin5.Diagnostic.Summary" contains invalid UTF-8

### ISSUE THREAD

**Issue by e11en** [hashicorp/terraform-provider-vsphere#1267]
### Terraform Version
v0.14.0

### vSphere Provider Version
provider registry.terraform.io/hashicorp/vsphere v1.24.2

### Terraform Configuration Files

Example from the docs:
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs

### Debug Output

```Error: rpc error: code = Internal desc = grpc: error while marshaling: proto: field "tfplugin5.Diagnostic.Summary" contains invalid UTF-8```

### Expected Behavior

To work

### Actual Behavior

Nothing

### Steps to Reproduce

Get example config from docs, add own credentials and vSphere server and run terraform apply (or terraform plan)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
Hi @e11en, thanks for the issue.  Would you mind rerunning the config with Terraform 0.13 and telling me if you encounter the same issue?

**Comment by e11en** [comment]
If tried it with Terraform 0.13.5 and unfortunately it shows the same error.

```
PS E:\terraform> terraform -v                                                  
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/vsphere v1.24.2

Your version of Terraform is out of date! The latest version
is 0.14.0. You can update by downloading from https://www.terraform.io/downloads.html
PS E:\terraform> terraform plan                                                
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: rpc error: code = Internal desc = grpc: error while marshaling: proto: field "tfplugin5.Diagnostic.Summary" contains invalid UTF-8

PS E:\terraform> 
```

**Comment by rafaelcanto** [comment]
Same issue here in v0.15.4 with AzureRM provider.

**Comment by rafaelcanto** [comment]
Solved for me, setting UT8 globally in Windows.

![image](https://user-images.githubusercontent.com/3123530/120120860-9086ff00-c176-11eb-914d-84c9e4c1789a.png)

**Comment by tenthirtyam** [comment]
Hi @e11en - does the [above workaround](https://github.com/hashicorp/terraform-provider-vsphere/issues/1267#issuecomment-851065430) resolve the issue for you?

Ryan

**Comment by tenthirtyam** [comment]
Hi @e11en - did the [above workaround](https://github.com/hashicorp/terraform-provider-vsphere/issues/1267#issuecomment-851065430) resolve the issue for you?

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.

**Comment by e11en** [comment]
Had this issue more then a year ago, I'm no longer working on this so I can't check it. I'll close this issue.
