### ISSUE TITLE
Ignore Changes for template_uuid

### ISSUE THREAD

**Issue by chessser** [hashicorp/terraform-provider-vsphere#1270]
I'm using v1.7 of terraform-provider-vsphere, and when updating the VCenter Template, the template_uuid changes, which means that when running a plan, it wants to re-create the VMs. This is inconvenient, as the state file needs to be updated to reflect the new template_uuid. Ideally the Terraform should not be re-creating the VM if the template changes.

Adding the following: 
`lifecycle { ignore_changes = [ clone[0].template_uuid ] }`

After [https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/455275a83fec49d5d19102f435857c5ec0bddc38/main.tf#L171](url) 
(inside the resource `"vsphere_virtual_machine" "Linux" {`)

Resolves the issue I am facing, but I appreciate this only resolves the issue locally. This works for me because I haven't configured [https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/455275a83fec49d5d19102f435857c5ec0bddc38/variables.tf#L22](url) to be anything more than one. The way that I have configured means that is not optional either, and so it will affect all resources.

My Terraform knowledge is not good enough to configure it for every use case, but having this setting available would be very useful.

If anyone is able to suggest how this might be configured correctly?

Thanks,

**Comment by chessser** [comment]
idiot

**Comment by alexjfisher** [comment]
Still the wrong github project! :) https://github.com/hashicorp/terraform-provider-vsphere/issues/1269#issuecomment-739823645
