### ISSUE TITLE
Instance UUID for 'vsphere_virtual_machine` resources

### ISSUE THREAD

**Issue by sachittiwari** [hashicorp/terraform-provider-vsphere#1277]
We have provisioned a VM in vSphere using terraform. The VM gets provisioned and the data is returned in the state file. But the response does not contain the attribute "Instance UUID" of the VM, which is used to uniquely identify the VM within the vCenter.
This can be used for VM reference as well as to make any vSphere API calls.

Ideally this Instance UUID instead of UUID must be returned as response. Is there any way we can get that in terraform.

Any suggestions/pointers would be appreciated.

**Comment by tenthirtyam** [comment]
@sachittiwari - I realize that this issue is rather stale, and I hope you've been able to come to a resolution since it was first entered. In the spirit of helping, I'm providing a method to return the instanceUUID using Terraform output.

```ccl
data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "vm" {
  depends_on = [
    vsphere_virtual_machine.vm
  ]
  name          = var.vm_name
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  #... other configurations...
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  #... other configurations...
  }
}

output "instanceUUID" {
  value = data.vsphere_virtual_machine.vm.id
}
```

After running `terraform apply` you'll see the following:

```bash
...
vsphere_virtual_machine.vm: Creation complete after 2m28s [id=42020056-4201-4ce4-afcb-2054b38c0256]
data.vsphere_virtual_machine.vm: Reading...
data.vsphere_virtual_machine.vm: Read complete after 0s [id=42020056-4201-4ce4-afcb-2054b38c0256]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

instanceUUID = "42020056-4201-4ce4-afcb-2054b38c0256"
```

Hope that helps.

Ryan
@tenthirtyam

**Comment by jeichhorn** [comment]
@tenthirtyam In my tests accessing the terraform output `vsphere_virtual_machine.vm.id` returns the `bios_uuid` and not the `instance_uuid` when comparing the values from the vsphere REST API `https://<VCENTER>/api/vcenter/vm/<VM>`.
Is this expected?

**Comment by tenthirtyam** [comment]
@jeichhorn, Yes, you are correct. I checked and the `uuid` and `id` in the state still appear to reflect the `uuid.bios` value.

I'm reopening https://github.com/hashicorp/terraform-provider-vsphere/issues/282 which went stale.

Ryan
