### ISSUE TITLE
Add automated provider acceptance tests

### ISSUE THREAD

**Issue by sumitAgrawal007** [hashicorp/terraform-provider-vsphere#1282]
Recently there has been many bug reports about OVA deployment failing with error, **runtime error: index out of range [0] with length 0.**
Given that it is a very widely used feature, can we run acceptance tests for every commit and make sure the test cases work.

Recently reported bugs on OVA deployment
I think all of these issues are the same:

https://github.com/hashicorp/terraform-provider-vsphere/issues/1252
https://github.com/hashicorp/terraform-provider-vsphere/issues/1257

There all relate to one commit that broke the OVA deployment flow.

**Comment by tenthirtyam** [comment]
Updated to an enhancement for the project to cover the tech debt that Alex and I have been discussing.
