### ISSUE TITLE
VM with bigger disk destroy fails with ""context deadline exceeded" error

### ISSUE THREAD

**Issue by unnikrishnan262** [hashicorp/terraform-provider-vsphere#1283]
### Terraform Version
Terraform v0.11.11

### vSphere Provider Version
1.24.2

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

resource "vsphere_virtual_machine" "vm" {
  depends_on = [  data.vsphere_folder.folder, phpipam_first_free_address.newips, dns_a_record_set.vmservers, dns_ptr_record.vserver-ptrs ]
  count = var.vm_count
  name = trimsuffix( format("%s-%s-%d.%s", var.service_name, var.vm_name ,count.index +1, var.internal_domain ), "." )
  resource_pool_id  = data.vsphere_resource_pool.pool.id
  #datastore_id      = data.vsphere_datastore.datastore.id
  datastore_cluster_id      = data.vsphere_datastore_cluster.datastore_cluster.id
  tags              = [data.vsphere_tag.tag-product-name.id, data.vsphere_tag.tag-service-name.id]
  folder            = data.vsphere_folder.folder.path
  num_cpus = local.skus[var.instance_type]["cpus"]
  memory   = local.skus[var.instance_type]["memory"]

  num_cores_per_socket = local.skus[var.instance_type]["cpus"] / 2  # To match with 2 socket UCS CPU, 32 CPU / 16 = 2 socket
  scsi_controller_count = 4 
  scsi_bus_sharing = "physicalSharing"  
  
  guest_id = var.OSimage
  sync_time_with_host = true
  network_interface {
    network_id = data.vsphere_network.vmSubnet.id
  }
  
###########################################################################
  disk {
    label = "Boot-Partition-DISK"
    unit_number = 0 
    size  = 15
    thin_provisioned = true
    #eagerly_scrub = false
  }
 disk {
    label       = "OS-DISK"
    unit_number = 1 
    size        = 200
    thin_provisioned = true
  }
  

 disk {
    label       = "Disk1"
    unit_number = 15 
    size        = 250
    thin_provisioned = true
  }
 disk {
    label       = "-Disk2"
    unit_number = 16 
    size        = 250
    thin_provisioned = true
  } 
 disk {
    label       = "-Disk3"
    unit_number = 30 
    size        = 250
    thin_provisioned = true
  }
 disk {
    label       = "Disk4"
    unit_number = 31
    size        = 250
    thin_provisioned = true
  }
 disk {
    label       = "Disk5"
    unit_number = 45 
    size        = 250
    thin_provisioned = true
  }
 disk {
    label       = "Disk6"
    unit_number = 46 
    size        = 250
    thin_provisioned = true
  }
  

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = format("%s-%s-%d", var.service_name, var.vm_name ,count.index +1)
        domain    = trimsuffix( var.internal_domain, "." )
      }
      network_interface {
        ipv4_address = format("%s", phpipam_first_free_address.newips["${count.index}"].ip_address)
        ipv4_netmask = var.netmask
      }
      ipv4_gateway    = var.gateway
      dns_suffix_list = [var.internal_domain]
      dns_server_list = var.dns_server
    }
  }
}

### Debug Output

module.arches-sc-z2.vsphere_virtual_machine.vm[0]: Still destroying... [id=423c2e34-7b13-6b5a-7dd6-880d8ba7b153, 5m10s elapsed]
module.arches-sc-z3.vsphere_virtual_machine.vm[0]: Still destroying... [id=423c6702-1a43-dd15-4bdf-de8a53dbe797, 5m10s elapsed]
2020/12/11 23:02:10 [DEBUG] module.arches-sc-z3.vsphere_virtual_machine.vm[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: error destroying virtual machine: Post "https://x.x.x.x/sdk": context deadline exceeded
2020/12/11 23:02:10 [ERROR] module.arches-sc-z3: eval: *terraform.EvalApplyPost, err: error destroying virtual machine: Post "https://x.x.x./sdk": context deadline exceeded
2020/12/11 23:02:10 [ERROR] module.arches-sc-z3: eval: *terraform.EvalSequence, err: error destroying virtual machine: Post "https://x.x.x./sdk": context deadline exceeded

### Panic Output

Error: error destroying virtual machine: Post "https://x.x.x.x/sdk": context deadline exceeded

### Expected Behavior

We should have an option to set the timeout value for the destroy operation. 

### Actual Behavior

VM with larger disks (6 x 250GB) takes more time to delete. But the current code error out after 5 mins. 
The actual destroy took 6 mins in my case. 

### Steps to Reproduce

- Create a VM with 6 additional disks part from the OS disk (6 x 25GB) as per the above code on vsphere 6.7

- Destroy the VM

**Comment by tenthirtyam** [comment]
Resolved in #1405 with the introduction of the `defaultAPITimeout` configuration for the provider.

Marking this issue as closed. If this issue is reappears with the latest version of the provider, please create a new issue linking back to this one for added context.

**Ryan Johnson**
Staff II Solutions Architect
Cloud Infrastructure Business Group, VMware
