### ISSUE TITLE
Relax `devices` as a required argument for `vsphere_distributed_switch` resource

### ISSUE THREAD

**Issue by heitmanr** [hashicorp/terraform-provider-vsphere#1290]
### Description

Distributed-Switches provide more features than Standard-vSwitches (for example "MAC Learning", starting with Version 6.6).

This makes it interesting to use Distributed-Switches even in Lab-Environments containing only one ESXi-Host.

Those environments are likely to
* contain only virtual-machines (no bare-metal servers outside the virtualization host)

So - there is no technical requirement to add "Uplinks" to the Distributed-Switch.

**Using the VSphere-GUI it's no problem to**

1. create a Distributed-Virtual-Switch
2. add an ESXi-Host to it
3. but leave the Uplink-Ports-List empty

**Trying the same in Terraform ends up in:**
```PowerShell
Error: host.0.devices: attribute supports 1 item as a minimum, config has 0 declared

  on vswitch.tf line 4, in resource "vsphere_distributed_virtual_switch" "dvs":
   4: resource "vsphere_distributed_virtual_switch" "dvs" {
```
Terraform requires, when adding "a host" to "a vsphere_distributed_virtual_switch"
a "devices"-Array

- which is not allowed to be empty
- this should be allowed

### Potential Terraform Configuration

The interesting line is
    **devices = []**

```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
  name          = var.vswitchname
  datacenter_id = data.vsphere_datacenter.dc.id
  version       = "6.6"

  uplinks = []
  active_uplinks = []
  standby_uplinks = []

  host {
    host_system_id = data.vsphere_host.host.id
    devices = []
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ron4all** [comment]
i hope, this is not too hard to implement - i thought this would be about to relax an unnecessary parameter-check which enforces an uplink-count of at least "1" which seems to be not relevant by the vSphere-API.

this breaks (at least mine) lab-workflows, maybe i'd add another NIC to my server so terraform is happy - i'd remove the uplink afterwards...
