### ISSUE TITLE
Expect Version "6.6" for Distributed-Virtual-Switches, too

### ISSUE THREAD

**Issue by heitmanr** [hashicorp/terraform-provider-vsphere#1291]
### Description

Using a vCenter Release >=7 with ESXi-Hosts Release 6.7 forbids distributed Switches Release 7.0
* the terraform default is to deploy the latest DVS-Release possible with the connected vCenter
* with vCenter v7.0 => DVS v7.0

The biggest common denominator is DVS v6.6:
![grafik](https://user-images.githubusercontent.com/26636908/102701510-f8e0c480-4257-11eb-81ed-cca4c5d3b2e4.png)

But this release is "not expected" and therefore forbidden with terraform.

```hcl
Error: expected version to be one of [5.0.0 5.1.0 5.5.0 6.0.0 6.5.0], got 6.6.0

  on vswitch.tf line 4, in resource "vsphere_distributed_virtual_switch" "dvs":
   4: resource "vsphere_distributed_virtual_switch" "dvs" {
```

### Potential Terraform Configuration

Version "6.6" is valid and should be expected.

```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
  name          = var.vswitchname
  datacenter_id = data.vsphere_datacenter.dc.id
  version       = "6.6.0"

...
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ron4all** [comment]
I wonder, i think i'm not the only consultant with customers, who are not ready for the upgrade to ESXi 7.0 but who want to use the new features of the Distributed Switch in version "6.6.0".

https://blogs.vmware.com/vsphere/2018/10/automating-upgrade-of-virtual-distributed-switch.html

Additionally:
It would be great, if the 
new feature of the 

- VDS 6.6 "MAC-Learning"

could get enabled using terraform, too.

**Comment by ron4all** [comment]
![grafik](https://user-images.githubusercontent.com/26636908/104602021-3c71f700-567b-11eb-970f-31b42e60ae9a.png)
