### ISSUE TITLE
When adding a Resource, an uninvolved (via OVF/OVA) deployed VM leads to "Error: this virtual machine requires a client CDROM device to deliver vApp properties"

### ISSUE THREAD

**Issue by heitmanr** [hashicorp/terraform-provider-vsphere#1292]
### Terraform Version
Terraform v0.13.5

### vSphere Provider Version
+ provider registry.terraform.io/hashicorp/vsphere v1.24.0

### Affected Resource(s)

* `vsphere_virtual_machine:` named `csr1kv-10`
  * which is up and running for a while now
  * specified in (not modified) file `csr.tf`
* `vsphere_distributed_port_group:` named `hq`
  * this is a new portgroup
  * specified in file `vswitch.tf`

### Terraform Configuration Files
No change here, the VM is up and running:
```hcl
resource "vsphere_virtual_machine" "csr1kv-10" {
  name = "Site-10-Router"
  resource_pool_id = vsphere_resource_pool.pool.id
  datastore_id = data.vsphere_datastore.ds.id
  datacenter_id = data.vsphere_datacenter.dc.id
  host_system_id = data.vsphere_host.host.id
...
  ovf_deploy {
    local_ovf_path = "..."
    disk_provisioning = "thin"
    ovf_network_map = {
        "GigabitEthernet1" = data.vsphere_network.mgmt_lan.id,
        "GigabitEthernet2" = vsphere_distributed_port_group.bb.id,
        "GigabitEthernet3" = data.vsphere_network.mgmt_lan.id
    }
  }

  vapp {
    properties = {
      "domain-name" = "lab.local",
 ...
    }
  }
}
```

the file "vswitch.tf" has got an additional portgroup, which should be used in a different (not mentioned in any .tf-file, yet) VM.

```hcl
resource "vsphere_distributed_port_group" "bb" {
  name          = var.network_backbone
  vlan_id       = var.network_backbone_id
  distributed_virtual_switch_uuid = data.vsphere_distributed_virtual_switch.dvs.id
}
```

### Debug Output

(https://gist.github.com/ron4all/5691eeb2d9ee7630a5aea066a4446573)

### Expected Behavior

The additional portgroup should be added.

The runnning VM which shouldn't block changes.

### Actual Behavior

An Error-Message is generated.

### Steps to Reproduce

```powershell
PS C:\TERRAFORM\vSphere> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.dc: Refreshing state... [id=datacenter-3]
data.vsphere_distributed_virtual_switch.dvs: Refreshing state... [id=50 39 0b 1b 2a 15 bf de-5c 71 77 34 ee f5 f8 28]
data.vsphere_datastore.ds: Refreshing state... [id=datastore-20]
data.vsphere_host.host: Refreshing state... [id=host-10]
data.vsphere_network.network: Refreshing state... [id=network-62]
data.vsphere_network.mgmt_lan: Refreshing state... [id=dvportgroup-141]
data.vsphere_compute_cluster.compute_cluster: Refreshing state... [id=domain-c176]
vsphere_folder.folder: Refreshing state... [id=group-v2014]
vsphere_distributed_port_group.bb: Refreshing state... [id=dvportgroup-2025]
vsphere_resource_pool.pool: Refreshing state... [id=resgroup-2012]
vsphere_virtual_machine.csr1kv-10: Refreshing state... [id=42392f37-a9ad-47ac-ed0e-8868996411c1]

------------------------------------------------------------------------

Error: this virtual machine requires a client CDROM device to deliver vApp properties

  on csr.tf line 1, in resource "vsphere_virtual_machine" "csr1kv-10":
   1: resource "vsphere_virtual_machine" "csr1kv-10" {
```

### Important Factoids

pretty standard setup.

### References

Empty

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by braunsonm** [comment]
Hey @heitmanr did you find a work around for this?

**Comment by tenthirtyam** [comment]
https://github.com/hashicorp/terraform-provider-vsphere/blob/6dfc334c1faf02fb6dd572ad4506add365622465/vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go#L605-L611

Ideally, https://github.com/hashicorp/terraform-provider-vsphere/issues/489#issuecomment-384536330 could be included in the documentation for instances where the "ISO Image" environment transport is enabled.

Ryan
