### ISSUE TITLE
vsphere_entity_permissions changed after every plan, even when specified in alphabetical order

### ISSUE THREAD

**Issue by leetecarey** [hashicorp/terraform-provider-vsphere#1293]
### Terraform Version
Terraform v0.13.5
### vSphere Provider Version
registry.terraform.io/hashicorp/vsphere v1.24.3
vCenter: 6.5/6.7

### Affected Resource(s)

- `vsphere_entity_permissions`

### Terraform Configuration Files
permissions.tf:

 

> resource "vsphere_entity_permissions" cluster1 {
>    entity_id = data.module.cluster1_cluster.cluster_id
>    entity_type = "HostSystem" 
>  permissions {
>      user_or_group = "VSPHERE.LOCAL\\auser"
>      propagate = true
>      is_group = false
>      role_id = data.vsphere_role.administrator.id
>    }
>    permissions {
>      user_or_group = "VSPHERE.LOCAL\\buser"
>      propagate = true
>      is_group = false
>      role_id = data.vsphere_role.readonly.id
>    }

### Expected Behavior

Permissions are changed once. Further applies should not change the entity. Users/Groups have been placed in alphabetical order as requested.

### Actual Behavior
After every run, the following occurs. It appears the results pulled back from VC are not alphabetical so therefore terraform changes the permissions after every run. With large numbers of permissions per entity this becomes unmanageable

Terraform will perform the following actions:
 vsphere_entity_permissions.cluster1 will be updated in-place

 ```
 _~ resource "vsphere_entity_permissions" "cluster1" {
           entity_id   = "datacenter-969"
        entity_type = "HostSystem"
        id          = "datacenter-969"

      ~ permissions {
            is_group      = false
            propagate     = true
          ~ role_id       = "-2" -> "-1"
          ~ user_or_group = "**VSPHERE.LOCAL\\buser" -> "VSPHERE.LOCAL\\auser"**
        }
      ~ permissions {
            is_group      = false
            propagate     = true
          ~ role_id       = "-1" -> "-2"
          ~ user_or_group = "**VSPHERE.LOCAL\\auser" -> "VSPHERE.LOCAL\\buser"**
        }
    }_

```

### Steps to Reproduce

Create 2 users auser and buser. Apply to a cluster/folder etc using vsphere_entity_permissions. Re-run the plan and observe the plan being changed on each run. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sumitAgrawal007** [comment]
Thanks for reporting this,
I will look into this.

**Comment by sumitAgrawal007** [comment]
I am not able to reproduce this, Can you confirm you have kept the permissions sorted on user/group name?
Can you also post all your .tf files.

**Comment by leetecarey** [comment]
As requested:

**datacenter.tf**
```
resource "vsphere_datacenter" "dc" {
  name = "TEST"
}
```
**permissions.tf**
```
data "vsphere_datacenter" "dc" {
    name        = var.vsphere_datacenter
}

data "vsphere_role" "administrator" {
  label = "Administrator"
}

data "vsphere_role" "readonly" {
  label = "Read-only"
}

resource "vsphere_entity_permissions" toplevel {
  entity_id = data.vsphere_datacenter.dc.id
  entity_type = "HostSystem"
  permissions {
    user_or_group = "VSPHERE.LOCAL\\auser"
    propagate = true
    is_group = false
    role_id = data.vsphere_role.administrator.id
  }
  permissions {
    user_or_group = "VSPHERE.LOCAL\\buser"
    propagate = true
    is_group = false
    role_id = data.vsphere_role.readonly.id
  }
}
```

On initial run it works without issues. Rerunning plan and adding further users, i.e "cuser", seems to trigger the reapplying issue.

**Result**

vsphere_datacenter.dc: Refreshing state... [id=TEST]
vsphere_entity_permissions.toplevel: Refreshing state... [id=datacenter-969]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  vsphere_entity_permissions.toplevel will be updated in-place
  ~ resource "vsphere_entity_permissions" "toplevel" {
        id          = "datacenter-969"
        # (2 unchanged attributes hidden)

      ~ permissions {
          ~ role_id       = "-2" -> "-1"
          ~ user_or_group = "VSPHERE.LOCAL\\buser" -> "VSPHERE.LOCAL\\auser"
            # (2 unchanged attributes hidden)
        }
      ~ permissions {
          ~ role_id       = "-1" -> "-2"
          ~ user_or_group = "VSPHERE.LOCAL\\auser" -> "VSPHERE.LOCAL\\buser"
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Many Thanks

**Comment by sumitAgrawal007** [comment]
Hi @leetecarey ,
I am still not able to reproduce this, Can we schedule a zoom video call to debug it ?
My email : asumit@vmware.com
