### ISSUE TITLE
vsphere_virtual_disk importing requires 3 arguments, but terraform supports only 2

### ISSUE THREAD

**Issue by kytomaki** [hashicorp/terraform-provider-vsphere#1295]
### Terraform Version

`0.13.3`

### vSphere Provider Version

`1.24.0`

### Affected Resource(s)

`vsphere_virtual_disk`

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

`terraform import module.foo.vsphere_virtual_disk.bar /DC/pool path/to/virtual_disk` would work

### Actual Behavior

`The import command expects two arguments`

### Steps to Reproduce

Try to import virtual disk resource e.g `terraform import module.foo.vsphere_virtual_disk.bar /DC/pool path/to/virtual_disk`

### Important Factoids

n/a

### References

* #1120 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dcardellino** [comment]
@kytomaki 
I had the same issue but I found the solution for this.
In your case the import statement would look something like this:

```
terraform import module.foo.vsphere_virtual_disk.bar /<dc-name>/[<datastore-name>]/path/to/virtual_disk.vmdk
```

Take care of the square brackets after the datacenter name and **NO** space after the datastore-name!

In my case i got it work ;)

**Comment by tenthirtyam** [comment]
@kytomaki What @dcardellino presented is correct and noted in the documentation for the `vSphere_virtual_disk` resource.

Docs example:

```bash
terraform import vsphere_virtual_disk.disk /dc1/[ds1] disk1_vmdk_path
```

Source:

https://github.com/hashicorp/terraform-provider-vsphere/blob/814675b5da80f286a082664d22455b7c8264134a/website/docs/r/virtual_disk.html.markdown?plain=1#L74-L88

@dcardellino - your example is  intuitive. I'll mark this one down to submit a docs PR as such:

```bash
terraform import vsphere_virtual_disk.foo /<dc-name>/[<datastore-name>]/path/to/foo.vmdk
```

```bash
terraform import module.foo.vsphere_virtual_disk.bar /<dc-name>/[<datastore-name>]/path/to/bar.vmdk
```

Hope this helps,
Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment]
The import format is:

```console
terraform import vsphere_virtual_disk.name "/<dc-name>/[<datastore-name>] path/to/disk.vmdk"`
```

```console
terraform import module.foo.vsphere_virtual_disk.name "/<dc-name>/[<datastore-name>] path/to/disk.vmdk"`
```

For example:

```console
terraform import vsphere_virtual_disk.foo "/sfo-w01-dc01/[sfo-w01-fs-vsan01] foo/foo.vmdk"
```

```console
terraform import module.foo.vsphere_virtual_disk.name "/sfo-w01-dc01/[sfo-w01-fs-vsan01] foo/foo.vmdk"
```

Ryan
