### ISSUE TITLE
VM Customization fails when using cloud-init-vmware-guestinfo on CentOS 7

### ISSUE THREAD

**Issue by skganji** [hashicorp/terraform-provider-vsphere#1298]
### Terraform Version
v0.14.3
### vSphere Provider Version
v1.24.3

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = var.vsphere_resource_pool
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_virtual_machine_template
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "cloned_virtual_machine" {
  count            = length(var.nodes)
  name             = lookup(var.nodes[count.index], "hostname")
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = data.vsphere_virtual_machine.template.num_cpus
  memory   = data.vsphere_virtual_machine.template.memory
  guest_id = data.vsphere_virtual_machine.template.guest_id

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  wait_for_guest_net_timeout = 0
  wait_for_guest_net_routable = false

   network_interface {
     network_id     = data.vsphere_network.network.id
     adapter_type   = data.vsphere_virtual_machine.template.network_interface_types[0]
   }

  disk {
    label = "disk0"
    size = data.vsphere_virtual_machine.template.disks.0.size
  }

  enable_disk_uuid = "true"

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = lookup(var.nodes[count.index], "hostname")
        domain    = var.dns_domain
      }
      network_interface {}
    }
  }

  extra_config = {
    "disk.EnableUUID" = "TRUE"
    "guestinfo.metadata"          = base64encode(file("${path.module}/templates/metadata.yaml"))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("${path.module}/templates/userdata.yaml"))
    "guestinfo.userdata.encoding" = "base64"
  }
}
```

### Expected Behavior

Terraform should have completed without errors and connect the Network.

### Actual Behavior

Exits with error
```vsphere_virtual_machine.cloned_virtual_machine[0]: Still creating... [11m0s elapsed]

Error:
Virtual machine customization failed on "/Home/vm/node01":

timeout waiting for customization to complete

The virtual machine has not been deleted to assist with troubleshooting. If
corrective steps are taken without modifying the "customize" block of the
resource configuration, the resource will need to be tainted before trying
again. For more information on how to do this, see the following page:
https://www.terraform.io/docs/commands/taint.html


  on terraform.tf line 32, in resource "vsphere_virtual_machine" "cloned_virtual_machine":
  32: resource "vsphere_virtual_machine" "cloned_virtual_machine" {
```

### Steps to Reproduce

1. `packer build -force -on-error=abort -var-file variables.json centos-7-packer.json`
2. `terraform apply`

### Important Factoids

Using vSphere 6.5.0
The OS in question is CentOS 7 (latest version). Template is built by packer using kickstart.

Packer config and ks.cfg - https://gist.github.com/skganji/df18cab1659fc0199a667206b9bf2c43
metadata and userdata for terraform - https://gist.github.com/skganji/911befcbaf26ee241d1b433a5aa3fc59

I am able to get it to work if i comment out the line 77 in centos-7-packer.json. The exact line is listed below...
`"curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh -"`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by skganji** [comment]
One thing to note is, if I comment out line 77 in packer.json, which does not install `cloud-init-vmware-guestinfo` and hence does not perform any customization on the VM. However without commenting the line, customization is complete, but terraform errors out. No errors found in the toolsDeployPkg.log or cloud-init.log. Both processes were successful.

**Comment by PSTobiasMueller** [comment]
I've an identical problem, although i use Ubuntu 20.04 as Template and not CentOS. I've found some vSphere KB that helped me to get the things working. But my workflow is not 100% stable. Some times the Virtual Machines cloned by the terraform vsphere provider hang on boot and is not customized properly.

- [Guest customization fails on Linux with systemd System and Service Manager (59687)](https://kb.vmware.com/s/article/59687): Although we're using vCenter Appliance 6.7 Update 3j (6.7.0.45000) i still hat do implement that line to make the VM Boot properly.
- [Enabling or disabling Linux guest customization with cloud-init (59557)](https://kb.vmware.com/s/article/59557): I've disabled the networking configuration via cloud-init. 

From my perspective this isn't a problem with the Terraform Provider. When i run the command: `vmware-rpctool "info-get guestinfo.userdata | base64 -d` i can verify that my user-data cloud config is available inside the vm.
When i connect me to the VM via Console and execute `cloud-init init` the VM is User-Data is configured properly.

On my environment the problem is that the hostnamectl status command inside the vsphere customization is not executed properly. It fails with Exit Code 256. Failed to create bus connection: No such file or directory. A Problem that should by solved with Update 3.

**Comment by tenthirtyam** [comment]
This **is not** an issue with the Terraform provider for vSphere, but rather it's an issue with the CentOS 7 machine image created with the Packer template which includes the `cloud-init` package...

https://gist.github.com/skganji/df18cab1659fc0199a667206b9bf2c43#file-centos-7-packer-json-L74-L77

I'd suggest modifying your Packer configuration to run a script file vs inline and add the following within a provisioner cleanup script:

```bash
#!/bin/bash

## Configure cloud-init
echo '> Installing cloud-init ...'
sudo touch /etc/cloud/cloud-init.disabled
sudo sed -i 's/^ssh_pwauth:   0/ssh_pwauth:   1/g' /etc/cloud/cloud.cfg
sudo sed -i -e 1,3d /etc/cloud/cloud.cfg
sudo sed -i "s/^disable_vmware_customization: false/disable_vmware_customization: true/" /etc/cloud/cloud.cfg
sudo sed -i "/disable_vmware_customization: true/a\\\nnetwork:\n  config: disabled" /etc/cloud/cloud.cfg
sudo sed -i "s@^[a-z] /tmp @# &@" /usr/lib/tmpfiles.d/tmp.conf
sudo sed -i "/^After=vgauthd.service/a After=dbus.service" /usr/lib/systemd/system/vmtoolsd.service
sudo sed -i '/^disable_vmware_customization: true/a\datasource_list: [OVF]' /etc/cloud/cloud.cfg
sudo cat << RUNONCE > /etc/cloud/runonce.sh
#!/bin/bash
# cloud-init runonce
## Enable cloud-init
sudo rm -f /etc/cloud/cloud-init.disabled
## Initialize cloud-init
sudo cloud-init init
sleep 20
sudo cloud-init modules --mode config
sleep 20
sudo cloud-init modules --mode final
## Mark cloud-init complete
sudo touch /etc/cloud/cloud-init.disabled
sudo touch /tmp/cloud-init.complete
sudo crontab -r
RUNONCE
sudo chmod +rx /etc/cloud/runonce.sh
echo "$(echo '@reboot ( sleep 30 ; sh /etc/cloud/runonce.sh )' ; crontab -l)" | sudo crontab -
echo '=> Installing cloud-init-vmware-guestinfo ...'
curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sudo sh - &>/dev/null

## Cleanup
echo '> Cleanup ...'
if [ -f /etc/udev/rules.d/70-persistent-net.rules ]; then
    sudo rm -f /etc/udev/rules.d/70-persistent-net.rules
fi
sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*
sudo truncate -s 0 /etc/machine-id
sudo rm -f /var/lib/dbus/machine-id
sudo ln -s /etc/machine-id /var/lib/dbus/machine-id
sudo cloud-init clean --logs --seed
sudo rm -f /etc/ssh/ssh_host_*
if [ -f /var/log/audit/audit.log ]; then
    sudo cat /dev/null > /var/log/audit/audit.log
fi
if [ -f /var/log/wtmp ]; then
    sudo cat /dev/null > /var/log/wtmp
fi
if [ -f /var/log/lastlog ]; then
    sudo cat /dev/null > /var/log/lastlog
fi
```
You should then be able to apply the customization and `extra_configs` via the provider once `cloud-init` is in working order.

Hope that helps.

Ryan
@tenthirtyam

Recommend: `close/not-a-bug`

**Comment by tenthirtyam** [comment]
HI @skganji - checking in to see if you are still experiencing this issue. See [comment above](https://github.com/hashicorp/terraform-provider-vsphere/issues/1298#issuecomment-956561294).

Ryan

**Comment by skganji** [comment]
@tenthirtyam,

Thank you for the suggestion. That worked. This issue can be closed.
