### ISSUE TITLE
Unable to specify deployment size (vCPU/vMem) using deploymentOption when deploying OVA's (NSX-T Manager)

### ISSUE THREAD

**Issue by daunce** [hashicorp/terraform-provider-vsphere#1305]
### Terraform Version
Terraform v0.14.3

### vSphere Provider Version
1.23.0+

### Affected Resource(s)
- 'virtual_machine_ovfdeploy'

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vmFromLocalOvf" {
  name             = "site-210-nsxm1"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  datacenter_id    = data.vsphere_datacenter.dc.id
  host_system_id   = data.vsphere_host.host.id

  ovf_deploy {
    // Url to local ovf/ova file
    local_ovf_path = "Z:\\Software\\VMware\\NSX-T\\nsx-unified-appliance-3.0.1.1.0.16556500.ova"
    disk_provisioning = "thin"
    ovf_network_map = {
      "VM Network" = data.vsphere_network.network.id
    }
  }

  vapp {
    properties = {
      "nsx_passwd_0"           = "VMware1!VMware1!"
      "nsx_cli_passwd_0"       = "VMware1!VMware1!"
      "nsx_cli_audit_passwd_0" = "VMware1!VMware1!"
      "nsx_cli_username"       = "admin"
      "nsx_cli_audit_username" = "audit"
      "nsx_hostname"           = "site-210-nsxm1.lab.vmw.local"
      "nsx_role"               = "NSX Manager"
      "nsx_gateway_0"          = "172.31.210.1"
      "nsx_ip_0"               = "172.31.210.21"
      "nsx_netmask_0"          = "255.255.255.224"
      "nsx_dns1_0"             = "172.31.3.9" # Add an extra here
      "nsx_domain_0"           = "lab.vmw.local"
      "nsx_ntp_0"              = "172.31.9.1"
      "nsx_isSSHEnabled"       = "True"
      "nsx_allowSSHRootLogin"  = "False"

    }
  }
}
```

### Expected Behavior
VM with correct vCPU/vMem deployed based on deploymentOption from sizes availble within .ovf file. ie: extra_small, small, medium, large.

### Actual Behavior
VM deployed with vCPU/vMem as per the default entry in the deploymentOption section of the .ovf

See 
```

    <Configuration ovf:id="medium" ovf:default="true">
      <Label ovf:msgid="config.medium.label">Medium</Label>
      <Description ovf:msgid="config.medium.description">
IMPORTANT: This configuration is supported for Local Manager Production deployment ('NSX Manager' role)
           This is supported for Global Manager Production deployment (but not required)
This configuration requires the following:
* 6 vCPU
* 24GB RAM
* 300GB Storage
* VM hardware version 10 or greater (vSphere 5.5 or greater)
```

### Steps to Reproduce

1. Using `resource "vsphere_virtual_machine" "vmFromLocalOvf"` above
2. `terraform apply`
3. VM deploys with successfully but using default deploymentOption size. For NSX-T Manager, that's medium: 6 vCPU, 24GB RAM.

### Important Factoids
* Deployed on vSphere 6.7 & vSphere 7.0 with same results.
* Tested with NSX-T Manager 3.0.
* deploymentOption used in NSX-T Manager, vRealize Operations Manager, vRealize Log Insight etc.

### References

* William Lam describes the ovf options here: https://www.virtuallyghetto.com/2013/08/flexible-ovf-deployments-using.html
* Latest OVF Spec (2015-08-27 Version 2.1.1) https://www.dmtf.org/sites/default/files/standards/documents/DSP0243_2.1.1.pdf
* deploymentOption and others described at https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.0/installation/GUID-5843917A-A1D1-4D19-B9B0-0FD4C900C31C.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Duplicate of [issue #1209?](https://github.com/hashicorp/terraform-provider-vsphere/issues/1209)?

**Comment by daunce** [comment]
Thanks @tenthirtyam. Not sure how I didn't find this before. Closing as duplicate.
