### ISSUE TITLE
Race condition after creating virtual disks 

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [hashicorp/terraform-provider-vsphere#1307]
### Terraform Version
0.13

### vSphere Provider Version
1.24.2

### Affected Resource(s)
`vsphere_virtual_disk`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_disk" "Mizaru-an3deploy1-stripe1-local_grafana_disks" {
  size         = 1
  # vmdk_path should not contain a folder name unless using a vSAN datastore - this configuration is for non vSAN
  vmdk_path    = "${var.node_names[count.index]}_disk_grafana.vmdk"
  datacenter   = var.vsphere_datacenter
  datastore    = data.vsphere_datastore.datastore[count.index].name
  count        = 2
  type         = "thin"

  # We expect external disks to be long-living, and so we explicitly set this flag to
  # tell Terraform to ignore all changes to avoid the disk being accidentally deleted.
  lifecycle {
    ignore_changes = all
  }
}
```

### Debug Output

```
2020-11-12T13:32:04.704Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:04 [INFO] Created disk.
2020-11-12T13:32:04.704Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:04 [DEBUG] Virtual Disk id: [ronnies-eql:storage1] Mizaru-an3deploy1-local-simon-primary_disk_grafana.vmdk
2020-11-12T13:32:04.704Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:04 [DEBUG] Reading virtual disk.
2020-11-12T13:32:05.486Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:05 [DEBUG] num results: 0
2020-11-12T13:32:05.486Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:05 [DEBUG] resourceVSphereVirtualDiskRead - could not find: Mizaru-an3deploy1-local-simon-primary_disk_grafana.vmdk
2020/11/12 13:32:05 [DEBUG] module.Mizaru-an3deploy1-local.vsphere_virtual_disk.Mizaru-an3deploy1-local_grafana_disks[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to module.Mizaru-an3deploy1-local.vsphere_virtual_disk.Mizaru-an3deploy1-local_grafana_disks[0], provider "registry.terraform.io/hashicorp/vsphere" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/11/12 13:32:05 [ERROR] eval: *terraform.EvalApplyPost, err: Provider produced inconsistent result after apply: When applying changes to module.Mizaru-an3deploy1-local.vsphere_virtual_disk.Mizaru-an3deploy1-local_grafana_disks[0], provider "registry.terraform.io/hashicorp/vsphere" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

We've seen a race condition when creating `vsphere_virtual_disk` objects:

In https://github.com/hashicorp/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_disk.go, in the `resourceVSphereVirtualDiskCreate` function, we create the disk and then return `resourceVSphereVirtualDiskRead`,

See:

```
	err = createHardDisk(client, vDisk.size, ds.Path(vDisk.vmdkPath), vDisk.initType, vDisk.adapterType, vDisk.datacenter)
	if err != nil {
		return err
	}

	d.SetId(ds.Path(vDisk.vmdkPath))
	log.Printf("[DEBUG] Virtual Disk id: %v", ds.Path(vDisk.vmdkPath))

	return resourceVSphereVirtualDiskRead(d, meta)

```

We then in `resourceVSphereVirtualDiskRead`, perform a datastore search (`HostDatastoreBrowserSearchSpec`) for the disk that matches the pattern ` ds.Path(vDisk.vmdkPath)` (in our case `Mizaru-an3deploy1-local-simon-primary_disk_grafana.vmdk`).

We've seen a race condition where this datastore search can occasionally return 0 results:

```
2020-11-12T13:32:05.486Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:05 [DEBUG] num results: 0
2020-11-12T13:32:05.486Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/11/12 13:32:05 [DEBUG] resourceVSphereVirtualDiskRead - could not find: Mizaru-an3deploy1-local-simon-primary_disk_grafana.vmdk
```

I am tempted to put in some defensive code into the `resourceVSphereVirtualDiskCreate` (e.g. a sleep), but I don't know if that feels too dirty / speculative. I also wonder if speaking to VMware about this is the right thing to do here.

### Expected Behavior

Deploy works

### Actual Behavior

Deploy fails for the whole module with:

```
Error: Provider produced inconsistent result after apply
 When applying changes to
 module.Mizaru-an3deploy1-stripe1-local.vsphere_virtual_disk.Mizaru-an3deploy1-stripe1-local_grafana_disks[0],
 provider "registry.terraform.io/hashicorp/vsphere" produced an unexpected new
 value: Root resource was present, but now absent.
 This is a bug in the provider, which should be reported in the provider's own
 issue tracker.
```

### Steps to Reproduce
This does not reproduce every time (we see it more than 10% of the time), and I fear may be correlate to the business of the rig (vSphere Client version 6.7.0.45000)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thanks very much in advance!

**Comment by andrew-lee-metaswitch** [comment]
We believe that the problem was that vSphere is really slow at listing disks if there are loads in the folder that you are looking at.  At the time here, we were just dumping all "additional-disks" in the root folder of our datastore which made everything really slow.

**Comment by tenthirtyam** [comment]
I've needed to perform a sleep in similar situations both in the provider and the vRealize Automation provider when accessing some resources. 

Here's a [link](https://github.com/hashicorp/terraform-provider-vsphere/issues/1228#issuecomment-1026292915) to a recent example in another issue.

**Ryan Johnson**
Staff II Solutions Architect
Cloud Infrastructure Business Group, VMware

**Comment by tenthirtyam** [comment]
Marking as `pending-closure`. This is often mitigated with the sleep timer. 

Here's a [link](https://github.com/hashicorp/terraform-provider-vsphere/issues/1228#issuecomment-1026292915) to a recent example in another issue.

**Ryan Johnson**
Staff II Solutions Architect
Cloud Infrastructure Business Group, VMware

**Comment by tenthirtyam** [comment]
Please add a reaction to the other enhancement PR as there are currently none (and no linked enhancement issue)

Ryan

**Comment by tenthirtyam** [comment]
Set to `needs-triage`.

Ryan

**Comment by tenthirtyam** [comment]
re: 1417, I see you closed the related issue. I'm going to reopen and properly link these.

**Comment by tenthirtyam** [comment]
Closing per the following and no +1 👍 reactions.

_"... it's been over a year and I seem to recall that either this isn't an issue for us, or we've worked around it, so I don't care about this"
_
