### ISSUE TITLE
Support for hot remove CPU and Memory on VMs

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/terraform-provider-vsphere#1308]
Today we have scenarios where we want to decrease our allocation of CPU and Memory of nodes that are managed by terraform.   ```Hot add``` is supported but we need support for ```Hot remove``` too.  Right now instead of a reboot after the change, terraform completely destroys the node and rebuilds it if we decrease either of those two configurations.

We can do these changes, manually, in vsphere but of course that defeats the end goal of TF managing the infra - is there something we are missing here, or is this just not supported?

Thanks
Ian

**Comment by idrennanvmware** [comment]
https://github.com/hashicorp/terraform-provider-vsphere/blob/3b1d5a379663f08f37a65b7d3c1406baad3c4259/vsphere/virtual_machine_config_structure.go#L202

Looks like we missed this, closing the issue :)

**Comment by tenthirtyam** [comment]
Hi @idrennanvmware - this issue is still marked as open. As the author, can you self-close?

Ryan
