### ISSUE TITLE
terraform 0.14.5 crash with vSphere provider 1.24.3

### ISSUE THREAD

**Issue by chrisadkin** [hashicorp/terraform-provider-vsphere#1316]
### Affected Resource(s)

vsphere_virtual_machine

### Terraform Configuration Files

virtual_machines.tf:

variable "vm_template" {
  default = "ubuntu-18.04-terraform-template"
}

variable "vm_domain" {
  default = "uklab"
}

variable "vm_linked_clone" {
  default = "false"
}

variable "virtual_machines" {
  default = {
    "master1" = {
       name         = "z-ca-bdc-master1"
       ipv4_address = "10.225.113.79"
       cidr_netmask = 22
       ipv4_gateway = "10.225.112.1"
       dns_server   = "10.225.112.2"
       ram          = 8192 
       logical_cpu  = 4
       disk0_size   = 40
       disk1_size   = 0
    },
    "master2" =  {
       name         = "z-ca-bdc-master2"
       ipv4_address = "10.225.113.80"
       cidr_netmask = 22
       ipv4_gateway = "10.225.112.1"
       dns_server   = "10.225.112.2"
       ram          = 8192
       logical_cpu  = 4
       disk0_size   = 40
       disk1_size   = 0
    },
    "worker1" = {
       name         = "z-ca-bdc-worker1"
       ipv4_address = "10.225.113.81"
       cidr_netmask = 22
       ipv4_gateway = "10.225.112.1"
       dns_server   = "10.225.112.2"
       ram          = 69632
       logical_cpu  = 12
       disk0_size   = 40
       disk1_size   = 80 
    },
    "worker2" = {
       name         = "z-ca-bdc-worker2"
       ipv4_address = "10.225.113.82"
       cidr_netmask = 22
       ipv4_gateway = "10.225.112.1"
       dns_server   = "10.225.112.2"
       ram          = 69632
       logical_cpu  = 12
       disk0_size   = 40
       disk1_size   = 80
    },
    "worker3" = {
       name         = "z-ca-bdc-worker3"
       ipv4_address = "10.225.113.83"
       cidr_netmask = 69632
       ipv4_gateway = "10.225.112.1"
       dns_server   = "10.225.112.2"
       ram          = 68
       logical_cpu  = 12
       disk0_size   = 40
       disk1_size   = 80
    }
  }
}

vsphere.tf:

# Declare TF variables
variable "VSPHERE_USER" {
  description = "user for access vSphere vCenter appliance with"
  type        = string
  default     = "admin"
}

variable "VSPHERE_PASSWORD" {
  description = "password for user used for accessing vSphere vCenter appliance"
  type        = string
  default     = "P@ssw0rd"
}

variable "VSPHERE_SERVER" {
  description = "vSphere server ip address"
  type        = string
  default     = "10.123.123.25"
}

variable "VSPHERE_DC" {
  description = "vSphere data center name"
  type        = string
  default     = "lab"
}

variable "VSPHERE_CLUSTER" {
  description = "vSphere cluster name"
  type        = string
  default     = "Development"
}

variable "VSPHERE_HOST" {
  description = "vSphere ESXi host"
  type        = string
  default     = "esx1.lab.storage.com" 
}

variable "VSPHERE_DATASTORE" {
  description = "Datastore to be used for provisioning virtual disks from"
  type        = string
  default     = "datastore_VSI"
}

variable "VSPHERE_NETWORK" {
  description = "Network to use for virtual machine"
  type        = string
  default     = "VM Network"
}

variable "VSPHERE_RESOURCE_POOL" {
  description = "Resource pool to allocate virtual machine to"
  type        = string
  default     = "/lab/host/Development/Resources/CA"
}

variable "VSPHERE_VM_TEMPLATE" {
  description = "Template to create virtual machines from"
  type        = string
  default     = "ubuntu-18.04-terraform-template"
}

main.tf

provider "vsphere" {
  user           = var.VSPHERE_USER
  password       = var.VSPHERE_PASSWORD
  vsphere_server = var.VSPHERE_SERVER

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "lab"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "Development"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "host" {
  name          = "esx1.lab.storage.com" 
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = "datastore-VSI"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = "/lab/host/Development/Resources/CA"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vm_template
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "standalone" {
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  for_each = var.virtual_machines
  name       = each.value.name
  memory     = each.value.ram
  num_cpus   = each.value.logical_cpu
  guest_id   = "ubuntu64Guest"

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    unit_number      = 0
    label            = "OS"
    size             = each.value.disk0_size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    linked_clone  = var.vm_linked_clone

    customize {
      timeout = "20"

      linux_options {
        host_name = each.value.name
        domain    = var.vm_domain
      }

      network_interface {
        ipv4_address = each.value.ipv4_address 
        ipv4_netmask = each.value.cidr_netmask 
      }

      ipv4_gateway    = each.value.ipv4_gateway 
      dns_server_list = [ each.value.dns_server ]
    }
  }
}

### Panic Output

Gist to crash.log contents:

https://gist.github.com/chrisadkin/84a26ffd0cb6e564b9aa6ec540b7156c#file-crash-log

### Expected Behavior

I expect terraform not to bomb out with an error message stating that the cause is likely to be a bug

### Actual Behavior

Crash per the contents of the crash.log

### Steps to Reproduce

terraform apply

### Important Factoids

The environment I have encountered this problem with comprises of the following:

1. Client machine I'm running terraform on is an Ubuntu 18.04 VMware VM
2. Terraform version is v.0.14.5
3. vSphere version is 7.0.1
4. Terraform vSphere provider version is 1.24.3

**Comment by koikonom** [comment]
Hi @chrisadkin, thanks for reporting this. 

This is definitely a bug in the way we handle invalid netmasks. It is triggered by the value  of `cidr_netmask`  (set to 69632) in the `worker3` block.
