### ISSUE TITLE
OS family for guest ID "rhel8_64Guest": could not find guest ID "rhel8_64Guest"

### ISSUE THREAD

**Issue by Wali4** [hashicorp/terraform-provider-vsphere#1319]
### Terraform Version
Terraform v0.14.2

### vSphere Provider Version
vsphere v1.24.3

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Actual Behavior

Error: cannot find OS family for guest ID "rhel8_64Guest": could not find guest ID "rhel8_64Guest"

on ../modules/servers/linux_vm/main.tf line 37, in resource "vsphere_virtual_machine" "linux_vm":
37: resource "vsphere_virtual_machine" "linux_vm" {
### Steps to Reproduce

Configure terraform to use Redhat8 template. In the vmware> pick OS type. Rhel 8 x64. 

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
One critically important prince of information missing is the version of vSphere in the environment.

RHEL 8 is only supported on vSphere 7.0 or higher.

https://www.vmware.com/resources/compatibility/search.php?deviceCategory=software&details=1&partner=75&operatingSystems=258&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc&testConfig=16

Please advise if this error is seen on 7.0+ and provide the example code along with vSphere version and build number.

Ryan
@tenthirtyam

**Comment by ianangles** [comment]
Evening all, Just picking up on this thread (because I've just had the same issue) and I believe RHEL8 is supported back to ESXi 6.5 according to my search: https://www.vmware.com/resources/compatibility/search.php?deviceCategory=software&details=1&partner=75&releases=485&operatingSystems=258&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc&testConfig=16

**Comment by tenthirtyam** [comment]
You are correct. Here’s an [updated link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=software&details=1&partner=75&releases=578,518,508,448,485,428,427,369,429,408,367,338&operatingSystems=258&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc&testConfig=16)  for 6.5 and later.

**Comment by tenthirtyam** [comment]
Hi @Wali4 - could you provide an update if this is still an issue for you. Please see [comment above](https://github.com/hashicorp/terraform-provider-vsphere/issues/1319#issuecomment-980791336).

Ryan

**Comment by Wali4** [comment]
Hi @tenthirtyam, sorry for the delay. this is no longer an issue for us. Thank you very much! we are on terraform 0.15x

**Comment by Wali4** [comment]
Thanks again.

**Comment by tenthirtyam** [comment]
Thanks for the update @Wali4! Great to hear! 🎉 

Ryan
