### ISSUE TITLE
OVF-Template Example - CoreOS Container Linux OVA unavailable (Retired due to EOL - May 2020)

### ISSUE THREAD

**Issue by nacho-osete** [hashicorp/terraform-provider-vsphere#1324]
### Terraform Version
v0.14.5
### vSphere Provider Version
v1.24.3

### Affected Resource(s)

examples/ovf-template/scripts/template.sh
examples/ovf-template/terraform/virtual_machines.tf

### Terraform Configuration Files

```hcl
Not required, the issue is completely independent of any .tf configuration, as long as the OVA resource is missing. 

The OVA publisher deprecated this image, suggesting to use Fedora Core OS as a replacement. 
Here's the EOL announcement: https://coreos.com/os/eol/.
```

### Debug Output

```shell
/examples/ovf-template$ make template
scripts/template.sh
govc: Get "https://stable.release.core-os.net/amd64-usr/current/coreos_production_vmware_ova.ova": dial tcp: lookup stable.release.core-os.net on 8.8.8.8:53: no such host
make: *** [Makefile:18: template] Error 1
```

### Expected Behavior

The template script should have downloaded the OVA for further vApp/VM provisioning in the next step of the working example. 

### Actual Behavior

As long as the OVA is not publicly available anymore, the template.sh script cannot build/prepare the OVA at this stage of the example deployment.

### Steps to Reproduce

Once you have your environment ready to go (terraform, govc, related build-essential tools as make and git) an you have populated your GoVC vars, as well as your Terraform tfvars at /examples/ovf-template/terraform/terraform.tfvars.

```shell
cd /examples/ovf-template/
. scripts/preload_vars.sh
make build
make template
```

### Important Factoids

Issue reproduced under a Debian 10 Buster environment.

### References

https://github.com/hashicorp/terraform-provider-vsphere/tree/master/examples/ovf-template
https://coreos.com/os/eol/

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nacho-osete** [comment]
I will try to manage a workaround with Fedora Core OS if it supports all the already present Terraform Ignite provider configuration details (and maybe then propose a pull request afterwards).

**Comment by nacho-osete** [comment]
Well, after using a Fedora Core OS as a replacement, it works until the third phase as intended (just before the instructed *make infrastructure* step) but no further on.

Here's a possible new URL reference that may be edited at  **/examples/ovf-template/scripts/template.sh**. This lets the *make template* stage work as expected, fully provisioning a Fedora Core OS template.

```
TEMPLATE_URL="https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/33.20210104.3.1/x86_64/fedora-coreos-33.20210104.3.1-vmware.x86_64.ova"
```
Now the initial steps work as intended;

```
cd /examples/ovf-template/
. scripts/preload_vars.sh
make build
make template

~/terraform-workspace/terraform-provider-vsphere/examples/ovf-template$ make template
scripts/template.sh
[04-02-21 16:30:54] Warning: Line 71: Invalid value 'VM Network' for element 'Connection'.
[04-02-21 16:32:07] Uploading disk.vmdk... OK
```

Additional details to mention about this:

- The **last warning is vCenter related**,  as stated there: https://github.com/vmware/govmomi/issues/488 and [there](http://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.wssdk.apiref.doc/vim.OvfManager.CreateDescriptorResult.html)
- The example **still needs to have a review/fix at some .tf files**, as some methods are deprecated with the latest version of Terraform. There also some data type mismatch assignments, on virtual_machines.tf and ignition.tf
- The **ignition provider is not officially supported anymore**, being [moved to a community-driven repo here](https://registry.terraform.io/providers/community-terraform-providers/ignition/latest). This bring further issues and will need a rework as well, but that's a different story.

**Comment by tenthirtyam** [comment]
@nacho-osete ,

I've come across the _**very same**_ issues with this example. 

Instead, I would suggest that the example be removed from the project and later replaced with a more modern working and maintained example (if warranted). For now, it's better to remove the example than have it not work as intended.

@iBrandyJackson - would you agree?

Ryan

**Comment by appilon** [comment]
@tenthirtyam I agree the `examples/` folder has fallen out of date and we should remove any examples that currently don't work or don't promote best practices

**Comment by tenthirtyam** [comment]
Thanks, @appilon. I'll submit a PR to remove the legacy, non-functional content in /examples.

**Comment by tenthirtyam** [comment]
PR #1553 has been submitted to remove all example content in the `examples/` directory which has fallen out of date and is no longer functional.

Ryan
