### ISSUE TITLE
Import of `r/vmfs_datastore` results in unexpected folder changes during `plan`

### ISSUE THREAD

**Issue by hugh-martin** [hashicorp/terraform-provider-vsphere#1325]
### Terraform Version
v0.14.5
### vSphere Provider Version
registry.terraform.io/hashicorp/vsphere v1.24.3

### Affected Resource(s)
vsphere_vmfs_datastore

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "HMA"
}

resource "vsphere_vmfs_datastore" "esxbuslogs01_SVC--host-470527" {
name           = "esxbuslogs01_SVC"
host_system_id = "host-470527"
disks          = ["naa.60050768018e032250000000000000a3"]
folder         = "group-s37528"
}

resource "vsphere_vmfs_datastore" "esxbuslogs01_SVC--host-466983" {
name           = "esxbuslogs01_SVC"
host_system_id = "host-466983"
disks          = ["naa.60050768018e032250000000000000a3"]
folder         = "group-s37528"
}
...
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I am attempting to import existing infrastructure into Terraform, starting with datastores.  After the import, I would expect that subsequent terraform plan executions would result in no changes (assuming that there are no actual changes in vCenter, which is the case here).

### Actual Behavior
Subsequent terraform plan executions are showing that the 'folder' attribute has changed on every datastore.

terraform import (after terraform plan):

<pre>
<em>terraform import vsphere_vmfs_datastore.esxbuslogs01_SVC--host-470527 datastore-73682:host-470527</em>

vsphere_vmfs_datastore.esxbuslogs01_SVC--host-470527: Importing from ID "datastore-73682:host-470527"...
vsphere_vmfs_datastore.esxbuslogs01_SVC--host-470527: Import prepared!
  Prepared vsphere_vmfs_datastore for import
vsphere_vmfs_datastore.esxbuslogs01_SVC--host-470527: Refreshing state... [id=datastore-73682]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

<em>terraform import vsphere_vmfs_datastore.esxbuslogs01_SVC--host-466983 datastore-73682:host-466983</em>

vsphere_vmfs_datastore.esxbuslogs01_SVC--host-466983: Importing from ID "datastore-73682:host-466983"...
vsphere_vmfs_datastore.esxbuslogs01_SVC--host-466983: Import prepared!
  Prepared vsphere_vmfs_datastore for import
vsphere_vmfs_datastore.esxbuslogs01_SVC--host-466983: Refreshing state... [id=datastore-73682]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
</pre>

terraform plan (after terraform import):

<pre>
...
vsphere_vmfs_datastore.esxbuslogs01_SVC--host-470527: Refreshing state... [id=datastore-73682]
vsphere_vmfs_datastore.esxbuslogs01_SVC--host-466983: Refreshing state... [id=datastore-73682]

# vsphere_vmfs_datastore.esxbuslogs01_SVC--host-470527 will be updated in-place
  ~ resource "vsphere_vmfs_datastore" "esxbuslogs01_SVC--host-470527" {
      + folder               = "group-s37528"
        id                   = "datastore-73682"
        name                 = "esxbuslogs01_SVC"
        tags                 = []
        # (10 unchanged attributes hidden)
    }
...
# vsphere_vmfs_datastore.esxbuslogs01_SVC--host-466983 will be updated in-place
  ~ resource "vsphere_vmfs_datastore" "esxbuslogs01_SVC--host-466983" {
      + folder               = "group-s37528"
        id                   = "datastore-73682"
        name                 = "esxbuslogs01_SVC"
        tags                 = []
        # (10 unchanged attributes hidden)
    }
...
</pre>

### Important Factoids
Please note that I am making an assumption that I should define a resource for every VMHost that each datastore is connected to, so there are multiple resource definitions for the same datastore (one per connected host).  Also, I am working with individual datastores, not datastore clusters.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @hugh-martin! 👋🏻 

I took some time to review this issue today regarding the continued drift on subsequent `apply` after an import.

However, before I dig into this, I did want to note that there was a discrepancy in the example configuration you referenced. It used the folder `id` rather than the folder `path` in the `folder` argument.

Below is an example configuration from my testing which was the baselineI used for the testing:

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = "m01-dc01"
}

data "vsphere_host" "host" {
  name          = "m01-esx01.rainpole.io"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_folder" "folder" {
  depends_on = [
    vsphere_folder.folder,
  ]
  path = "foo"
}

resource "vsphere_folder" "folder" {
  path = "foo"
  type = "datastore"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_vmfs_datastore" "gh-1325" {
  name           = "gh-1325"
  disks          = ["naa.64cd98f045c4f20025b647f1efc809df"]
  host_system_id = data.vsphere_host.host.id
  folder         = data.vsphere_folder.folder.path
}
```

In this example, I can import the both resources.

```console
❯ terraform import vsphere_vmfs_datastore.gh-1325 datastore-52026:host-10
vsphere_vmfs_datastore.gh-1325: Importing from ID "datastore-52026:host-10"...
vsphere_vmfs_datastore.gh-1325: Import prepared!
  Prepared vsphere_vmfs_datastore for import
vsphere_vmfs_datastore.gh-1325: Refreshing state... [id=datastore-52026]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

❯ terraform import vsphere_folder.folder /foo
vsphere_folder.folder: Importing from ID "/foo"...
vsphere_folder.folder: Import prepared!
  Prepared vsphere_folder for import
vsphere_folder.folder: Refreshing state... [id=group-s52025]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

If I run a plan, no changes are required to the folder in this very simple pattern:

```console
❯ terraform plan
vsphere_folder.folder: Refreshing state... [id=group-s52025]
vsphere_vmfs_datastore.gh-1325: Refreshing state... [id=datastore-52026]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences,
so no changes are needed.
```

And the correct information is in the state for the `r/vmfs_datastore`:

```json
    {
      "mode": "managed",
      "type": "vsphere_vmfs_datastore",
      "name": "gh-1325",
      "provider": "provider[\"local/hashicorp/vsphere\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "accessible": true,
            "capacity": 1597459,
            "custom_attributes": {},
            "datastore_cluster_id": "",
            "disks": [
              "naa.64cd98f045c4f20025b647f1efc809df"
            ],
            "folder": "foo",                                 <<<<======= folder path
            "free_space": 1595925,
            "host_system_id": "host-10",
            "id": "datastore-52026",
            "maintenance_mode": "normal",
            "multiple_host_access": false,
            "name": "gh-1325",
            "tags": [],
            "uncommitted_space": 0,
            "url": "ds:///vmfs/volumes/622126f7-99ad9964-e34c-4cd98f4a36d1/"
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }
```

However, let's say I change the plan to be even simpler but use a nested path of `foo/bar` for the `folder`.

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = "m01-dc01"
}

data "vsphere_host" "host" {
  name          = "m01-esx01.rainpole.io"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_folder" "folder" {
  path = "/m01-dc01/datastore/foo"
}

resource "vsphere_vmfs_datastore" "gh-1325" {
  name           = "gh-1325"
  disks          = ["naa.64cd98f045c4f20025b647f1efc809df"]
  host_system_id = data.vsphere_host.host.id
  folder         = data.vsphere_folder.folder.path
}
```

I can import this successfully:

```console
❯ terraform import vsphere_vmfs_datastore.gh-1325 datastore-52028:host-10
vsphere_vmfs_datastore.gh-1325: Importing from ID "datastore-52028:host-10"...
vsphere_vmfs_datastore.gh-1325: Import prepared!
  Prepared vsphere_vmfs_datastore for import
vsphere_vmfs_datastore.gh-1325: Refreshing state... [id=datastore-52028]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

However, on a `plan` or `apply` the following will be seen which it the issue you are seeing repeatedly as the delta is seen but not applied to the state.

```console
❯ terraform plan
vsphere_vmfs_datastore.gh-1325: Refreshing state... [id=datastore-52028]

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_vmfs_datastore.gh-1325 will be updated in-place
  ~ resource "vsphere_vmfs_datastore" "gh-1325" {
      ~ folder               = "foo" -> "m01-dc01/datastore/foo"
        id                   = "datastore-52028"
        name                 = "gh-1325"
        tags                 = []
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

This above pattern **_seems_** to be what you are expereincing and it might be based on your `path`

I ran another, more complicated example with nested datastore folders like `/<datacenter>/datastore/<folder_0>/<folder_1>` with success.

For example:

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = "m01-dc01"
}

data "vsphere_host" "host" {
  name          = "m01-esx01.rainpole.io"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_folder" "folder_foo" {
  path = "foo"
  type = "datastore"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_folder" "folder_bar" {
  path = "foo/bar"
  type = "datastore"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_vmfs_datastore" "gh-1325" {
  name           = "gh-1325"
  disks          = ["naa.64cd98f045c4f20025b647f1efc809df"]
  host_system_id = data.vsphere_host.host.id
  folder         = vsphere_folder.folder_bar.path
}
```

Results:

```console
❯ terraform import vsphere_folder.folder_foo /foo
vsphere_folder.folder_foo: Importing from ID "/foo"...
vsphere_folder.folder_foo: Import prepared!
  Prepared vsphere_folder for import
vsphere_folder.folder_foo: Refreshing state... [id=group-s52032]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

❯ terraform import vsphere_folder.folder_bar /bar
vsphere_folder.folder_bar: Importing from ID "/bar"...
vsphere_folder.folder_bar: Import prepared!
  Prepared vsphere_folder for import
vsphere_folder.folder_bar: Refreshing state... [id=group-s52033]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

❯ terraform import vsphere_vmfs_datastore.gh-1325 datastore-52034:host-10
vsphere_vmfs_datastore.gh-1325: Importing from ID "datastore-52034:host-10"...
vsphere_vmfs_datastore.gh-1325: Import prepared!
  Prepared vsphere_vmfs_datastore for import
vsphere_vmfs_datastore.gh-1325: Refreshing state... [id=datastore-52034]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

The state looks as follows for `r/vmfs_datastore`:

```json
    {
      "mode": "managed",
      "type": "vsphere_vmfs_datastore",
      "name": "gh-1325",
      "provider": "provider[\"local/hashicorp/vsphere\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "accessible": true,
            "capacity": 1597459,
            "custom_attributes": {},
            "datastore_cluster_id": "",
            "disks": [
              "naa.64cd98f045c4f20025b647f1efc809df"
            ],
            "folder": "foo/bar",,                                 <<<<======= folder path
            "free_space": 1595925,
            "host_system_id": "host-10",
            "id": "datastore-52034",
            "maintenance_mode": "normal",
            "multiple_host_access": false,
            "name": "gh-1325",
            "tags": [],
            "uncommitted_space": 0,
            "url": "ds:///vmfs/volumes/62212d76-e682bed2-feb1-4cd98f4a36d1/"
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }
```

And running a` plan` or `apply` shows no changes:

```console
❯ terraform plan
vsphere_folder.folder_bar: Refreshing state... [id=group-s52033]
vsphere_folder.folder_foo: Refreshing state... [id=group-s52032]
vsphere_vmfs_datastore.gh-1325: Refreshing state... [id=datastore-52034]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences,
so no changes are needed.
```

Based on the testing, I beleive that this is functioning as intended.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on [the previous comments and testing](https://github.com/hashicorp/terraform-provider-vsphere/issues/1325#issuecomment-1058502022).

If this issue is reproducible with the [latest](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) version of the provider using the syntax mentioned prior or if you feel this issue should be reopened, please create a new issue with reference to this one for added context. 

Thank you!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
