### ISSUE TITLE
Vapp option in vsphere_virtual_machine resource does not work with other types than String

### ISSUE THREAD

**Issue by barbaluc** [hashicorp/terraform-provider-vsphere#1333]
### Terraform Version
Terraform v0.14.2

### vSphere Provider Version
version = "1.24.0" (versions above doesn't work at all)

### Affected Resource(s)
`vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "haproxy" {
  name  = "haproxy"
  datastore_id  = data.vsphere_datastore.datastore.id
  resource_pool_id  = data.vsphere_compute_cluster.cluster.resource_pool_id
  host_system_id = data.vsphere_host.host.id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  datacenter_id  = data.vsphere_datacenter.dc.id
  ovf_deploy {
    remote_ovf_url  = "https://cdn.haproxy.com/download/haproxy/vsphere/ova/haproxy-v0.1.10.ova"
    disk_provisioning  = "thick"
    ip_protocol = "IPV4"
    ip_allocation_policy = "STATIC_MANUAL"
    ovf_network_map = {
      "Management" = data.vsphere_network.lan.id
      "Workload"  = data.vsphere_network.kubernetes.id
      "Frontend"  = data.vsphere_network.kubernetes.id
    }
  }
  vapp {
    properties = {
      "permit_root_login"  = "True"
      "root_pwd"  = "root_pwd"
      "dataplane_port" = "5556"
      "haproxy_pwd"  = "haproxy_pwd"
      "haproxy_user" = "admin"
      "service_ip_range"  = "service_ip_range"
      "hostname"  = "haproxy"
      "management_gateway"  = "management_gateway"
      "management_ip"  = "management_ip"
      "nameservers"  = "nameservers"
      "workload_gateway" = "workload_gateway"
      "workload_ip" = "workload_ip"
    }
  }
}
```

### Debug Output

https://gist.github.com/barbaluc/693582cacb70f23c743b183b1147d54f

### Expected Behavior

All parameters should be take into account an be visible in virtualmachine settings (vApp options)

### Actual Behavior

The parameters with types different from string (Password, boolean, int) has vanished

### Steps to Reproduce

terraform init
terraform apply

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@barbaluc 

For the case of boolean, I can provide some insight.

In Terraform a `bool` is `true` or `false`.

**Example**: Variable for the Terraform provider for VMware vSphere configuration.

```hcl
variable "vsphere_insecure" {
  type        = bool
  description = "Allow insecure connections. Set to `true` for self-signed certificates."
  default     = false
}
```

However, for OVF properties, even though the type is `booleen`, the vApp Options only accept the values of "True" or "False". In these instances, it's recommended to define the variable as a `string` in the Terraform plan and pass the value in the correct title case.

**Example**: Variable for Terraform provider for VMware vSphere to pass as an OVF property to an OVA.

```hcl
variable "appliance_ssh_enabled" {
  type        = string
  description = "Enable SSH on the virtual appliance. One of `True` or `False`."
  default     = "True"
}
```

By doing so, the property will be reflected correctly in vSphere.

>NOTE:  You **won't** be able to get crafty declare it as bool in Terraform and then attempt to convert it to a title case string using `title(format("%s", var.appliance_ssh_enabled))` as Go is strongly typed.

Hope this helps,
Ryan

**Comment by barbaluc** [comment]
Hello @tenthirtyam,

Thanks for your help. I well try this.

Lucas
