### ISSUE TITLE
Deleted dvPortGroup results in ServerFaultCode: The object 'vim.dvs.DistributedVirtualPortgroup:dvportgroup-105452' has already been deleted or has not been completely created

### ISSUE THREAD

**Issue by ptpford** [hashicorp/terraform-provider-vsphere#1337]
### Terraform Version
0.14.5
### vSphere Provider Version
v1.24.3

### Affected Resource(s)
- `vsphere.distributed_port_group`

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "site" {
  name = "site"
}

resource "vsphere_distributed_virtual_switch" "site-vms" {
  name          = "site-dvSwitch-vm"
  datacenter_id = data.vsphere_datacenter.site.id

  uplinks         = ["uplink1", "uplink2"]
  active_uplinks  = ["uplink1", "uplink2"]
  standby_uplinks = []
}

resource "vsphere_distributed_port_group" "site-servers" {
  name                            = "dvs-servers"
  distributed_virtual_switch_uuid = vsphere_distributed_virtual_switch.site-vms.i
d

  vlan_id = 100
}

```

### Debug Output

https://gist.github.com/ptpford/4661e07c4fc66580bfc75c53e1a7a8ab

### Expected Behavior

Detect the missing resource and re-create it.

### Actual Behavior

Errorred out on the now-missing resource.

### Steps to Reproduce

1. `terraform apply`
2. Login to vCenter and delete the port group
3. `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@ptpford,

The following with the `depends_on` should resolve the issue:

```hcl
data "vsphere_datacenter" "site" {
  name = "site"
}

resource "vsphere_distributed_virtual_switch" "site-vms" {
  name            = "site-dvSwitch-vm"
  datacenter_id   = data.vsphere_datacenter.site.id
  uplinks         = ["uplink1", "uplink2"]
  active_uplinks  = ["uplink1", "uplink2"]
  standby_uplinks = []
}

resource "vsphere_distributed_port_group" "site-servers" {
  depends_on                      = ["vsphere_distributed_virtual_switch.site-vms"]
  name                            = "dvs-servers"
  distributed_virtual_switch_uuid = vsphere_distributed_virtual_switch.site-vms.id
  vlan_id                         = 100
}
```

Let me know if this helps,

Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the comments and solution provided earlier in the thread.

If the issue persists with the latest version of the provider, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware
