### ISSUE TITLE
vsphere_content_library_item doc: name property argument reference seems wrong

### ISSUE THREAD

**Issue by magnush0lm** [hashicorp/terraform-provider-vsphere#1340]
At https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/content_library_item the argument reference lists "name" as "The name of the Content Library.".

I suspect it should be "The name of the Content Library **_item_**."

**Comment by tenthirtyam** [comment]
Submitted https://github.com/hashicorp/terraform-provider-vsphere/pull/1507 to address this issue.

Ryan
@tenthirtyam
