### ISSUE TITLE
Wrong template when cloning

### ISSUE THREAD

**Issue by dghogg** [hashicorp/terraform-provider-vsphere#1342]
### Terraform Version
0.14.6

### vSphere Provider Version
1.24.3

### Affected Resource(s)

data "vsphere_virtual_machine" "template"

### Notes

Hi team. I haven't attached my config files because I'd need to redact most of it (as I'm sure many do) and it's basically a generic copy/paste from the Hashicorp site of the vsphere module for provisioning VMs from templates. Anyway - when I target a template named like this:

"WINDOWS_ADMIN_DC3"

It picks up "WINDOWS_ADMIN_DC1" instead. I've now removed the underscores and the correct template is being targetted. Not sure how the mechanism works behind the scenes but it seems to dislike underscores.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
This issue really needs more information for community support. If you are unable to provide additional information or if the problem is resolved, please update.

Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment]
cc @iBrandyJackson for review.

**Comment by tenthirtyam** [comment]
Hi @dghogg,

I'm marking this issue as closed based on the comments earlier in the thread and the staleness of the issue..

However, I did do some sanity checks with the latest version of the provider (as of v2.0.2) using templates with underscores and the same names (`WINDOWS_ADMIN_DC3` and `WINDOWS_ADMIN_DC1`). I was unable to reproduce the issue and the correct templates were used from the data source.

A simple example used in the reproduction is provided below:

 ```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
    datastore_id     = data.vsphere_datastore.datastore.id
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      windows_options {
        computer_name         = var.vm_name
        join_domain           = var.domain
        domain_admin_user     = var.domain_admin_username
        domain_admin_password = var.domain_admin_password
        admin_password        = var.vm_admin_password
      }
      network_interface {
        ipv4_address = var.vm_ipv4_address
        ipv4_netmask = var.vm_ipv4_netmask
      }

      ipv4_gateway    = var.vm_ipv4_gateway
      dns_suffix_list = var.vm_dns_suffix_list
      dns_server_list = var.vm_dns_server_list
    }
  }

  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
}
```

If the issue persists with the latest version of the provider, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
