### ISSUE TITLE
Ability to change the auto_logon username during windows clone customization

### ISSUE THREAD

**Issue by bsmienk** [hashicorp/terraform-provider-vsphere#1343]
When we use the vsphere_virtual_machine Terraform resource to clone and customize Windows Server, we like to use the auto_logon, admin_password and run_once_command_list parameters to perform some steps after the installation.
However, Terraform will also join the server to our domain. When that happens, the local administrator account gets a different name thanks to our CIS policies. Because of that, Terraform fails to logon and perform the command list.

Obviously, there are work-arounds to make this work, but I think it would be useful to have the ability to change the username that is used for auto_logon.

**Comment by jweigand** [comment]
I don't believe this is possible due to *VMware* limitations, not an issue with the provider itself. VMware does not provide a method for setting a username other than "Administrator" to login during customization. Take Terraform out of the equation, you'd have this same issue if you were manually deploying the VMs through vCenter.

**Comment by bsmienk** [comment]
> 
> 
> I don't believe this is possible due to _VMware_ limitations, not an issue with the provider itself. VMware does not provide a method for setting a username other than "Administrator" to login during customization. Take Terraform out of the equation, you'd have this same issue if you were manually deploying the VMs through vCenter.

I don't have much experience cloning and customizing Windows Server using VMWare itself, so I believe you when you say that this is a VMWare limitation. I do have experience using Windows Deployment Services and unattend files to install and customize WIndows Servers. I was expecting VMWare to use the same method (under water) to customize Windows Servers.

Using an unattend file, I am able to change the auto logon username.
If this indeed impossible in VMWare, this request should be closed.

**Comment by tenthirtyam** [comment]
@appilon, could you review the above thread and close this enhancement issue? 

Ryan
