### ISSUE TITLE
join_domain on Windows server not reporting a failure when failing to join the domain

### ISSUE THREAD

**Issue by kinwolfqc** [hashicorp/terraform-provider-vsphere#1350]
In the code, I forgot to add the `domain_admin_user` field.   Yet, doing the apply and creating the VM returned no error at all, but of course, the server wasn't joined to any domain.  Rerunning it reported the infrastructure as up-to-date.  So, I got no error message that joining the domain failed and I was actually wondering why the server wasn't joining the domain at all.  It's only by looking in the tfstate file that I noticed `domain_admin_password` and `domain_admin_user` were empty and then tracked down my error/omission in the code.

### Terraform Version
0.13.4
### vSphere Provider Version
1.24.3

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = var.vm_name
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = "Labs"

  num_cpus = var.vm_vcpu_count
  memory   = var.vm_memory
  guest_id = data.vsphere_virtual_machine.template.guest_id

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  disk {
    label            = "data"
    size             = 10
    thin_provisioned = true
    unit_number      = 1
  }
  disk {
    label            = "e"
    size             = 10
    thin_provisioned = true
    unit_number      = 2
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      windows_options {
        computer_name  = var.vm_name
        join_domain    = var.domain_name
        admin_password = var.vm_admin_password
      }

      #DHCP.
      network_interface {}
    }

  }
}
```

### Expected Behavior

An error should be reported that joining the domain failed

### Actual Behavior

No error message, success reported and infrastructure reported as fully compliant on a re-run.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Ideally, I think the behavior should be that if ` join_domain` is used in the `windows_options { }` configuration, that `domain_admin_user` and `domain_admin_password` should be required. 

I think this can be best addressed with `RequiredWith:  []string{"join_domain"},` being added to schema for `domain_admin_user` and `domain_admin_password` in `virtual_machine_customize_subresource.go`. By doing so, if `join_domain` is used, these two arguments would be required.

For example:

```go
 // CustomizationIdentification 
 "domain_admin_user": { 
 	Type:          schema.TypeString, 
 	Optional:      true, 
 	ConflictsWith: []string{cWindowsKeyPrefix + "." + "workgroup"}, 
        RequiredWith:  []string{"join_domain"},
 	Description:   "The user account of the domain administrator used to join this virtual machine to the domain.", 
 }, 
 "domain_admin_password": { 
 	Type:          schema.TypeString, 
 	Optional:      true, 
 	Sensitive:     true, 
 	ConflictsWith: []string{cWindowsKeyPrefix + "." + "workgroup"}, 
        RequiredWith:  []string{"join_domain"},
 	Description:   "The password of the domain administrator used to join this virtual machine to the domain.", 
 }, 
 "join_domain": { 
 	Type:          schema.TypeString, 
 	Optional:      true, 
 	ConflictsWith: []string{cWindowsKeyPrefix + "." + "workgroup"}, 
 	Description:   "The domain that the virtual machine should join.", 
 }, 
 "workgroup": { 
 	Type:          schema.TypeString, 
 	Optional:      true, 
 	ConflictsWith: []string{cWindowsKeyPrefix + "." + "join_domain"}, 
 	Description:   "The workgroup for this virtual machine if not joining a domain.", 
 }, 
```

Reference: https://github.com/hashicorp/terraform-provider-vsphere/blob/3d39b81023d0f75134f1a7131fdd0ffbfb30e059/vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go#L147-L172

@appilon - Let me know your thoughts on this one if you have a moment to review it.

If so, I can take this one to update and test. 

Ryan
