### ISSUE TITLE
Documentation is not clear about required privileges and at which level these should be applied

### ISSUE THREAD

**Issue by greeneg** [hashicorp/terraform-provider-vsphere#1356]
### Description

Our environment uses a least-privilege environment. When we provision, we get NoPermission errors when it tries to provision:

NoPermission: RESOURCE (vm-3962:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-3962), ACTION (PolicyIDByVirtualDisk)

Current privileges:
- Datastore
  - Allocate space
  - Browse datastore
  - Low level file operations
  - Remove file
  - Update virtual machine files
  - Update virtual machine metadata
- Folder (all)
  - Create folder
  - Delete folder
  - Move folder
  - Rename folder
- Network
  - Assign network
- Resource
  - Apply recommendation
  - Assign virtual machine to resource pool
- Virtual Machine
  - Configuration (all) - for now
  - Guest Operations (all) - for now
  - Interaction (all)
  - Inventory (all)
  - Provisioning (all)

Looking for more thorough documentation on privileges required and what segments of the vCenter the privileges should be assigned under.

**Comment by tenthirtyam** [comment]
Are you looking for a single set documentation of privileges per resource/data source?

Ryan

**Comment by bhadrim** [comment]
@tenthirtyam Thank you for looking into this. It would be nice to have a table in a single page as documented in _Required Privileges for Common Tasks table_ in this [page](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.security.doc/GUID-4D0F8E63-2961-4B71-B365-BBFA24673FDB.html)
