### ISSUE TITLE
`self.default_ip_address` not updating

### ISSUE THREAD

**Issue by fabricesemti80** [hashicorp/terraform-provider-vsphere#1359]
Hi!

I have an issue similar to  [this one](https://github.com/hashicorp/terraform-provider-vsphere/issues/671)

I am creating a VM with a module fine, and it is receiving a DHCP address upon creation.

![image](https://user-images.githubusercontent.com/37410363/110474844-10518000-80d8-11eb-80f9-3bd8d51ed2dd.png)

As per my [script](https://code.prkr.li/6047731a2b38ad032b4b667a), the customization then changes the ipv4_address. This change is confirmed by VMware

![image](https://user-images.githubusercontent.com/37410363/110475292-9e2d6b00-80d8-11eb-930c-d55c3cd7ea53.png)

(as you can see, there is also VMware tools installed, so vSphere is aware of the address)

However Terraform still times out, as the provisioner - using  host     = self.default_ip_address - still tries to connect to the intial / DHCP address.

Attached are the full log files, where Terraform recreates this resource (and fails to run the provisioners, as described).

![image](https://user-images.githubusercontent.com/37410363/110475525-e5b3f700-80d8-11eb-9e95-493ba88a2512.png)
[terraform.txt](https://github.com/hashicorp/terraform-provider-vsphere/files/6108712/terraform.txt)

- is there any workaround for this please
- if not, is there any plans to fix this?
- (for single VM, I might be able to get away with hard coding the IP into the .tf file, but for multiple VM creation I need a dynamic way to populate the address....)

**Comment by tenthirtyam** [comment]
Hi @fabricesemti80, is this still an issue that you are experiencing? If so, can you share a redacted version of the configuration plan?

Ryan

**Comment by tenthirtyam** [comment]
Marking as closed based on the staleness of the issue and no community reactions. 👍🏻 👎🏻 

If the issue persists with [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), even using the basic config example above,  please open a new issue and reference this issue for additional context. If/when opening a new issue, please provide a copy of the module in a Gist as this would be helpful.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
