### ISSUE TITLE
Affinity rules fails to update after VM ID changes

### ISSUE THREAD

**Issue by javierlga** [hashicorp/terraform-provider-vsphere#1362]
### Terraform Version
v0.13.5

### vSphere Provider Version
1.24.3

### Affected Resource(s)

- `vsphere_virtual_machine`
- `vsphere_compute_cluster_vm_affinity_rule`

### Terraform Configuration Files

```hcl
module "vsphere-vm" {
  source = "../vms"

  vm_info = [
    {
      name = "vm-aff"
    }]

  disk_info = [{
    size = 60
  }]

  resource_pool_id  = "XXX"
  vm_template_info  = "XXX"
  network_ids       = "XXX"
}

module "aff-rule" {
  source = "../affinity-rules"

  create_affinity_rule = true

  rule_name  = "aff-rule"
  cluster_id = "XXX"
  vm_ids     = module.vsphere-vm.vm_id
}

```

### Debug Output
https://gist.github.com/javierlga/23d3b40cac3afcd5e303e749233ef911#file-vsphere-debug-output

### Expected Behavior
Create a VM and an affinity rule, update the VM, and successfully update the affinity rule as well.

### Actual Behavior
After updating a VM (like changing the name for example), affinity rules fails to update.

### Steps to Reproduce
1. `terraform apply`
2.  Update a VM attribute like the name.
3. `terraform apply`
4. VM will be updated but the affinity rule crashes.

### Important Factoids
No

### References
No

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by javierlga** [comment]
> What do you mean "the affinity rule crashes" - is there an error?
> 
> I'm not aware of many/any vcenter operations that would cause the VM ID to change, including changing the name, that would cause the vcenter database to lose track of the VM if the ID changed. Are you sure it's actually changing?

Yes I saw it during the apply, this is the error that I have:

Error: A specified parameter was not correct: rulesSpec[0].info.key

**Comment by lsybrandt** [comment]
Here to report the same issue.   

Error: A specified parameter was not correct: rulesSpec[0].info.key

Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/vault v2.14.0
+ provider registry.terraform.io/hashicorp/vsphere v1.24.0

Code snip

resource "vsphere_compute_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule" {
  name                = "terraform-anti-affinity"
  enabled            = true
  mandatory        = true
  compute_cluster_id  = data.vsphere_compute_cluster.cluster.id
  virtual_machine_ids = vsphere_virtual_machine.vm.*.id
}

This happens on a VM rebuild of a server in an affinity ruleset

I think it is happening because it will remove the UUID of the VM, but not know the replacement UUID in the order the rule requires it

      + virtual_machine_ids = [
          + "420ca5d3-2581-52d0-25c8-e6c5dc04e1e1",
        ]

**Comment by tenthirtyam** [comment]
@appilon - would you suggest this is an `enhancement` rather than a `bug`?

**Comment by tenthirtyam** [comment]
This would be expected behavior. 

For simplicity, let's say you have a plan to manage an anti-affinity rule for a set of virtual machines like below.

This example is based on:
- Terrafrom v1.1.4
- Terraform Provider for vSphere v2.0.2
- vSphere v7.0.3c

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.2"
    }
  }
  required_version = ">= 1.1.4"
}

variable "ruleset_name" {
  type        = string
  description = "The name of the anti-affinity rule."
}

able "ruleset_vms" {
  type        = list(string)
  description = "A list of virtual machines."
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "ruleset_vms" {
  count         = length(var.ruleset_vms)
  name          = var.ruleset_vms[count.index]
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_compute_cluster_vm_anti_affinity_rule" "tf-example-01" {
  name                = var.ruleset_name
  enabled             = true
  compute_cluster_id  = data.vsphere_compute_cluster.cluster.id
  virtual_machine_ids = data.vsphere_virtual_machine.ruleset_vms[*].id
}
```

and your vars are

```hcl
vsphere_datacenter = "m01-dc01"
vsphere_cluster    = "m01-cl01"
ruleset_name       = "tf-example-01"
ruleset_vms = [
  "tf-example-01a",
  "tf-example-01b"
]
```

Now, let's say that virtual machine `tf-example-01B` is rebuilt outside in another plan, thus the ID will change.

On the next run of the plan you'll see:

```console
❯ terraform apply --auto-approve
vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01: Refreshing state... [id=domain-c6045:201]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01 has changed
  ~ resource "vsphere_compute_cluster_vm_anti_affinity_rule" "tf-example-01" {
        id                  = "domain-c6045:201"
        name                = "tf-example-01"
      ~ virtual_machine_ids = [
          - "420295d6-ff61-fc41-ac6c-e669a63a3596",
            # (1 unchanged element hidden)
        ]
        # (3 unchanged attributes hidden)
    }
```

And then the following...

```console
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01 will be updated in-place
  ~ resource "vsphere_compute_cluster_vm_anti_affinity_rule" "tf-example-01" {
        id                  = "domain-c6045:201"
        name                = "tf-example-01"
      ~ virtual_machine_ids = [
          + "4202ce45-0e8a-e045-b5d9-d9cf887a192a",
            # (1 unchanged element hidden)
        ]
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

At this point, the anti-affinity rule is back to the desired state with the replacement `tf-example-01B`.

That said, I could have also run the following to force the entire `vsphere_compute_cluster_vm_anti_affinity_rule` resource to be recreated:

```console
❯ terraform taint vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01
Resource instance vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01 has been marked as tainted.

❯ terraform apply --auto-approve
vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01: Refreshing state... [id=domain-c6045:201]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01 is tainted, so must be replaced
-/+ resource "vsphere_compute_cluster_vm_anti_affinity_rule" "tf-example-01" {
      ~ id                  = "domain-c6045:201" -> (known after apply)
      - mandatory           = false -> null
        name                = "tf-example-01"
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01: Destroying... [id=domain-c6045:201]
vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01: Destruction complete after 0s
vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01: Creating...
vsphere_compute_cluster_vm_anti_affinity_rule.tf-example-01: Creation complete after 0s [id=domain-c6045:202]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

Which for the original description should work to taint the `vsphere_compute_cluster_vm_anti_affinity_rule` resource but not the `vsphere_virtual_machine` resources and thus force a destroy and recreate only on the `vsphere_compute_cluster_vm_anti_affinity_rule` resource on the next apply.

@appilon - Would you agree that this would be an expected behavior when a virtual machine resource ID changes and one such method to resolve the discrepancy in the state for the anti-affinity rule resource?

**Comment by javierlga** [comment]
@tenthirtyam To be honest I'm no longer working with the client, so it's difficult to test it again with a newer Terraform or provider version, however, I'd like to mention that the example provided may work because you're managing the resources independently (one state for the VMs and one for the affinity rules), in my scenario both resources were modified in the same action (sharing one single state).

**Comment by tenthirtyam** [comment]
@javierlga, yes you are correct regarding the simplistic example. However, as I mentioned, you could taint the specific resource in a shared state to force that resource to be recreated with the updated ID.

Does that make sense?

**Comment by javierlga** [comment]
@tenthirtyam Yes, tainting it makes sense, but if you're using Terraform Cloud/Enterprise workspaces and use the VCS workflow, you can't manage the state, and also, even when working with the CLI driven one, it forces the operator to run specific actions outside of a pipeline, for example.

**Comment by tenthirtyam** [comment]
Thanks for the updates, @javierlga. I'll pass this up next to @appilon for issue perspective.

**Comment by cagataygurturk** [comment]
I have encountered the same problem after my VMs were replaced by new ones. A workaround is to use lifecycle.replace_triggered_by and use the vsphere_virtual_machine_node resource as trigger:

```
resource "vsphere_compute_cluster_vm_anti_affinity_rule" "node" {
  for_each            = {for pool_id, pool in {for pool_id, pool in var.node_pools : pool_id => pool if pool.anti_affinity == true} : pool_id => pool if pool.count > 0}
  name                = each.key
  compute_cluster_id  = data.vsphere_compute_cluster.gws.id
  virtual_machine_ids = [
  for node_name, node in local.nodes : vsphere_virtual_machine.node[node_name].id if node.node_pool_name == each.key
  ]
  mandatory = true
  lifecycle {
    replace_triggered_by = [vsphere_virtual_machine.node]
  }
}
```

At least in my use case, whenever I replace my vsphere_virtual_machine's, first the affinity rule is completely destroyed and a new one is created with new IDs.

**Comment by tenthirtyam** [comment]
That's a very clever solution to address this concern, @cagataygurturk.

Would you consider doing a PR on the resource to demonstrate the scenario and how to address it?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by cagataygurturk** [comment]
Please see https://github.com/hashicorp/terraform-provider-vsphere/pull/1700 @tenthirtyam

**Comment by tenthirtyam** [comment]
Merged!
