### ISSUE TITLE
Enhance the `extra_config` argument use with OVF/OVA

### ISSUE THREAD

**Issue by avseelam** [hashicorp/terraform-provider-vsphere#1370]
### Description

The extra config attribute currently doesn't work as expected with deployment of VM through OVF/OVA

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@avseelam - could you provide an example that is not working for you!

Ryan

**Comment by tenthirtyam** [comment]
Marking as `pending-closure`. More context is needed to support any desired enhancements requests.

Ryan
