### ISSUE TITLE
Import of `vsphere_datacenter` resource does not register `folder` argument

### ISSUE THREAD

**Issue by backstorey** [hashicorp/terraform-provider-vsphere#1374]
### Terraform Version
0.14.8
### vSphere Provider Version
1.25.0

### Affected Resource(s)

vsphere_datacenter

### Terraform Configuration Files

```hcl
resource "vsphere_datacenter" "bar" {
  name = "BAR"
  folder = "/FOO/"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

```terraform import vsphere_datacenter.bar /FOO/BAR```

Should import the datacenter resource, including the path to it's parent folder.

### Actual Behavior

The datacenter succesfully imports, but the folder property ends up as null in the state.  It's not getting imported.

Similiarly, running:

```terraform state show vsphere_datacenter.bar```

Shows the folder property as missing.

```hcl
resource "vsphere_datacenter" "bar" {
    custom_attributes = {}
    id                = "BAR"
    moid              = "datacenter-7624"
    name              = "BAR"
    tags              = []
}
```

This causes subsequent plan operations to trigger a destroy / recreate, because it detects any change to the datacenter's parent folder attribute.

### Steps to Reproduce

- Manually create a datcenter called 'BAR' in a top level datacenter folder called 'FOO'.
- Import into the state
- Run a plan without any changes, and see the proposed destroy / recreate operation.
- Check in the state file, and see ```"folder": null``` against the imported resource.

### Important Factoids

This was tested against 7.0U2 and 7.0GA.  I know these aren't technically supported vsphere releases yet.  Will try find time to spin up a 6.5 / 6.7 vcenter to test.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rabbitt** [comment]
👍

**Comment by tenthirtyam** [comment]
Marking this issue as `confirmed` as it's reproducable.

Example Configuration:

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

resource "vsphere_folder" "folder" {
  path = "hello"
  type = "datacenter"
}

resource "vsphere_datacenter" "datacenter" {
  depends_on = [
    vsphere_folder.folder,
  ]
  name   = "world"
  folder = "/hello/"
}
```

Import Existing Datacenter in a Datacenter Folder:

`> terraform import vsphere_datacenter.datacenter /hello/world`

Results:

```console
❯ terraform import vsphere_datacenter.datacenter /hello/world
vsphere_datacenter.datacenter: Importing from ID "/hello/world"...
vsphere_datacenter.datacenter: Import prepared!
  Prepared vsphere_datacenter for import
vsphere_datacenter.datacenter: Refreshing state... [id=world]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.



❯ terraform apply -refresh-only -auto-approve
vsphere_datacenter.datacenter: Refreshing state... [id=world]

No changes. Your infrastructure still matches the configuration.

Terraform has checked that the real remote objects still match the result of your most recent changes, and found no
differences.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
````

Terraform State:

```json
  "resources": [
    {
      "mode": "managed",
      "type": "vsphere_datacenter",
      "name": "datacenter",
      "provider": "provider[\"registry.terraform.io/hashicorp/vsphere\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "custom_attributes": null,
            "folder": null,
            "id": "world",
            "moid": "datacenter-46029",
            "name": "world",
            "tags": null
          },
```

Looking at the `resourceVSphereDatacenterImport` in `r/vsphere_datacenter`, it does not appear to get the relative path and set the folder into state using the folder helper functions.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
