### ISSUE TITLE
distributed port_group resource does not support "trunk"

### ISSUE THREAD

**Issue by urraco77** [hashicorp/terraform-provider-vsphere#1384]
### Terraform Version
v0.14.10
### vSphere Provider Version
v1.25.0

### Affected Resource(s)

- `vsphere_distributed_port_group`

### Terraform Configuration Files

resource "vsphere_distributed_port_group" "pg" {
  name = "pg-test"
  distributed_virtual_switch_uuid = vsphere_distributed_virtual_switch.dvs.id
  vlan_id = "4095"
}

### Debug Output

$ gitlab-terraform validate
Initializing the backend...
Successfully configured the backend "http"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Reusing previous version of hashicorp/vsphere from the dependency lock file
- Using previously-installed hashicorp/vsphere v1.25.0
Terraform has been successfully initialized!
Error: expected vlan_id to be in the range (0 - 4094), got 4095
  on network_vds.tf line 67, in resource "vsphere_distributed_port_group" "pg":
  67: resource "vsphere_distributed_port_group" "pg" {
ERROR: Job failed: exit status 1

### Expected Behavior

Create a trunk port_group

### Steps to Reproduce
use the example in this reference https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/host_port_group#vlan_id

### References

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/host_port_group
there is a same issue closed: #1009

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njferrant** [comment]
+1 also running into this issue. My use case is to use TF to create a trunk port group to attach it to a firewall.

**Comment by njferrant** [comment]
@urraco77 

Looks like you can use the `vlan_range` block, which isn't listed in the documentation, to create a trunk:
```
data "vsphere_datacenter" "dc" {
  name = "dc01"
}

data "vsphere_distributed_virtual_switch" "dvs" {
  datacenter_id = data.vsphere_datacenter.dc.id
  name          = "vds01"
}

resource "vsphere_distributed_port_group" "pg" {
  name                            = "trunk01"
  distributed_virtual_switch_uuid = data.vsphere_distributed_virtual_switch.dvs.id
  vlan_range {
    max_vlan = 1000
    min_vlan = 0
  }
}
```

**Comment by urraco77** [comment]
@njferrant nice workaround!!

**Comment by tenthirtyam** [comment]
> @urraco77
> 
> Looks like you can use the `vlan_range` block, which isn't listed in the documentation, to create a trunk:

This is mentioned in the documentation for the resource.

```markdown
* `vlan_range` - (Optional) Used to denote VLAN trunking. Use the `min_vlan`
  and `max_vlan` sub-arguments to define the tagged VLAN range. Multiple
  `vlan_range` definitions are allowed, but they must not overlap. Example
  below:

```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
  # ... other configuration ...
  vlan_range {
    min_vlan = 1
    max_vlan = 1000
  }
  vlan_range {
    min_vlan = 2000
    max_vlan = 4094
  }
}
```

Reference: https://github.com/hashicorp/terraform-provider-vsphere/blob/37fd52c400e2d7901c51c67ad683b2e7d06c6bf3/website/docs/r/distributed_virtual_switch.html.markdown?plain=1#L312-L329

Ryan

**Comment by tenthirtyam** [comment]
cc @appilon and @iBrandyJackson for review. I think this is already covered in the existing provider documentation.

Ryan
