### ISSUE TITLE
Documentation - example code for vsphere_compute_cluster_vm_anti_affinity_rule is wrong

### ISSUE THREAD

**Issue by ChrisGWarp** [hashicorp/terraform-provider-vsphere#1393]
The example for the vsphere_compute_cluster_vm_anti_affinity_rule does not work (at all).

`resource "vsphere_compute_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule" {`
`  name                = "terraform-test-cluster-vm-anti-affinity-rule"`
`  compute_cluster_id  = "${data.vsphere_compute_cluster.cluster.id}"`
`  virtual_machine_ids = ["${vsphere_virtual_machine.vm.*.id}"]`
`}`

Results in:
`│`
`│ Error: Incorrect attribute value type`
`│ `
`│   on xxx.tf line 215, in resource "vsphere_compute_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule":`
`│  215:   virtual_machine_ids = ["${vsphere_virtual_machine.vm.*.id}"]`
`│     ├────────────────`
`│     │ vsphere_virtual_machine.vm is (sensitive value)`
`│ `
`│ Inappropriate value for attribute "virtual_machine_ids": element 0: string required.``

Probably because it's looking for a Map rather than a List and the * (splat) does not work. The correct way to use it is:

`resource "vsphere_compute_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule" {`
`    name                = "terraform-test-cluster-vm-anti-affinity-rule"`
`    compute_cluster_id  = "${data.vsphere_compute_cluster.cluster.id}"`
`    virtual_machine_ids = [ for k, v in vsphere_virtual_machine.vm : v.id ]`
`}`

This probably applies to the other affinity rules, but I have not tried them.

**Comment by tenthirtyam** [comment]
Closes: #1394
