### ISSUE TITLE
Add support for shutdown VM state

### ISSUE THREAD

**Issue by benfab** [hashicorp/terraform-provider-vsphere#1394]
### Description

As an infrastructure operator, I would like to keep some of my vSphere VMs in shutdown state, so they are not consuming compute capacity.  

### Potential Terraform Configuration

This could be defined in the Terraform configuration files by introducing the "desired_status" argument, as shown below:

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"

  [...]

  desired_status = "SHUTDOWN"
}
```

### References

This feature is available with the Google provider:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#desired_status

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aishwarya128** [comment]
Hi @koikonom ,

I would like to contribute on this issue, so picking up this if its not already worked upon

**Comment by tenthirtyam** [comment]
PR: https://github.com/hashicorp/terraform-provider-vsphere/pull/1533

**Comment by tenthirtyam** [comment]
After some deliberations with the maintainers, we've decided that at this time this capability will not be added to the provider as it tends to blur the lines between [mutable vs. immutable infrastructure](https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure).

If you take a look back to #327, the same enhancement was requested and the maintainer at the time [shared the reasoning](https://github.com/hashicorp/terraform-provider-vsphere/issues/327#issuecomment-352559036) at the time for not including the capability. 

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
