### ISSUE TITLE
Add support for running a script before powering on a `vsphere_virtual_machine` resource

### ISSUE THREAD

**Issue by cuffm** [hashicorp/terraform-provider-vsphere#1395]
Although this topic has been raised and closed before, I'd like to re-open in the hope I've missed something as I'm very new to Terraform. Prior to the provider powering on the VM I'd like the ability to run a script.  We use Nuage Software Defined Networking and for the VM to come up on the network it has to be "stitched" into a Nuage Enterprise, something I can easily script. Once the script has completed the provider would power on the VM as normal. I am working with Terraform  0.15.0.  Thanks in advance.

**Comment by maxadamo** [comment]
I'm afraid this is a feature request for Terraform and not for this specific plugin.

**Comment by tenthirtyam** [comment]
Recommend: `type/enhancement`

@cuffm - Can the script _(or even API call)_ with a provisioner _(or another provider included the plan)_ not be performed after power-on and allow communications then proceed?

Ryan

**Comment by tenthirtyam** [comment]
@iBrandyJackson - could you label this item as `enhancement` for review, please?

**Comment by tenthirtyam** [comment]
@appilon amd @tejavar, could either or both of you weight in on this one. I'm of the opinion that this would be out of scope for the provider.

Ryan

**Comment by tenthirtyam** [comment]
After recently discussing with the project team, it was decided that this was not an enhancement that this provider would not implement. You may be able to use a provisioner or another provider to invoke the required configuration in Nuage.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
