### ISSUE TITLE
Add support for a `vsphere_distributed_port_group` data source

### ISSUE THREAD

**Issue by pezhore** [hashicorp/terraform-provider-vsphere#1410]
### Description

Although we have a resource for creating/manipulating a new distributed port group, there is no data source for retrieving a current distributed port group. This is challenging when attempting to use other resources (e.g. `vsphere_entity_permissions`) - requiring the end user to find the mo-ref/entity id manually.

The data resource would require a parent distributed virtual switch id and a port group name (used for searching/filtering distributed port groups). For brevity, I chose `dvs_id` but that could easily be `virtualswitch_id` or something else that's more robust.

### Potential Terraform Configuration

```hcl
data "vsphere_datacenter" "datacenter" {
  name = "dc1"
}

data "vsphere_distributed_virtual_switch" "dvs" {
  name          = "terraform-test-dvs"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_distributed_port_group" "my-dvpg" {
 name   = "terraform-test-dvpg"
 dvs_id = data.vspherer_distributed_virtual_switch.dvs.id
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by cerrakoth** [comment]
To add colour to why this would be useful - We would like to start deploying VMs via Terraform in an environment which already contains distributed port groups. We currently would need to create a new dpg managed by Terraform or import the existing dpg to the state which is not an optimal way of doing this.

**Comment by burnsjared0415** [comment]
so this was just write for vsphere_network to pull back the distribution or standard switch would it work for this problem?
https://github.com/hashicorp/terraform-provider-vsphere/pull/2281

**Comment by pezhore** [comment]
That might work? From my read of the Changelog on that PR, it would seem to cover my use case.

**Comment by burnsjared0415** [comment]
i updated it so it would look like this
```
data "vsphere_datacenter" "datacenter" {
  name = "dc-01"
}

data "vsphere_network" "my_port_group" {
  datacenter_id = data.vsphere_datacenter.datacenter.id
  name          = "VM Network"
  network_type = "Network"
  }
  ```

**Comment by pezhore** [comment]
yeah that should work for me.!

**Comment by burnsjared0415** [comment]
I had to make a couple changes to the code, once it is release it, i will close out this issue
