### ISSUE TITLE
Datastore ISO not connected at VM power on

### ISSUE THREAD

**Issue by cyrokamogawa** [hashicorp/terraform-provider-vsphere#1411]
### Terraform Version
Terraform v0.15.0
on windows_amd64

### vSphere Provider Version
provider registry.terraform.io/hashicorp/vsphere v1.26.0

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 4096
  guest_id = "windows8Server64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 100
  }

  cdrom {
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    path         = <path/to/iso>
  }
}
```

### Expected Behavior
The datastore ISO is connected to the VM at power on automatically.

### Actual Behavior
The datastore ISO is not connected to the VM at power on automatically.

### Steps to Reproduce
1. terraform init
2. terraform apply
3. Open VCSA and test the VM

### Important Factoids
When I try to launch a VM console in VCSA, it says "Operating system not found." Looking at the VM settings, the CD/DVD drive section has a checkbox checked for "Connect at power on." This is supposed to connect the datastore ISO that I specified to the VM, but the ISO is not connected. I have to manually connect it and reboot the VM for it to work. We've built VMs through Power CLI before and did not have this problem.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jimdevops19** [comment]
I added my reaction. As I am still facing this issue.

**Comment by tenthirtyam** [comment]
@cyrokamogawa @jimdevops19 - I'm not seeing this issue occur in the `latest` (v2.0.2) provider.

With the below, the datastore ISO will automatically connect.

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.2"
    }
  }
  required_version = ">= 1.0.10"
}

provider "vsphere" {
  user                 = "administrator@vsphere.local"
  password             = "VMware1!"
  vsphere_server       = "m01-vc01.rainpole.io"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "m01-dc01"
}

data "vsphere_network" "network" {
  name          = "DHCP"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = "m01-cl01"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = "local-hdd-01"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = "photon-hello-world"
  num_cpus         = 2
  memory           = 4096
  guest_id         = "vmwarePhoton64Guest"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = 20
    thin_provisioned = true
  }
  cdrom {
    datastore_id = data.vsphere_datastore.datastore.id
    path         = "/iso/linux/photon/photon-4.0-ca7c9e933.iso"
  }
}
```

<img width="852" alt="image" src="https://user-images.githubusercontent.com/7771363/140448368-669c2bba-b9ab-4937-8962-a19c51b2e5a5.png">

Note however that this example plan will fail as the Photon OS ISO used here is not configured for an auto-installation.

Hopes this helps,
Ryan
@tenthirtyam

Recommend: `close/not-a-bug` in `latest`.

**Comment by tenthirtyam** [comment]
Hi @cyrokamogawa and @jimdevops19, 

could you confirm if you are seeing the same issue in the [latest release](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) of the provider? I was not able to reproduce the issue in [the above](https://github.com/hashicorp/terraform-provider-vsphere/issues/1411#issuecomment-961580857).

Ryan

**Comment by cyrokamogawa** [comment]
Hi, I was able to figure out my issue. It was just because the file path extension was supposed to be in all caps. Thanks for offering your support though.
