### ISSUE TITLE
Error: while retrieving import spec: while checking deployment option: invalid ovf deployment <validdeploymentoptionname> specified, valid deployments are:

### ISSUE THREAD

**Issue by djpbessems** [hashicorp/terraform-provider-vsphere#1412]
### Terraform Version
0.15.0
### vSphere Provider Version
v1.26.0

### Affected Resource(s)
- `vsphere_ovf_vm_template`
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
terraform {
  backend "pg" {}
 
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 1.26.0"
    }
  }
}
 
provider "vsphere" {
    vsphere_server       = var.hv_fqdn
    user                 = var.hv_username
    password             = var.hv_password
 
    allow_unverified_ssl = true
}
 
data "vsphere_datacenter" "dc" {
  name                   = var.hv_datacenter
}
 
data "vsphere_resource_pool" "pool" {
  name                   = "/${var.hv_datacenter}/host/${var.hv_cluster}/Resources"
  datacenter_id          = data.vsphere_datacenter.dc.id
}
 
data "vsphere_datastore" "datastore" {
  name                   = var.hv_datastore
  datacenter_id          = data.vsphere_datacenter.dc.id
}
 
data "vsphere_network" "network" {
  name                   = var.hv_network
  datacenter_id          = data.vsphere_datacenter.dc.id
}
 
data "vsphere_host" "host" {
  name                   = var.hv_host
  datacenter_id          = data.vsphere_datacenter.dc.id
}
 
data "vsphere_ovf_vm_template" "ovf" {
  name                      = "ovf"
  resource_pool_id          = data.vsphere_resource_pool.pool.id
  datastore_id              = data.vsphere_datastore.datastore.id
  host_system_id            = data.vsphere_host.host.id
 
  remote_ovf_url            = var.vm_ovfurl
  allow_unverified_ssl_cert = true
 
  deployment_option         = var.vm_deploymentoption
 
  ovf_network_map = {
    "VM Network": data.vsphere_network.network.id
  }
}
 
resource "vsphere_virtual_machine" "vm" {
  name                   = var.vm_hostname
 
  num_cpus               = data.vsphere_ovf_vm_template.ovf.num_cpus
  memory                 = data.vsphere_ovf_vm_template.ovf.memory
 
  datacenter_id          = data.vsphere_datacenter.dc.id
  folder                 = var.hv_folder
 
  guest_id               = data.vsphere_ovf_vm_template.ovf.guest_id
  resource_pool_id       = data.vsphere_ovf_vm_template.ovf.resource_pool_id
  datastore_id           = data.vsphere_ovf_vm_template.ovf.datastore_id
  host_system_id         = data.vsphere_ovf_vm_template.ovf.host_system_id
 
  ovf_deploy {
    ovf_network_map      = data.vsphere_ovf_vm_template.ovf.ovf_network_map
    remote_ovf_url       = data.vsphere_ovf_vm_template.ovf.remote_ovf_url
    deployment_option    = data.vsphere_ovf_vm_template.ovf.deployment_option
  }
 
  vapp {
    properties = {
      "deployment.customer"    = var.vm_customer
      "deployment.projectnr"   = var.vm_projectnumber
      "deployment.projectname" = var.vm_projectname
 
      "vmconfig.disksize.3"    = var.vm_disk3size
 
      "guestinfo.hostname"     = var.vm_hostname
      "guestinfo.ipaddress"    = var.vm_ipaddress
      "guestinfo.netmask"      = var.vm_netmask
      "guestinfo.gateway"      = var.vm_gateway
      "guestinfo.dns"          = var.vm_dns
      "guestinfo.domain_name"  = var.vm_searchdomain
      "guestinfo.ntp"          = var.vm_ntp
 
      "guestinfo.enable_domain_join"   = var.adds_domainmember
      "guestinfo.domain_short_name"    = var.adds_netbios
      "guestinfo.domain_controller"    = var.adds_fqdn
      "guestinfo.domain_join_user"     = var.adds_username
      "guestinfo.domain_join_password" = var.adds_password
 
      "guestinfo.viadmin_password"   = var.pw_viadmin
      "guestinfo.viuser_password"    = var.pw_viuser
      "guestinfo.viservice_password" = var.pw_viservice
 
      "guestinfo.monitor_server" = var.snmp_fqdn
 
      "guestinfo.ora_include_sw"       = var.ora_include_sw
      "guestinfo.ora_include_database" = var.ora_include_database
      "guestinfo.ora_include_weblogic" = var.ora_include_weblogic
      "guestinfo.ora_sid"              = var.ora_sid
      "guestinfo.ora_sga"              = var.ora_sga
      "guestinfo.ora_pga"              = var.ora_pga
      "guestinfo.ora_sys_password"     = var.ora_sys_password
      "guestinfo.ora_system_password"  = var.ora_system_password
      "guestinfo.ora_license"          = var.ora_license
      "guestinfo.ora_archive_log_mode" = var.ora_archive_log_mode
      "guestinfo.ora_debug_mode"       = var.ora_debug_mode
    }
  }
}
```

### Debug Output
https://pastebin.com/QxzpSbjS

### Panic Output
n/a

### Expected Behavior
Terraform should produce a terraform.plan based on the defined deploymentoption in the .ovf file, to execute with `terraform apply`

### Actual Behavior
Terraform does not seem to recognise that there are deployment options defined at all, and returns an error.

### Steps to Reproduce
1. `terraform init -upgrade -input=false -backend-config="conn_str=<omitted>"` ---> Works correctly
2. `terraform plan -var-file='vm.tfvars' -var-file='vsphere.tfvars' -var="<variouspasswords>=<omitted>" -input=false -out=terraform.plan` ---> Returns error.

### Important Factoids
Tested both on a vCenter version 6.7 and 7.0

### References
n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by koikonom** [comment]
Hi @djpbessems, thanks for taking the time to report this issue. 

The errors comes from the code that checks if the deployment option chosen is defined in the OVF file. Can you make sure that the value of variable `vm_deploymentoption` matches one of the deployment options defined in the OVF file?

**Comment by djpbessems** [comment]
> The errors comes from the code that checks if the deployment option chosen is defined in the OVF file. Can you make sure that the value of variable `vm_deploymentoption` matches one of the deployment options defined in the OVF file?

The ovf file is generated by myself (along with updating the .mf file), so I'm 100% certain that I'm using the correct value:
```
<DeploymentOptionSection>
  <Info>Deployment Type</Info>
  <Configuration ovf:id="small">
    <Label>Small deployment</Label>
    <Description>2 vCPU/4GB RAM</Description>
  </Configuration>
  <Configuration ovf:id="medium">
    <Label>Medium</Label>
    <Description>4 vCPU/8GB RAM</Description>
  </Configuration>
  <Configuration ovf:id="large">
    <Label>Large deployment</Label>
    <Description>6 vCPU/12GB RAM</Description>
  </Configuration>
</DeploymentOptionSection>
```

In the file `vm.tfvars` I have the following line:
```
vm_deploymentoption = "medium"
```

**Comment by koikonom** [comment]
Interesting, it looks like the OVF deployment descriptor we get back from vsphere returns an empty list of deployment options.

Would it be possible to share the OVF so I can test further?

**Comment by djpbessems** [comment]
Sure, please check https://pastebin.com/CTeJj2Ci

Hopefully you can use this without the accompanying .vmdk files, because they contain IP.

**Comment by koikonom** [comment]
OK that helped a lot. 

The actual issue is that lines 144 to 166 are probably in the wrong place causing some parse error. Unfortunately I missed a case where  the call to`ParseDescriptor()` returns no errors, but the parse errors are part of the API call's result. I will address this in a separate PR.

**Comment by djpbessems** [comment]
I'll look into refactoring my code to produce a properly ordered OVF file. But have to say I'm surprised the order would matter, because that's not something I'd actually expect when dealing with XML...

**Comment by djpbessems** [comment]
After updating the order of the XML, this issue has been resolved. Thanks for troubleshooting with me.

I have noticed another (minor) issue that I will create a new ticket for though: the vsphere provider does not handle vApp Properties of type `boolean` very intuitive, their value right now *must* be passed as a string `True`/`False` (with capital letters).
