### ISSUE TITLE
Terraform import vmware folder has error

### ISSUE THREAD

**Issue by behnm** [hashicorp/terraform-provider-vsphere#1421]
### Affected Resource(s)

 Please list the resources as a list, for example:
 `vsphere_folder.vmFolder`

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.
--->

### Terraform Configuration Files

```hcl
// Provider's data
provider "vsphere" {
  user                 = lookup(var.vcenterMapUsername, var.vcenterIp)
  password             = file("../files/Password.txt")
  vsphere_server       = var.vcenterIp
  allow_unverified_ssl = true
}

//data 
data "vsphere_datacenter" "dc" {
  name = var.vcenterMapDatacenter
}

//Terraform.tfvars Files
vcenterIp = "MyvcenterServer"
vcenterMapDatacenter = "Datacenter"
vcenterMapUsername = {
  "MyvcenterServer" = "MyadminUser"
}

// Variables of Vcneter
variable "vcenterIp" {
  description = "Vcenter IP address"
  type        = string
}
variable "vcenterMapDatacenter" {
  description = "Datacenter defined in the Vcenter"
  type        = string
}
variable "vcenterMapUsername" {
  description = "Vcenter Username"
  type        = map(any)
}

// Variables of VM
variable "vmFolder" {
  description = "VM folder"
  type        = string
}

// Resource for create folder
resource "vsphere_folder" "vmFolder" {
  path          = "development-AREA/Management-Area/behnam3"
  type          = "vm"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```

### Debug Output

`Error: path must start with a trailing slash`

### Actual Behavior

Error: path must start with a trailing slash

### Steps to Reproduce

1. terraform import  vsphere_folder.vmFolder vsphere_folder.vmFolder.id

### References

* #0000

### Community Note

I created a folder on vmware without errors, However when I wanted to import the data of current folder , I saw the error.

**Comment by tenthirtyam** [comment]
Hi @behnm,

An existing folder can be imported into this resource via its **full path** (**not** the MOID).

For example:

```console
terraform import vsphere_folder.folder "/my_datacenter/vm/my_vm_folder"
terraform import vsphere_folder.folder "/my_datacenter/datastore/my_datastore_folder"
terraform import vsphere_folder.folder "/my_datacenter/network/my_network_folder"
terraform import vsphere_folder.folder "/my_datacenter/datacenter/my_datacenter_folder"
terraform import vsphere_folder.folder "/my_datacenter/hostandcluster/my_host_and_cluster_folder"
```

And example when the folder is nested:

```console
terraform import vsphere_folder.folder "/my_datacenter/vm/foo/bar"
```

For the your configuration above:

```console
terraform import vsphere_folder.vmFolder "/Datacenter/vm/development-AREA/Management-Area/behnam"
```

**Documentation Reference**: [resource_vsphere_folder > importing](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/folder#importing)

Recommended: `close/user-error`

Ryan

**Comment by tenthirtyam** [comment]
HI @behnm - have you had a chance to review [my prior comment](https://github.com/hashicorp/terraform-provider-vsphere/issues/1421#issuecomment-995390137) and retest the scenario using the full path on the import?

```console
terraform import vsphere_folder.vmFolder "/Datacenter/vm/development-AREA/Management-Area/behnam"
```

Ryan

**Comment by tenthirtyam** [comment]
Hi @behnm 

I'm marking this issue as closed based on the comments and solution provided earlier in the thread. 

If the issue persists, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
