### ISSUE TITLE
Documentation ; vsphere_virtual_machine : disk options conflict

### ISSUE THREAD

**Issue by dcpc007** [hashicorp/terraform-provider-vsphere#1424]
### Terraform Version
1.0 

### vSphere Provider Version
2.0.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files
n/a

### Problem 
Mismatch in documentaion between description and examples : 
At the very least, there must be **name** and **size** attributes. (...)

(...)
  disk {
    **label** = "disk0"
    size  = "10"
  }

--> label seems to be the correct configuration, and name throw an error in terraform plan

### References
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#disk-options

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Included update in PR #1513.
