### ISSUE TITLE
vsphere_vApp_container error create vApp on DRS Cluster

### ISSUE THREAD

**Issue by JM2K69** [hashicorp/terraform-provider-vsphere#1436]
### Terraform Version
1.0.1
### vSphere Provider Version
2.0.2

### Affected Resource(s)
It was impossible to create a vApp on a DRS Cluster

### Terraform Configuration Files

```hcl
provider "vsphere" {
    user           = "Administrator"
    password       = "MySecre€P@$$w0rd!"
    vsphere_server = "vcsa.lab.dom"

    # If you have a self-signed cert
    allow_unverified_ssl = true
}

variable "datacenter" {
  default = "Datacenter"
}

variable "cluster" {
  default = "SCO-LABO"
}
data "vsphere_datacenter" "dc" {
  name = "${var.datacenter}"
}

data "vsphere_compute_cluster" "compute_cluster" {
  name          = "${var.cluster}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_vapp_container" "vapp_container" {
  name                    = "terraform-vapp-container-test"
  parent_resource_pool_id = "${data.vsphere_compute_cluster.compute_cluster.id}"
}
```

### Debug Output

[Gist -Link](https://gist.github.com/JM2K69/69ca03cc0e2b67784a8d32c9d998a18f)

### Steps to Reproduce

1. `terraform apply -auto-approve`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by koikonom** [comment]
Thanks for opening this issue. It seems like our example is wrong and we'll have to fix it. The parent resource pool id should be `data.vsphere_compute_cluster.compute_cluster.resource_pool_id` and not `data.vsphere_compute_cluster.compute_cluster.id`.

**Comment by JM2K69** [comment]
This example ils from pour website docs and why in vspjere you Can create a vapp directly onnthe des cluster and Aldo in a resource pool
