### ISSUE TITLE
Brownfield vsphere_compute_cluster without defining vsphere_host

### ISSUE THREAD

**Issue by BradCalvertHCA** [hashicorp/terraform-provider-vsphere#1437]
I am somewhat new to TF, so feel free to let me know if there is a more appropriate way to go about this problem.

Is it possible to brownfield import only datacenter and cluster objects in to TF state and completely ignore the host memberships, without directly editing the state file? When importing the vsphere_compute_cluster objects, they come in to the state file with:

```
"host_managed": null,
"host_system_ids": [],
```

So when immediately running ```terraform plan``` or ```terraform apply```, it tries to fix the ```host_managed``` by setting it to true like I want. But since I did not (and currently do not want to) import my hosts in to TF state, it also tries to remove the existing hosts from the cluster.

```
+ host_managed = true
~ host_system_ids = [
   - "host-67907",
   - "host-67910",
   - "host-67913",
   - "host-67916",
   - "host-67919",
   - "host-67922",
]
```

It seems that if you are setting ```host_managed``` to true in an operation, it shouldn't ALSO try to make a change to the host inventory in the same operation (at least based on the cluster resource configuration). This feels somewhat like a bug to me, but I am not sure?

Note that if I edit the state file manually to ```"host_managed": true``` for all the clusters, the TF plan works as expected.

### Terraform Version
1.0.0
### vSphere Provider Version
2.0.1

### Affected Resource(s)
- `vsphere_compute_cluster`
- `vsphere_host`

### Terraform Configuration Files

```hcl
resource "vsphere_compute_cluster" "clu" {
  for_each = { for obj in local.cluster_inv : "${obj.name}" => obj }

  datacenter_id = each.value.dc_moid
  name          = each.value.name
  host_managed  = true
}
```

### Expected Behavior

After importing datacenters and clusters in to state, I want to manage the cluster settings without concerning TF with the individual host memberships.

### Actual Behavior

When running TF Plan or Apply, TF tries to remove the hosts in the cluster as they do not have configurations, despite using ```host_managed  = true``` in the cluster configuration.

### Steps to Reproduce
1) Import vSphere Datacenters: ```terraform import vsphere_datacenter.dc["DC_NAME"] /DC_NAME```
2) Import vSphere Cluster: ```terraform import 'vsphere_compute_cluster.clu ["CLU_NAME"]' /DC_NAME/host/CLU_NAME```
3) Set up TF configuration to use ```host_managed  = true``` in the ```resource "vsphere_compute_cluster" "clu"``` resource block
4) Run ```terraform plan```
5) TF tries to set ```host_managed``` from null to true, but also tries to remove all the existing hosts in the cluster since they are not in state.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@BradCalvertHCA - a quick check-in to see if you have tried the `lifecycle` meta argument from the previous comment.

Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the suggested solution and time since last response.

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
