### ISSUE TITLE
vsphere terraform provider not reporting changes to multiple disk

### ISSUE THREAD

**Issue by ncecere** [hashicorp/terraform-provider-vsphere#1439]
When implementing a change to several VM's on vsphere the terraform provider didn't report that one of the disks was going to be orphaned as a change.  It wasn't until I applied the change that i discovered that one of the attached disks had been removed from the VM.

vsphere 6.7.2
terraform 1.0.1

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the staleness of the issue and no community reactions. 👍🏻 👎🏻 

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
