### ISSUE TITLE
could not split path "/VMWareFarm/VMWareFarm_host/Cluster01 ESXi 6.7/Resources" on "/host"

### ISSUE THREAD

**Issue by freola** [hashicorp/terraform-provider-vsphere#1440]
### Terraform Version

Terraform v1.0.1
on windows_amd64

### vSphere Provider Version

provider registry.terraform.io/hashicorp/vsphere v2.0.2

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 2.0.2"
    }
  }
}

provider "vsphere" {
  vim_keep_alive = 30
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_compute_cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name = var.windows_template
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  count = var.vm-count

  name             = "${var.vm-name}-${count.index + 1}"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  
  num_cpus                   = var.vm-cpu
  memory                     = var.vm-ram
  guest_id                   = data.vsphere_virtual_machine.template.guest_id
  scsi_type                  = data.vsphere_virtual_machine.template.scsi_type
  wait_for_guest_net_timeout = -1
  
  network_interface {
    network_id   = data.vsphere_network.network.id
	  adapter_type = "vmxnet3"
  }

  disk {
    label            = "${var.vm-name}-${count.index + 1}.vmdk"
    thin_provisioned = true
    size             = data.vsphere_virtual_machine.template.disks.0.size
  }

  disk {
    label            = "${var.vm-name}-${count.index + 1}_1.vmdk"
    unit_number      = 1
    thin_provisioned = true
    size             = data.vsphere_virtual_machine.template.disks.0.size
  }
  
  clone {
      template_uuid = data.vsphere_virtual_machine.template.id
    
    customize {
      windows_options {
        computer_name         = "${var.vm-name}-${count.index + 1}"
        join_domain           = var.join_domain
        domain_admin_user     = var.domain_admin_user
        domain_admin_password = var.domain_admin_pass
      }

      network_interface {}
      timeout = 30

    }
    
  }
}
```

### Debug Output

https://gist.github.com/freola/4dabd325198b0c00fb1005d054bc5906

### Expected Behavior

Expected behavior was that terraform should have created a VM in the selected cluster

### Actual Behavior

We got a error that says:

```hcl
 Error: could not split path "/VMWareFarm/VMWareFarm_host/Cluster01 ESXi 6.7/Resources" on "/host"

   with vsphere_virtual_machine.vm[0],
   on main.tf line 44, in resource "vsphere_virtual_machine" "vm":
   44: resource "vsphere_virtual_machine" "vm" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

VSphere version is 6.7.0.48000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @freola - 

I assume you'd like the `vsphere_virtual_machine` resource to be deployed in the`/Resources` root resource pool of the cluster? 

If so, could you try the following configuration?

Changes:

```hcl
data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_compute_cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  #... other configuration ...
  resource_pool_id = data.vsphere_resource_pool.pool_id
```

An updated configuration:
```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 2.0.2"
    }
  }
}

provider "vsphere" {
  vim_keep_alive = 30
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_compute_cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name = var.windows_template
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  count = var.vm-count

  name             = "${var.vm-name}-${count.index + 1}"
  resource_pool_id = data.vsphere_resource_pool.pool_id
  
  num_cpus                   = var.vm-cpu
  memory                     = var.vm-ram
  guest_id                   = data.vsphere_virtual_machine.template.guest_id
  scsi_type                  = data.vsphere_virtual_machine.template.scsi_type
  wait_for_guest_net_timeout = -1
  
  network_interface {
    network_id   = data.vsphere_network.network.id
	  adapter_type = "vmxnet3"
  }

  disk {
    label            = "${var.vm-name}-${count.index + 1}.vmdk"
    thin_provisioned = true
    size             = data.vsphere_virtual_machine.template.disks.0.size
  }

  disk {
    label            = "${var.vm-name}-${count.index + 1}_1.vmdk"
    unit_number      = 1
    thin_provisioned = true
    size             = data.vsphere_virtual_machine.template.disks.0.size
  }
  
  clone {
      template_uuid = data.vsphere_virtual_machine.template.id
    
    customize {
      windows_options {
        computer_name         = "${var.vm-name}-${count.index + 1}"
        join_domain           = var.join_domain
        domain_admin_user     = var.domain_admin_user
        domain_admin_password = var.domain_admin_pass
      }

      network_interface {}
      timeout = 30

    }
    
  }
}
```

Hope this helps,
Ryan
@tenthirtyam

**Comment by freola** [comment]
> Hi @freola -
> 
> I assume you'd like the `vsphere_virtual_machine` resource to be deployed in the`/Resources` root resource pool of the cluster?
> 
> If so, could you try the following configuration?
> 
> Changes:
> 
> ```terraform
> data "vsphere_compute_cluster" "cluster" {
>   name          = var.vsphere_compute_cluster
>   datacenter_id = data.vsphere_datacenter.dc.id
> }
> 
> data "vsphere_resource_pool" "pool" {
>   name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
>   datacenter_id = data.vsphere_datacenter.datacenter.id
> }
> 
> resource "vsphere_virtual_machine" "vm" {
>   #... other configuration ...
>   resource_pool_id = data.vsphere_resource_pool.pool_id
> ```
> 
> An updated configuration:
> 
> ```terraform
> terraform {
>   required_providers {
>     vsphere = {
>       source  = "hashicorp/vsphere"
>       version = "~> 2.0.2"
>     }
>   }
> }
> 
> provider "vsphere" {
>   vim_keep_alive = 30
>   user           = var.vsphere_user
>   password       = var.vsphere_password
>   vsphere_server = var.vsphere_server
> 
>   # If you have a self-signed cert
>   allow_unverified_ssl = true
> }
> 
> data "vsphere_datacenter" "dc" {
>   name = var.vsphere_datacenter
> }
> 
> data "vsphere_datastore" "datastore" {
>   name          = var.vsphere_datastore
>   datacenter_id = data.vsphere_datacenter.dc.id
> }
> 
> data "vsphere_compute_cluster" "cluster" {
>   name          = var.vsphere_compute_cluster
>   datacenter_id = data.vsphere_datacenter.dc.id
> }
> 
> data "vsphere_resource_pool" "pool" {
>   name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
>   datacenter_id = data.vsphere_datacenter.datacenter.id
> }
> 
> data "vsphere_network" "network" {
>   name          = var.vsphere_network
>   datacenter_id = data.vsphere_datacenter.dc.id
> }
> 
> data "vsphere_virtual_machine" "template" {
>   name = var.windows_template
>   datacenter_id = data.vsphere_datacenter.dc.id
> }
> 
> resource "vsphere_virtual_machine" "vm" {
>   count = var.vm-count
> 
>   name             = "${var.vm-name}-${count.index + 1}"
>   resource_pool_id = data.vsphere_resource_pool.pool_id
>   
>   num_cpus                   = var.vm-cpu
>   memory                     = var.vm-ram
>   guest_id                   = data.vsphere_virtual_machine.template.guest_id
>   scsi_type                  = data.vsphere_virtual_machine.template.scsi_type
>   wait_for_guest_net_timeout = -1
>   
>   network_interface {
>     network_id   = data.vsphere_network.network.id
> 	  adapter_type = "vmxnet3"
>   }
> 
>   disk {
>     label            = "${var.vm-name}-${count.index + 1}.vmdk"
>     thin_provisioned = true
>     size             = data.vsphere_virtual_machine.template.disks.0.size
>   }
> 
>   disk {
>     label            = "${var.vm-name}-${count.index + 1}_1.vmdk"
>     unit_number      = 1
>     thin_provisioned = true
>     size             = data.vsphere_virtual_machine.template.disks.0.size
>   }
>   
>   clone {
>       template_uuid = data.vsphere_virtual_machine.template.id
>     
>     customize {
>       windows_options {
>         computer_name         = "${var.vm-name}-${count.index + 1}"
>         join_domain           = var.join_domain
>         domain_admin_user     = var.domain_admin_user
>         domain_admin_password = var.domain_admin_pass
>       }
> 
>       network_interface {}
>       timeout = 30
> 
>     }
>     
>   }
> }
> ```
> 
> Hope this helps, Ryan @tenthirtyam

Hi Ryan!

Thx for your replay, I did try this but i got the same issue.

What I can see it looks like terraform expect that the path should be "/VMWareFarm/host/Cluster01 ESXi 6.7/Resources" but in our case it is "/VMWareFarm/VMWareFarm_host/Cluster01 ESXi 6.7/Resources" and then it dosen't know what to do because it can't find the "/host/" in the path, I guess that this is hard coded in the module to split on "/host"?
 
The problem for us is that "VMWareFarm_host" is a root path that can not be changed in VmWare and I know that if we did reinstall VmWare we should get the "right" root path that should be "host", but this is a big thing to do and it would be nice if this could be handled in the module.

Regards,
Fredrik

**Comment by tenthirtyam** [comment]
Hi @freola, 

If possible, could you share the structure of your vCenter Server > datacenter > cluster > hosts path?

It might help to think about a workaround, for example, with the trimprefix function and then fix up the resulting path.

Ryan

**Comment by freola** [comment]
Hi @tenthirtyam,

The path with parents is: "vcenter/Hosts & Clusters/VMWareFarm/VMWareFarm_host/Cluster01 ESXi 6.7/esxhost"

The host is "**esxhost**", Parent to esxhost is "**Cluster01 ESXi 6.7**" that is the cluster, parent to the cluster is "**VMWareFarm_host**" that is some sort of root path (here is what I can see the issue, by default this path is "host" but not in our case...), under that you have the datacenter that is "**VMWareFarm**", then a parent to the datacenter that is "**Hosts & Clusters**" and then the 
"**vcenter**".

Hope this give som clarity in to the issue.

Regards,
Fredrik

**Comment by tenthirtyam** [comment]
Hi Fredrik,

Yes, it does make sense now. It does not sound like it's a cluster folder, but something else has changed which is atypical.

The provider would expect `/VMwareFarm/host` as the path, not `/VMwareFarm/VMwareFarm_host`, which is interesting how that might have changed. 

I should look similar to the followiing:

```bash
> govc ls
/VMwareFarm/vm
/VMwareFarm/network
/VMwareFarm/host
/VMwareFarm/datastore
```

Unfortunately, I don't think there is a workaround, as it's likely dependent on the expected path.

I recommend opening a case with VMware Support to investigate the ability and impact of correcting the path.

Ryan

**Comment by tenthirtyam** [comment]
Hi @freola,

Were you able to open a case with VMware Support to investigate the ability and impact of correcting the path discussed above?

Ryan

**Comment by freola** [comment]
Hi @tenthirtyam,

We will upgrade our environment and at the same time make a new fresh installation so we will get the right path. No case opend agains VMware and as this seams to only be a problem for us we can close this issue.

Thx for your help @tenthirtyam!

Fredrik

**Comment by tenthirtyam** [comment]
Happy to assist!
