### ISSUE TITLE
Creating VM with vsphere_content_library_item template fails when adding 2 networks

### ISSUE THREAD

**Issue by devosrobbe** [hashicorp/terraform-provider-vsphere#1441]
### vSphere Provider Version

- `2.0.2`
### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files
https://drive.google.com/file/d/1lQefQmF6zpj0N5NBDDwhtOoNN9D-yOEM/view?usp=sharing

### Debug Output

https://gist.github.com/devosrobbe/7830ffcdc02f634731c57d100ff4bcc7.js

### Expected Behavior

-  Expected behavior was that terraform should have created a VM with 2 networks on the vcenter

### Actual Behavior

```
╷
│ Error: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.invalid_argument","value":{"error_type":"INVALID_ARGUMENT","messages":[{"args":["network_mappings","com.vmware.vcenter.ovf.library_item.resource_pool_deployment_spec"],"default_message":"Could not convert field 'network_mappings' of structure 'com.vmware.vcenter.ovf.library_item.resource_pool_deployment_spec'","id":"vapi.bindings.typeconverter.fromvalue.struct.field.error"},{"args":[],"default_message":"Element already present in the map.","id":"vapi.bindings.typeconverter.map.duplicate.element"}]}}
│
│   with module.Windowsvm.vsphere_virtual_machine.Windows,
│   on ..\module_src\resource.tf line 1, in resource "vsphere_virtual_machine" "Windows":
│    1: resource "vsphere_virtual_machine" "Windows" {
│
╵
2
```

### Steps to Reproduce

1. `terraform apply`

### Extra info

When i execute the same code but with one network adaptor, no problems occur.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by doumhfr** [comment]
same problem here

**Comment by doumhfr** [comment]
ok so it's worth that I was thinking
if we use ovf content library, we can't create vm with more than one network card
if we use vm template; we can't create vm using storage policy (to have an automatic placement) :


│ Error: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.invalid_argument","value":{"error_type":"INVALID_ARGUMENT","messages":[{"args":["vmHomeStorage"],"default_message":"Datastore ID must be specified in field vmHomeStorage.","id":"com.vmware.vdcs.vmtx-main.missing_datastore_id_for_field"}]}}
│ 
│   with vsphere_virtual_machine.test1,
│   on servers.tf line 2, in resource "vsphere_virtual_machine" "test1":
│    2: resource "vsphere_virtual_machine" "test1"{
│ 

so currently I can't find any solution except doing all deployment manually, selecting the datastore, etc.

**Comment by doumhfr** [comment]
it seems to be a limitation on vmware side

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-CA4478D8-EC1B-47AD-B48E-38CD26B489FF.html :
During the deployment of an OVF template, only guest OS customization is supported. Hardware customization is not supported.

so for me the ovf as content library item is totally unusable. We can't create an image for each hardware configuration we need (x network cards, x disks etc).

is there a way to use vm-template with storage policy ?

**Comment by tenthirtyam** [comment]
Per the VMware vSphere product documentation, which compares the use of VM Templates vs OVF Templates in Content Library:

> _"During the deployment of an OVF template, only guest OS customization is supported. **Hardware customization is not supported**."_

Reference: [The VM Template as a Content Library Item](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-CA4478D8-EC1B-47AD-B48E-38CD26B489FF.html)

Regards,
Ryan

cc @appilon and @iBrandyJackson for review and closue.

**Comment by appilon** [comment]
Closing as per @tenthirtyam recommendation
