### ISSUE TITLE
create vmvare report:  list-attached-tags:401 

### ISSUE THREAD

**Issue by xuxiaoahang2018** [hashicorp/terraform-provider-vsphere#1442]
Details Terrafrom version - Terraform v0.13.3 VCenter Vsphere Version - vSphere Client version 6.7.0.40000

Once in 3 attempts Terraform executes successfully but Sometimes Fails i.e, VM gets created successfully but fails post task with below error.

Failure [ERROR] eval: *terraform.EvalApplyPost, err: POST https://192.128.1.1/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 401 Unauthorized

2020/09/23 18:35:03 [ERROR] eval: *terraform.EvalSequence, err: POST https://192.128.1.1/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 401 Unauthorized

Troubleshooting Done: The account has Administrator role in VCenter Checked the sessions of the user and terminated the account used by Terraform still no luck.

**Comment by tenthirtyam** [comment]
Hi, @xuxiaoahang2018 

In addition to needing more information, such as the configuration example, provider version, etc - to reproduce / tes the scenario, it should be noted at what level the permissions are provided. See the [Permissions on Tag Objects](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-2199584C-B422-4EEF-9340-5449E1FB7DAE.html) in the vSphere docs. 

Were you using `administrator@vsphere.local` or an account specific role/scope for tagging?

Ryan

**Comment by tenthirtyam** [comment]
I'm marking this issue as closed based on the limited information to reproduce the issue and no response.

If the issue persists with the latest version of the provider, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
