### ISSUE TITLE
`sync_time_with_host` incorrectly defaults to `false`

### ISSUE THREAD

**Issue by sirhc-chris** [hashicorp/terraform-provider-vsphere#1443]
### Summary

There is a problem introduced in this PR (https://github.com/hashicorp/terraform-provider-vsphere/pull/1431), whereby `sync_time_with_host` defaults to `false`.

This should not default to `false`. In VMware, this defaults to `true` for a new virtual machine, which is what they recommend:

> One-off time sync: Guest system clock is synchronized to host time upon specific VM life-cycle events that can cause guest clock to become incorrect, such as resuming from vMotion or a snapshot. This capability is recommended for use and turned on by default.

src: https://kb.vmware.com/s/article/1189

Having this default to `false` means any existing VM will have this setting change, unless it had been explicitly set previously.

`sync_time_with_host_periodically` should continue to default to false.

In version `2.0.1` of the module, the `sync_time_with_host` option performed the function of what `sync_time_with_host_periodically` now does, hence why the option originally defaulted to `false`, and hence why this has been missed.

### Terraform Version
`1.0.0`

### vSphere Provider Version
`2.0.2`

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior
`sync_time_with_host` defaults to `true`

### Actual Behavior
`sync_time_with_host` defaults to `false`

### References

* https://github.com/hashicorp/terraform-provider-vsphere/pull/1431
* https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#sync_time_with_host
* https://kb.vmware.com/s/article/1189

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@sirhc-chris - I agree that this should be set to `true` by default as it is recommended and configured by default on when using the vSphere Client, PowerCLI, API, etc unless explicitly set to `false`.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/7771363/140452133-e95067a1-6848-4afb-a0ad-ac57a7c335a8.png">

I'll submit a PR to have this addressed (code and docs) using this issue as a reference.

Regards,
Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment]
Additional reference: https://kb.vmware.com/s/article/1189

> VMware Tools performs two types of time corrections:
> 
> **One-off time sync:** Guest system clock is synchronized to host time upon specific VM life-cycle events that can cause guest** clock to become incorrect, such as resuming from vMotion or a snapshot. This capability is recommended for use and turned **_ON_** by default.
> 
> **Periodic time sync:** Guest system clock is periodically (every 60 seconds) synchronized to track host time. It is recommended that guests use a native time synchronization service – such as NTPD or Chrony in Linux based operating systems, and W32Time for Microsoft Windows. If that's not viable, periodic time sync provides an alternative. This capability is turned **_OFF_** by default.
> 

I'll begin to prepare this change so that the provider behavior is consistent with the API, PowerCLI, and the UI.

Ryan

**Comment by tenthirtyam** [comment]
Awaiting merge of 1522 before submitting the pull request for this issue. Since there will be doc changes and 1522 has substantial updates for the `vsphere_virtual_machine` resource.

cc @appilon

**Comment by tenthirtyam** [comment]
1522 has now been merged so I'll pick this one up next. Already did some of changes and testing a while back.
