### ISSUE TITLE
Possible allowed values for ip_allocation_policy in vsphere_virtual_machine resource

### ISSUE THREAD

**Issue by sumanth-lingappa** [hashicorp/terraform-provider-vsphere#1444]
### Terraform Version
latest (2.0.2)
### vSphere Provider Version
7.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {
  name                       = var.virtual_machine_name
  resource_pool_id           = data.vsphere_resource_pool.pool.id
  datastore_id               = data.vsphere_datastore.datastore.id
  host_system_id             = data.vsphere_host.host.id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  datacenter_id              = data.vsphere_datacenter.dc.id

  network_interface {
    network_id = data.vsphere_network.eth0.id
  }



  scsi_type = "lsilogic"

  num_cpus  = var.num_cpus
  memory    = var.memory

  ovf_deploy {
    remote_ovf_url            = var.remote_vpx_ovf_path
    enable_hidden_properties = true
    ip_allocation_policy = "STATIC_MANUAL" # What are the other allowed values?

  }

}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sumanth-lingappa** [comment]
I need to configure `ip_allocation_policy` as `STATIC_IPPOOL`.
Please let me know the possible allowed values for this attribute.

**Comment by tenthirtyam** [comment]
Hi @sumanth-lingappa, 

Did the above help answer your question?

Ryan

**Comment by tenthirtyam** [comment]
@appilon, looping you in for your thoughts on the above.

Ryan

**Comment by appilon** [comment]
Closing due to time since last reply
