### ISSUE TITLE
`vsphere_tag_category` incorrectly parses alias for `associable_types = ["All"]`

### ISSUE THREAD

**Issue by sirhc-chris** [hashicorp/terraform-provider-vsphere#1445]
### Summary

The `All` alias for a tag category (`associable_types = ["All"]`) isn't working correctly, the tag category isn't available to be assigned to any object within vSphere. It seems terraform isn't parsing `All` as an alias to vSphere, instead it's parsing it as a value, therefore the tags can't be used.

On first glance it looks correct in vSphere:
```
PS C:\> Get-TagCategory -Name tftest | Select-Object *

Name        : tftest
Description :
Cardinality : Multiple
EntityType  : {All}
```
However if I create a tag category in vSphere (outside of Terraform), selecting all object types, it looks like this instead (it lists all object types in `EntityType`, not simply listing `All`):
```
PS C:\> Get-TagCategory -Name test | Select-Object *

Name        : test
Description :
Cardinality : Multiple
EntityType  : {Cluster, DistributedSwitch, com.vmware.content.library.Item, ResourcePool...}
```
If I try to edit the tag category created by Terraform in the vSphere UI, it looks like this:
![category-created-in-terraform](https://user-images.githubusercontent.com/70642973/124788047-f0748080-df40-11eb-999a-87e170d9cb75.png)

Compared with the tag category created correctly outside of Terraform:
![category-created-in-vsphere](https://user-images.githubusercontent.com/70642973/124788104-ff5b3300-df40-11eb-9981-8dba9f3edf2e.PNG)

### Terraform Version
`1.0.0`

### vSphere Provider Version
`2.0.2`

### Terraform Configuration Files

```hcl
resource "vsphere_tag_category" "tag_cat_tftest" {
  name        = "tftest"
  cardinality = "MULTIPLE"
  associable_types = [
    "All",
  ]
}
```
The workaround is to declare all object types explicitly under `associable_types`, but it would be nice to use the `All` alias.

### Expected Behavior

After setting `associable_types = ["All"]`, the tag category should be available to be assigned to all object types

### Actual Behavior

After setting `associable_types = ["All"]`, the tag category is not available to be assigned to any object type

### Steps to Reproduce

1. `terraform apply`
2. Observe output of `Get-TagCategory -Name tftest | Select-Object EntityType`

### References

* https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/tag_category

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
It seems as though commit b120f5b03bed9f7238c41b51c71164e3899e6ccf made a change to `vsphere/tags_helper.g`o that removed the `vSphereTagTypeAll = "All"` along with others during a set of changes to address linter issues. 

This may be the reason the documented alias (All) has been reported to no longer work.

@appilon - do you recall the historical context.

Ryan

**Comment by appilon** [comment]
I am inspecting the changes in that commit now and it would appear that "ALL" never worked. There was constants for associable_types at some point (and were removed when a linter identified they were never referenced in the code). From what I can tell, vsphere expects when "ALL" is selected in the UI that a set of all the types is passed programmatically (that is, the UI's ALL is merely sugar for that full payload). This is fixable, but it does start to get a little messy in terms of diff suppression to distinguish the user manually passing every type VS passing ALL.

**Comment by appilon** [comment]
I can't find within govmomi the list of tag types that the system understands, if anyone can link to it in powercli or govmomi please link it.

**Comment by tenthirtyam** [comment]
Let me know if the [Tagging Tag Association APIs](https://developer.vmware.com/apis/vsphere-automation/latest/cis/tagging/tag_association/) docs help.

Ryan

**Comment by tenthirtyam** [comment]
Here you go @appilon. I just scraped it in a browser session/\.

```json
{
   "categoryName":"foo",
   "categoryDescription":"bar",
   "multipleCardinality":false,
   "associableEntityTypes":[
      "Folder",
      "ClusterComputeResource",
      "Datacenter",
      "Datastore",
      "StoragePod",
      "DistributedVirtualPortgroup",
      "DistributedVirtualSwitch",
      "VmwareDistributedVirtualSwitch",
      "HostSystem",
      "com.vmware.content.Library",
      "com.vmware.content.library.Item",
      "HostNetwork",
      "Network",
      "OpaqueNetwork",
      "ResourcePool",
      "VirtualApp",
      "VirtualMachine"
   ]
}
```
