### ISSUE TITLE
Add support for a `vsphere_compute_cluster_host_group` data source

### ISSUE THREAD

**Issue by doumhfr** [hashicorp/terraform-provider-vsphere#1449]
### Description

Hi,

we have a problem creating vsphere_compute_cluster_vm_host_rule

we have a terraform project which create all our vsphere infrastructure. datacenter, cluster, hosts, etc.
this project know all the infrastructure and can create vsphere_compute_cluster_host_group.

after that, each time we have a project that need virtual machines, we have a terraform for this project to create all needed things related to the project (vm, distributed_port_group, anti afinity rules etc). All the code is generated with a description of resources provided by the project manager.

but in these projects I have to create vsphere_compute_cluster_vm_group to be able to create vsphere_compute_cluster_vm_host_rule

but when I want to create the rule, I can't, because I can't use the pre created host groups.
importing is not a solution, we don't want that another project can modify the group.

why the vsphere_compute_cluster_host_group doesn't support data to utilize an host group already created ?

### Potential Terraform Configuration

```hcl

data "vsphere_compute_cluster_host_group" "hostgroup1" {
  name               = "hostgroup1"
  compute_cluster_id = data.vsphere_compute_cluster.cluster.id
}

resource "vsphere_compute_cluster_vm_group" "vm_group1" {
  name                = "vm_group1"
  compute_cluster_id  = data.vsphere_compute_cluster.cluster.id
  virtual_machine_ids = [vsphere_virtual_machine.vm1.id, vsphere_virtual_machine.vm2.id]
}

resource "vsphere_compute_cluster_vm_host_rule" "host_rule1" {
  compute_cluster_id       = data.vsphere_compute_cluster.cluster.id
  name                     = "terraform-host-rule1"
  vm_group_name            = vsphere_compute_cluster_vm_group.vm_group1.name
  affinity_host_group_name = data.vsphere_compute_cluster_host_group.hostgroup1.name
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @Nitin052,

The team welcome contributions to the provider. efore you get started, I recommend reading the [contributing guidelines](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/docs/CONTRIBUTING.md) and information on [submitting pull requests](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/docs/PULL_REQUESTS.md) to get started.

Please reach out to @appilon, @iBrandyJackson,  and myself with any submission questions.

Ryan

**Comment by tenthirtyam** [comment]
Submitted for review in pull request https://github.com/hashicorp/terraform-provider-vsphere/pull/1636.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
