### ISSUE TITLE
Changing `datastore_cluster_id` on  `vsphere_virtual_machine` resource does not move virtual machine

### ISSUE THREAD

**Issue by doumhfr** [hashicorp/terraform-provider-vsphere#1454]
### Terraform Version
1.0.2
### vSphere Provider Version
2.0.2

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "tst1"{
  name  = "tst1"
  resource_pool_id  = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_cluster_id = data.vsphere_datastore_cluster.clusterdatastore.id
```

### Debug Output

```console
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.tst1 will be updated in-place
  ~ resource "vsphere_virtual_machine" "tst1" {
      ~ datastore_id                            = "datastore-2061" -> (known after apply)
        id                                      = "422802a0-ce16-f312-70e1-7944870303b7"
        name                                    = "tst1"
        # (67 unchanged attributes hidden)
        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vsphere_virtual_machine.tst1: Modifying... [id=422802a0-ce16-f312-70e1-7944870303b7]
vsphere_virtual_machine.tst1: Still modifying... [id=422802a0-ce16-f312-70e1-7944870303b7, 10s elapsed]
vsphere_virtual_machine.tst1: Modifications complete after 10s [id=422802a0-ce16-f312-70e1-7944870303b7]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behavior

virtual machine is moved to new datastore

### Actual Behavior

nothing happens.
If you re run terraform apply you still have the same modificatn

### Steps to Reproduce

create a vm to a datastore cluster
after creation, change the code to change the datastore cluster

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
I can confirm that this issue **does** occur with the following `latest` versions:
- Terraform v1.1.0
- Terraform Provider for vSphere v2.0.2
- vSphere v7.0.3

Under the following scenarios:
- Change between `datastore_cluster.id`
- Change between from `datastore.id`  `> to >` `datastore_cluster.id`

However, the `terraform apply` is successful and the `.tfstate` **does inaccurately reflect** that the change took place.

It **does not** occur from  `datastore_cluster.id` `> to >`  `datastore.id`



Ryan

**Comment by tenthirtyam** [comment]
Pull request #1546 submitted to address this issue.
