### ISSUE TITLE
Annotation for `vsphere_virtual_machine` updated without any changes

### ISSUE THREAD

**Issue by jsalgado78** [hashicorp/terraform-provider-vsphere#1459]
### Terraform Version
Terraform v1.0.3

### vSphere Provider Version
provider.vsphere v2.0.2

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "srv113des1" {
    annotation                              = <<-EOT
        Actualizada a RHEL 6.3 estable
        Selinux permisivo
        IPTABLES desactivado
    EOT
    name                                    = "srv113des1"
}

```

### Expected Behavior

Annotation shouldn't be detected as changed after executing terraform import and terraform plan without any change and using terraform state show output to create config file

### Actual Behavior

Terraform plan shows annotation will be updated without any change in config file. This config file is created from terraform state show command output so annotation field has not changed
 
```hcl
  # vsphere_virtual_machine.srv113des1 will be updated in-place
  ~ resource "vsphere_virtual_machine" "srv113des1" {
      ~ annotation                              = <<-EOT
            Actualizada a RHEL 6.3 estable
            Selinux permisivo
            IPTABLES desactivado
        EOT
        name                                    = "srv113des1"
        tags                                    = []
        # (66 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```
### Steps to Reproduce

1. terraform import vsphere_virtual_machine.srv113des1 /datacenter/vm/srv113des1
2. Create a complete config file from terraform state show virtual_machine.srv113des1 command output
3. terraform plan

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Confirming that this issue exists in latest (v2.0.2).

**Ryan Johnson**
Staff II Solutions Architect
Cloud Infrastructure Business Group, VMware

**Comment by tenthirtyam** [comment]
@appilon , I think this would be considered expected behavior. Let me know if you agree.

Let me see if I can explain this one.

If the virtual machine template has an existing annotation (e.g. "Built by Packer") then this will be the initial annotation unless _defined_ by the `annotation` argument in the resource. 

If no annotation argument is provided, during each plan/apply it will show that a change is present to update the existing value found during the refresh to - `"Built by Packer" -> null`

```console
 # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
      - annotation                              = "Built by Packer" -> null
        id                                      = "42029153-4567-54cb-0d63-2bee5822b2e6"
        name                                    = "gh-1459"
        tags                                    = []
        # (66 unchanged attributes hidden)
```

However, it does **not** set the value to `null` and will always show the change until a value is **_explicitly_** set on the resource in the configuration.

If this is expected, then the workaround would be to use the `lifecycle` meta-argument.

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ...
  lifecycle {
    ignore_changes = [
      annotation,
    ]
  }
```

Ryan

**Comment by tenthirtyam** [comment]
After further investigation with Alex, we've tested a fix and I'll be submitting a pull request for inclusion in the next release.

Ryan
