### ISSUE TITLE
Import vsphere_distributed_portgroup doesn't work version > 1.25

### ISSUE THREAD

**Issue by gbordier35** [hashicorp/terraform-provider-vsphere#1461]
### Terraform Version
v1.0.3
### vSphere Provider Version
v2.0.2

### Affected Resource(s)

--- `vsphere_distributed_port_group`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "2.0.2"
    }
  }
}

provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = false
}

variable "vsphere_server" {
  description = "vCenter"
  type        = string
}

variable "vsphere_user" {
  description = "vSphere username"
  type        = string
}

variable "vsphere_password" {
  description = "vSphere password of vsphere_user"
  type        = string
  sensitive   = true
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_distributed_virtual_switch" "dvs" {
  name          = var.dvs
  datacenter_id = data.vsphere_datacenter.dc.id
}

variable "vsphere_datacenter" {
  description = "vSphere datacenter"
  type        = string
}

variable "dvs" {
  description = "Distributed virtual switch"
  type        = string
}

variable "vlan_name" {
  description = "VLAN name"
  type        = string
}

resource "vsphere_distributed_port_group" "vlan" {
  name                            = var.vlan_name
  description                     = "Test VLAN"
  number_of_ports                 = 256
  type                            = "earlyBinding"
  block_override_allowed          = true
  distributed_virtual_switch_uuid = data.vsphere_distributed_virtual_switch.dvs.id
  network_resource_pool_key       = null
  port_config_reset_at_disconnect = true
  vlan_id                         = (regex("VLAN(\\d{1,3})_", var.vlan_name ))[0]
  active_uplinks                  = ["lag1"]
  standby_uplinks                 = []
}
```

### Debug Output

```
# terraform import vsphere_distributed_port_group.vlan dvportgroup-<ID>
vsphere_distributed_port_group.vlan: Importing from ID "dvportgroup-<ID>"...
╷
│ Error: error locating portgroup: please specify a datacenter
```

### Expected Behavior

Import dvportgroup

Example with vsphere provider v1.25.0 : 
```
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "1.25.0"
    }
  }
}

# terraform import vsphere_distributed_port_group.vlan dvportgroup-<ID>
vsphere_distributed_port_group.vlan: Importing from ID "dvportgroup-<ID>"...
vsphere_distributed_port_group.vlan: Import prepared!
  Prepared vsphere_distributed_port_group for import
vsphere_distributed_port_group.vlan: Refreshing state... [id=dvportgroup-<ID>]
```

### Actual Behavior

It's not possible to import an existing dvportgroup with version > 1.25.0 : 
```
# terraform import vsphere_distributed_port_group.vlan dvportgroup-<ID>
vsphere_distributed_port_group.vlan: Importing from ID "dvportgroup-<ID>"...
╷
│ Error: error locating portgroup: please specify a datacenter
```

### Steps to Reproduce

1. Copy configuration code with version 2.0.2
2. terraform init
2. terraform apply -> dvportgroup will be create
3. Remove terraform.tfstate
6. terraform import vsphere_distributed_port_group.vlan dvportgroup-<ID> => Error locating portgroup
7. Change version of provider from 2.0.2 to 1.25.0
8. Remove .terraform.d, .terraform.lock.hcl
9. terraform init
10. terraform import vsphere_distributed_port_group.vlan dvportgroup-<ID>
```
vsphere_distributed_port_group.vlan: Importing from ID "dvportgroup-<ID>"...
vsphere_distributed_port_group.vlan: Import prepared!
  Prepared vsphere_distributed_port_group for import
vsphere_distributed_port_group.vlan: Refreshing state... [id=dvportgroup-<ID>]
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kev-in-shu** [comment]
Hi,

I noticed that a few other resources have implemented import via a path instead of the id.

And after scratching my head some time, I managed to import my portgroups using a path like this

`/$datacenter_name/network/$network_folder/$switch_name/$portgroup_name`

I feel like this is much harder than just passing an ID, as it's not really clear what counts as a folder from vSphere UI.

Also the documentation for `vsphere_distributed_port_group` was not updated to reflect this change.

Regards,

Kevin

**Comment by tenthirtyam** [comment]
It appears that the changes to use MoID that were implemented by @sumitAgrawal007  in https://github.com/hashicorp/terraform-provider-vsphere/commit/f39415bb536db0b0eb70986ccb7437f6befbc87b#diff-71902d0785ad0ca9cf7b4edc595ff89b91e141d86dca8010d5458aa8932ab847 for PR #1208 were overwritten by @koikonom in https://github.com/hashicorp/terraform-provider-vsphere/commit/44939f347c4813580b59a1178334c323cac2276c#diff-71902d0785ad0ca9cf7b4edc595ff89b91e141d86dca8010d5458aa8932ab847 for PR #1381.

It looks like it might have been a mistake since the markdown for the docs were not included.

@appilon @iBrandyJackson - let me know if  you'd like me to PR and test this to revert back to @sumitAgrawal007's change.

cc @tejavar

**Comment by appilon** [comment]
@tenthirtyam Thanks for tracking down the history, I seem to recall this period as a time we did refactoring/fixing of tests post SDK v2.0.0 upgrade, its possible a test was "fixed" by this reversion (and sometimes fix just means failing silently now, or passing but re-introducing other bugs such as what's being described).

If you have the bandwidth, would you have an environment to test the potential reversion against the associated acceptance tests?

**Comment by tenthirtyam** [comment]
I'd be happy to take the time to look at it. Let's catch over email to ensure I perform it correctly in my labs. 

Inbox me at johnsonryan [at] vmware [dot] com.

Ryan
