### ISSUE TITLE
Error: Virtual machine customization failed when deploying rhel8.2 from content library template

### ISSUE THREAD

**Issue by jabtk** [hashicorp/terraform-provider-vsphere#1470]
### Terraform Version

Terraform v1.0.5

### vSphere Provider Version
hashicorp/vsphere v2.0.2 (signed by HashiCorp)

### VmWare Vsphere version
6.7

### Target system version
RHEL 8.2

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
variables.tf
main.tf

```hcl
variables.tf
variable "vsphere_server" {
    type = string
    default = "vcenter.domain.com"
}

variable "vsphere_user" {
    type = string
    sensitive = true
    default = "username"
}

variable "vsphere_password" {
    type = string
    sensitive = true
    default = "password"
}

variable "vsphere_datacenter" {
    type = string
    default = "sDatacenter"
}

variable "vsphere_network" {
    type = string
    default = "VLAN_1"
}

variable "vm_name" {
    type = string
    default = "rhel-test1"
}

variable "vm_cpu_num" {
    type = number
    default = 2
}

variable "vm_mem_size" {
    type = number
    default = 8192
}

variable "template_name" {
  type = string
  default = "RHEL82-Template-PROD"
}

variable "content_library" {
  type = string
  default = "Test-Library"
}

variable "hostname" {
    type = string
    default = "rhel-test1"
}

variable "ssh_password" {
    type = string
    sensitive = true
    default = "TestPass"
}

variable "domain" {
  type = string
  default = "domain1.com"
}

variable "ipv4_address" {
  type = string
  default = "10.0.0.10"
}

variable "ipv4_netmask" {
  type = number
  default = 24
}

variable "ipv4_gateway" {
  type = string
  default = "10.0.0.3"
}

variable "dns_list" {
  type = map(list(string))
  default = {
    "domain1.com"    = ["10.0.0.1", "10.0.0.2"]
    "domain2.com" = ["20.0.0.1", "20.0.0.2"]
  }
} 

variable "disk_size" {
  type = list(any)
  default = [ {
      size   = 100,
      number = 0
    },
    {
      size   = 20,
      number = 1
    } ]
}

variable "cluster" {
  type = string
  default = "CLUSTER1"
}

variable "datastore" {
  type = string
  default = "DATASTORE1"
}


main.tf
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_content_library" "library" {
  name = var.content_library
}

data "vsphere_content_library_item" "item" {
  name       = var.template_name
  library_id = data.vsphere_content_library.library.id
  type       = "ovf"
}

resource "vsphere_virtual_machine" "vm" {
  name                   = var.vm_name
  datastore_id           = data.vsphere_datastore.datastore.id
  resource_pool_id       = data.vsphere_compute_cluster.cluster.resource_pool_id
  num_cpus               = var.vm_cpu_num
  memory                 = var.vm_mem_size
  cpu_hot_add_enabled    = true
  memory_hot_add_enabled = true
  scsi_type              = "lsilogic-sas"

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  dynamic "disk" {
    for_each = [for d in var.disk_size: {
      size   = d.size
      number = d.number
    }]

    content {
      label            = format("disk%s", disk.value.number)
      size             = disk.value.size
      unit_number      = disk.value.number
      thin_provisioned = false
    }
  }

  clone {
    template_uuid = data.vsphere_content_library_item.item.id

    customize {
      linux_options {
        host_name = var.hostname
        domain    = var.domain
      }

      network_interface {
        ipv4_address = var.ipv4_address
        ipv4_netmask = var.ipv4_netmask
        dns_server_list = var.dns_list[var.domain]
      }

      ipv4_gateway = var.ipv4_gateway
      timeout      = 7
    }

  }

}


```

### Debug Output
N/A

### Panic Output
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m0s elapsed]
╷
│ Error:
│ Virtual machine customization failed on "/sDatacenter/vm/rhel-test1":
│
│ An error occurred while customizing VM rhel-test1. For details reference the log file <No Log> in the guest OS.
│
│ The virtual machine has not been deleted to assist with troubleshooting. If
│ corrective steps are taken without modifying the "customize" block of the
│ resource configuration, the resource will need to be tainted before trying
│ again. For more information on how to do this, see the following page:
│ https://www.terraform.io/docs/commands/taint.html
│
│
│   with vsphere_virtual_machine.vm,
│   on main.tf line 39, in resource "vsphere_virtual_machine" "vm":
│   39: resource "vsphere_virtual_machine" "vm" {

### Expected Behavior
Create VM based on mentioned configuration with proper hostname(DNS Name) and assigned IP address to connected Network adapter

### Actual Behavior
VM has incorrect name taken from template, network adapter is disconnected, option "Connect at power on" is unchecked in vmware and IP address is not assigned. When there is manually created VM from same content library template, VM has proper hostname, network adapter is connected and option "Connect at power on" is checked (therefore I suppose that template built by packer is correct).

### Steps to Reproduce
Please check that API call to vmware is done correctly from terraform, as manual VM creation works properly but deployment via terraform is not able to set hostname and "connect at power on" option.

Propose correction to my code if you find any problems.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@jabtk - I notice that your configuration is not declaring the firmware as `bios` or `efi` for the resoure. 

Any content library items from the content library will default to `bios` - this is the default for any `vsphere_virtual_machine` resource. However, the default recommended firmware for RHEL 8 is `efi`.

Which are you using? 

If using EFI, set:

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configurations...
  firmware = "efi"
  # ... other configurations...
}
```

If using EFI _with secure boot_, set:

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configurations...
  firmware = "efi"
  efi_secure_boot_enabled = true
  # ... other configurations...
}
```

Hope this helps,
Ryan
@tenthirtyam

`status/waiting-on-response`

**Comment by tenthirtyam** [comment]
@jabtk - hope all is well, I just want to loop back and see if your issue was the firmware setting or not.

Would you mind updating this issue?

Ryan

**Comment by tenthirtyam** [comment]
Hi @jabtk, checking in to see if you have had any success in resolving your issue based on my prior comments ([1](https://github.com/hashicorp/terraform-provider-vsphere/issues/1470#issuecomment-964453489)) ([2](https://github.com/hashicorp/terraform-provider-vsphere/issues/1470#issuecomment-998455791)). 

Any content library items from the content library will default to `bios` - this is the default for any `vsphere_virtual_machine` resource. However, the default recommended firmware for RHEL 8 is `efi`.

Which are you using? 

If using EFI, set:

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configurations...
  firmware = "efi"
  # ... other configurations...
}
```

If using EFI _with secure boot_, set:

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configurations...
  firmware = "efi"
  efi_secure_boot_enabled = true
  # ... other configurations...
}
```

Hope this helps,
Ryan

cc @appilon @iBrandyJackson

**Comment by jabtk** [comment]
Hello,

sorry for late response, I was able to fix this issue by adding additional packages into ks.cfg file to be installed during installation.

These packages were added to ks.cfg:
%packages --ignoremissing
@^server-product-environment
kexec-tools
@compat-libraries
@core
@development
sysstat.x86_64
ksh.x86_64
zsh.x86_64
ftp.x86_64
lftp.x86_64
oddjob.x86_64
oddjob-mkhomedir.x86_64
pam_krb5.x86_64
sssd.x86_64
sssd-ldap.x86_64
mlocate.x86_64
nfs-utils.x86_64
pam_krb5.x86_64
sssd.x86_64
sssd-ldap.x86_64
mlocate.x86_64
nfs-utils.x86_64
compat-gcc-44.x86_64
compat-gcc-44-c++.x86_64
nmap.x86_64
tcpdump.x86_64
krb5-workstation.x86_64
xterm.x86_64
OpenIPMI.x86_64
ipmitool.x86_64
tree.x86_64
lsscsi.x86_64
tog-pegasus.x86_64
rpm-devel.x86_64
uuidd.x86_64
uuid.x86_64
ntp.x86_64
ntpdate.x86_64
aide.x86_64
prelink.x86_64
tcsh.x86_64
mailx.x86_64
syslinux.x86_64
genisoimage.x86_64
attr.x86_64
pciutils.x86_64
net-tools.x86_64
xorg-x11-xauth.x86_64
net-snmp.x86_64
vim-enhanced.x86_64
dosfstools.x86_64
efibootmgr.x86_64
ed.x86_64
bc.x86_64
oddjob.x86_64
oddjob-mkhomedir.x86_64
sssd.x86_64
adcli.x86_64
realmd.x86_64
rear.x86_64
samba-common-tools.x86_64
open-vm-tools.x86_64
%end

Not sure which package fixed the issue, I would need to install them one by one(maybe net-tools.x86_64), but issue was fixed by this.

**Comment by tenthirtyam** [comment]
Thanks for the update @jabtk!

This was likely resolved by the installation of open-vm-tools. I also assume perl was also installed. Both are required for guest customization.

Please consider marking the issue as closed if resolved.

Ryan

**Comment by appilon** [comment]
closing since it appears resolved
