### ISSUE TITLE
Add support for managing vCenter Single Sign-on domain local users

### ISSUE THREAD

**Issue by erltho** [hashicorp/terraform-provider-vsphere#1477]
### Description

I want to be able to create a local SSO user in vSphere. 

### Potential Terraform Configuration

```hcl
resource "vsphere_local_user" "example" {
    name = "example"
    password = "example123"
    user_description = "This is a test user"
    first_name = "Ex"
    last_name = "ample"
    email_adress ="exampleatexample.com"
   role = "(RegularUser|Administrator)"
}
```

### Reference

SSO group feature:
https://github.com/hashicorp/terraform-provider-vsphere/issues/1413

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Superseded by #1413 which now covers both local users and groups.
