### ISSUE TITLE
Unable to ignore clone block or/and its attributes with `lifecycle` meta-argument options

### ISSUE THREAD

**Issue by c0razo** [hashicorp/terraform-provider-vsphere#1478]
### Terraform Version
1.0.6

### vSphere Provider Version
1.21.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior

ignore that block / keys to prevent recreating the resource

### Actual Behavior

the plan ignores the code and always wants to change the clone block, which forces recreation

### Steps to Reproduce

1. `terraform plan`

### code and plan
i think i tried every way 
```hcl
lifecycle {
    ignore_changes = [
     clone.0.ovf_network_map, clone.0.ovf_storage_map, ovf_deploy, ovf_deploy.0, ovf_deploy.0.ovf_network_map
    ]
  }
```
still there
![image](https://user-images.githubusercontent.com/74508567/132823725-5cc360fb-ec15-4b19-a649-c9a41e511997.png)

do you have the same experience? how am i able to ignore that? i dont even figure it out where it came from. i cannot change anything in the resources due to this, so it is kind of a red flag. 

thank you in advance for any help!

**Comment by pascal-hofmann** [comment]
Not sure if this would work, but I'm able to ignore other attributes inside the `clone` block like this:

```
  lifecycle {
    ignore_changes = [
      clone[0].customize[0].timeout,
      clone[0].customize[0].dns_server_list,
      clone[0].customize[0].linux_options[0].host_name,
      clone[0].template_uuid,
    ]
  }
```

**Comment by tenthirtyam** [comment]
Hi @c0razo,

As @pascal-hofmann, [mentions above](https://github.com/hashicorp/terraform-provider-vsphere/issues/1478#issuecomment-921645118) you can do this; however, you need to use `clone[0].attribute` vs `clone.0.attribute` as seen in your issue description.

Also, I would recommend updating the provider and using the newer `vsphere_ovf_vm_template` data source for the OVA.

Regards,
Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as resolved based on the [solution example](https://github.com/hashicorp/terraform-provider-vsphere/issues/1478#issuecomment-921645118) provided in the previous comment.

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ...
  lifecycle {
    ignore_changes = [
      clone[0].customize[0].timeout,
      clone[0].customize[0].dns_server_list,
      clone[0].customize[0].linux_options[0].host_name,
      clone[0].template_uuid,
    ]
  }
}
```

or even for all clone,

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ...
  lifecycle {
    ignore_changes = [
      clone[0],
    ]
  }
}
```

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
