### ISSUE TITLE
NIC randomly connected

### ISSUE THREAD

**Issue by kaiszy** [hashicorp/terraform-provider-vsphere#1487]
### Terraform Version

Terraform v1.0.7
on linux_amd64

### vSphere Provider Version

hashicorp/vsphere v2.0.2

### Affected Resource(s)

```
resource "vsphere_virtual_machine" "vm" {

  for_each = var.servers

  name             = each.value.name
  resource_pool_id = data.vsphere_resource_pool.pool.id

  datastore_id = data.vsphere_datastore.datastore[each.value.datastore].id

  num_cpus = var.cpucores
  memory   = var.memory
  guest_id = data.vsphere_virtual_machine.template.guest_id

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label            = "disk0"
    thin_provisioned = false
    unit_number      = 0
    size             = var.hdsize
  }

  disk {
    label            = "swap"
    thin_provisioned = true
    unit_number      = 1
    size             = var.swapsize
  }

  dynamic "disk" {
    for_each = [ for disk in var.extradisks: disk ]

    content {
     label            = disk.value.label
     unit_number      = disk.value.unit
     datastore_id     = data.vsphere_datastore.datastore[each.value.datastore].id
     size             = disk.value.size
     eagerly_scrub    = false
     thin_provisioned = true
    }
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      linux_options {
        host_name = each.value.name
        domain    = var.domain
      }

      network_interface {
        ipv4_address = each.value.ip
        ipv4_netmask = 24
      }

      ipv4_gateway = var.gateway

      dns_suffix_list = var.search_domains
      dns_server_list = var.dns_server_list
    }
  }

}
```
### Terraform Configuration Files

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/null" {
  version = "3.1.0"
  hashes = [
    "h1:vpC6bgUQoJ0znqIKVFevOdq+YQw42bRq0u+H3nto8nA=",
    "zh:02a1675fd8de126a00460942aaae242e65ca3380b5bb192e8773ef3da9073fd2",
    "zh:53e30545ff8926a8e30ad30648991ca8b93b6fa496272cd23b26763c8ee84515",
    "zh:5f9200bf708913621d0f6514179d89700e9aa3097c77dac730e8ba6e5901d521",
    "zh:9ebf4d9704faba06b3ec7242c773c0fbfe12d62db7d00356d4f55385fc69bfb2",
    "zh:a6576c81adc70326e4e1c999c04ad9ca37113a6e925aefab4765e5a5198efa7e",
    "zh:a8a42d13346347aff6c63a37cda9b2c6aa5cc384a55b2fe6d6adfa390e609c53",
    "zh:c797744d08a5307d50210e0454f91ca4d1c7621c68740441cf4579390452321d",
    "zh:cecb6a304046df34c11229f20a80b24b1603960b794d68361a67c5efe58e62b8",
    "zh:e1371aa1e502000d9974cfaff5be4cfa02f47b17400005a16f14d2ef30dc2a70",
    "zh:fc39cc1fe71234a0b0369d5c5c7f876c71b956d23d7d6f518289737a001ba69b",
    "zh:fea4227271ebf7d9e2b61b89ce2328c7262acd9fd190e1fd6d15a591abfa848e",
  ]
}

provider "registry.terraform.io/hashicorp/template" {
  version = "2.2.0"
  hashes = [
    "h1:94qn780bi1qjrbC3uQtjJh3Wkfwd5+tTtJHOb7KTg9w=",
    "zh:01702196f0a0492ec07917db7aaa595843d8f171dc195f4c988d2ffca2a06386",
    "zh:09aae3da826ba3d7df69efeb25d146a1de0d03e951d35019a0f80e4f58c89b53",
    "zh:09ba83c0625b6fe0a954da6fbd0c355ac0b7f07f86c91a2a97849140fea49603",
    "zh:0e3a6c8e16f17f19010accd0844187d524580d9fdb0731f675ffcf4afba03d16",
    "zh:45f2c594b6f2f34ea663704cc72048b212fe7d16fb4cfd959365fa997228a776",
    "zh:77ea3e5a0446784d77114b5e851c970a3dde1e08fa6de38210b8385d7605d451",
    "zh:8a154388f3708e3df5a69122a23bdfaf760a523788a5081976b3d5616f7d30ae",
    "zh:992843002f2db5a11e626b3fc23dc0c87ad3729b3b3cff08e32ffb3df97edbde",
    "zh:ad906f4cebd3ec5e43d5cd6dc8f4c5c9cc3b33d2243c89c5fc18f97f7277b51d",
    "zh:c979425ddb256511137ecd093e23283234da0154b7fa8b21c2687182d9aea8b2",
  ]
}

provider "registry.terraform.io/hashicorp/vsphere" {
  version = "2.0.2"
  hashes = [
    "h1:/9qlE9Ni7mhl3cTHLhmYg1AFuyBnXqie53Q5Ujor6oU=",
    "zh:0b72856d2a89b118adf64dcfc75a0b0f7d8875e9872c637a9a0549d4a3dd9383",
    "zh:2cf50f17464feeac60039f4d36656835895260798d4d9167a1ff2d4e1e464dce",
    "zh:39d5f1c99bd4024d88b95892711f234afeb2b83700cdbd3df68a60c6b3bb0ac7",
    "zh:551b68f91f5eefa4daee4d826d27d2bc10236e0642fdafd066604884b2a06816",
    "zh:8454b5e7dbbf0300bbab1ecd73c12511cf35c0c493ad18e31742d58798e11026",
    "zh:84a8233a60240e0020de513668a20d015a7fbc760ad6ab639d52e6ddabfa3376",
    "zh:95574b7f092e77f9c629770b802d1635903f14d8d88d3828a96f58ca072876a5",
    "zh:a262c779c112e4d6ac47152d6c6303308180dfd4d5929b980cf24707ca9218e9",
    "zh:c7622cfa8bab6a6f122c0ab3d4767ecf0f52ccf32d64020aa4e9581f91da5586",
    "zh:e01cfc79d21c7151c97047afdc79dfe7bf37c0063908829200480a03359e4c2e",
    "zh:f64c3f283c31477886c3d16592426dbefa2cab55f2885cb3351cef094ad898a0",
  ]
}
```

### Expected Behavior

When i want to rollout several Servers with the above piece of source i expect that all of them will be customized.

### Actual Behavior

The machines will be cloned from template. Than randomly some of the machines NIC will not got to connected state and terraform failed for this machine. All of them use the same tempolate/settings.

### Steps to Reproduce

1. `terraform apply`

### References

VSphere Version 7.0.2
* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ryantho6** [comment]
I'm having this same issue, despite the template having "connect at power on" enabled. Also, this only seems to happen for Linux VMs.

**Comment by tenthirtyam** [comment]
This is _**most likely**_ an issue with the Linux distribution if cloud-init is installed and if the configuration for the machine image has not been configured to address use of the correct data source (e.g. [VMware] with cloud-init 21.3+) and order of customization operations.

**Recommend**: `close/not-a-bug`.

Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment]
@kaiszy - checking in to see if you have an update based on my prior comments ([1](https://github.com/hashicorp/terraform-provider-vsphere/issues/1487#issuecomment-950419206)) ([2](https://github.com/hashicorp/terraform-provider-vsphere/issues/1487#issuecomment-955804496)).

If your issue does stem from `cloud-init` you'll need to disable it to allow guest customizations to work.

I have examples that cover this in my [vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere) project that may help. By default, the Ubuntu 20.04 image uses `cloud-int` for customization but the CHANGELOG mentions the changes needed to disable `cloud-init`.

Hope this helps.
Ryan

cc @appilon and @iBrandyJackson

**Comment by appilon** [comment]
I will be closing this issue based on time since reply by the person posting. If the issue does persist please open a new issue and reference this one for context
