### ISSUE TITLE
Data vsphere_folder inconsistent result plan/apply

### ISSUE THREAD

**Issue by fgionghi** [hashicorp/terraform-provider-vsphere#1492]
### Terraform Version
1.0.8
### vSphere Provider Version
2.0.2

### Affected Resource(s)

- `vsphere_folder`

### Terraform Configuration Files
data.tf:
```hcl
data "vsphere_folder" "folder-service" {
  path = "/mydomaindc/vm/terraform/services"
}
```
vm.tf:
```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "mydyndns"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_cluster_id     = data.vsphere_datastore_cluster.unity.id
  folder = data.vsphere_folder.folder-service.path

  num_cpus = 1
  memory   = 1024
  guest_id = "ubuntu64Guest"



  network_interface {
    network_id = data.vsphere_network.net.id
  }

  disk {
    label = "disk0"
    size  = 30
    thin_provisioned = true
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      linux_options {
        host_name = "mydyndns"
        domain    = "mydomain.local"
      }

      network_interface {
        ipv4_address = "ip"
        ipv4_netmask = 24

      }
      dns_server_list = [ "ip", "ip" ]
      ipv4_gateway = "ip"
    }
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir /etc/salt",
      "apt-get update",
      "echo 'master: salt-server.mydomain.eu' > /etc/salt/minion",
      "apt-get install -o Dpkg::Options::='--force-confold' --force-yes -y salt-minion",

     ]

    connection {
    type     = "ssh"
    user     = "root"
   # password = "root"
    private_key = <<EOT
private-key
EOT
    host     = vsphere_virtual_machine.vm.default_ip_address
  }
}
}
```

### Debug Output
The code above is working during the plan:
https://gist.github.com/fgionghi/d4f126f29a9189fe2d1ca78ccac7a317

But in the apply i get:
https://gist.github.com/fgionghi/eb2eb8eb7916a0aafdef3ea602aec47f

### Expected Behavior

It should find the folder. 

### Actual Behavior

It not find the folder and it add `/mydomaindc/vm/` at the biginning of the path:
```
│ Error: folder '/mydomaindc/vm/mydomaindc/vm/terraform/services' not found
│ 
│   with vsphere_virtual_machine.vm,
│   on main.tf line 1, in resource "vsphere_virtual_machine" "vm":
│    1: resource "vsphere_virtual_machine" "vm" {
```
And it's true that `/mydomaindc/vm/mydomaindc/vm/terraform/services` doesn't exist.

### Steps to Reproduce

Try to get a nested folder through data.

### Additional infos
If I don't use `/mydomaindc/vm/` at all like this:
```hcl
data "vsphere_folder" "folder-service" {
  path = "terraform/services"
}
```
it fails during the plan.

If I use this syntax directly in the VM definition:
```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "mydyndns"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_cluster_id     = data.vsphere_datastore_cluster.unity.id
  folder = "terraform/services"
  #data.vsphere_folder.folder-service.path

  num_cpus = 1
  memory   = 1024
  guest_id = "ubuntu64Guest"
```
it works and the machine is correctly created. Is this an expected behavior and I shouldn't use `data.vpshere_folder` inside a VM?

**Comment by tenthirtyam** [comment]
Yes, you can **absolutely**__ use the `vsphere_folder` data source to drive placement, but you need to make some slight modifications as illustrated below:

```hcl
data "vsphere_folder" "folder" {
  path = "/${data.vsphere_datacenter.datacenter.name}/vm/terraform/services"
}
```
and...

```hcl

resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  folder                  = trimprefix(data.vsphere_folder.folder.path, "/${data.vsphere_datacenter.datacenter.name}/vm") 

```

I've posted an example here: https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine/clone-template-linux-nested-folder

Ryan
@tenthirtyam

Recommend: `close/not-a-bug`

**Comment by tenthirtyam** [comment]
Hi @fgionghi -

I noticed you closed the issue. I just wanted to check in and ask if my example help you past your issue.

Thanks,
Ryan
