### ISSUE TITLE
`vsphere_host_virtual_switch` resource attempts to change the VMNIC order

### ISSUE THREAD

**Issue by CSimpiFoN** [hashicorp/terraform-provider-vsphere#1503]
### Terraform Version
v1.0.3
### vSphere Provider Version
v2.0.2

### Affected Resource(s)
- `vsphere_host_virtual_switch`

### Terraform Configuration Files

```hcl
resource "vsphere_host_virtual_switch" "switch" {
  name            = var.name
  host_system_id  = var.host_system_id
  number_of_ports = var.number_of_ports
  mtu             = var.mtu

  network_adapters = var.network_adapters

  active_nics    = var.active_nics
  standby_nics   = var.standby_nics
  teaming_policy = var.teaming_policy

  allow_promiscuous      = var.allow_promiscuous
  allow_forged_transmits = var.allow_forged_transmits
  allow_mac_changes      = var.allow_mac_changes

  shaping_enabled           = var.shaping_enabled
  shaping_average_bandwidth = var.shaping_average_bandwidth
  shaping_peak_bandwidth    = var.shaping_peak_bandwidth
  shaping_burst_size        = var.shaping_burst_size
}
```
```hcl
module "management_networks_gib-prd-esxi01" {
  source = "./modules/vsphere_host_virtual_switch"

  name             = "vSwitch0"
  network_adapters = ["vmnic1", "vmnic4"]
  active_nics      = ["vmnic1", "vmnic4"]
  host_system_id   = module.gibraltar_production_hosts.id["gib-prd-esxi01"]
}
```
![image](https://user-images.githubusercontent.com/35144906/139226395-aff5e741-1963-4fc4-b5c7-fb196e455d2b.png)

### Debug Output
```hcl
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
  # module.management_networks_gib-prd-esxi01.vsphere_host_virtual_switch.switch has been changed
  ~ resource "vsphere_host_virtual_switch" "switch" {
        id                        = "tf-HostVirtualSwitch:host-241890:vSwitch0"
        name                      = "vSwitch0"
      ~ network_adapters          = [
          - "vmnic1",
            "vmnic4",
          + "vmnic1",
        ]
        # (19 unchanged attributes hidden)
    }
Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
─────────────────────────────────────────────────────────────────────────────
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # module.management_networks_gib-prd-esxi01.vsphere_host_virtual_switch.switch will be updated in-place
  ~ resource "vsphere_host_virtual_switch" "switch" {
        id                        = "tf-HostVirtualSwitch:host-241890:vSwitch0"
        name                      = "vSwitch0"
      ~ network_adapters          = [
          - "vmnic4",
            "vmnic1",
          + "vmnic4",
        ]
        # (19 unchanged attributes hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy
```
```hcl
│ Error: error updating host vSwitch: ServerFaultCode: An error occurred during host configuration.
│ 
│   with module.management_networks_gib-prd-esxi01.vsphere_host_virtual_switch.switch,
│   on modules/vsphere_host_virtual_switch/main.tf line 1, in resource "vsphere_host_virtual_switch" "switch":
│    1: resource "vsphere_host_virtual_switch" "switch" {
```

### Expected Behavior
Terraform should not see any changes made, as the configuration was done by it in previous run, and was nothing changed since then.

### Actual Behavior
Terraform wants to change the order to the actual current settings, then it fails, as it cannot be done

### Steps to Reproduce
- Have ESXi cluster
- Setup the network with VMNICs added
- Do whatever other change to hosts via Terraform

### Important Factoids
- vCenter 7.0 u3
- ESXi 7.0

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@appilon, do you have any thoughts on why the order could be lost in the above?

Ryan

**Comment by tenthirtyam** [comment]
Hi @CSimpiFoN, 

I attempted to run a reproduction of this reported issue a testbed today, but I was unable to observe the reported behavior with the same configuration. All tests ran with the expected results - `vmnic1` and  `vmnic4` remained in the same order with every apply.

```console
Terraform v1.1.5
Provider: v2.0.2
vSphere: v7.0.3(c)
```

Basic example:

```hcl
resource "vsphere_host_virtual_switch" "switch" {
  name            = "gh-1503"
  host_system_id  = data.vsphere_host.host.id
  number_of_ports = 42
  mtu             = 1500

  network_adapters = ["vmnic1", "vmnic4"]

  active_nics    = ["vmnic1", "vmnic4"]
  standby_nics   = []
  teaming_policy = "loadbalance_ip"

  allow_promiscuous      = false
  allow_forged_transmits = false
  allow_mac_changes      = false

  shaping_average_bandwidth = 0
  shaping_burst_size        = 0
  shaping_peak_bandwidth    = 0
}
```

Are you still experiencing this issue?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the inability to reproduce the issue and no community reactions. 👍🏻 👎🏻 

If the issue persists with [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), even using the basic config example above,  please open a new issue and reference this issue for additional context. If/when opening a new issue, please provide a copy of the module in a Gist as this would be helpful.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
