### ISSUE TITLE
Terraform does not ignore all attributes mentioned in the `lifecycle` Meta-Argument 

### ISSUE THREAD

**Issue by elifsamedin** [hashicorp/terraform-provider-vsphere#1510]
### Terraform Version

```
$ terraform version 
Terraform v1.0.10
```

### vSphere Provider Version

```
$ terraform providers 

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/vsphere] 2.0.2
```

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```
  lifecycle {
    ignore_changes = [
      annotation,
      custom_attributes,
      extra_config,
      pci_device_id,
      tags,
    ]
  }
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform should ignore the attributes included in the `ignore_changes` list.

### Actual Behavior

After firstly applying the configuration, the `custom_attributes`, `extra_config`, `pci_device_id`, and `tags` attributes are `null`.

```
$ terraform state pull | grep -E "custom_attributes|extra_config|pci_device_id|tags"
            "custom_attributes": null,
            "extra_config": null,
            "pci_device_id": null,
            "tags": null,
```

Without any code updates or actions within VMware vSphere, the second time I execute `terraform apply`:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.**********.vsphere_virtual_machine.vm has been changed
  ~ resource "vsphere_virtual_machine" "vm" {
      + custom_attributes                       = {}
      + extra_config                            = {}
        id                                      = "42290199-cf0e-ce6d-2bc1-3d96bd8245ef"
        name                                    = "**********"
      + pci_device_id                           = []
      + tags                                    = []
        # (63 unchanged attributes hidden)

      ~ clone {
          + ovf_network_map = {}
          + ovf_storage_map = {}
            # (3 unchanged attributes hidden)

          ~ customize {
              + dns_server_list = []
              + dns_suffix_list = []
                # (1 unchanged attribute hidden)


                # (2 unchanged blocks hidden)
            }
        }


        # (2 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
tfstate reflects the above updates as well.

```
$ terraform state pull | grep -E "custom_attributes|extra_config|pci_device_id|tags"
            "custom_attributes": {},
            "extra_config": {},
            "pci_device_id": [],
            "tags": [],
```

### Steps to Reproduce

See above.

### References

* #1463

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by TimVerbois** [comment]
Have the same issue, tried to use ignore_changes = all

```terraform
  lifecycle {
    ignore_changes = all
  }
```

but still it gives the same warnings:

```
  ~ resource "vsphere_virtual_machine" "main" {
      ~ guest_ip_addresses                      = [
            # (3 unchanged elements hidden)
            "fe80::ecee:eeff:feee:eeee",
          - "fe80::ecee:eeff:feee:eeee",
          - "fe80::ecee:eeff:feee:eeee",
          - "fe80::ecee:eeff:feee:eeee",
          - "fe80::ecee:eeff:feee:eeee",
            "10.111.27.22",
            # (1 unchanged element hidden)
        ]
        id                                      = "420f9620-9aaf-5e95-98d9-c1d45df3fd3a"
```

I assume these messages come from interfaces that are created by kubernetes on these VM's.  

Even if I run a `terraform apply -refresh-only`, an hour later, we have the same problem.  If it is kubernetes that changes the ip addresses part, it is pretty normal that it is changed a lot.  This makes using Terraform in combination with kubernetes pretty problematic.

**Comment by TimVerbois** [comment]
Maybe an important addition:

we use vsphere provide version 2.0.2, but the problem does not come up using Terraform 0.15.5, only when we upgrade to the latest Terraform 1.1.2.

**Comment by tenthirtyam** [comment]
Hi @elifsamedin and @TimVerbois,

This is expected behavior for the computed values.

Notice that _**`"No changes. Your infrastructure matches the configuration. Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only"`**_ is displayed.

If you run `terraform apply -refresh-only` then the `guest_ip_addresses`, etc are updated in `.tfstate`, as expected.

For example: 

```console
❯ terraform apply -refresh-only -auto-approve
vsphere_virtual_machine.vm: Refreshing state... [id=4202d9f3-d384-35cf-9c49-a2934e6f3b4f]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # vsphere_virtual_machine.vm has changed
  ~ resource "vsphere_virtual_machine" "vm" {
      ~ default_ip_address                      = "172.16.11.192" -> "172.16.11.202"
      ~ guest_ip_addresses                      = [
          - "172.16.11.192",
          + "172.16.11.202",
            "fe80::250:56ff:fe82:5a9a",
        ]
        id                                      = "4202d9f3-d384-35cf-9c49-a2934e6f3b4f"
        name                                    = "ubuntu-cloud-init"
        tags                                    = []
        # (64 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

This is a refresh-only plan, so Terraform will not take any actions to undo these. If you were expecting these changes then you can apply this plan to record the updated values in the Terraform state without changing any remote objects.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Notice the last three lines above....

```console
This is a refresh-only plan, so Terraform will not take any actions to undo these. If you were expecting these changes then you can apply this plan to record the updated values in the Terraform state without changing any remote objects.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

So, in the example, the state is updated accordingly with the refresh.

```json
            "guest_id": "ubuntu64Guest",
            "guest_ip_addresses": [
              "172.16.11.202",
              "fe80::250:56ff:fe82:5a9a"
            ],
```

The addition to the `lifecycle` meta-argument is unnecessary as that's tracking changes, not these computed values.

### The "TL;DR" 😀 

This is expected behavior for the computed values. The the `plan` and `apply` are notifying that the computed value has changed and will be refreshed in the `.tfstate`.

I'm tagging @appilon for any additional comments.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.

**Comment by tenthirtyam** [comment]
Duplicate: #1463

**Comment by tenthirtyam** [comment]
@appilon has shared confirmed that this is the expected behavior in the #1463, but he has raised a UX issue with Terraform core regarding the CLI presentation.

https://github.com/hashicorp/terraform-provider-vsphere/issues/1463#issuecomment-1034103856

Marking as closed.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc
