### ISSUE TITLE
Doesnt connect the network adapter

### ISSUE THREAD

**Issue by it-pappa** [hashicorp/terraform-provider-vsphere#1511]
Terraform Version

v1.0.10

Expected Behavior

Network Adapter should be connected.
Actual Behavior

Isnt connected and get error:
An error occurred while setting up network properties of the guest OS. See the log file /var/log/vmware-imc/toolsDeployPkg.log in the guest OS for details.
Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
Use any guides from online:
vSphere 6.7
Template built with packer v 1.7.6
template OS: Ubuntu 20.04 Iso.
Additional Context

I have tested with minimal config and larger, i have tested the guides on hashicorp/terraform website and more.
References

Seen this been mentioned alot but hasnt seen anyone solving this.

**Comment by dbond007** [comment]
If the network isn't connected, that usually means vmware customisation didn't complete successfully. That usually means the version of vcenter you are using doesn't support the is you are customisation.  Vcenter 6.7u3g or newer is needed for Ubuntu 20.04 customisation. You mentioned 6.7 but not a specific version.

**Comment by tenthirtyam** [comment]
@it-pappa,

This would not be a bug, but rather assistance with the configuration.

I would recommend that you post your build config `.hcl` and the `user-data` files here or in a Gist.

You can find a working example in my [github.com/rainpole/packer-vsphere](https://github.com/rainpole/packer-vsphere) project.

- In the project, the v21.10 and v21.10.1 releases have this address w/o `cloud-init` installed.
- The updates now `main` via a clone (as of this date) resolve the same issue with `cloud-init` 21.3 and the `VMware` data source.

Regards,
Ryan

**Comment by tenthirtyam** [comment]
@it-pappa Are you trying to use `linux_options` for vm guest customization or `extra_config` for a cloud-init use case?

Ryan

**Comment by it-pappa** [comment]
@tenthirtyam 
`provider "vsphere" {
  user           = var.vsphere_username
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  allow_unverified_ssl = true
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 6144
  guest_id = "ubuntu64Guest"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
  network_id    = "${data.vsphere_network.network.id}"
  adapter_type  = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
}

  disk {
    label = "disk0"
    size  = 25
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "terraformtest"
        domain    = "local"
      }

      network_interface {
        ipv4_address = "192.168.1.43"
        ipv4_netmask = 24
      }

      ipv4_gateway = "192.168.1.1"
      dns_server_list = ["192.168.1.1"]
    }
  }
}`

**Comment by tenthirtyam** [comment]
Below are working examples for both scenarios:

1. Ubuntu Server with [VM Guest Customization](https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine/clone-template-linux-guest-customization)
2. Ubuntu Server with [Cloud-Init](https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine/clone-template-linux-cloud-init)

You can find working examples for 1 in the v21.10 and v21.10.1 release of [GitHub.com/rainpole/packer-vsphere](https://GitHub.com/rainpole/packer-vsphere).

You can find working examples for 2 in the `main` release of [GitHub.com/rainpole/packer-vsphere](https://GitHub.com/rainpole/packer-vsphere) as of this date if you clone the repo.

Hope this helps,
Ryan

Recommend: `not-a-bug`

**Comment by it-pappa** [comment]
@dbond007  looks like i have: 6.7.0.21000

**Comment by tenthirtyam** [comment]
Refer to [this KB](https://kb.vmware.com/s/article/59687) for pre-vSphere 6.7 Update 3.

Ryan

**Comment by it-pappa** [comment]
@tenthirtyam @dbond007 
Ok, all yesterday I patched up all my systems. 

Tried to deploy a new template with packer and then used terraform. I got error:
Failed to create bus connection: No such file or directory

No network adopter connected.

**Comment by tenthirtyam** [comment]
@it-pappa,

Can you provide a copy of the Terraform configuration [ in a markdown code block](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for HCL that has been formatted with `terraform fmt` for review?

Ryan

**Comment by it-pappa** [comment]
Looks like the issue was due to unpatched host. 
Patch up the vCenter and esxi hosts together with hardware versions and you are all set. 

You will still get errors but the networking issue is gone as long as you do the workaround linked here from vmware: 
https://kb.vmware.com/s/article/59557
