### ISSUE TITLE
Error processing network device changes post-clone: network_interface.0: failed to create EthernetCardBackingInfo

### ISSUE THREAD

**Issue by santiagoamez** [hashicorp/terraform-provider-vsphere#1520]
### Terraform Version

1.0.8

### vSphere Provider Version

2.0.2

### vSphere Version

6.7

### Affected Resource(s)

- `vsphere_virtual_machine`
- `vsphere_distributed_port_group`

### Terraform Configuration Files

I am unable to publish the configuration files

### Debug Output

Error: error reconfiguring virtual machine: error processing network device changes post-clone: network_interface.0: failed to create EthernetCardBackingInfo For /DC1/network/vlan209: System.Read privilege required for config.distributedVirtualSwitch

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply

### References

There is a similar error already discussed, however it refers to not finding the object or item. My problem is about a permission apparently. 

(https://github.com/hashicorp/terraform-provider-vsphere/issues/316)

### Community Note

Hi, I am trying to create a virtual machine, however, when I create a network interface, I get the error shown above. Apparently my profile requires a special permission on the distributed virtual switch, however I do not know what it is. Does anyone have any idea? Thank you very much.

**Comment by tenthirtyam** [comment]
For the user account accessing the vCenter Server, is a default or custom vSphere role being assigned to the account?

If a custom role, when create via the UI it’s automatically granted system.read (along with system.view and system.anonymous) however, if the role was created with Terraform, you must add these privileges.

Ryan

**Comment by santiagoamez** [comment]
@tenthirtyam Effectively the error was because it did not have permissions in the distributed virtual switch. Thank you
