### ISSUE TITLE
Customization of the guest operating system failed, even though open-vm-tools is installed.

### ISSUE THREAD

**Issue by joltcan** [hashicorp/terraform-provider-vsphere#1523]
### Terraform Version

1.0.11

### vSphere Provider Version

provider "registry.terraform.io/hashicorp/vsphere" {
  version = "2.0.2"

### vSphere Version

6.7.0.46000

### Affected Resource(s)

vsphere_virtual_machine clone

### Terraform Configuration Files

```hcl

# override defaults from variables.tf
locals {
    vlan = "vlanXX"
    disk_size = 40
    memory = 4096
    cpus = 2
    gateway = "172.16.10.1"
    vmware_host = "172.16.90.34"
    vmware_storage = "NVME1 - 34"
}

variable "esxi_hosts" {
  default = [
    "c1-rabbit-cluster1"
  ]
}

variable "ip_map" {
    default = [
        "172.16.10.121",
        "172.16.10.122"
    ]
}

# from env
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "dc"
}

data "vsphere_datastore" "datastore" {
  name          = local.vmware_storage
  datacenter_id = data.vsphere_datacenter.dc.id
}

# https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/datastore_cluster
data "vsphere_compute_cluster" "cluster" {
  name          = "cluster"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = local.vlan
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.template_name}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#creating-a-virtual-machine-from-a-template
resource "vsphere_virtual_machine" "vm" {
  count            = "${length(var.esxi_hosts)}"
  name             = "${var.esxi_hosts[count.index]}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = local.cpus
  memory   = local.memory
  guest_id = "debian10_64Guest"

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    label             = "${data.vsphere_virtual_machine.template.disks.0.label}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.esxi_hosts[count.index]}"
        domain    = "${var.domain_name}"
      }

      network_interface {
        ipv4_address = "${var.ip_map[count.index]}"
        ipv4_netmask = 24
      }

      ipv4_gateway = "${local.gateway}"
    }
  }
}
```

### Debug Output

[gist](https://gist.github.com/joltcan/2f2d523f5f0456a6fd2d0339c5743cb2)

### Expected Behavior

Host should be created with the specified disk size.

### Actual Behavior

```bash
│ Error: error sending customization spec: Customization of the guest operating system 'debian10_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.
│
│   with vsphere_virtual_machine.vm[0],
│   on main.tf line 61, in resource "vsphere_virtual_machine" "vm":
│   61: resource "vsphere_virtual_machine" "vm" {
│

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I've tried with both the default debian 11 cloud image as well as creating a debian 11 install, both with the debian open-vm-tools package, and by manual install via VMware tools tar.gz file, same issue regardless.

The disk formatting is just a regular partition with 1 swap and one root, both as primaries.

If I don't add clone, then the vm is created without disk.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by dbond007** [comment]
Debian isn't supported by vsphere for customisation, switch it to OtherGuest64 or Ubuntu 64  and it should work

**Comment by joltcan** [comment]
I would love to, but I get an other error then:

```
│ Error: invalid guest ID "OtherGuest64" for clone. Please set it to "debian10_64Guest"
```

**Comment by joltcan** [comment]
Ah, I need to change the vm itself, Ill try!

**Comment by joltcan** [comment]
Yey! It worked! Thank you so much! I've been googling like crazy but never found that particular solution.

Had to use `otherLinux64Guest` though.

**Comment by dbond007** [comment]
No problem. When you move to vSphere 7, you should be able to use debian10_64Guest again, as support for debian 10 and 11 was added to vsphere 7.
