### ISSUE TITLE
Unable to delete VM folder & VMDK inside datastore after VM deletion triggered by TF

### ISSUE THREAD

**Issue by gitprady** [hashicorp/terraform-provider-vsphere#1536]
Terraform Version : Terraform v1.0.11
vSphere Provider Version : 2.0.2
vSphere Version : 6.7 Build Number : 18831049

### Affected Resource(s)

Issue : After VM is deleted from TF, it still keeps VMDK & the VM folder inside the datastore.

### Debug Output

```console
vsphere_virtual_machine.vmtf2[1]: Destroying... [id=423f48c6-708e-e085-206e-7ad30070ba53]
vsphere_virtual_machine.vmtf2[1]: Still destroying... [id=423f48c6-708e-e085-206e-7ad30070ba53, 10s elapsed]
vsphere_virtual_machine.vmtf2[1]: Destruction complete after 18s
```
### TF Code

```hcl
resource "vsphere_virtual_machine" "vmtf2" {
  count            = var.vm_count
  name             = "${var.vmprefix}${count.index + 1}"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  #num_cpus = 2
  #memory   = 1024
  guest_id = "windows9Server64Guest"
  folder = "Wrangler"
  efi_secure_boot_enabled = true
  enable_disk_uuid                        = true 
  enable_logging                          = true 
  firmware                                = "efi" 

  memory                                  = 8192 
  nested_hv_enabled                       = true
  num_cpus                                = 2
  num_cores_per_socket                    = 2
  sata_controller_count                   = 1
  scsi_type                               = "lsilogic-sas"
  tags                                    = []
  vbs_enabled                             = true
  vvtd_enabled                            = true

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    keep_on_remove   = true
    label = "disk0"
    size  = 250

  }
  cdrom {
    client_device = true
  }

 clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    timeout = 50
    customize {
      windows_options {
        computer_name = "${var.vmprefix}${count.index + 1}"
        admin_password = var.domain_admin_password
        join_domain           = var.windomain
        domain_admin_user     = var.domain_admin_user
        domain_admin_password = var.domain_admin_password
        organization_name     = var.orgname
        auto_logon = true
        auto_logon_count = 1
        run_once_command_list = [
            "cmd.exe /C Powershell.exe -executionpolicy bypass -file c:\\temp\\test.ps1 -user SA-DSP_AutoVM",
        ]
      }
     network_interface {}      
    }
  }
 ``` 

##  Datastore Screenshot

![image](https://user-images.githubusercontent.com/29676864/146053073-c76416ee-77d7-4c8a-87d3-5f5162d2f90b.png)

**Comment by tenthirtyam** [comment]
Hi @gitprady - I'm not observing this issue with the following:

- Terraform `v1.11.0`
- Terraform Provider for VMware vSphere `v2.0.2`
- vCenter Server `v7.0.3.00100`

Below is an animated GIF of a simple reproduction that uses a CentOS 8 template, an NFS datastore, and guest customization based on VMware Tools.

![gh-1536](https://user-images.githubusercontent.com/7771363/146088064-9455860b-0153-49fe-b8b5-75da443e50f0.gif)

Ryan

**Comment by gitprady** [comment]
Many thanks Ryan for quick reply.

We are not using NFS storage, will come back to you shortly with full details of storage type.

**Comment by tenthirtyam** [comment]
I also tested on local and vSAN (all-flash) earlier w/o issues.

Ryan

**Comment by tenthirtyam** [comment]
Hi @gitprady - check-in to see if you had any update on the storage type and if this issue is still being seen.

Ryan

**Comment by tenthirtyam** [comment]
Hi @gitprady - check-in to see if you had any update on the storage type and if this issue is still being seen.

Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as `pending-closure` based on [previous comment](https://github.com/hashicorp/terraform-provider-vsphere/issues/1536#issuecomment-994096944) during reproduction attempts on local, NFS, and vSAN.  

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the comments provided earlier in the thread.

If the issue persists with the latest version of the provider, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware
