### ISSUE TITLE
Unclear documentation deploying ovf

### ISSUE THREAD

**Issue by per-lind** [hashicorp/terraform-provider-vsphere#1538]
### Affected Resource(s)

- `vsphere_virtual_machine`

### Actual Behavior
 As a new user of the the vsphere provider it is unclear what paramters that need to be set and what is actually imported from the ovf template.

This tells me that basiclly I should make sure all settings are manually set.

Using the OVF/OVA to deploy virtual machines can result in situations where the resulting VM does match what's specified in the OVF specification because the provider will attempt to apply its own settings on top of that. For example if memory is not set in a vsphere_virtual_machine resource, then terraform will assume that it has to apply the default. There are also cases where the hardware specifications may not be applicable and changes need to be made. The way to work around these cases is to use the vsphere_ovf_vm_template data source that will parse the OVF template and export the settings as outputs, that are then passed as parameters to the vsphere_virtual_machine resource. Please note that the parameters to ovf_deploy are still required, in order for vSphere to do the actual deployment, as shown in the example below:
https://github.com/hashicorp/terraform-provider-vsphere/blob/632f1562c35badcb70771bda0529b2b4b6d80214/website/docs/r/virtual_machine.html.markdown?plain=1#L321

But this one tells me it is not necessary
The ovf_deploy block can be used to create a new virtual machine from an ovf/ova template either from local system or remote URL. While deploying, the VM properties are taken from ovf and setting them in configuration file is not necessary.
The `ovf_deploy` block can be used to create a new virtual machine from an ovf/ova
https://github.com/hashicorp/terraform-provider-vsphere/blob/632f1562c35badcb70771bda0529b2b4b6d80214/website/docs/r/virtual_machine.html.markdown?plain=1#L1433

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by tenthirtyam** [comment]
Please take a look at the proposed changes submitted in PR #1513 that helps to clarify and provide newer examples.

https://github.com/hashicorp/terraform-provider-vsphere/pull/1513/files

Ryan
