### ISSUE TITLE
Virtual Machine MoRef in Data Source and Virtual Machine Snapshot Data Source

### ISSUE THREAD

**Issue by adarobin** [hashicorp/terraform-provider-vsphere#1540]
### Description

I am working on a Terraform provider for [VMware Horizon](https://github.com/umich-vci/terraform-provider-horizon) so that I can automate desktop pool creation in our environment. As a part of that, I need to be able to get the managed object reference of both a virtual machine and a snapshot.  The virtual machine datasource does not expose the moref and there is no data source for virtual machine snapshots.

I can submit a PR for this, though I'm not too experienced with writing tests.

### Potential Terraform Configuration

```hcl
data "vsphere_datacenter" "dc" {
  name = "dc1"
}

data "vsphere_virtual_machine" "image" {
  name          = "vdi-image"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine_snapshot" "snapshot" {
  virtual_machine_uuid = data.vsphere_virtual_machine.image.id
  snapshot_name        = "Snapshot Name"
}

resource "horizon_desktop_pool_automated" "pool" {
  // not the full resource, just here to illustrate how i'd use the moref from the virtual machine
  parent_vm_id = data.vsphere_virtual_machine.image.moref
  base_snapshot_id = data.vsphere_virtual_machine_snapshot.snapshot.id
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @adarobin, I would recommend splitting this to two related enhancement issues to be tracked individually.

Perhaps we could arrange and discuss the creation of the test cases with @appilon?

Ryan

**Comment by adarobin** [comment]
@tenthirtyam Horizon exposes those values with APIs so I ended up implementing data sources in my provider. If you aren’t managing the resources with the vSphere provider then using the data source in my Horizon provider probably makes more sense as you won’t have to auth to vCenter.

I do have a PR I could submit for the vm data source - the amount of code was trivial and the tests should be easy to extend.

**Comment by tenthirtyam** [comment]
Sounds good, Adam. Let us know if you want to submit a pull request and even if you like to have a discussion beforehand.

Have a great weekend and thanks for being a member of the provider community.

Ryan

**Comment by tenthirtyam** [comment]
Hi Adam! 👋 

I wanted to sync back with you and see if you are still interested in contributing the support based your [fork](https://github.com/adarobin/terraform-provider-vsphere) and branch (`vm-datasource`)

If so, perhaps @appilon can assist with test cases?

Thanks!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Hi Adam! 👋 

I wanted to sync back with you and see if you are still interested in contributing the support based your [fork](https://github.com/adarobin/terraform-provider-vsphere) and branch (`vm-datasource`)

If so, perhaps @appilon can assist with test cases?

Thanks!

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
