### ISSUE TITLE
Operating System not found, while launching vsphere vm using terraform

### ISSUE THREAD

**Issue by godgiftedme** [hashicorp/terraform-provider-vsphere#1547]
Getting error when I launched VM stating operating system not found. And in CMD its showing "timeout waiting for available ip address"
VM is launched successfully.
Please guide.

**```
data "vsphere_datacenter" "dc" {
  name = "ICEE"
}

data "vsphere_datastore" "datastore" {
  name          = "DS0004"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = "10.206.2.155/Resources"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = "Clone2VM"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "iso_datastore" {
  name          = "DS00001"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "terraformtestvm" {
  name             = "CloneVMnew"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus                   = 2
  memory                     = 2048
  guest_id                   = data.vsphere_virtual_machine.template.guest_id
  wait_for_guest_net_timeout = 0
  scsi_type                  = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  cdrom {
    datastore_id = data.vsphere_datastore.iso_datastore.id
    path         = "DS00001 / SW_DVD9_Win_Server.ISO"
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = false
    thin_provisioned = true
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
}
```**

**Comment by tenthirtyam** [comment]
Is your originating template is using EFI and EFI Secure Boot? If so, you'll need to set this to return the configuration from the data source.

```hcl
resource "vsphere_virtual_machine" "terraformtestvm" {
  # ... other configuration...
  firmware = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  # ... other configuration...
}
```

Without specifying this configuration, the default is BIOS and would lead to **OS Not Found** if the template uses EFI.

Ryan

**Comment by godgiftedme** [comment]
Solved. Thanks @tenthirtyam 
I have a new issue. Take a look if you get time.
Thanks
