### ISSUE TITLE
Destroy tries to delete the folder first and fails

### ISSUE THREAD

**Issue by vajeen** [hashicorp/terraform-provider-vsphere#1552]
When terraform destroy is called, it tries to destroy the vm folder first and after destroying the VMs, it throws an error saying 
"Error: folder is not empty, please remove all items before deleting"

Here's the complete output
![tf_error](https://user-images.githubusercontent.com/29272725/149344199-2c3a0e73-654d-4d6c-b2e6-88c8cab3ebaa.JPG)

**Comment by tenthirtyam** [comment]
Is the creation of the `vm_folder` resource derived from the same plan? If so, are there other objects contained within the folder that are not managed by the plan?

If there are other objects within the folder object that are not managed by the plan, this would be one reason for this to correctly occur.

If may be good to provided a redacted view of your plan.

Ryan

**Comment by vajeen** [comment]
Yes. creation of the vm_folder resource is derived from the same plan. Only created one VM along with the folder

**Comment by tenthirtyam** [comment]
Is there a depends_on included in you plan config? Can you share a redacted copy of your configuration?

**Comment by doumhfr** [comment]
can you post your terraform code ? Are you sure you define the folder in the vm as a terraform object (data or resource) and not just a name ?

**Comment by tenthirtyam** [comment]
Hi @vajeen,

Checking in to see if you had any update on the plan, if any `depends_on` was included, and if this issue is still being seen.

I suspect the issue is related to the dependency not being set in the plan.

Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the comments and solution (use of `depends_on = [ ]`)provided earlier in the thread.

If the issue persists with the latest version of the provider, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware
