### ISSUE TITLE
Existing `vsphere_virtual_machine` resources are getting destroyed while provisioning new `vsphere_virtual_machine` resources

### ISSUE THREAD

**Issue by godgiftedme** [hashicorp/terraform-provider-vsphere#1556]
### Previous instances getting destroyed while launching new instances. 

```hcl
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server
  # If you have a self-signed cert
  allow_unverified_ssl = true
}
#Data Sources
data "vsphere_datacenter" "dc" {
  name = var.dc
}

data "vsphere_resource_pool" "pool" {
  name          = var.pool
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Retrieve datastore information on vsphere
data "vsphere_datastore" "datastore" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Retrieve network information on vsphere
data "vsphere_network" "network" {
  name          = var.network
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Retrieve template information on vsphere
data "vsphere_virtual_machine" "template" {
  name          = var.templet
  datacenter_id = data.vsphere_datacenter.dc.id
}
#Virtual Machine Resource
resource "vsphere_virtual_machine" "vmachine2" {
  count                      = var.Server_parameter["count"]
  name                       = "${var.Server_parameter["hostname"]}-${count.index + 1}"
  resource_pool_id           = data.vsphere_resource_pool.pool.id
  datastore_id               = data.vsphere_datastore.datastore.id
  num_cpus                   = var.Server_parameter["vcpu"]
  memory                     = var.Server_parameter["ram"]
  guest_id                   = data.vsphere_virtual_machine.template.guest_id
  scsi_type                  = data.vsphere_virtual_machine.template.scsi_type
  firmware                   = var.Server_parameter["firmware"]
  wait_for_guest_net_timeout = 0
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = "e1000"
  }
  disk {
    label            = "${var.Server_parameter["hostname"]}.vmdk"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      windows_options {
        computer_name  = "${var.Server_parameter["hostname"]}-${count.index + 1}"
        admin_password = var.Server_parameter["admin_password"]
      }
      network_interface {
        ipv4_address = ""
        ipv4_netmask = 24
      }
      ipv4_gateway = ""
    }
  }
}
```

Also, when windows vms are launched, they are launching successfully, but at the end getting a timeout error.

VM customization failed
Timeout waiting for customization

**Comment by tenthirtyam** [comment]
@godgiftedme, could you please format the  code above using the markdown tools for better readability? Thanks!

**Comment by godgiftedme** [comment]
Sure

[Vsphere terraform.txt](https://github.com/hashicorp/terraform-provider-vsphere/files/7904621/Vsphere.terraform.txt)

**Comment by tenthirtyam** [comment]
Based upon initial description, are you editing the **same** plan file as the previous to add the new instances or are you creating a new olan? If the former, yes, that would delete the other instances as Terraform seems to reach the desired state of the plan.

Also, I recommend the use of for_each vs count.

Ryan

**Comment by tenthirtyam** [comment]
https://www.freecodecamp.org/news/how-to-format-code-in-markdown/

**Comment by godgiftedme** [comment]
Hi Ryan

Thanks for the quick reply. 
I will describe the issue in detail.
I launched 5 VMs through terraform and it launched successfully. 
Next again I tried to launch 10 VMs but this time, its deleting those 5 previous VMs on Vsphere and then will launch new VMs. 

Also, I am getting an error at end, that says 
Virtual Machine customization failed
timeout waiting for customization to complete.

![image](https://user-images.githubusercontent.com/68272525/150331565-b5f421b6-1518-4fb3-b7bd-c7f607ee882e.png)

**Comment by godgiftedme** [comment]
Yes, I am editing the same file

**Comment by tenthirtyam** [comment]
Are you **adding** to the server parameters variables or deleting and adding new information to the variables and reusing it for a new set of workloads?

If you are editing and reusing the same plan for deployment new workloads Terraform would compare the tfstate and plan and seek to ensure desired state. Thus, it would resolve to deleting the prior since they are in the tfstate but not the updated plan.

**Comment by godgiftedme** [comment]
Great, Thanks for the help. 
What about the error, I am getting?
Do you have any idea about that?

Thanks
Abhishek

**Comment by tenthirtyam** [comment]
Hard to tell it you are trying to configure DHCP or static based on your stanza which is not fully configured.

```hcl
network_interface {
   ipv4_address = ""
   ipv4_netmask = 24
}
ipv4_gateway = ""
}
```

If DHCP, remove these. If static, configure this fully.

This is probably where guest customization is having issues.

Ryan

**Comment by tenthirtyam** [comment]
Hi @godgiftedme, checking in to see if the above resolved you issue.

Ryan

**Comment by tenthirtyam** [comment]
Hi @godgiftedme, checking in to see if the above resolved you issue.

Ryan

**Comment by godgiftedme** [comment]
Hi Ryan, I am receiving an error while launching the vms. Vms are created successfully but a new error occurred

 POST https://<ip>/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 401 Unauthorized

Can you help me with this. 
When creating VMs more than 10 this error comes.

**Comment by tenthirtyam** [comment]
Te above message appears to indicate that the user the provider is running under does not have privileges to view (read) the vSphere tags.

**Comment by godgiftedme** [comment]
I am not trying to view the tags. How can I rectify this error?

**Comment by tenthirtyam** [comment]
However, the provider would read the tags for the `vsphere_virtual_machine` resources.

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the comments earlier in the thread.

If the issue persists with the latest version of the provider, please open a new issue and reference this originating issue.

**Ryan Johnson**
Staff II Solutions Architect, VMware
