### ISSUE TITLE
Add support for setting root password in Linux customization

### ISSUE THREAD

**Issue by greeneg** [hashicorp/terraform-provider-vsphere#1557]
### Description

Currently, cloning Windows instances can have a dynamically created customization spec applied that allows setting the Administrator password. VMware's own vRealize product can do this for Linux as well. Can we please get a way of doing so on clone of Linux instances?

### Potential Terraform Configuration

Much like the Windows Options section, we could have something like this:

```hcl
customize {
  linux_options {
    root_password: var.root_pass
  }
}
```

**Comment by tenthirtyam** [comment]
There is an **upstream dependency** on vSphere to support this enhancement.

Linux guest customizations in vSphere would need to support the ability to configure the default `root` password similar to how Windows guest customizations in vSphere supports changing the default `administrator` password. This does not exist today.

As an alternative, the provider could add a customization script option (as seen in Linux guest customizations) to the `linux_options` _(similar to the `run_once_command_list` within `windows_options`)_  to allow you to  programmatically set the password. For example, hypotectically use the Terraform Provider for Vault to pass generate/receive the secret and pass to the script.

Of course, for Linux, you could also transition from guest customization to cloud-init based deployments where this can be set. cloud-init 21.3 now has the `VMware` datasource.

Ryan

cc @appilon

**Comment by tenthirtyam** [comment]
Similar to #1385 in terms of potential enhancement (customization script) and use of cloud-init.
