### ISSUE TITLE
Add support for distributed switch membership as a `vsphere_host` resource argument

### ISSUE THREAD

**Issue by heitmanr** [hashicorp/terraform-provider-vsphere#1564]
### Description

Right now, each ESXi-Host participating in a DVS is
* configured in HCL to "be part of the DVS"

The ability to configure this in a different way in HCL:
* make the DVS-Membership a property of the ESXi-Host.
would enable dynamic "creation" of ESXi-Hosts [add them to vCenter/Cluster etc] and afterwards to the DVS:
* without having to change the DVS-Setup.

This DVS-Setup is absolutely static right now, I didn't figure out a way to use a data-structure, List etc. to add ESXi-Hosts to a DVS.

```HCL
resource "vsphere_distributed_virtual_switch" "dvs-v" {
  name = "CL1V"
  datacenter_id   = vsphere_datacenter.nested_datacenter["DC"].moid
  version = "6.5.0"
...
  host {
    host_system_id = vsphere_host.nested_hosts["esx-11-v"].id
    devices        = var.network_interfaces
  }
  host {
    host_system_id = vsphere_host.nested_hosts["esx-12-v"].id
    devices        = var.network_interfaces
  }
}
```

### Potential Terraform Configuration

I'd suggest the same configuration-logic, which is possible with ESX-Host-to-Cluster-Assignments, too:
* boolean-flag "host_managed" within the DVS-Object
* reference within each host towards it's DVS

```HCL
resource "vsphere_distributed_virtual_switch" "dvs-v" {
  name = "CL1V"
  datacenter_id   = vsphere_datacenter.nested_datacenter["DC"].moid
  version = "6.5.0"
...
  host_managed = true
}
```

```HCL
resource "vsphere_host" "nested_hosts" {
  for_each = var.esxhosts

  hostname = cidrhost(var.mgmt_lans[each.value.oob_lan].subnet, each.value.oob_host_id)
  username = "root"
  password = var.vesx_rootpassword
  cluster  = vsphere_compute_cluster.nested_cluster[each.value.cluster].id
  connected = true
  thumbprint = data.vsphere_host_thumbprint.nested_hosts[each.key].id

  dvs = { 
              dvs_id = vsphere_distributed_virtual_switch.dvs_v.id
              devices = var.network_interfaces
  }
}

variable "network_interfaces" {
  default = [
    "vmnic1",
    "vmnic2",
  ]
}
```

### References

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/distributed_virtual_switch

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@heitmanr, can you share some additional rationale and context for this additional configuration path. 

For example, is the goal to allow for different vmnics to be used on a per host level when there is a vendor or hardware mismatch within a cluster or across clusters?

Ryan
