### ISSUE TITLE
Documentation: vsphere_distributed_port_group - "vlan_range"-property is not documented

### ISSUE THREAD

**Issue by heitmanr** [hashicorp/terraform-provider-vsphere#1565]
### Description

The Property
- vlan_id

is documented, but

- vlan_range

not.

It's working fine for me - I hope, this is expected and only the doc's might need the vlan_range get mentioned!?

### Working Terraform Configuration

```hcl

resource "vsphere_distributed_port_group" "pg" {

  name                            = "PG-all-VLAN"
  distributed_virtual_switch_uuid = "${vsphere_distributed_virtual_switch.dvs.id}"

  #vlan_id = 0
  vlan_range {
         min_vlan = 0
         max_vlan = 4094
       }
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Hi @heitmanr, I believe that this is well documented in the below for `vsphere_distributed_switch`:

https://github.com/hashicorp/terraform-provider-vsphere/blob/01f0f19481abdfd709df066f4dddb6b9405f8a82/website/docs/r/distributed_virtual_switch.html.markdown?plain=1#L303-L320

Which appears in https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/distributed_virtual_switch as the below:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/7771363/151828654-55f24e5f-a42e-4297-899f-215604743fcb.png">

I assume you are referring to an update for the `vsphere_distributed_port_group` resource instead?

Ryan

**Comment by heitmanr** [comment]
yes, you're right - my fault - the title of my note should have been "vsphere_distributed_port_group" not "VDS/Distributed-Switch".

**Comment by tenthirtyam** [comment]
@heitmanr, would you mind updating the issue title so that we can best track an update to the docs?
