### ISSUE TITLE
Dynamically add `disk { }` to `vsphere_virtual_machine` resource when cloning from template

### ISSUE THREAD

**Issue by NitishGupta9282** [hashicorp/terraform-provider-vsphere#1574]
Hi 
    i want to create a vm using template on vsphere. My requirement is that if a template has 2 disks then terraform automatically add disk1 to my configuration or if there is only one disk in template then it stick to disk0. how can i do this configuration?

**Comment by NitishGupta9282** [comment]
Here is my code:-

provider "vsphere" {
#  version        = "1.15.0"
  user           = "${var.username}"
  password       = "${var.password}"
  vsphere_server = "vcenter-noids.gemalto.com"
  allow_unverified_ssl = true
}

# The Data sections are about determining where the virtual machine will be placed.
# Here we are naming the vSphere DC, the cluster, datastore, virtual network and the template
# name. These are called upon later when provisioning the VM resource

data "vsphere_datacenter" "dc" {
  name = "testdc"
}

data "vsphere_datastore" "datastore" {
  name        = "testds"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_resource_pool" "pool" {
  name          = "test.lab.local/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "Template_RHEL"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# The Resource section creates the virtual machine, in this case
# from a template

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform_automation"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${data.vsphere_virtual_machine.template.num_cpus}"
  memory   = "${data.vsphere_virtual_machine.template.memory}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
  co

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  
  disk {
    label            = "disk1"
    size             = "${data.vsphere_virtual_machine.template.disks.1.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.1.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.1.thin_provisioned}"
    unit_number      = 1
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "test"
        domain    = "test.internal"
      }
      network_interface {}
    }
  }
}


# Finally, we're outputting the IP address of the new VM

output "my_ip_address" {
 value = "${vsphere_virtual_machine.vm.default_ip_address}"
}

**Comment by tenthirtyam** [comment]
Add an additional `disk {}` stanza to get he resource.

**Comment by NitishGupta9282** [comment]
How can you explain ....it is very important plsh guide me to resolve this ?

**Comment by NitishGupta9282** [comment]
I am getting this error

**Comment by NitishGupta9282** [comment]
╷
│ Error: Missing required argument
│
│   on main.tf line 65, in resource "vsphere_virtual_machine" "vm":
│   65:   disk {}
│
│ The argument "label" is required, but no definition was found.

**Comment by tenthirtyam** [comment]
``` hcl
disk {
 #... config
}

disk {
 #... config
}

```

**Comment by NitishGupta9282** [comment]
I am getting this error  
The argument "label" is required, but no definition was found.

**Comment by tenthirtyam** [comment]
Documentation: `vsphere_virtual_machine` [Disk Options](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#disk-options)

**Comment by NitishGupta9282** [comment]
Here is my new code:-

```
provider "vsphere" {

  user           = "${var.username}"
  password       = "${var.password}"
  vsphere_server = "vcenter-test.com"
  allow_unverified_ssl = true
}
data "vsphere_datacenter" "dc" {
  name = "testdc"
}

data "vsphere_datastore" "datastore" {
  name        = "testds"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_resource_pool" "pool" {
  name          = "test.lab.local/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "Template_RHEL"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform_automation"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${data.vsphere_virtual_machine.template.num_cpus}"
  memory   = "${data.vsphere_virtual_machine.template.memory}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
  co

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    .....    #config
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "test"
        domain    = "test.internal"
      }
      network_interface {}
    }
  }
}

output "my_ip_address" {
 value = "${vsphere_virtual_machine.vm.default_ip_address}"
}

**Comment by tenthirtyam** [comment]
Please refer to the documentation linked above. There is an abridged example and information regarding the required and optional arguments.

Ryan

**Comment by tenthirtyam** [comment]
It covers the scenario. Please look for the Disk Options portion. There you will see the below **abridged** example and the all required and optional arguments.

`resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ...
  disk {
    label       = "disk0"
    size        = "10"
  }
  disk {
    label       = "disk1"
    size        = "100"
    unit_number = 1
  }
  # ... other configuration ...
}`

**Comment by NitishGupta9282** [comment]
I  know how to configure disks ... my requirement is that if i select a new template in which 3 hard disk is connected then i dont want to come to terraform script again and define another disk .. it should be added automatically .. may it should be done with dynamic blocks but i am not able to crack the correct syntax.. thats why i come here ....

**Comment by tenthirtyam** [comment]
Yes, a dynamic block for `disk` with a `for each` on a would be a valid path that would allow you to simply provide the data in your vars, with an object map for example.

**Comment by NitishGupta9282** [comment]
Plsh provide me the configuration of that block ?

**Comment by tenthirtyam** [comment]
Take a look at this [community module structure ](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/master/main.tf)for an immediate example of how it can be done with a more elaborate dynamic block.

The could be vastly simplified based on your personal use case or scenario.

**Comment by tenthirtyam** [comment]
Marking as `pending-closure`. 

Please comment if the dynamic block example sed in the [community module](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/master/main.tf) did not help.

**Comment by Tigershark2005** [comment]
This is how I did it:
`dynamic "disk" {
    for_each = var.vsphere_disks
    content {
        label = "disk${disk.value["number"]}"
        size = disk.value["size"]
        unit_number = disk.value["number"]
    }
}`
This lets you send in as many disks as you want to your module. What I send in is:
`vsphere_disks = [
    {
        number = 0
        size = 75
    },
    {
        number = 1
        size = 100
    }
]`

Now here's the issue with that, there seems to be a bug in the vsphere provider or something because any disk after the first gets added to the VM but then doesn't get its attributes set correctly. The size is 0MB and the provisioning type is wrong. When I look at my plan before applying everything is correct, size, type, everything. It tries to create it exactly as expected, it just doesn't come out that way in vCenter.

**Comment by tenthirtyam** [comment]
Marking this issue as closed based on the previous comments and suggested solutions.

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
