### ISSUE TITLE
Update `master` branch to `main`  

### ISSUE THREAD

**Issue by iBrandyJackson** [hashicorp/terraform-provider-vsphere#1584]
Update `master` branch to `main`  as per our company initiative: https://discuss.hashicorp.com/t/inclusive-language-changes/12797

**Comment by tenthirtyam** [comment]
Very minor post change updates needed to links with the following:

`https://github.com/hashicorp/terraform-provider-vsphere/blob/master/`. 

Simple search/replace. 🙃 

Ryan

**Comment by iBrandyJackson** [comment]
ℹ️  
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

> After we rename the branch, any collaborator with a local clone of the repository will need to update the clone.
> 
> From the local clone of the repository on a computer, run the following commands to update the name of the default branch.
> 
> ```
> $ git branch -m OLD-BRANCH-NAME NEW-BRANCH-NAME
> $ git fetch origin
> $ git branch -u origin/NEW-BRANCH-NAME NEW-BRANCH-NAME
> $ git remote set-head origin -a
> ```
> Optionally, run the following command to remove tracking references to the old branch name.
> 
> `$ git remote prune origin`

**Comment by appilon** [comment]
The plan moving forward is to perform release of `v2.1.0` of the provider in the near future using our legacy release pipeline. After which we will port this provider the new release methods which use a custom [github action](https://github.com/hashicorp/ghaction-terraform-provider-release/) and [goreleaser](https://goreleaser.com/), as well as switch the branch name to `main`.

I have pinned this issue for some increased visibility and linked to our discuss post which outlines the initiative.
