### ISSUE TITLE
`r/vsphere_nas_datastore` not mounted to additional hosts as day-two

### ISSUE THREAD

**Issue by rutgerblom** [hashicorp/terraform-provider-vsphere#1589]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.1.4

### Terraform Provider

v2.0.2

### VMware vSphere

7.0.3

### Description

Adding additional ESXi hosts to the "host_system_ids" does not result in the datastore being mounted on the additional ESXi hosts. First after I unmount the datastore, remove the terraform state for the resource, and let terraform provision the datastore again, it is mounted to all hosts defined under ""host_system_ids". 

### Affected Resources

resource/vsphere_nas_datastore

### Terraform Configuration

```
variable "all_esxi_hosts" {
    default = [
        "esxi01.sddc.lab",
        "esxi02.sddc.lab",
        "esxi03.sddc.lab" <--- newly added host
    ]
}

data "vsphere_host" "all_esxi_hosts" {
  count         = "${length(var.all_esxi_hosts)}"
  name          = "${var.all_esxi_hosts[count.index]}"
  datacenter_id = "datacenter-1018"
}

resource "vsphere_nas_datastore" "ds15" {
  name              = "ds15"
  host_system_ids   = data.vsphere_host.all_esxi_hosts.*.id
  remote_hosts      = "192.158.1.10"
  remote_path       = "/ds15"
}
```

### Expected Behavior

The datastore being mounted on the additional hosts.

### Actual Behavior

The datastore is not mounted on the additional hosts.

### Steps to Reproduce

The datastore is not mounted on the additional host.

**Comment by tenthirtyam** [comment]
Have you tried it similar to the following example:

https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-storage-nfs-datastore

Ryan

**Comment by tenthirtyam** [comment]
It's quite possibly a bug, or an implementation details of the original developers did not consider.

Let us know the results and we will prioritize as a bug or enhancement if that's the case.

Ryan

**Comment by rutgerblom** [comment]
> It's quite possibly a bug, or an implementation details of the original developers did not consider.
> 
> Let us know the results and we will prioritize as a bug or enhancement if that's the case.
> 
> Ryan

I tried using the "for each" method you suggested but the result is the same. Terraform applies the changes in its state but nothing happens. The next time I run terraform plan/apply it wants to commit the same changes again. 
It doesn't look like the vCenter API is contacted when running this or at least there is nothing in the hosts' event logs that indicates something is happening.

Thank you.

Rutger

**Comment by tenthirtyam** [comment]
Hi Rutger,

I think I see the issue and will try and get some time next week to provide a working example that addressed the concern. If so, I'll PR the docs and update that as well. Stay tuned.

Ryan

**Comment by rutgerblom** [comment]
Hi Ryan,

That sounds promising. Thanks for taking the time to look into this.

Rutger

Den lör 5 mars 2022 kl 01:47 skrev Ryan Johnson ***@***.***>:

**Comment by tenthirtyam** [comment]
👋 Hi @rutgerblom - just an FYI that I haven't forgotten about this and started to review the code today.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by rutgerblom** [comment]
Thanks Ryan. Appreciate the effort you put into this.

Rutger

tis 22 mars 2022 kl. 02:24 skrev Ryan Johnson ***@***.***>:
