### ISSUE TITLE
Unable to create exact clone of Windows template

### ISSUE THREAD

**Issue by NitishGupta9282** [hashicorp/terraform-provider-vsphere#1591]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.1.4

### Terraform Provider

2.0.2

### VMware vSphere

7.0.3.00100

### Description

Hi 

I have one template of Window Server 2016. I want to Create a vm using this template from terraform script..  I have seen that the vm which is created from this template doesnt have any files which is present in the template and i am able to login without Administrator password in the VM...I am attaching my windows script for your reference.

### Affected Resources

'resource/vsphere_virtual_machine'

### Terraform Configuration

```hcl
provider "vsphere" {
  vsphere_server = "xxxxxxxxxx"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "DS_TEST"
}

data "vsphere_datastore" "datastore" {
  name        = "DS-SSD"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_resource_pool" "pool" {
  name          = "ds-esxi.lab.local/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "DevOps_WIndows_Template"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform_automation_Windows"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus = "${data.vsphere_virtual_machine.template.num_cpus}"
  memory   = "${data.vsphere_virtual_machine.template.memory}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  firmware = "${data.vsphere_virtual_machine.template.firmware}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
        label = "disk0"
        size = "${data.vsphere_virtual_machine.template.disks.0.size}"
        eagerly_scrub = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
        thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
 }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    timeout = 60
    customize {
     windows_options {
       computer_name = "test1"
       full_name     = "test1.local"
      }
     network_interface {}
    }
  }
}

```

### Expected Behavior

Created VM should be the exact replica of template and I can able to access using Administrator password

### Actual Behavior

Created VM from template doesnt have files created on template

**Comment by tenthirtyam** [comment]
Hi @NitishGupta9282,

If you want the machine to be a direct clone and not customized, run without the following stanza in the resource:

```
customize {
  windows_options {
    computer_name = "test1"
    full_name = "test1.local"
}
```

This will skip machine prep and just clone.

When you say the file are not present, are these from another disk? If there are more than one disk you'll need to add a disk stanza for each.

Ryan

**Comment by tenthirtyam** [comment]
It's the same as using a customization specification directly in vSphere as it runs the system through a SysPrep. 

For files that may need to be retained on each clone, I'd recommend placing these in a location other than the default administrator user profile.

Ryan

**Comment by NitishGupta9282** [comment]
Ok ...Thank You for your help.
