### ISSUE TITLE
Unable to configure a vmk port for vSAN

### ISSUE THREAD

**Issue by zkzqzk** [hashicorp/terraform-provider-vsphere#1593]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

Terraform v1.1.5

### Terraform Provider

v2.0.2

### VMware vSphere

v7.03

### Description

below configuration won't work. so not able to create vmkernal port with vsan enabled.

```hcl
resource "vsphere_vnic" "vsan" {
  host                    = vsphere_host.host.id
  distributed_switch_port = vsphere_distributed_virtual_switch.dvs.id
  distributed_port_group  = vsphere_distributed_port_group.pg.id
  ipv4 {
    dhcp = true
  }
  netstack = "vsan"
}
```

error is :

```console
│ Error: ServerFaultCode: vim.fault.NotFound
│
│   with vsphere_vnic.vsan[0],
│   on main.tf line 69, in resource "vsphere_vnic" "vsan":
│   69: resource "vsphere_vnic" "vsan" {
```

### Affected Resources

`r/vsphere_vnic`

### Terraform Configuration

```hcl
resource "vsphere_vnic" "vsan" {
host = vsphere_host.host.id
distributed_switch_port = vsphere_distributed_virtual_switch.dvs.id
distributed_port_group = vsphere_distributed_port_group.pg.id
ipv4 {
dhcp = true
}
netstack = "vsan"
}
```

### Panic Output

```console
│ Error: ServerFaultCode: vim.fault.NotFound
│
│   with vsphere_vnic.vsan[0],
│   on main.tf line 69, in resource "vsphere_vnic" "vsan":
│   69: resource "vsphere_vnic" "vsan" {
```

### Expected Behavior

expected to create a vmk port in vSphere with VSAN service enabled

### Actual Behavior

give an error

```console
│ Error: ServerFaultCode: vim.fault.NotFound
│
│   with vsphere_vnic.vsan[0],
│   on main.tf line 69, in resource "vsphere_vnic" "vsan":
│   69: resource "vsphere_vnic" "vsan" {
```

### Steps to Reproduce

example not working configuration:

```hcl
resource "vsphere_vnic" "vsan" {
  host                    = vsphere_host.host.id
  distributed_switch_port = vsphere_distributed_virtual_switch.dvs.id
  distributed_port_group  = vsphere_distributed_port_group.pg.id
  ipv4 {
    dhcp = true
  }
  netstack = "vsan"
}
```

**Comment by tenthirtyam** [comment]
Hi, @zkzqzk!

Please format your configuration(s) and place it in the **Terraform Configuration** section of the issue form. Please also format any outputs placing these in the requested sections.

Learn more about [Code Formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by zkzqzk** [comment]
Hi Ryan,

I have place the configuration and output to the corresponding filed.

Actually, it may not be an issue itself as vSAN is an option of “Enabled services” instead of “TCP/IP stack” which map to netstack in the terraform configuration.

Currently, I don’t see how we can configure the “enabled services” in terraform.  I think it is a reasonable requirement to enable services on VMK port.


***@***.***

Regards,

Ken
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by tenthirtyam** [comment]
Your configurations and messages are still not formatted. I'll edit your issue text.

**Comment by tenthirtyam** [comment]
Your issue content has been updated.

**Comment by tenthirtyam** [comment]
re: `netstack = "vsan"`

This is the reason for the error.

Values supported for `netstack` (TCP/IP stack) the currently include: 'defaultTcpipStack', 'vmotion', and 'provisioning'. vSAN does not have a dedicated stack.

https://github.com/hashicorp/terraform-provider-vsphere/blob/70388c72372f037287b3e642d95c84742549894a/vsphere/resource_vsphere_vnic.go#L264-L271

For enabling specific services on a vmk, please submit a detailed enhancement request for the provider.

Ryan

**Comment by zkzqzk** [comment]
Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
