### ISSUE TITLE
Add support to enable services on a vmk

### ISSUE THREAD

**Issue by zkzqzk** [hashicorp/terraform-provider-vsphere#1594]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, it is not able to specify services in resource vsphere_vnic.

### Use Case(s)

enable vsan, iscsi, etc services on vmk port which are common operation tasks.

### Potential Terraform Provider Configuration
```hcl
resource "vsphere_vnic" "v1" {
  host                    = data.vsphere_host.h1.id
  distributed_switch_port = vsphere_distributed_virtual_switch.d1.id
  distributed_port_group  = vsphere_distributed_port_group.p1.id
  ipv4 {
    dhcp = true
  }
  enabled_services = ["vsan"]
}
```

**Comment by tenthirtyam** [comment]
Hi, @zkzqzk!

Please format your configuration(s) and place it in the **Potential Terraform Provider Configuration** section of the issue form. Learn more about [Code Formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by zkzqzk** [comment]
is it formatted better now?

**Comment by zkzqzk** [comment]
added, thanks.

**Comment by xeor** [comment]
Is there a known workaround for this? I want to add vsan to a vnic
