### ISSUE TITLE
Add support for ParaVirtualRDMA network interface adapter type

### ISSUE THREAD

**Issue by cspnanda** [hashicorp/terraform-provider-vsphere#1597]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support for ParaVirtualRDMA Adapter Type for VM. This is a very important adapter type for low latency high bandwidth communication. I am proposing

```
resource "vsphere_virtual_machine" "vm_terraform" {
....
network_interface {
    network_id = data.vsphere_network.network.id
    adapter_type = "vmxnet3vrdma"
}
....
}
```

### Use Case(s)

RDMA between VMs is known as Paravirtual RDMA. Introduced from vSphere 6.5, VMs with a PCIe virtual NIC that supports standard RDMA API can leverage PVRDMA technology. VMs must be connected to the same distributed virtual switch to leverage Paravirtual RDMA. This is very useful use case for HPC.

### Potential Terraform Provider Configuration

```
resource "vsphere_virtual_machine" "vm_terraform" {
....
network_interface {
    network_id = data.vsphere_network.network.id
    adapter_type = "vmxnet3vrdma"
}
....
}
```

**Comment by tenthirtyam** [comment]
⚠️ **Critical Reference**: https://github.com/vmware/govmomi/pull/2766

This requires introduction in upstream `vmware/govmomi` **first** and subsequent upgrade of the version used by this provider.

**Comment by tenthirtyam** [comment]
ℹ️ Related Issue(s)

- https://github.com/vmware/govmomi/issues/2765

cc @embano1

**Comment by tenthirtyam** [comment]
Depends on https://github.com/hashicorp/terraform-provider-vsphere/issues/1657.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
