### ISSUE TITLE
Add support for vTPM

### ISSUE THREAD

**Issue by damo2929** [hashicorp/terraform-provider-vsphere#1599]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

As vmware now has a native key provider so encryption via the TPM is now possible easily.
Would it be possible to add an option to include a vTPM module on the vm configuration when created so that the TPM can be used inside the VM.

 

### Use Case(s)

have an option on the vm hardware section to have
vTPM option to Include / not include  if not set then default to not include

when included terraform should add the machine device entries to the vm.

**Comment by tenthirtyam** [comment]
ℹ️ **Important information**:

- vTPM: vSphere 6.7 and later
- Native Key Provider: vSphere 7.0 Update 2 and later

**Comment by anbohm** [comment]
Any update on this request? Need the vTPM part also.

**Comment by tenthirtyam** [comment]
Hi @anbohm  - this enhancement is still a backlog item for the maintainers per the tagged milestone.

If you or another member of the community would like to contribute this enhancement, it can be picked up earlier.

**Comment by martinrohrbach** [comment]
Hi @tenthirtyam, will this be reassigned soon(tm)? Can you give us any update on this maybe?

**Comment by tenthirtyam** [comment]
> Hi @tenthirtyam, will this be reassigned soon(tm)? Can you give us any update on this maybe?

I unassigned if from myself since I currently don’t have the bandwidth to work on it at this in my personal time.

**Comment by JM2K69** [comment]
Any news about this Issue 😊

**Comment by burnsjared0415** [comment]
this is being worked, will send out a update as we find the solution
