### ISSUE TITLE
Debian guest OS type not usable

### ISSUE THREAD

**Issue by ZeikoFr** [hashicorp/terraform-provider-vsphere#1600]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.6

### Terraform Provider

v2.0.2

### VMware vSphere

v7.0.3

### Description

Same problem as here : https://github.com/hashicorp/terraform-provider-vsphere/issues/1523

I cannot use Debian 11 as a guest OS type. I encounter this error : 

```
Error: error sending customization spec: Customization of the guest operating system is not supported due to the given reason: 
│ 
│   with vsphere_virtual_machine.vm-one[0],
│   on main.tf line 60, in resource "vsphere_virtual_machine" "vm-one":
│   60: resource "vsphere_virtual_machine" "vm-one" {

```

But debian 10 and 11 are supported since vSphere 7 : https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf

### Affected Resources

vsphere_virtual_machine

### Terraform Configuration

```
data "vsphere_datacenter" "dc" {
  name = "DC-packer"
}

data "vsphere_resource_pool" "pool" {
  # If you haven't resource pool, put "Resources" after cluster name
  name          = "Cluster-packer/Resources"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "host" {
  name          = ""
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Retrieve datastore information on vsphere
data "vsphere_datastore" "datastore" {
  name          = "sds-mirror-packer-silver-01"
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Retrieve network information on vsphere
data "vsphere_network" "network" {
  name          = "dmz"
  datacenter_id = data.vsphere_datacenter.dc.id
}

# Retrieve template information on vsphere
data "vsphere_virtual_machine" "template" {
  name          = "debian-11-2022-02-16"
  datacenter_id = data.vsphere_datacenter.dc.id
}

#### VM CREATION ####

# Set vm parameters
resource "vsphere_virtual_machine" "vm-one" {
  count            = 1
  name             = "vm-${count.index + 1}"
  num_cpus         = 2
  memory           = 4096
  datastore_id     = data.vsphere_datastore.datastore.id
  host_system_id   = data.vsphere_host.host.id
  resource_pool_id = data.vsphere_resource_pool.pool.id
  guest_id         = data.vsphere_virtual_machine.template.guest_id
  scsi_type        = data.vsphere_virtual_machine.template.scsi_type
  firmware = data.vsphere_virtual_machine.template.firmware

  # Set network parameters
  network_interface {
    network_id = data.vsphere_network.network.id
  }

  # Use a predefined vmware template has main disk
  disk {
    label            = "disk0"
    size             = 14
  }
  disk {
    label            = "disk1"
    unit_number      = 1
    size             = 1
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      linux_options {
        host_name = "vm-${count.index + 1}"
        domain    = "test.internal"
      }

      network_interface {
      }

    }
  }
}
```

### Expected Behavior

The guest OS should be the same as my template : Debian GNU/Linux 11 (64-bit)

### Actual Behavior

I can't start a vm unless I use "otherLinux64bits"'

### Steps to Reproduce

Create a debian 11 vm with Debian GNU/Linux 11 (64-bit) guest OS => crash

### References

https://github.com/hashicorp/terraform-provider-vsphere/issues/1523

**Comment by tenthirtyam** [comment]
This is not an issue with the provider, but is instead an issue with guest customization of Debian on vSphere 7.

On [the link you posted](https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf) there is also a [link to a KB](https://kb.vmware.com/s/article/85845) for Debian. Which unfortunately is not public at this time. If you open a case with VMware Support the workaround noted in the KB is the same from the #1523 - using `otherLinux64bit`.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

--

KB is quoted as follows:

Workaround
1. Power-Off the VM

2.Edit VM settings, select "Linux" for option "Guest OS" and select "Other 4.x or later Linux (64-bit) / Other 4.x or
   later Linux (32-bit)" for option "Guest OS Version"
    example:

     Right click the VM and select "Edit Settings" ---> "VM Options" ----> "General Options"
     For option "Guest OS", select "Linux".
     For option "Guest OS Version", select "Other 4.x or later Linux (64-bit) / Other 4.x or later Linux (32-bit)"

3. Click "OK" to save the settings

4. Apply guest customization to the VM
