### ISSUE TITLE
Add support for applying existing customization specs to `r/virtual_machine`

### ISSUE THREAD

**Issue by tejavar** [hashicorp/terraform-provider-vsphere#1604]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Allow the ability to apply an existing virtual machine customization specification to `r/virtual_machine` during a cloning workflow.

### Use Case(s)

This would allow users to apply an existing customization specification during the creation of the virtual machine resource and simplify/reduce the amount of inline configuration needed for a virtual machine resource. 

Currently, we cannot utilize customization specifications that already exist within the vSphere inventory.

### References

Similar to the enhancement request made in GH-97.

**Comment by tenthirtyam** [comment]
The scope of implementation would need to cover the following:

- A resource for creating/importing customization specifications + passing passwords.
- A data source for returning the customization specification.
- How to address customization specifications that require user inputs that the current model allows, but which might be addressable with a blended model of the existing path with customization specification.
