### ISSUE TITLE
Add support in `r/vsphere_file` not to automatically inflate a .vmdk

### ISSUE THREAD

**Issue by rgaduput** [hashicorp/terraform-provider-vsphere#1605]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.2

### Terraform Provider

v2.0.2

### VMware vSphere

v6.7.0

### Description

We have VM disk files which were thin provisioned, whose size on Linux disk is about 2.5G, But actual size of the disk was about 150G. When we used `resource/vsphere_file` to copy the .vmdk file into a data store from my local linux machine, the size of the disk file getting inflated (like thick provisioned) into the actual size which is 150G and takes lot of time to copy.
I have one more disk (secondary, not bootable), whose file size is about 10MB. But after file upload to datastore its expanded into its true size 2.6TB. You can image how long it could take to copy such.
Why is this happening like this, how can i keep the disk files as thin provisioned even after copy ?

### Affected Resources

`resource/vsphere_file`

### Terraform Configuration

```
resource "vsphere_file" "acp_disk_upload" {
  datacenter       = var.vsphere_datacenter_name
  datastore        = var.vsphere_datastore_name
  source_file      = var.source_file_path
  destination_file = var.destination_file_path
}
```

### Expected Behavior

Disk file sizes to be remained as thin provisioned.

### Actual Behavior

Disk file sizes expanded into real size.

**Comment by tenthirtyam** [comment]
This is currently the expected behavior. The .vmdk is uploaded to a temporary path. Once the upload is completed, the .vmdk file is moved (L206-209) to the final destination, at which time it is inflated.

https://github.com/hashicorp/terraform-provider-vsphere/blob/8d9b7472ae1369156d2093498eacb13e57e8f91b/vsphere/resource_vsphere_file.go#L197-L209

Rather, an **enhancement** could be considered to investigate including a provisioning option.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Self-assigning this issue for pull request. I believe that I have a method to address this enhancement.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
The inflating of the file is the same result if you were to upload the .vmdk to a datastore path and then move the file (virtual disk) using the vSphere UI. While the initial upload would be the originating file size, after the move it will inflate.  

Ryan Johnson
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Based on review of the enhancement request and detailed testing of the scenarios, this enhancement is being labeled as `declined` and closed.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
