### ISSUE TITLE
Create a Network and VM and assign the created network to the VM without running "terraform apply" twice

### ISSUE THREAD

**Issue by Tjalf01** [hashicorp/terraform-provider-vsphere#1608]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

Terraform v1.1.5

### Terraform Provider

Provider v2.1.0

### VMware vSphere

6.7.0

### Description

Hello Guys :)

I recently started lerning Terraform.

I want to build an IT infrastructure
My current problem is that I want to create a VM and assign it to a network which I created with the same command
I just want to execute "terraform apply" once

Of course, the bug in my script is that terraform can't read the data resource because it doesn't exist yet.
Is it still somehow possible to create a switch/port group and a VM and assign the created network to the VM without running "terraform apply" twice

### Affected Resources

resource "vsphere_virtual_machine"

resource "vsphere_host_virtual_switch"
resource "vsphere_host_port_group"

data "vsphere_network"

### Terraform Configuration

provider "vsphere" {
  user           = "root"
  password       = "xxx"
  vsphere_server = "xxx"
}

data "vsphere_datacenter" "dc" {
  name = "dc1"
}

data "vsphere_host" "host" {
  name          = "localhost.it-p.de"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = "esxi1/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "vPortgroup-Test" {
  name          = "vPortgroup-Test"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_host_virtual_switch" "vSwitch-Test" {
  name           = "vSwitch-Test"
  host_system_id = "${data.vsphere_host.host.id}"

   network_adapters = []

  active_nics  = []
  standby_nics = []
}

resource "vsphere_host_port_group" "vPortgroup-Test" {
  name                = "vPortgroup-Test"
  host_system_id      = "${data.vsphere_host.host.id}"
  virtual_switch_name = "${vsphere_host_virtual_switch.vSwitch-Test.name}"
}

resource "vsphere_virtual_machine" "TestVM" {
  name             = "TestVM"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  host_system_id   = data.vsphere_host.host.id

  num_cpus = 2
  memory   = 2048
  guest_id = "oracleLinux8_64Guest"

  network_interface {
    network_id = "${data.vsphere_network.vPortgroup-Test.id}"
  }

  disk {
    label = "disk0"
    size  = 16
  }
    cdrom {
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    path         = "ISOs/OracleLinux-R8-U5-x86_64-dvd.iso"
  }
}

### Debug Output

[root@localhost scripts]# terraform apply
╷
│ Error: error fetching network: network 'vPortgroup-Test' not found
│
│   with data.vsphere_network.vPortgruppe-Test,
│   on main.tf line 26, in data "vsphere_network" "vPortgruppe-Test":
│   26: data "vsphere_network" "vPortgruppe-Test" {

### Expected Behavior

Is it possible to create a switch/port group and a VM and assign the created network to the VM without running "terraform apply" twice

### Actual Behavior

It didn't created the Network or the VM :(

**Comment by tenthirtyam** [comment]
Hello,  Tjalf01 !  👋🏻 

Could you please format the code in the **Terraform Configuration** using the Markdown editor?

Learn more about [Code Formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

Ryan Johnson
Staff Ii Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Hello,  Tjalf01 !  👋🏻 

This issue would not be classified as a `bug` and should ideally be discussed on discuss.hashicorp.com.

To address your issue, you'll need to use the `depends_on [ ]` to ensure that the dependencies are set to create the objects in the correct order.

Ryan Johnson
Staff Ii Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Hello, Tjalf01 ! 👋🏻

Did the previous comment and high-level example help to address your issue?

**Ryan Johnson**
Staff Ii Solutions Architect | VMware, Inc.

**Comment by Tjalf01** [comment]
IT-P GmbH · Seligmannallee 6 · 30173 Hannover
Amtsgericht Hannover · HRB 55855
Geschäftsführer: Matthias Funke & Michael Nölke
Tel. 0511 61 68 04-0 ·  Fax 0511 61 68 04-17 · www.it-p.de
