### ISSUE TITLE
Move provider to the use `hashicorp/terraform-plugin-docs`

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-provider-vsphere#1611]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The provider could benefit from using the [doc generator](https://github.com/hashicorp/terraform-plugin-docs). This will allow documentation to be maintained in the `Description` field of the schema, and examples can live in the example folder. Unfortunately, the current descriptions are not the source of truth, so we will have to reverse the process, getting the current docs placed back into descriptions and the creation of the examples folder.

Hopefully this can be automated, if not, good old copy paste.

### Use Case(s)

N/A

**Comment by tenthirtyam** [comment]
Per the `terraform-plugin-docs` README it isexperimental not ready for production use.

Will keep this issue on the backlog and monitor advancements in the plugin.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
