### ISSUE TITLE
Add support for UUID field in `d/virtual_machine `

### ISSUE THREAD

**Issue by kalenarndt** [hashicorp/terraform-provider-vsphere#1612]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The current `vsphere_virtual_machine` datasource does not support doing lookups based on the VM's UUID. Ideally we should include an optional field so customers can do lookups based on the unique identifier instead of the name

### Use Case(s)

HCP Packer exports the UUID of the template when it finishes the build for the iteration

![image](https://user-images.githubusercontent.com/6990206/156639783-cbbaba02-d3f2-4c9e-a68f-27a0126baec0.png)

HCP Packer also lets us assign the iteration to a channel. An example would be iteration 4 is assigned to production and when you use the HCP provider to deploy VMs you tell it to use that channel and the bucket name and it gives you back the object id to use in the cloud of your choice. 

![image](https://user-images.githubusercontent.com/6990206/156640370-0981fe99-d0b7-48f7-9b3d-91b48386c970.png)

In VMware we have to pass the name back in as we unable to lookups via the recorded UUID. If an administrator is doing a force replacement with packer the name will stay the same but the UUID will change. This means that if someone publishes verison 4 as the default for the channel production and the administrator force replaces it with 5 additional iterations (version 9) we would return the name and not be able to fail the deployment.

Current workaround is to append a timestamp to the name of the VM as it has been deployed but ideally we should be able to do lookups based on the UUID

**Comment by tenthirtyam** [comment]
ℹ️ Related:
- https://github.com/hashicorp/terraform-provider-vsphere/issues/282 regarding transitioning to UUID ad the ID of the resource.
