### ISSUE TITLE
Unable to upload the vmdk file when the destination folder doesnt exist

### ISSUE THREAD

**Issue by Kishanbhatk** [hashicorp/terraform-provider-vsphere#1614]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v0.13.3

### Terraform Provider

v2.1.0

### VMware vSphere

v7.0.1

### Description

I have used the offcial v2.1.0 terraform vmware provider plugin to upload the VMDK file to the destination folder . The plugin will throw error when the destination directory doesnt exist . It seems like  the issue has been resolved in https://github.com/hashicorp/terraform-provider-vsphere/pull/1590 , but still we are facing the issue when we try uploading the VMDK to the destination ( when we dont have destination directory ) . We can try out create_directories option , but we need the functionality in such a way that we only want to create a folder when it doesnt exist. ISO uploads are working fine but this issue is seen in VMDK uploads . 

### Affected Resources

`resource/vsphere_file`

### Terraform Configuration

```hcl
resource "vsphere_file" "upload" {

  datacenter = data.vsphere_datacenter.datacenter.id
  datastore  = var.vsphere_datastore_name

  source_file        = "/home/kishan/file.vmdk"
  destination_file   = "source_files/file.vmdk"
}
```
// Here folder 'source_files' is not present in the data store 

### Panic Output

```console
vsphere_file.upload["vmdk1"]: Still creating... [10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m30s elapsed]
vsphere_file.upload["vmdk1"]: Creation complete after 3m36s [id=[datastore1] ha-datacenter/source_files/file.vmdk]

vsphere_file.upload["vmdk1"]: Still creating... [4m40s elapsed]

Error: error File /vmfs/volumes/5ff5a927-3c8bedec-1ea5-e4434b298064/tfm-temp-457776264/file.vmdk was not found
```

### Expected Behavior

File should be uploaded properly

### Actual Behavior

Error while trying to upload the file 

### References

#1587

**Comment by tenthirtyam** [comment]
Closing this issue since the dialogue has continued in reopened #1587 instead of this new issue.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
