### ISSUE TITLE
Tags on `r/vsphere_host` are not accepted

### ISSUE THREAD

**Issue by rutgerblom** [hashicorp/terraform-provider-vsphere#1616]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.4

### Terraform Provider

v2.0.2

### VMware vSphere

v7.0.3

### Description

When adding the "tags" attribute to a "vsphere_host" resource I receive "Error: Unsupported argument".

### Affected Resources

resource/vsphere_host

### Terraform Configuration

```


resource "vsphere_host" "host" {
  for_each        = var.vsphere_host
  hostname        = each.value["hostname"]
  username        = var.esxi_user
  password        = var.esxi_password
  tags            = [vsphere_tag.tag["tag01"].id]
  cluster         = vsphere_compute_cluster.cluster[each.value.cluster].id
  thumbprint      = each.value["thumbprint"]
}
```

### Expected Behavior

The ESXi host to get tagged with the value of "[vsphere_tag.tag["tag01"].id]"

### Actual Behavior

```
│ Error: Unsupported argument
│
│   on modules\vsphere_configure\main.tf line 132, in resource "vsphere_host" "host":
│  132:   tags            = [vsphere_tag.tag["tag01"].id]
│
│ An argument named "tags" is not expected here.
```

### Environment Details

Terraform v1.1.4 on windows_amd64
ESXi 7.0.3c
vCenter 7.0.3c

**Comment by rutgerblom** [comment]
That was it! It works fine with v2.1.1. Thanks.

Rutger

Den tis 8 mars 2022 kl 19:20 skrev Ryan Johnson ***@***.***>:

**Comment by tenthirtyam** [comment]
Thanks for confirming, Marking as closed.
