### ISSUE TITLE
vapp properties not update and will show when do terraform apply even without any change

### ISSUE THREAD

**Issue by Nagendran2807** [hashicorp/terraform-provider-vsphere#1617]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.1.7

### Terraform Provider

v2.0.2

### VMware vSphere

v7.0.3

### Description

vapp properties not update and will show when do terraform apply even without any change

### Affected Resources

`resource/vsphere_virtual_machine`

### Expected Behavior

changes shouldn't display when do terraform apply even without any change

### Actual Behavior

Whenever do terraform apply even without any change it will trying to add every time
<img width="546" alt="Screenshot 2022-03-08 at 7 54 42 PM" src="https://user-images.githubusercontent.com/23469360/157257222-eba4ba3a-948b-42e3-9532-e78b7e82fb06.png">

But those changes reflected in vcenter console... Able to view those things in UI but not reflected in terraform side that's why it will show and trying to add whenever do terraform apply

### Steps to Reproduce

```hcl
  vapp_properties = {
    "hostname"    = var.vcg_name
    "public-keys" = var.vcadmin_ssh_key

    "eth0.ipAllocationType" = "STATIC"
    "eth1.ipAllocationType" = "STATIC"
}
```

### Screenshots

<img width="546" alt="Screenshot 2022-03-08 at 7 54 42 PM" src="https://user-images.githubusercontent.com/23469360/157257598-cc7be9b0-63ec-45fc-8533-02d830f3c5df.png">

**Comment by tenthirtyam** [comment]
There is a common practice to use the lifecycle meta argument to ignore these types of properties that are only used for the initial provisioning.

For example, to ignore all of the vApp properties:

```hcl
resource vsphere_virtual_machine "foo" {
...
 vapp {
 ...
 }
 lifecycle {
   ignore_changes = [
     vapp[0].properties,
   ]
 }
}
```

Or to ignore specific properties:

```hcl
resource vsphere_virtual_machine "foo" {
...
 vapp {
 ...
 }
 lifecycle {
   ignore_changes = [
     vapp[0].properties.eth0.ipAllocationType,
     vapp[0].properties.eth1.ipAllocationType,
   ]
 }
}
```

Ryan

**Comment by Nagendran2807** [comment]
@tenthirtyam I agree... Already added this block to address this one locally... I thought, this would be temporary so that raised the ticket... Thanks for your input

**Comment by tenthirtyam** [comment]
Try:

```hcl
resource vsphere_virtual_machine "foo" {
...
 vapp {
 ...
 }
 lifecycle {
   ignore_changes = [
     vapp[0].properties.eth0,
     vapp[0].properties.eth1,
   ]
 }
}
```

**Comment by Nagendran2807** [comment]
`vapp[0].properties` only works... Rest not working

**Comment by tenthirtyam** [comment]
That's very interesting. It appears that following is the most conducive workaround:

```hcl
resource vsphere_virtual_machine "foo" {
...
 vapp {
 ...
 }
 lifecycle {
   ignore_changes = [
     vapp[0].properties,
   ]
 }
}
```

**Comment by Nagendran2807** [comment]
Agree
