### ISSUE TITLE
Add support for custom attributes on `r/vsphere_host`

### ISSUE THREAD

**Issue by rutgerblom** [hashicorp/terraform-provider-vsphere#1618]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The "custom_attributes" argument is not available on `resource/vsphere_host`. It would be nice to be able to add custom attributes to ESXi host resources.

### Use Case(s)

Adding custom attributes to ESXi host objects using Terraform CLI.

**Comment by tenthirtyam** [comment]
Submitted in pull request https://github.com/hashicorp/terraform-provider-vsphere/pull/1619.

Ryan
