### ISSUE TITLE
OVF deployments do not work if multiple ISOs are needed

### ISSUE THREAD

**Issue by ckhordiasma** [hashicorp/terraform-provider-vsphere#1624]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.0.1

### Terraform Provider

v2.1.1

### VMware vSphere

v7.0.2.00200

### Description

Some appliance OVAs (like the cisco 8000v) utilize an ISO for installation and an ISO for initial one-touch configuration. 

Because the vsphere provider can only attach one CDROM (https://github.com/hashicorp/terraform-provider-vsphere/issues/1164), terraform vm deployments from OVA do not work for these appliances. 

### Affected Resources

resource/vsphere_virtual_machine

### Expected Behavior

VM boots successfully after provisioning from OVA

### Actual Behavior

VM does not boot because the boot ISO was not attached 

OR

VM does not get correct provisioning because configuration ISO was not attached

### Steps to Reproduce

1. Get an OVA that requires multiple ISOs
2. attempt to provision OVA using terraform vsphere provider

### References

https://github.com/hashicorp/terraform-provider-vsphere/issues/1164

**Comment by tenthirtyam** [comment]
I would recommend that this be filed as an `enhancement` request versus a `bug`.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Marked as duplicate and additional context for >1 CD-ROM is now added to https://github.com/hashicorp/terraform-provider-vsphere/issues/1164.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
