### ISSUE TITLE
`r/virtual_machine` doesn't refresh `scsi_controller_count` attribute

### ISSUE THREAD

**Issue by zsolt-zadory** [hashicorp/terraform-provider-vsphere#1632]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.5

### Terraform Provider

v2.1.1

### VMware vSphere

v7.0.1

### Description

If a new SCSI controller and disk is added manually to an already existing virtual machine then Terraform doesn't recognize either of them after refresh. If we update the code accordingly, the plan will show them as new entities and try to add them which causes apply to fail with the message `Error: disk.2: cannot assign disk: unit number 0 on SCSI bus 1 is in use`.

I noticed that `resourceVSphereVirtualMachineRead` function doesn't actually reads back the scsi_controller_count attribute and `DiskRefreshOperation` function seems to select disks based on that information.

### Affected Resources

`resource/vsphere_virtual_machine`

### Expected Behavior

Terraform state should reflect external changes after refresh. `scsi_controller_count ` should increase with 1 and the new disk should appear as "oprhaned_disk_N".

### Actual Behavior

Terraform ignores the new controller and the disk added to it.

### Steps to Reproduce

1. Create a VM with 1 SCSI controller
2. Manually add a new SCSI controller
3. Add a disk to the new controller

**Comment by tenthirtyam** [comment]
@appilon - since `scsi_controller_count` is not a computed attribute I would not expect this to be incremented since the change is made outside of Terraform. 

Instead, the VM would need to be deleted from the state and then imported with the configuration due to the prior external change, do you agree?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
