### ISSUE TITLE
Add support for timeout configuration to virtual machine reconfiguration tasks

### ISSUE THREAD

**Issue by rashaev** [hashicorp/terraform-provider-vsphere#1646]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add ability to configure timeout for Reconfiguration tasks after virtual machine creation. Now the timeout value is a constant equal to 5 minutes

### Use Case(s)

If VM Reconfiguration tasks take more than 5 minutes, then the task does not complete successfully. The ability to configure the timeout in the provider settings will avoid this problem. To do this, you can use the api_timeout parameter that was added earlier.

### Potential Terraform Provider Configuration

```
provider "vsphere"  {
  vsphere_server = var.vsphere_vcenter
   user           = var.vsphere_user
   password       = var.vsphere_password
   api_timeout    = 20
}
```

### References

#1645

**Comment by tenthirtyam** [comment]
Investigating pulling this forward into `v2.2.0` milestone...

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
