### ISSUE TITLE
Unable to enumerate disks when building Windows VM

### ISSUE THREAD

**Issue by usmcguy** [hashicorp/terraform-provider-vsphere#1647]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.1.8

### Terraform Provider

2.1.1

### VMware vSphere

v7.0.3

### Description

The terraform config can create the VM, but it doesnt appear to properly create/attach the disk. When the script runs with plan, there are no errors. But when applied, an error is returned "Unable to enumerate all disks". When viewing the VM in vCenter, it exists with all other settings configured properly, except for the disk.

### Affected Resources

resource/vsphere_virtual_machine

### Terraform Configuration

`terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "= 2.1.1"
    }
  }
}

provider "vsphere" {
  vsphere_server = "<--removed for privacy-->"
  client_debug = "true"
}

data "vsphere_datacenter" "datacenter" {
  name     = "<--removed for privacy-->"
}

data "vsphere_datastore" "datastore" {
  name          = "<--removed for privacy-->"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "Management" {
  name          = "<--removed for privacy-->"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name = "${data.vsphere_compute_cluster.Management.name}/Resources"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "server0" {
  name = "_Test"
  resource_pool_id = data.vsphere_compute_cluster.Management.resource_pool_id
  datastore_id = data.vsphere_datastore.datastore.id
  num_cpus = 2
  memory = 4096
  firmware = "efi"
  efi_secure_boot_enabled = "true"
  guest_id = "windows9Server64Guest"
  hardware_version = 15
  network_interface {
    network_id = "network-76951"
    adapter_type = "vmxnet3"
  }
  disk {
    label = "disk0"
    size = "100"
    datastore_id = data.vsphere_datastore.datastore.id
    thin_provisioned = "true"
    eagerly_scrub = "false"
    unit_number = 0
  }
}`

### Debug Output

https://gist.github.com/usmcguy/c2b543ed569d23d587d8e5c79af4ef34

### Expected Behavior

Create VM with 100GB disk

### Actual Behavior

VM Created with 0 MB disk and no vmdk file in datastore.

### Steps to Reproduce

terraform apply

**Comment by tenthirtyam** [comment]
Likely a duplicate of #1639.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
@appilon Looks like 3 reports of the same issue.

**Comment by usmcguy** [comment]
I tried using Terraform v0.12.20 and vsphere provider v1.26.0 like 8uachaille mentioned in #1639, but I didnt have any different result.

**Comment by tenthirtyam** [comment]
Best to close this duplicate and add a 👍 https://github.com/hashicorp/terraform-provider-vsphere/issues/1639.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by usmcguy** [comment]
Closing ticket as it may be a duplicate of #1639. Adding comments to the other ticket moving forward.
