### ISSUE TITLE
Terraform can't destroy `r/vsphere_virtual_machine` with attached virtual disk

### ISSUE THREAD

**Issue by lostplan** [hashicorp/terraform-provider-vsphere#1651]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.1.7

### Terraform Provider

2.1.1

### VMware vSphere

7.0.3

### Description

When a virtual machine is in a particular state:

* Uses attached virtual disk
* Has manually created snapshots

When replacing or destroying the VM, Terraform will first attempt to detach the external disk. However, vSphere will not allow the operation.

### Affected Resources

`resource/vsphere_virtual_machine`

### Terraform Configuration

```
resource "vsphere_virtual_disk" "persistent_disk" {
  size               = 4
  type               = "thin"
  vmdk_path          = "test-independent.vmdk"
  create_directories = true
  datacenter         = data.vsphere_datacenter.dc.name
  datastore          = data.vsphere_datastore.datastore.name
}

resource "vsphere_virtual_machine" "test_vm" {
  name             = "example-vm"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = "test"

  num_cpus = 2
  memory   = 1024

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    unit_number      = 0
    label            = "disk0"
    thin_provisioned = true
    size             = 32
  }

  disk {
    unit_number  = 1
    label        = "disk1"
    disk_mode    = "independent_persistent"
    attach       = true
    path         = vsphere_virtual_disk.persistent_disk.vmdk_path
    datastore_id = data.vsphere_datastore.datastore.id
  }

  guest_id = "ubuntu64Guest"
}
```

### Expected Behavior

Terraform should be able to destroy the VM.

### Actual Behavior

Terraform cannot destroy the VM.

Terraform error:
`Error: error detaching virtual disks: Invalid configuration for device '0'.`

vCenter internal error:
`Invalid configuration for device '0'. Cannot remove virtual disk from the virtual machine because it or one of its parent disks is part of a snapshot of the virtual machine.`

### Steps to Reproduce

1. `terraform apply` (create a configuration similar to that defined above)
2. In vCenter client, manually take a snapshot of the VM
3. Simulate an upgrade by running `terraform taint 'vsphere_virtual_machine.test_vm'`
4. `terraform apply`

**Comment by tenthirtyam** [comment]
@lostplan - using simply UI or PowerShell, are you able to perform are you able to perform the same destroy task for the VM without error?

I suspect that this operation is blocked and that this is by design since the attached disk is participating in the VM snapshot.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by lostplan** [comment]
@tenthirtyam Yes, I can destroy the VM from the vSphere UI

**Comment by lostplan** [comment]
Just checking – have you had a chance to look at this?

**Comment by tenthirtyam** [comment]
Hi @lostplan,

I took some time this weekend to run through the scenario with the following example:

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_disk" "persistent_disk" {

  size               = 1024
  type               = "thin"
  vmdk_path          = "gh-1651.vmdk"
  create_directories = true
  datacenter         = data.vsphere_datacenter.datacenter.name
  datastore          = data.vsphere_datastore.datastore.name
}


resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  disk {
    unit_number  = 1
    label        = "disk1"
    disk_mode    = "independent_persistent"
    attach       = true
    path         = vsphere_virtual_disk.persistent_disk.vmdk_path
    datastore_id = data.vsphere_datastore.datastore.id
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      windows_options {
        computer_name         = var.vm_name
        join_domain           = var.domain
        domain_admin_user     = var.domain_admin_username
        domain_admin_password = var.domain_admin_password
        admin_password        = var.vm_admin_password
      }
      network_interface {
        ipv4_address = var.vm_ipv4_address
        ipv4_netmask = var.vm_ipv4_netmask
      }

      ipv4_gateway    = var.vm_ipv4_gateway
      dns_suffix_list = var.vm_dns_suffix_list
      dns_server_list = var.vm_dns_server_list
    }
  }

  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
}
```

This results in the same error if an externally managed snapshot exists:

`Error: error detaching virtual disks: Invalid configuration for device '0'.`

However, you would get the exact same error in the vSphere UI if you attempt to remove the virtual disk from the virtual machine first (versus just deleting it).

Terraform is running the `resourceVSphereVirtualDiskDelete` delete function, as expected, against the virtual disk first and fails because the virtual machine and the disk is still attached while the snapshot is present.

I've not yet determined a workaround to the issue, even though it is technically performing as expected based on the code and configuration.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
This is performing as expected based on the code and configuration. The introduction of an externally created snapshot is the catalyst for the issue. Consider managing the snapshots using Terraform or check for snapshots before destroy operations.

Ryan Johnson
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
