### ISSUE TITLE
Add support for unverified/untrusted ESXi host thumbprint

### ISSUE THREAD

**Issue by rutgerblom** [hashicorp/terraform-provider-vsphere#1655]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Like we allow `allow_unverfied_ssl` for the vSphere provider (vCenter connection), for day 1 operations on ESXi hosts it is necessary to allow self-signed certificates to onboard newly installed/re-installed ESXi hosts. 
Therefore I would like to suggest an `allow_unverfied_thumbprint` parameter on the `vshpere_host`resource.

### Use Case(s)

Allow smoother onboarding and management of newly installed ESXi hosts that don't have a signed/trusted SSL certificate (yet).

**Comment by tenthirtyam** [comment]
Hi @rutgerblom,

Have you tried using the [thumbprint data source](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/host_thumbprint) option with the `insecure` argument?

For example:

```hcl
data "vsphere_datacenter" "datacenter" {
  name = var.datacenter_name
}

data "vsphere_compute_cluster" "cluster" {
  name = var.cluster_name
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_host_thumbprint" "esxi01" {
  address = "esxi01.example.com"
  insecure = true
}

resource "vsphere_host" "esxi01" {
  hostname = "esxi01.example.com"
  username = "root"
  password = "VMware1!"
  thumbprint = data.vsphere_host_thumbprint.esxi01.id
  cluster = data.vsphere_compute_cluster.cluster.id
}
```

Does this solve the issue?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by rutgerblom** [comment]
Hi Ryan,

I'm looking for a way to silently add ESXi hosts without having to deal
with their thumbprints.

Best regards

Den tors 23 juni 2022 kl 00:29 skrev Ryan Johnson ***@***.***

**Comment by tenthirtyam** [comment]
Marking this enhancement issue as `not-planned`.

**Reasoning**: The recommended practice is to confirm the thumbprint of the entity in the resource, which can be provided through the `d/vsphere_host_thumbprint` data source as seen passed to `r/vsphere_host`.

This will ensure that the thumbprint is provided upon initial addition to vCenter Server. Once added to vCenter Server, VMCA (_if custom certificates are not used_) will issue a new certificate which will be picked up by Terraform on the next refresh of the state, Terraform would also pick up any changes during day-two operations.

The proposal to silently add ESXi hosts without addressing thumbprints is not recommended.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
