### ISSUE TITLE
Any chance of a release?

### ISSUE THREAD

**Issue by holmesb** [hashicorp/terraform-provider-vsphere#1661]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Hi,

We're keen to easily start using some of the [cool new features](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md). Any chance of a v2.2.0 release? Apologies if this is a newb request, but I can't see any documented policy about when new releases are created.

Many thanks

### Use Case(s)

.

**Comment by tenthirtyam** [comment]
We are keen on completing the issues seen in the v2.2.0 milestone. See https://github.com/hashicorp/terraform-provider-vsphere/milestone/6.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
[v2.2.0 Milestone Tracking](https://github.com/hashicorp/terraform-provider-vsphere/milestone/6)

Marking as closed.
