### ISSUE TITLE
Unable to create a VM due to VirtualMachine.Config.AddNewDisk permission

### ISSUE THREAD

**Issue by diversys** [hashicorp/terraform-provider-vsphere#1666]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.1

### Terraform Provider

v2.1.1

### VMware vSphere

v6.7.0.42000

### Description

Hi there.

I am unable to create a VM, according to debug logs this is because I don't have permissions to create new disks.
I can create a VM just fine in vSphere UI as well as using `govc`: `govc vm.create -pool "Resource" test-vm` but not with Terraform.
Also govc reports that I have required permissions: 
```
govc role.ls "Geoinfosystems host" | grep AddNewDisk
VirtualMachine.Config.AddNewDisk
```

### Affected Resources

`resource/vsphere_virtual_machine`

### Terraform Configuration

```
provider "vsphere" {
  user           = ""
  password       = ""
  vsphere_server = ""
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = ""
}

data "vsphere_datastore" "datastore" {
  name          = "esx-4232"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "DC3-PROD-LACP"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = ""
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm1" {
  name             = "testvm01"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = "test"
  guest_id         = "debian11Guest"
  num_cpus         = 2
  memory           = 4096

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label = "disk0"
    size  = "20"
  }

}
```

### Debug Output

Terraform output https://gist.github.com/diversys/f6ca3c17f0bdc841540d0c89028e9ebe
govmomi xml error: https://gist.github.com/diversys/16b37601eb93b08f757ecb7daf0a57e8

```
vsphere_virtual_machine.vm1: Creating...
╷
│ Error: error creating virtual machine: ServerFaultCode: Permission to perform this operation was denied.
│
│   with vsphere_virtual_machine.vm1,
│   on instances.tf line 1, in resource "vsphere_virtual_machine" "vm1":
│    1: resource "vsphere_virtual_machine" "vm1" {
```

` grep -rnI privilegeId ~/.govmomi`
`/home/diver/.govmomi/debug/2022-06-02T18-00-43.559206006/1-0023.res.xml:7:<soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>Permission to perform this operation was denied.</faultstring><detail><NoPermissionFault xmlns="urn:vim25" xsi:type="NoPermission"><object type="Folder">group-v544661</object><privilegeId>VirtualMachine.Config.AddNewDisk</privilegeId></NoPermissionFault></detail></soapenv:Fault>`

### Expected Behavior

VM should be created without errors.

### Actual Behavior

Getting `Error: error creating virtual machine: ServerFaultCode: Permission to perform this operation was denied.`

**Comment by tenthirtyam** [comment]
I would recommend providing a list of the specific privileges attached to the role that has been assigned to the user.

There's not a direct correlation between an action working in GOVC and it working in Terraform as the implementations can differ. For example, you'll often need Storage Profile View privilege in the provider when it may not be required when using GOVC.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by diversys** [comment]
Hi, Storage Profile View is not in the list, when is it needed? Can you spot if anything else is missing?

govc role.ls Geoinfosystems
```
System.Anonymous
System.Read
System.View
VirtualMachine.Inventory.Create
```

govc role.ls "Geoinfosystems host"
```
Datastore.AllocateSpace
Datastore.Browse
Datastore.FileManagement
Global.SetCustomField
Host.Local.CreateVM
Host.Local.DeleteVM
Host.Local.ReconfigVM
Network.Assign
Resource.AssignVMToPool
Resource.ColdMigrate
Resource.HotMigrate
System.Anonymous
System.Read
System.View
Task.Create
VirtualMachine.Config.AddExistingDisk
VirtualMachine.Config.AddNewDisk
VirtualMachine.Config.AddRemoveDevice
VirtualMachine.Config.AdvancedConfig
VirtualMachine.Config.CPUCount
VirtualMachine.Config.DiskExtend
VirtualMachine.Config.DiskLease
VirtualMachine.Config.EditDevice
VirtualMachine.Config.Memory
VirtualMachine.Config.RemoveDisk
VirtualMachine.Config.Rename
VirtualMachine.Config.ResetGuestInfo
VirtualMachine.Config.Resource
VirtualMachine.Config.Settings
VirtualMachine.Config.UpgradeVirtualHardware
VirtualMachine.Interact.AnswerQuestion
VirtualMachine.Interact.ConsoleInteract
VirtualMachine.Interact.DeviceConnection
VirtualMachine.Interact.GuestControl
VirtualMachine.Interact.PowerOff
VirtualMachine.Interact.PowerOn
VirtualMachine.Interact.Reset
VirtualMachine.Interact.SetCDMedia
VirtualMachine.Interact.ToolsInstall
VirtualMachine.Inventory.Create
VirtualMachine.Inventory.CreateFromExisting
VirtualMachine.Inventory.Delete
VirtualMachine.Inventory.Move
VirtualMachine.Inventory.Register
VirtualMachine.Provisioning.Clone
```

**Comment by tenthirtyam** [comment]
Look like this issue could be on the "test" folder.

```xml
<NoPermissionFault xmlns="urn:vim25" xsi:type="NoPermission"><object type="Folder">group-v544661</object><privilegeId> VirtualMachine.Config.AddNewDisk </privilegeId></NoPermissionFault>
```

Assume you are **only** using the account to `vsphere_virtual_machine` resources?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by diversys** [comment]
"test" folder? Not sure what you mean, please elaborate on that. `vsphere_virtual_machine` is the only resource I'm trying to create. Or did you mean something else? I'm a bit puzzled. Thanks!

**Comment by diversys** [comment]
Ah, I see what you mean by "test" folder. I replaced real folder name from "ДПИС VM" to "test" when posting here. Could the name be a problem? The other question (about `vsphere_virtual_machine` resources) I still struggle to understand.

**Comment by tenthirtyam** [comment]
```hcl
resource "vsphere_virtual_machine" "vm1" {
  #...other config
  folder           = "test"
```
 Seems to be `<object type="Folder">group-v544661</object>`

Could be access to that folder.... perhaps.

Ryan

**Comment by diversys** [comment]
Renaming this folder to a Latin name didn't help. Is there anything else I could try or ask vSphere admins? Appreciate your help.

**Comment by diversys** [comment]
This is a duplicate of #1212.
