### ISSUE TITLE
Add support for vSAN dedupe and compression feature.

### ISSUE THREAD

**Issue by SlimYang** [hashicorp/terraform-provider-vsphere#1669]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

vSAN Dedupe and Compression feature is introduced in 6.2 release but this is not yet supported in Terraform. This feature is widely used by our vSAN customers to save the spaces they are using for their staging and production environment. The feature request is to support the Terraform customers who are using the vSphere/vSAN provider to have the ability to configure the vSAN dedupe/compression feature with the provider.

### Use Case(s)

Allow Terraform users to configure vSAN dedupe and compression via the vSphere provider.

### Potential Terraform Provider Configuration

```hcl
resource compute_cluster "compute_cluster" {
  # ... other configuration
  vsan_enabled                    = true
  vsan_dedupe_compression_enabled = true
  vsan_disk_group {
    cache = data.vsphere_vmfs_disks.cache_disks[0]
    storage = data.vsphere_vmfs_disks.storage_disks
  }
  # ... other configuration
}
```

### References

Introduction to vSAN dedupe and compression feature --
1. [How to Manage Disks in a Cluster with Deduplication and Compression
](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.virtualsan.doc/GUID-3D2D80CC-444E-454E-9B8B-25C3F620EFED.html)
2. [VSAN 6.2 Part 1 – Deduplication and Compression](https://cormachogan.com/2016/02/12/vsan-6-2-part-1-deduplication-and-compression/)

Current vSAN supportability code links --
1. [Terraform support for vSAN setting](https://registry.terraform.io/providers/hashicorp/vsphere/1.25.0/docs/resources/compute_cluster#cluster-vsan-settings )
2. [vsan_enabled field on Github](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/resource_vsphere_compute_cluster.go#L486)
3. [vsan_disk_groupd field on Github](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/resource_vsphere_compute_cluster.go#L492)

The dedupe/compression field is now present in govmomi ([link](https://github.com/vmware/govmomi/blob/master/vsan/types/types.go#L5261))

**Comment by tenthirtyam** [comment]
Submission by:

> **Yang Yang**
> Staff Engineer, vSAN | VMware, Inc.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
