### ISSUE TITLE
`r/vsphere_virtual_disk` is not destroyed; showing error

### ISSUE THREAD

**Issue by raja444** [hashicorp/terraform-provider-vsphere#1678]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.4

### Terraform Provider

v2.0.2

### VMware vSphere

6.7.0

### Description

While Try to do the terraform destroy. 
All other nodes are able to destroyed successfully,
but `r/vsphere_virtual_disk` is not destroyed.

info is just below :

```hcl
disk {
    label                = "add_disk1"
    attach               = "true"
    path                 = "prasanna-dir-worker1/add_disk1.vmdk"
    unit_number          = "2"
    datastore_id         = "${data.vsphere_datastore.datastore1__2_.id}"
  }

resource "vsphere_virtual_disk" "add_disk1" {
    create_directories          = "true"
    vmdk_path                   = "prasanna-dir-worker1/add_disk1.vmdk"
    size                                  = "50"
    datacenter                  = "vmcreation"
    datastore                   = "datastore1 (2)"
    type                        = "thin"
}
```

### Affected Resources

NA

### Expected Behavior

it should destroy all the vm's.

### Actual Behavior

only Virtual disk alone, its not getting destroyed while doing terraform destroy cmd.
showing error. 

```console
Error caused by file /vmfs/volumes/61fd7bf1-4b8d42f6-6a29-00f28b2cb226/prasanna-dir-worker1/add_disk1.vmdk
```

**Comment by tenthirtyam** [comment]
Try adding a dependency with `depends_on`.

**Comment by raja444** [comment]
I have used depends_on as below here.

in my python file, i have used terraform.
 'resource "vsphere_virtual_disk" "add_disk' + str(self.numOfdisk) + '" {\n'
                                   **'    depends_on                  = [vsphere_virtual_machine.'+ str(self.name) +']\n'**
                                   '    create_directories          = "true"\n'
                                   '    vmdk_path                   = "' + str(self.name) + '/add_disk' + str(self.numOfdisk) + '.vmdk"\n'
                                   '    size                        = "' + str(datastore_sz) + '"\n'
                                   '    datacenter                  = "' + str(datacenter_na) + '"\n'
                                   '    datastore                   = "' + str(datastore_na) + '"\n'
                                   '    type                        = "thin"\n'
                                   '}\n'


and my sample.tf file output is below:
resource "vsphere_virtual_disk" "add_disk1" {
    depends_on                  = [vsphere_virtual_machine.prasanna-dir-worker1]
    create_directories          = "true"
    vmdk_path                   = "prasanna-dir-worker1/add_disk1.vmdk"
    size                        = "50"
    datacenter                  = "OMD"
    datastore                   = "datastore1 (2)"
    type                        = "thin"
}


Getting this error,
 Error: Reference to undeclared resource
│
│   on samp.tf line 325, in resource "vsphere_virtual_disk" "add_disk1":
│  325:     depends_on                  = [vsphere_virtual_machine.prasanna-dir-worker1]
│
│ A managed resource "vsphere_virtual_machine" "prasanna-dir-worker1" has not been declared in the root module.
╵


Could you please help?

**Comment by tenthirtyam** [comment]
It _appears_ that the `vsphere_virtual_machine.prasanna-dir-worker1` resource is not in the same file or set of config files.

Please use the code formatting tools. I edited your original post for readability.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by raja444** [comment]
Now its working fine.
changed like depends_on = [vsphere_virtual_machine.'+ str(self.tfid) +']\n'

Thanks Ryan Johnson. :)

**Comment by raja444** [comment]
Yes you can close. Thanks Ryan Johnson :)
