### ISSUE TITLE
Add support for vmware_host_passthrough by id

### ISSUE THREAD

**Issue by holmesb** [hashicorp/terraform-provider-vsphere#1684]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Hi,

Currently if multiple PCI devices exist of the same name, can only passthrough all or none. `vmware_host_passthrough` [only supports device name](https://github.com/ansible-collections/community.vmware/blob/c673d7517eb3a49bbb83e29661ab65fc84cc61c1/plugins/modules/vmware_host_passthrough.py#L42), not ID. So if only some NICs\GPUs need to be passedthrough, can't be done.

Cheers.

### Use Case(s)

Passthrough specific device

**Comment by tenthirtyam** [comment]
@holmesb - did you mean to close this enhancement request?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by holmesb** [comment]
Yes, wrong project, pls reopen #1685 which is intended for this Terraform provider.
