### ISSUE TITLE
Disk size calculation error in i386 release of provider

### ISSUE THREAD

**Issue by Suselz** [hashicorp/terraform-provider-vsphere#1686]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.3, Windows

### Terraform Provider

Windows,  v2.2.0,  i386

### VMware vSphere

v7.0.1

### Description

I got calculation disk size error when trying to create VM with disk or resize disk via i386 (x32) vSphere provider.
When i try to create\resize disk I'm getting an error:

```Invalid configuration for device '0'```

I turned on the debug mode for provider:
```
provider "vsphere" {
...
  client_debug = true
  client_debug_path = "./logs"
}
```
I found the following bug:
When i try to create disk more than 1 GB i get negative disk size values (some times it's `0` value) in the final API request in fields `capacityInKB` and `capacityInBytes`:
```
...
               <deviceChange xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="VirtualDeviceConfigSpec">
                    <operation>edit</operation>
                    <device XMLSchema-instance:type="VirtualDisk">
                        <key>2000</key>
                        <deviceInfo XMLSchema-instance:type="Description">
                            <label>Hard disk 1</label>
                            <summary>2,048,000 KB</summary>
                        </deviceInfo>
...
                       <capacityInKB>-1048576</capacityInKB>
                        <capacityInBytes>-1073741824</capacityInBytes>
...
```

amd64 version of provider works fine:
```
...

      <deviceChange xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="VirtualDeviceConfigSpec">
                    <operation>edit</operation>
                    <device XMLSchema-instance:type="VirtualDisk">
                        <key>2000</key>
                        <deviceInfo XMLSchema-instance:type="Description">
                            <label>Hard disk 1</label>
                            <summary>209,715,200 KB</summary>
                        </deviceInfo>
...                  
                        <capacityInKB>262144000</capacityInKB>
                        <capacityInBytes>268435456000</capacityInBytes>
        
...


```

### Affected Resources

for test i use simple creation of empty VM :

```
resource "vsphere_virtual_machine" "vm_test3" {
  name                        = "vm_test3"
  resource_pool_id            = data.vsphere_compute_cluster.main-cluster.resource_pool_id
  host_system_id              = data.vsphere_host.esxi01.id
  datastore_id                = data.vsphere_datastore.HDD_Datastore_2.id
  num_cpus                    = 1
  memory                      = 1024
  guest_id                    = "other3xLinux64Guest"
  wait_for_guest_net_routable = "false"
  wait_for_guest_net_timeout  = "0"
  
  network_interface {
    network_id = data.vsphere_network.vxlan-00.id
  }
  disk {
    label            = "disk0"
    size             = "250"
  }
}

```

### Expected Behavior

Created VM with expected disk size

### Actual Behavior

Not created VM, or created with unexpected disk size (for example - if i crate VM with 5Gb disk, a VM with a 1 GB disk will be created)

**Comment by tenthirtyam** [comment]
The following operating system/architecture combinations for compiled binaries are available in the registry as a part of the release process. 

- Darwin / AMD64
- Darwin / ARMv8
- Linux / AMD64
- Linux / ARMv8 (sometimes referred to as AArch64 or ARM64)
- Linux / ARMv6
- Windows / AMD64

Binaries for the following combinations are also shipped; however, we typically do not prioritize fixes for these:

- Linux / 386
- Windows / 386
- FreeBSD / 386
- FreeBSD / AMD64

[Reference](https://www.terraform.io/registry/providers/os-arch)

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
