### ISSUE TITLE
error: dial tcp :22: connect: no route to host 

### ISSUE THREAD

**Issue by raja444** [hashicorp/terraform-provider-vsphere#1689]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.1.4

### Terraform Provider

v2.0.2

### VMware vSphere

6.7.0

### Description

facing  timeout - last error: dial tcp :22: connect: no route to host while apply terraform

Vm is created with ip and mask by terraform, after that terraform try to ssh that machine, but its not happening and receiving i/o timeout issue. "timeout - last error: dial tcp 10.126.175.61:22: i/o timeout"

### Affected Resources

not able to create vm machine.

### Expected Behavior

should able to create vm machine

### Actual Behavior

got a tcp time error

**Comment by tenthirtyam** [comment]
Hi @raja444! 👋 

The details provided in the issue detail are insufficient to help troubleshoot and provide community assistance. 

Please edit the issue to update details, including environmental information and redacted provider configurations.

This will enable community members and/or maintainers to help you resolve the issue or confirm a Terraform provider or Terraform core issue.

Thanks!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by raja444** [comment]
1. Vm is created by terraform, it got a ip.
2. terraform tried to do ssh that vm to perform some operation.
3. ssh is not happening. got "i/o time out issue"
"timeout - last error: dial tcp 10.126.175.61:22: i/o timeout"

Could you please help me on this?

**Comment by raja444** [comment]
in my terraform.tf file contain vm details with ip address.
vm created using terraform only.
ip everything is assign while terraform apply.
but after that terraform tried to do ssh the vm for some time.
finally got i/o time out error.

**Comment by tenthirtyam** [comment]
Do you SSH to the provisioned virtual machine or use the web console/vmrc to perform the check?

If SSH, did you connect from the same host running Terraform or another bastion host?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Generally, I would using a configuration like such along with the VM resource.

```hcl
resource "null_resource" "init" {

  depends_on ["vsphere_virtual_machine.foo"]

  provisioner "remote-exec" {
    inline = [
      "echo hello world",
    ]
    connection {
      type     = "ssh"
      host     = var.vm_ipv4_address
      user     = "root"
      password = var.vm_root_password
      port     = "22"
      agent    = false
    }
  }
}
```

**Comment by raja444** [comment]
resource "null_resource" "repo_connect" {
   depends_on = [vsphere_virtual_machine.venkat_omd_repo]
     connection {
       type = "ssh"
       host = "10.126.175.61"
        user = "root"
        password = "iptv_123"
    }
    provisioner "remote-exec" {
        on_failure = continue
        inline = [
        ]
    }
}

I tried to do SSH to the provisioned vm.  from other host machine.
Vm machine ip 10.126.175.61 <--> ssh from this machine-> 10.126.252.96 ip 

Intention is  : tried to do ssh that vm and need to do some operation in that vm.
but ssh itself is getting failed.  and got i/o time out error

**Comment by tenthirtyam** [comment]
You should consider checking if SSHD is running on the provisioned VM and also if `PermitRootLogin` is enabled in the service configuration.

**Comment by raja444** [comment]
SSHD is running and permitRootLogin also enabled.
#LoginGraceTime 2m
PermitRootLogin yes
#StrictModes yes
#MaxAuthTries 6

systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-07-05 04:23:36 EDT; 13min ago
     Docs: man:sshd(8)

This Provisioned VM is created by Terraform only.

One scenario :  Terraform tried to do ssh for 5mins,  then it will throw error like "i/o timeout".
Meanwhile,  i went to provisioned vm console with in 5mins, then if i do restart network.
Then ssh is happened in Terraform. otherwise it will throw error.

any idea how fix this issue?

**Comment by tenthirtyam** [comment]
TCP 22 permitted between the networks?

**Comment by raja444** [comment]
Tcp 22 Details in Provision VM :

[root@test_machine ~]# sudo ss -tulpn | grep :22
tcp   LISTEN 0      128          0.0.0.0:22        0.0.0.0:*    users:(("sshd",pid=1201,fd=5))
tcp   LISTEN 0      128             [::]:22           [::]:*    users:(("sshd",pid=1201,fd=7))
[root@test_machine ~]# sudo netstat -tulpn | grep :22

tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1201/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1201/sshd
[root@test_machine ~]#




Terraform running in the below machine : TCP 22 details

[root@localhost vmware-integration]# sudo ss -tulpn | grep :22
tcp    LISTEN     0      128       *:22                    *:*                   users:(("sshd",pid=2941,fd=3))
tcp    LISTEN     0      128    [::]:22                 [::]:*                   users:(("sshd",pid=2941,fd=4))
[root@localhost vmware-integration]#
[root@localhost vmware-integration]# sudo netstat -tulpn | grep :22
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2941/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      2941/sshd

look like permitted only.

**Comment by tenthirtyam** [comment]
If you are unable to SSH between the host running Terraform and the virtual machine provisioned by the Terraform provider, then the `remote-exec` provisioner will fail.

This appears to be an environmental issue.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by raja444** [comment]
just clone the vm using vm-template.
In that template, added DEFROUTE=yes.

now able to do SSH between the host.
It is working fine.

Next time, I will update the code block statements as you mentioned.
Thanks Ryan Johnson for the support.

**Comment by tenthirtyam** [comment]
Thanks for the update, @raja444 - great to hear that it's working now!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Generally, the GitHub issues are for **only** recommended bug reports or enhancement requests. If it falls into those categories, then yes. 

If it is for general community assistance and troubleshooting, the recommended location is [discuss.hashicorp.com.](https://discuss.hashicorp.com/tags/c/terraform-providers/31/vsphere). 

You'll see the link for Community Discussions when you start the process of create an issue:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/7771363/177361131-3755da98-8aaf-47ac-824e-e90f3f40539d.png">

Additionally, there is a [#terraform](https://vmwarecode.slack.com/archives/C1647LTK7) Slack channel on the VMware {code} workspace.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/7771363/177361338-e1752f65-9009-434f-87e3-64d90116352f.png">

In either of these communities, you'll get broader community help.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
