### ISSUE TITLE
Add support for `vsphere_host_virtual_switch` without `standby_nics` argument

### ISSUE THREAD

**Issue by holmesb** [hashicorp/terraform-provider-vsphere#1690]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Hi,

I can create a Standard Virtual Switch in vSphere Client without a standby NIC adapter:
![image](https://user-images.githubusercontent.com/5072156/177375858-deadab47-4a2f-42b5-8740-8bead9adb820.png)

But if I try to create the same using `vsphere_host_virtual_switch` resource, by either leaving out `standby_nics`:
```
The argument "standby_nics" is required, but no definition was found
```
or set to `standby_nics = [""]`:
```
Error: standby NIC entry "" not present in network_adapters list
```
Terraform errors. If you run out of spare NICs, you can't create a Virtual Switch using this provider.

Cheers.

### Use Case(s)

Create Standard Virtual Switch without having to specify a standby NIC. IMO, the `standby_nics` argument should be optional.

### Potential Terraform Provider Configuration

```hcl
resource "vsphere_host_virtual_switch" "main" {
  name = "vswitch"
  host_system_id = "a_host"
  network_adapters = ["vmnic0"]
  active_nics  =  ["vmnic0"]
}
```
or

```hcl
resource "vsphere_host_virtual_switch" "main" {
  name = "vswitch"
  host_system_id = "a_host"
  network_adapters = ["vmnic0"]
  active_nics  =  ["vmnic0"]
  standby_nics = [""]
}
```

**Comment by tenthirtyam** [comment]
After a brief review of `r/vsphere_host_virtual_switch`, it should be possible to update the following:

https://github.com/hashicorp/terraform-provider-vsphere/blob/fa3580820d1e27ff36419f87f8c2b487c6a167fa/vsphere/resource_vsphere_host_virtual_switch.go#L29-L32

to:

```go
s["active_nics"].Required = true 
s["standby_nics"].Required = false
```

..and achieve the desired results.

I'll work on adding this option, testing, and updating the docs if required.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Additionally, you can certainly perform this operation with the following configuration:

```hcl
resource "vsphere_host_virtual_switch" "gh-1690" {
  name = "gh-1690"
  host_system_id = data.vsphere_host.host.id
  network_adapters = ["vmnic0"]
  active_nics  =  ["vmnic0"]
  standby_nics = []
}
```

However, that's not very intuative and setting `s["standby_nics"].Required = false` may be a better option so that the configuration looks more like:

```hcl
resource "vsphere_host_virtual_switch" "gh-1690" {
  name = "gh-1690"
  host_system_id = data.vsphere_host.host.id
  network_adapters = ["vmnic0"]
  active_nics  =  ["vmnic0"]
}
```

and if any additionals are added to n`etwork_adapters` that are not active would be kept in the unused.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Hi @holmesb, 👋 

I've added a pull request to address this issue. Once merged and included in a release, you'll be able to use this:

```hcl
resource "vsphere_host_virtual_switch" "gh-1690" {
  name = "gh-1690"
  host_system_id = data.vsphere_host.host.id
  network_adapters = ["vmnic0"]
  active_nics  =  ["vmnic0"]
}
```

...instead of this:

```hcl
resource "vsphere_host_virtual_switch" "gh-1690" {
  name = "gh-1690"
  host_system_id = data.vsphere_host.host.id
  network_adapters = ["vmnic0"]
  active_nics  =  ["vmnic0"]
  standby_nics = []
}
```
