### ISSUE TITLE
Error: Upload failed: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by raja444** [hashicorp/terraform-provider-vsphere#1691]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.4

### Terraform Provider

v2.0.2

### VMware vSphere

6.7.0

### Description

Tried to upload the file from to provisioned vm through terraform.
got a error.
Error: Upload failed: wait: remote command exited without exit status or exit signal

Please list the full steps required to reproduce the issue, for example:
git clone
terraform init
`terraform apply
I’d want some help in avoiding this error

I have queried in community assistance too. but i didnt get help.
could you please help me on this?

### Affected Resources

![image](https://user-images.githubusercontent.com/62252606/177519450-1eb87652-a921-4066-9ee3-649cfb7c34cc.png)

### Expected Behavior

without error, it should upload.

### Actual Behavior

showing upload failed error.

**Comment by tenthirtyam** [comment]
Hi @raja444,

Please provide more information on the error, configuration, etc by editing the content with _No Reponse_ shown.

Please keep in mind that this would be a Terraform issue rather than a provider issue as it's related to the provisioner.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Unfortunately, the request for more information on the error, configuration, etc was not provided. 

Since it's been over 7 days (9) marking the issue as closed.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
