### ISSUE TITLE
REPLACE WITH A SHORT DESCRIPTION

### ISSUE THREAD

**Issue by haseungyeon** [hashicorp/terraform-provider-vsphere#1694]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.5

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.3

### Description

vsphere_virtual_disk resource:
when I chose the type of the virtual disk to "lazy"
tfstate file allocate that value  as "preallocated".

### Affected Resources

Everytime I run "terraform apply" disk is deleted and newly created, though there are no changes in my code.

### Expected Behavior

Bad effects to virtual disk atttached virtual machine.

### Actual Behavior

Same as expected behavior

**Comment by tenthirtyam** [comment]
Hi @haseungyeon,

No example configuration has been provided for review or reproduction. 

Without this information it will be difficult to provide assistance.

Please update the details of the issue with additional information and _markdown formatted_ configuration.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
