### ISSUE TITLE
`r/vsphere_folder` : "provider produced inconsistent final plan"

### ISSUE THREAD

**Issue by krishz10** [hashicorp/terraform-provider-vsphere#1699]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

Terraform v1.2.6

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.3

### Description

When expanding the plan for vsphere_folder.mgmts to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/vsphere" produced an invalid new value for .path: was cty.StringVal("
│ XXX/YYYY"), but now cty.StringVal("XXX/YYY").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Affected Resources or Data Sources

.

### Terraform Configuration

terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = ">= 2.0"
    }
  }
}

# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = var.username
  password       = var.password
  vsphere_server = var.vcenter

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

# Deploy
data "vsphere_datacenter" "dc" {
  name = var.dc
}

resource "vsphere_folder" "parent" {
  path           = var.parent_folder
  type           = "vm"
  datacenter_id  = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "webs" {
  path           ="${vsphere_folder.parent.path}/web"
  type           = "vm"
  datacenter_id  = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "dbs" {
  path           ="${vsphere_folder.parent.path}/Databases"
  type           = "vm"
  datacenter_id  = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "file_srvs" {
  path           ="${vsphere_folder.parent.path}/File Servers"
  type           = "vm"
  datacenter_id  = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "mgmts" {
  path           ="${vsphere_folder.parent.path}/Management"
  type           = "vm"
  datacenter_id  = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "mgmt_wins" {
  path           ="${vsphere_folder.mgmts.path}/Windows"
  type           = "vm"
  datacenter_id  = data.vsphere_datacenter.dc.id
}

### Debug Output

.

### Panic Output

.

### Expected Behavior

.

### Actual Behavior

.

### Steps to Reproduce

.

**Comment by tenthirtyam** [comment]
Hi @krishz10 👋 

This can be accomplished with the following simple example:

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_folder" "parent" {
  depends_on = [
    vsphere_folder.parent
  ]
  path = "/${data.vsphere_datacenter.dc.name}/vm/${var.vsphere_folder}"
}

resource "vsphere_folder" "parent" {
  path          = var.vsphere_folder
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "web" {
  path          = "${data.vsphere_folder.parent.path}/web"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "db" {
  path          = "${data.vsphere_folder.parent.path}/db"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "file" {
  path          = "${data.vsphere_folder.parent.path}/file"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "mgmt" {
  path          = "${vsphere_folder.parent.path}/management"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "mgmt_win" {
  path          = "${vsphere_folder.mgmt.path}/windows"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_folder" "mgmt_lin" {
  path          = "${vsphere_folder.mgmt.path}/linux"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}
```

Results:

```console
❯ terraform apply -auto-approve
data.vsphere_datacenter.dc: Reading...
data.vsphere_datacenter.dc: Read complete after 0s [id=datacenter-3]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.vsphere_folder.parent will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "vsphere_folder" "parent" {
      + id   = (known after apply)
      + path = "/m01-dc01/vm/gh-1699"
    }

  # vsphere_folder.db will be created
  + resource "vsphere_folder" "db" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "m01-dc01/vm/gh-1699/db"
      + type          = "vm"
    }

  # vsphere_folder.file will be created
  + resource "vsphere_folder" "file" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "m01-dc01/vm/gh-1699/file"
      + type          = "vm"
    }

  # vsphere_folder.mgmt will be created
  + resource "vsphere_folder" "mgmt" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "gh-1699/management"
      + type          = "vm"
    }

  # vsphere_folder.mgmt_lin will be created
  + resource "vsphere_folder" "mgmt_lin" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "gh-1699/management/linux"
      + type          = "vm"
    }

  # vsphere_folder.mgmt_win will be created
  + resource "vsphere_folder" "mgmt_win" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "gh-1699/management/windows"
      + type          = "vm"
    }

  # vsphere_folder.parent will be created
  + resource "vsphere_folder" "parent" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "gh-1699"
      + type          = "vm"
    }

  # vsphere_folder.web will be created
  + resource "vsphere_folder" "web" {
      + datacenter_id = "datacenter-3"
      + id            = (known after apply)
      + path          = "m01-dc01/vm/gh-1699/web"
      + type          = "vm"
    }

Plan: 7 to add, 0 to change, 0 to destroy.
vsphere_folder.parent: Creating...
vsphere_folder.parent: Creation complete after 0s [id=group-v136013]
data.vsphere_folder.parent: Reading...
vsphere_folder.mgmt: Creating...
data.vsphere_folder.parent: Read complete after 0s [id=group-v136013]
vsphere_folder.file: Creating...
vsphere_folder.web: Creating...
vsphere_folder.db: Creating...
vsphere_folder.mgmt: Creation complete after 1s [id=group-v136014]
vsphere_folder.mgmt_win: Creating...
vsphere_folder.mgmt_lin: Creating...
vsphere_folder.db: Creation complete after 0s [id=group-v136015]
vsphere_folder.web: Creation complete after 0s [id=group-v136016]
vsphere_folder.file: Creation complete after 0s [id=group-v136017]
vsphere_folder.mgmt_lin: Creation complete after 0s [id=group-v136018]
vsphere_folder.mgmt_win: Creation complete after 0s [id=group-v136019]

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.
```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/7771363/181641856-58f010fd-745b-4367-9d9e-c4b349fd6c7e.png">

**In the future. please format the code and complete the issue report per the template.**

<img width="873" alt="image" src="https://user-images.githubusercontent.com/7771363/181641926-db98d742-118e-428e-9a44-768844482357.png">

Also, for community assistance and discussions, please use [discuss.hashicorp.com](discuss.hashicorp.com) as seen here:

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/7771363/181642140-21c5bd55-45b0-4b87-b6da-f89ea3480d64.png">

You can also seek help on the VMware {Code} Slack workspace in the [#terraform channel](https://vmwarecode.slack.com/archives/C1647LTK7).

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by krishz10** [comment]
I have used your code but still getting same error

 When expanding the plan for vsphere_folder.mgmt to include new values
learned so far during apply, provider "
registry.terraform.io/hashicorp/vsphere" produced an invalid new value for
.path: was cty.StringVal(" Terraform/management"),
│ but now cty.StringVal("Terraform/management").

**Comment by tenthirtyam** [comment]
The plan provided was tested on vSphere 7.0.3. Your results may be due to an environmental configuration returning `Terraform/management`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
If you need further assistance, please provide your full, **formatted** configuration **and** variables for reproduction.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
