### ISSUE TITLE
Not able to create multiple TF providers through vsphere in terraform.

### ISSUE THREAD

**Issue by raja444** [hashicorp/terraform-provider-vsphere#1703]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.4

### Terraform Provider

v2.0.2

### VMware vSphere

6.7.0

### Description

Unable to create multiple tf providers through vsphere in terraform.

is there any limitation, Terraform will perform any particular vsphere client version ?

### Affected Resources or Data Sources

With single tf providers, i m able to create vm and access.
but with multiple tf providers, im  unable to create it.

### Terraform Configuration

![image](https://user-images.githubusercontent.com/62252606/182108909-ff847224-2831-4df1-95c2-9820f712dc7f.png)

### Debug Output

![image](https://user-images.githubusercontent.com/62252606/182108940-3a1dcbb1-b199-406c-ab62-4ad56f9bd617.png)

### Expected Behavior

vm should able to create.

### Actual Behavior

unable to create vm's.

### Steps to Reproduce

just create multiple tf providers and try to create vm.

**Comment by tenthirtyam** [comment]
This is a general Terraform configuration question and not an issue with the provider.

You'll need to the `alias` [meta-argument](https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations) for the provider configuration.

High-level Example:

```hcl
provider "vsphere" {
  alias = "foo"
  # ... provider config
}

provider "vsphere" {
  alias = "bar"
  # ... provider config
}

resource "vsphere_compute_cluster" "foo" {
  provider = vsphere.foo
  # ... cluster config
}

resource "vsphere_compute_cluster" "bar" {
  provider = vsphere.bar
  # ... cluster config
}
```

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
