### ISSUE TITLE
error reconfiguring virtual machine: error processing disk changes post-clone: disk.0

### ISSUE THREAD

**Issue by EmmaWrong** [hashicorp/terraform-provider-vsphere#1705]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.9

### Terraform Provider

v2.2.0

### VMware vSphere

6.7.0.5

### Description

creating a new ovf image from remote I get this error:
Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: NoPermission: RESOURCE (vm-663125:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-663125), ACTION (PolicyIDByVirtualDisk)

using the code below

I checked the permission, especially the Profile-driven storage -> Profile-driven storage view permission which is set on cluster level. Using govc with the same vsphere environment and user, the ovf provisioning is working without problems using this code:

```
$GOVCBIN import.spec $IGNFOLDER/images/$CLUSTERBASEVERSION.$CLUSTERPATCHVERSION.ova | python -m json.tool > $IGNFOLDER/images/rhcos.json			
					seachandreplaceinfile \"Network\":.* \"Network\":\"$VLAN\" $IGNFOLDER/images/coreos.json
```

`$GOVCBIN import.ova -name=$TEMPLATENAME$TEMPLATEID -options=$IGNFOLDER/images/coreos.json -host=$TEMPLATEHOST -ds=$DATASTOREPATH -folder=$TEMPLATEFOLDER $IGNFOLDER/images/$CLUSTERBASEVERSION.$CLUSTERPATCHVERSION.ova`				

So there might be a difference in the implementation between tf and govc

### Affected Resources or Data Sources

```
+ ovf_network_map           = {
              + "VM Network" = "dvportgroup-500892"
            }
```

### Terraform Configuration

```
ovf_deploy {
        remote_ovf_url            = "${var.http_server}/${var.image_path}/${each.key}"
        disk_provisioning         = "thin"
        ip_protocol               = "IPV4"
        ip_allocation_policy      = "STATIC_MANUAL"
        ovf_network_map   = {
            "VM Network" = data.vsphere_network.network.id
        }
    }
```

### Debug Output

Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: NoPermission: RESOURCE (vm-663125:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-663125), ACTION (PolicyIDByVirtualDisk)

### Expected Behavior

network is attached to the vm

### Actual Behavior

Exits with error

### Steps to Reproduce

no

**Comment by tenthirtyam** [comment]
Hi @EmmaWrong,

Could you please apply code formatting to the configuration and console outputs using the markdown tools per the issue template?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Check to ensure the following are present:

```
VirtualMachine.Config.SwapPlacement
StorageProfile.View
```

Ensure the `StorageProfile` permissions on the top level element in the hierarchy.

**Comment by EmmaWrong** [comment]
These are the permissions. StorageProfile on top level is not allowed on a non-root user in our company and it works with these permissions with govc but not with TF

## Datastore
Allocate space
Browse datastore
Remove file
Update virtual machine files
Update virtual machine metadata



## Folder
Create folder
Delete folder
Move folder
Rename folder


## vSphere Tagging
Assign or Unassign vSphere Tag
Create vSphere Tag
Create vSphere Tag Category
Delete vSphere Tag
Delete vSphere Tag Category
Edit vSphere TagEdit vSphere Tag Category
Modify UsedBy Field For Category
Modify UsedBy Field For Tag


## Network
Assign network


## Resource
Apply recommendation
Assign vApp to resource pool
Assign virtual machine to resource pool



## Profile-driven storage
Profile-driven storage update
Profile-driven storage view




## vApp
Add virtual machine
Assign resource pool
Assign vApp
Clone
Create
Delete
Export
Import
Move
Power off
Power on
Rename
Suspend
Unregister
View OVF environment
vApp application configuration
vApp instance configuration
vApp managedBy configuration
vApp resource configuration


## Virtual machine
Change Configuration
Acquire disk lease
Add existing disk
Add new disk
Add or remove device
Advanced configuration
Change CPU count
Change Memory
Change Settings
Change Swapfile placement
Change resource
Configure Host USB device
Configure Raw device
Configure managedBy
Display connection settings
Extend virtual disk
Modify device settings
Query Fault Tolerance compatibility
Query unowned files
Reload from path
Remove diskRename
Reset guest informationSet annotation
Toggle disk change tracking
Toggle fork parent
Upgrade virtual machine compatibility
privilege.VirtualMachine.Config.Unlock.label

Edit Inventory
Create from existing
Create new
Move
Register
Remove
Unregister

Guest operations
Guest operation alias modification
Guest operation alias query
Guest operation modifications
Guest operation program execution
Guest operation queries

Interaction
Answer question
Backup operation on virtual machine
Configure CD media
Configure floppy media
Connect devices
Console interaction
Create screenshot
Defragment all disks
Drag and drop
Guest operating system management by VIX API
Inject USB HID scan codes
Install VMware Tools
Pause or Unpause
Perform wipe or shrink operationsPower off
Power on
Record session on virtual machine
Replay session on virtual machine
Reset
Resume Fault Tolerance
SuspendS
uspend Fault Tolerance
Test failover
Test restart Secondary VM
Turn off Fault Tolerance
Turn on Fault Tolerance

Provisioning
Allow disk access
Allow file access
Allow read-only disk access
Allow virtual machine download
Allow virtual machine files upload
Clone templateClone virtual machine
Create template from virtual machine
Customize guestDeploy templateMark as template
Mark as virtual machine
Modify customization specification
Promote disks
Read customization specifications
Service configuration
Allow notifications
Allow polling of global event notifications
Manage service configurations
Modify service configuration
Query service configurations
Read service configuration

**Comment by tenthirtyam** [comment]
Bear in mind that `govc` and the provider are different implementations. There are instances where additional permissions are required by the provider due to implementation details.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Please refer to this similar issue.

https://github.com/hashicorp/terraform-provider-vsphere/issues/1658

**Comment by EmmaWrong** [comment]
This is sad, because not every TF implementer has high permissions on the environment, so useless for some groups, altough govc works.

**Comment by tenthirtyam** [comment]
Also, please refer to this issue: https://github.com/hashicorp/terraform-provider-vsphere/issues/1216

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Yes, unfortunately this is a requirement of the provider implementation by the original maintainers. 

Please feel free to propose an enhancement request that may be able to address such a requirement as technical debt. 

If you would like to [contribute](CONTRIBUTING.md) such an enhancement to the project, contributions are also welcome.

In the meantime, please review the previously mentioned issues. Both mention the top-level requirement.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Hi @EmmaWrong,

If setting the permissions as described in the other issues resolves the reported issue, please update the issue and let us know the status. At this time, it's a requirement for the provider implementation.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
