### ISSUE TITLE
Imported Attributes' Values Not Match Creation Default Values/Creation Module Defined

### ISSUE THREAD

**Issue by mingjliu-cisco** [hashicorp/terraform-provider-vsphere#1706]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v0.14.6

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.2

### Description

Once the VM being created by `terraform apply` command, and trying to import the same VM without changes, we are seeing following differences.
PS: already added attributes to avoid `clone` to be present for imported VM terraform module and added the attributes `"imported": true`.

    ~ resource "vsphere_virtual_machine" "virtual_machine" {
        + datastore_cluster_id                    = "group-p19533"
          id                                      = "42144650-cee2-ad1f-7935-5e0420b19cab"
          name                                    = "test_vm_1"
        ~ sata_controller_count                   = 1 -> 0
          tags                                    = []
        ~ wait_for_guest_net_timeout              = 5 -> 0
          # (63 unchanged attributes hidden)
  
        ~ disk {
            ~ keep_on_remove   = true -> false
              # (19 unchanged attributes hidden)
          }
        ~ disk {
            ~ keep_on_remove   = true -> false
              # (19 unchanged attributes hidden)
          }
  
          # (1 unchanged block hidden)
      }

As per the [document](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine), `keep_on_remove` is defaulted with false, and after creation, the value is `false` in state file, but once imported, it turned out to be `true`. 
![图片](https://user-images.githubusercontent.com/23260919/182312699-82771e90-4172-4e91-aaff-e8cabdb51016.png)

`sata_controller_count` is the same to `keep_on_remove`, which is not configured and the state file being value `0`, but imported one is `1`.

`wait_for_guest_net_timeout` was given value 0 when creating the VM, but imported as value 5.

`datastore_cluster_id` was given value while the VM creation, but imported as `null`.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

    
      resource "vsphere_virtual_machine" "virtual_machine" {
        wait_for_guest_net_timeout = 0
        dynamic disk {
          for_each = var.disks
          content {
            label            = disk.value["label"])
            size             = disk.value["disk_size"]
            unit_number      = disk.value["unit_number"]
            thin_provisioned = disk.value["thin_provisioned"]
            eagerly_scrub    = disk.value["eagerly_scrub"]
            disk_mode        = disk.value["disk_mode"]
          }
        }
        dynamic clone {
          for_each = var.imported ? [] : [1]
          content {
            timeout       = var.clone_timeout_minutes
            template_uuid = var.template_uuid
            customize {
              timeout         = 0
              dns_server_list = var.dns_server_list
              dns_suffix_list = [var.vm_domain]
              ipv4_gateway    = var.gateway
            }
          }
        }
      
        name                       = var.host_name
        resource_pool_id           = data.vsphere_compute_cluster.compute_cluster.resource_pool_id
        datastore_cluster_id       = data.vsphere_datastore_cluster.datastore_cluster.id
        enable_logging             = var.enable_logging
        folder                     = var.folder_name
      
        num_cpus            = var.cpu
        cpu_reservation     = var.cpu_reservation
        cpu_hot_add_enabled = var.cpu_hot_add_enabled
      
        memory                 = var.memory
        memory_reservation     = var.memory_reservation
        memory_hot_add_enabled = var.memory_hot_add_enabled
        guest_id               = var.guest_id
        scsi_type              = var.scsi_type
        scsi_controller_count  = var.scsi_controller_count
      }

### Debug Output

N/A

### Expected Behavior

- Imported values should be default values which was not given in the creation terraform configuration.
- Imported values should be given values which was given in the creation terraform configuration.

### Actual Behavior

as described in description part.

### Steps to Reproduce

- create a vm without specifying these default attributes, and setup datastore cluster
- Import the same VM, with altered import attribute without changing clone dependent attrbutes.

**Comment by tenthirtyam** [comment]
Hi @MountainBlanc,

Firstly, thank you for reporting the issue and fully completing the issue template - it is **much** appreciated.

Can you please test and verify if the issue occurs with v2.2.0 (`latest`) of the provider? I notices you posted `v2.0.0`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by MountainBlanc** [comment]
Hi @tenthirtyam ,
Following screenshot(left side being `terraform apply` result, right side being `terraform import` result) showing that with 2.2.0 version provider the value difference still there.
![图片](https://user-images.githubusercontent.com/23260919/182758809-2f57e992-f9c9-4312-b883-36557dc49ebc.png)

**Comment by tenthirtyam** [comment]
Thanks for confirming. I’ve updated the issue details to `v2.2.0`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
