### ISSUE TITLE
Setting `datadisksize` vApp property for OVA/OVF deployment has no effect

### ISSUE THREAD

**Issue by IreshMM** [hashicorp/terraform-provider-vsphere#1708]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.2.6

### Terraform Provider

2.2.0

### VMware vSphere

7.0.2.00400

### Description

For an OVA deployment, in the case where disk size is taken as an argument as below,

```xml
<ProductSection ovf:required="false">
      <Info>Appliance customization</Info>
      <Product>APIConnect</Product>
      <Category>Disk settings</Category>
      <Property ovf:key="datadisksize" ovf:qualifiers="MinValue(50)" ovf:runtimeConfigurable="false" ovf:type="int" ovf:userConfigurable="true" ovf:value="250">
        <Label>Size for the data disk</Label>
        <Description>The size of the disk, in gigabytes. Min 50GB.</Description>
      </Property>
</ProductSection>
```

Used to set the disk size as below,
```xml
<DiskSection>
    <Info>Virtual disk information</Info>
    <Disk ovf:capacity="${datadisksize}" ovf:capacityAllocationUnits="byte * 2^30" ovf:diskId="vmdisk2" ovf:fileRef="" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" ovf:populatedSize="0"/>
</DiskSection>
```

Disk size argument has no effect on the actual disk size and default disk is used for the virtual machine. This is probably due to virtual machine being created first along with the disk allocation and vApp properties are set afterwords.

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`

### Terraform Configuration

```hcl

resource "vsphere_virtual_machine" "management-vm" {
  name                       = "APIConnect-management"
  folder                     = data.vsphere_folder.folder.path
  datacenter_id              = data.vsphere_datacenter.datacenter.id
  datastore_id               = data.vsphere_datastore.datastore.id
  host_system_id             = data.vsphere_host.esxi-host.id
  resource_pool_id           = data.vsphere_resource_pool.default.id
  guest_id                   = data.vsphere_ovf_vm_template.management-ova.guest_id
  scsi_type                  = data.vsphere_ovf_vm_template.management-ova.scsi_type
  nested_hv_enabled          = data.vsphere_ovf_vm_template.management-ova.nested_hv_enabled
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  ovf_deploy {
    allow_unverified_ssl_cert = true
    local_ovf_path            = data.vsphere_ovf_vm_template.management-ova.local_ovf_path
    disk_provisioning         = data.vsphere_ovf_vm_template.management-ova.disk_provisioning
    ovf_network_map           = data.vsphere_ovf_vm_template.management-ova.ovf_network_map
    ip_protocol               = "IPV4"
    ip_allocation_policy      = "STATIC_MANUAL"
    deployment_option         = "small"
  }
  cdrom {
    datastore_id = data.vsphere_datastore.datastore.id
    path         = vsphere_file.management-iso.destination_file
  }
  vapp {
    properties = {
      "datadisksize" = "300"
    }
  }
}
```

### Debug Output

https://gist.github.com/IreshMM/c13337de02dd8ea8f5229d1698210769

### Expected Behavior

Disk size being affected

### Actual Behavior

Disk size isn't affected

### Steps to Reproduce

Use a OVA template with a similar behavior as mentioned in Description 

### Environment Details

```console
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

### References

#1074

**Comment by tenthirtyam** [comment]
Please provide a reference to the source OVA/OVF file.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by IreshMM** [comment]
@tenthirtyam Issue was with IBM API Connect version 10 appliances which I don't have permission to share publicly. What we can do however is that test the scenario with a sample ova for this specific use case.

**Comment by tenthirtyam** [comment]
Hi @IreshMM, 

Please provide the sample OVA/OVF with the same ovf/vapp properties and I'll be happy to test the scenario.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
