### ISSUE TITLE
Windows VM keep restart upon launching from template

### ISSUE THREAD

**Issue by Kezuko** [hashicorp/terraform-provider-vsphere#1709]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.6

### Terraform Provider

v2.2.0

### VMware vSphere

v6.7.0

### Description

I am trying to set up a windows server 2016 from a template and call it to run a few commands using run_once_command_list, but it seems that my VM keeps restarting before the VM officially run finish the powershell commands. Upon restart, I could see that the install-WindowsFeature is in, and it imported the modules, but the VM wasn't a primary domain controller. If I were to do it manually with all these commands in a VM, it will automatically becomes a primary DC. However, it doesn't seems to happen to it when i use terraform and clone it from the template and calls all these functions. Is it some sort of bug?

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`

### Terraform Configuration

```hcl
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      windows_options {
        computer_name   = "terraform-testing"
        admin_password  = "passw0rd"
        auto_logon      = true
        auto_logon_count = 2

        run_once_command_list = [
          "winrm quickconfig -force",
          "winrm set winrm/config @{MaxEnvelopeSizekb=\"100000\"}",
          "winrm set winrm/config/Service @{AllowUnencrypted=\"true\"}",
          "winrm set winrm/config/Service/Auth @{Basic=\"true\"}",
          "netsh advfirewall set allprofiles state off",
         "powershell.exe Install-WindowsFeature -name AD-Domain-Services -IncludeManagementTools",
         "powershell.exe Import-Module ADDSDeployment",
         "powershell.exe $password = ConvertTo-SecureString Sing@tel -AsPlainText -Force",
          "powershell.exe Install-ADDSForest -CreateDnsDelegation:$false -DomainMode '7' -DomainName 'testing.local' -DomainNetbiosName 'testing' -ForestMode '7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true"
        ]
      }
      network_interface {
        ipv4_address = "var.ipaddress"
        ipv4_netmask = 24
      }
      ipv4_gateway = "var.gatewayipaddress"
    }
  }
}
```

### Debug Output

-

### Expected Behavior

I would have expected the VM that was launched from the template to become a Primary DC.

### Actual Behavior

VM did not become a primary DC.

### Steps to Reproduce

Following the codes will re-produce i will assume.

**Comment by tenthirtyam** [comment]
It would be prudent to first to a comparison to rule out if the scenario works in the traditional manner.

If you attempt an typical clone from template from the vSphere UI and apply the same run once commands for the guest customization do you get the same or different result? 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
> 

If I were to use the command on the template without using terraform, it works and managed to promote the template to primary domain controller. But if I were to use terraform and perform the run once commands on the template, it will not become a primary domain controller, and it seems like this "powershell.exe Install-ADDSForest -CreateDnsDelegation:$false -DomainMode '7' -DomainName 'testing.local' -DomainNetbiosName 'testing' -ForestMode '7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true" code was not being executed.

**Comment by tenthirtyam** [comment]
Can you please confirm if the same issue occurs if the same commands are provided to a VM guest customization workflow vs just running the commands manually on a provisioned VM?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
> Can you please confirm if the same issue occurs if the same commands are provided to a VM guest customization workflow vs just running the commands manually on a provisioned VM?
> 
> **Ryan Johnson** Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

The same issue does not occurs when I run the commands manually on a provisioned VM.

**Comment by tenthirtyam** [comment]
My aologies, I think you may be misunderstanding my question. If you perform the deployment in the vSphere UI using a **guest customization specification** and provide the same set of run once commands to the **guest customization specification**, what are the results.

This would help to determine if it's an issue in the fictions that pass the command to the guest customization workflow or another other limitation due to the sequence.

Your other option is to simply use a PowerShell provisioner block and pass the commands after the completion of guest customizations.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
> My apologies, I think you may be misunderstanding my question. If you perform the deployment in the vSphere UI using a **guest customization specification** and provide the same set of run once commands to the **guest customization specification**, what are the results.
> 
> This would help to determine if it's an issue in the functions that pass the commands to the guest customization workflow or another other limitation due to the sequence.
> 
> Your other option is to simply use a PowerShell provisioner block and pass the commands after the completion of guest customizations.
> 
> **Ryan Johnson** Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

I am sorry, as I am pretty new to vSphere. How do I perform the deployment in the vSphere UI using a guest customization specification? Also, will like to check, when you mentioned "PowerShell provisioner block" do you mean this? https://www.terraform.io/language/resources/provisioners/local-exec

**Comment by tenthirtyam** [comment]
Regarding the provisioner, yes, that's the correct documentation.

Regarding testing with guest customization specifications (_assuming you are using vCenter Server and not a standalone host_) see https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-EB5F090E-723C-4470-B640-50B35D1EC016.html and https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-F3E382AB-72F6-498A-BD26-7EC0BFE320A0.html.


**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
I seems to have difficulties understanding that 2 document. How do I enter commands via the customisation of OS?

May I ask for provisioner, it seems like it is used in the main resource {} rather than inside the "windows options", will it still be able to run the commands?

**Comment by Kezuko** [comment]
Seems that when I tried to run using provisioner, it has this error.
│ Error: local-exec provisioner error
│
│   with vsphere_virtual_machine.Wins-Ad,
│   on main.tf line 44, in resource "vsphere_virtual_machine" "Wins-Ad":
│   44:   provisioner "local-exec" {
│
│ Error running command '        "winrm quickconfig -force"
│         "winrm set winrm/config '@{MaxEnvelopeSizekb="100000"}'"
│         "winrm set winrm/config/Service '@{AllowUnencrypted="true"}'"
│         "winrm set winrm/config/Service/Auth '@{Basic="true"}'"
│         "netsh advfirewall set allprofiles state off"
│ ': exec: "PowerShell": executable file not found in $PATH. Output:

**Comment by tenthirtyam** [comment]
Something like this:

```hcl
provisioner "remote-exec" {
    depends_on = [vsphere_virtual_machine.foo]
    inline = [
"powershell.exe -Command Write-Host 'hello'",
"powershell.exe -Command Write-Host 'world'"
]
    connection {
      type     = "winrm"
      https = false
      user     =  var.winrm_user
      password = var.winrm_password
      agent = false,
      insecure = true             
    }
  }

```
Where `var.winrm_user` = `Administrator`.

Ensure WinRM is enabled in your base image.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
You need to ensure that the WinRM settings are **already enabled** in your base image, for example, if you create them with Packer.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
Seems to have some sort of error.
│ Error: Unsupported argument
│
│   on main.tf line 45, in resource "vsphere_virtual_machine" "Wins-Ad":
│   45:     depends_on = [vsphere_virtual_machine.Wins-Ad]
│
│ An argument named "depends_on" is not expected here.
╵
╷
│ Error: Missing required argument
│
│   on main.tf line 50, in resource "vsphere_virtual_machine" "Wins-Ad":
│   50:     connection {
│
│ The argument "host" is required, but no definition was found.

**Comment by tenthirtyam** [comment]
Apologies, I'm doing it from (poor) memory in my phone whilst on vacation. I updated the example above to be added to the resource block.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
I should be the one apologising for disturbing on your vacation. By the way, Just want to check, they required me to fill in "host" variable in the connection. Is that to fill in with the IP Address that I going to give it to that vm?

**Comment by Kezuko** [comment]
Wow, it seems to work with hello world. I will try it with the other commands that I want to try

**Comment by tenthirtyam** [comment]
Yes, I added the `host` argument to the example. You can get it from the resource itself or pass the IP as a variable that you know you'll be setting.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
vsphere_virtual_machine.Wins-Ad (remote-exec): C:\Users\Administrator>powershell.exe -Command Install-ADDSForest -CreateDnsDelegation:$false -DomainMode '7' -DomainName 'testing.local' -DomainNetbiosName 'testing' -ForestMode '7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true
vsphere_virtual_machine.Wins-Ad (remote-exec): Install-ADDSForest : Cannot bind parameter 'SafeModeAdministratorPassword' to the target. Exception setting
vsphere_virtual_machine.Wins-Ad (remote-exec): "SafeModeAdministratorPassword": "SafeModeAdministratorPassword cannot be null."
vsphere_virtual_machine.Wins-Ad (remote-exec): At line:1 char:186
vsphere_virtual_machine.Wins-Ad (remote-exec): + ... 7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force: ...
vsphere_virtual_machine.Wins-Ad (remote-exec): +                                                         ~~~~~~~~~
vsphere_virtual_machine.Wins-Ad (remote-exec):     + CategoryInfo          : WriteError: (:) [Install-ADDSForest], ParameterBindingException
vsphere_virtual_machine.Wins-Ad (remote-exec):     + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.DirectoryServices.Deployment.PowerShell.Commands.Instal
vsphere_virtual_machine.Wins-Ad (remote-exec):    lADDSForestCommand

╷
│ Error: remote-exec provisioner error
│
│   with vsphere_virtual_machine.Wins-Ad,
│   on main.tf line 44, in resource "vsphere_virtual_machine" "Wins-Ad":
│   44:   provisioner "remote-exec" {
│
│ "C:/Temp/terraform_727529087.cmd" exit status: 1


Seems like I have faced the issue where it stated the "SafeModeAdministratorPassword" is null but I did declare $password to be my password.

This are the commands I have used
 provisioner "remote-exec" {
    inline = [
      "powershell.exe -Command Import-Module ADDSDeployment",
      "powershell.exe -Command $password = ConvertTo-SecureString passw0rd -AsPlainText -Force",
      "powershell.exe -Command Install-ADDSForest -CreateDnsDelegation:$false -DomainMode '7' -DomainName 'testing.local' -DomainNetbiosName 'testing' -ForestMode '7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true"]
  }
    connection {
      type     = "winrm"
      https = false
      user     =  "Administrator"
      password = "Sing@tel"
      agent = false
      insecure = true
      host = "172.31.102.156"
    }

**Comment by Kezuko** [comment]
vsphere_virtual_machine.Wins-Ad (remote-exec): C:\Users\Administrator>powershell.exe -Command Install-ADDSForest -CreateDnsDelegation:$false -DomainMode '7' -DomainName 'testing.local' -DomainNetbiosName 'testing' -ForestMode '7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true
vsphere_virtual_machine.Wins-Ad (remote-exec): Install-ADDSForest : Cannot bind parameter 'SafeModeAdministratorPassword' to the target. Exception setting
vsphere_virtual_machine.Wins-Ad (remote-exec): "SafeModeAdministratorPassword": "SafeModeAdministratorPassword cannot be null."
vsphere_virtual_machine.Wins-Ad (remote-exec): At line:1 char:186
vsphere_virtual_machine.Wins-Ad (remote-exec): + ... 7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force: ...
vsphere_virtual_machine.Wins-Ad (remote-exec): + ~~~~~~~~~
vsphere_virtual_machine.Wins-Ad (remote-exec): + CategoryInfo : WriteError: (:) [Install-ADDSForest], ParameterBindingException
vsphere_virtual_machine.Wins-Ad (remote-exec): + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.DirectoryServices.Deployment.PowerShell.Commands.Instal
vsphere_virtual_machine.Wins-Ad (remote-exec): lADDSForestCommand

╷
│ Error: remote-exec provisioner error
│
│ with vsphere_virtual_machine.Wins-Ad,
│ on main.tf line 44, in resource "vsphere_virtual_machine" "Wins-Ad":
│ 44: provisioner "remote-exec" {
│
│ "C:/Temp/terraform_727529087.cmd" exit status: 1

Seems like I have faced the issue where it stated the "SafeModeAdministratorPassword" is null but I did declare $password to be my password.

This are the commands I have used
provisioner "remote-exec" {
inline = [
"powershell.exe -Command Import-Module ADDSDeployment",
"powershell.exe -Command $password = ConvertTo-SecureString passw0rd -AsPlainText -Force",
"powershell.exe -Command Install-ADDSForest -CreateDnsDelegation:$false -DomainMode '7' -DomainName 'testing.local' -DomainNetbiosName 'testing' -ForestMode '7' -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true"]
}
connection {
type = "winrm"
https = false
user = "Administrator"
password = "passw0rd"
agent = false
insecure = true
host = "172.31.102.156"
}

**Comment by tenthirtyam** [comment]
It's probably related to how the password in the script is being processed / passed as a secure string rather than a specific issue with the provider itself:

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kezuko** [comment]
> It's probably related to how the password in the script is being processed / passed as a secure string rather than a specific issue with the provider itself:
> 
> **Ryan Johnson** Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

Yes seems like it, managed to get the comment got through but it doesn't work. Urgh, its a pain in the ass for trying to get the AD and promote the VM as Primary DC. But thank you so much for your help!

**Comment by tenthirtyam** [comment]
You're welcome!

Feel free to close the issue for the provider if you are satisfied that it's related to PowerShell. Hope you're able to get the command syntax working for the provisioner method.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
