### ISSUE TITLE
Add build for openbsd_amd64

### ISSUE THREAD

**Issue by eradman** [hashicorp/terraform-provider-vsphere#1710]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/vsphere...
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/vsphere v2.2.0 does not have a package
│ available for your current platform, openbsd_amd64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers
│ are available for all platforms. Other versions of this provider may have
│ different platforms supported.
```

### Use Case(s)

This would allow vsphere to be managed by terraform on OpenBSD

```
$ uname -a
OpenBSD t460s.eradman.com 7.1 GENERIC.MP#3 amd64
```

**Comment by tenthirtyam** [comment]
The following operating system/architecture combinations for compiled binaries are available in the registry as a part of the release process defined in goreleaser for most Official provider.

- Darwin / AMD64
- Darwin / ARMv8
- Linux / AMD64
- Linux / ARMv8 (sometimes referred to as AArch64 or ARM64)
- Linux / ARMv6
- Windows / AMD64

Binaries for the following combinations are also shipped; however, the maintainers typically do not prioritize fixes for these:

- Linux / 386
- Windows / 386
- FreeBSD / 386
- FreeBSD / AMD64

Please consider using one of the recommended system/architecture combinations. Alternatively, you can build and [reference the provide locally](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/docs/INSTALL.md#configure-the-terraform-configuration-files-1).

[Reference](https://www.terraform.io/registry/providers/os-arch)

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by eradman** [comment]
@tenthirtyam thanks for the quick reply. I was able to build this locally

```sh
RELEASE="2.2.0"
DST="$HOME/.terraform.d/plugins/local/hashicorp/vsphere/$RELEASE/openbsd_amd64"
mkdir -p $DST
ftp https://github.com/hashicorp/terraform-provider-vsphere/archive/refs/tags/v$RELEASE.tar.gz
tar -zxf v$RELEASE.tar.gz
cd terraform-provider-vsphere-$RELEASE
go build
mv terraform-provider-vsphere $DST/terraform-provider-vsphere_v$RELEASE
```

With the following provider:

```
vsphere = {
    source = "local/hashicorp/vsphere"
    version = "2.2.0"
}
```

**Comment by tenthirtyam** [comment]
Excellent!

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
If you really want to have a little fun with it you could wrap it into a container.

Here's a base example:

https://github.com/tenthirtyam/container-terraform/blob/main/Dockerfile


**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
