### ISSUE TITLE
Add support for joining ESXi hosts to Active Directory

### ISSUE THREAD

**Issue by jatinpurohit92** [hashicorp/terraform-provider-vsphere#1732]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Please add the support for allowing the ESXi host to join the AD domain. PowerCLI ref: https://developer.vmware.com/docs/powercli/latest/vmware.vimautomation.core/commands/set-vmhostauthentication/#JoinDomain 

### Use Case(s)

Security Audit

**Comment by tenthirtyam** [comment]
@jatinpurohit92 - please consider providing a govmomi reference, if available.
