### ISSUE TITLE
Add support for including a `description` attribute in `r/vsphere_role`

### ISSUE THREAD

**Issue by MarcusFoelling** [hashicorp/terraform-provider-vsphere#1734]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

it seems that current implementation of vsphere_role resource of hashicorp/vsphere provider is lacking the ability to define the description property of a given vCenter Role

### Use Case(s)

current implementation does not allow to configure mentioned content

### Potential Terraform Provider Configuration

```hcl
resource vsphere_role "role1" {
  name = "my_terraform_role"
  description = "this role can manage alerts and datacenters"
  role_privileges = ["Alarm.Acknowledge", "Alarm.Create", "Datacenter.Create", "Datacenter.Move"]
}
```

### References

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/vsphere_role

**Comment by tenthirtyam** [comment]
`AuthorizationManager.AddRole` in `vmware/govomi` does not support the inclusion of the description (summary) to the pass to the resource

Might need some more digging, but this may be an upstream requirement.

https://github.com/vmware/govmomi/blob/bb0307eb84ae981cfca7fc8d680821a2c2be3c6d/object/authorization_manager.go#L138-L143

https://github.com/hashicorp/terraform-provider-vsphere/blob/2f53f7a557185a49b97313de823d663935d089de/vsphere/resource_vsphere_role.go#L48-L64

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
