### ISSUE TITLE
Add support for `template_id` in `clone` block as an alternative option to `template_uuid`

### ISSUE THREAD

**Issue by mingjliu-cisco** [hashicorp/terraform-provider-vsphere#1736]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Template UUID is not Unique per vCenter, which means the template uuid could be shared by different VM template in multiple data centers in the same vCenter(accessible vCenters).

As such it would cause problems when using `template_uuid` as identifier to VM template.

Hypothesis: template_id is unique across accessible vCenters

### Use Case(s)

One shared VM template located in one data store shared for multiple data center/vCenter to clone VMs. 

### Potential Terraform Provider Configuration

`
clone {
    template_id = "xxxxxx"
    # template_uuid = "xxxx"
}
`

**Comment by tenthirtyam** [comment]
The scope of this request would be covered by an [existing backlog item](https://github.com/hashicorp/terraform-provider-vsphere/issues/282) for the transition to the instance UUID.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
