### ISSUE TITLE
Error deploying from remote ova/ovf

### ISSUE THREAD

**Issue by waldner** [hashicorp/terraform-provider-vsphere#1739]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.8

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.3

### Description

Trying to create a VM from a remote OVA image fails with the following error:

```
Error: error while importing ovf/ova template, error while uploading the disk vm-2.nvram Put "https://10.1.0.2/nfc/52403efe-5044-eef5-28ec-ae066ac4d521/disk-1.nvram": net/http: HTTP/1.x transport connection broken: http: ContentLength=270840 with Body length 133950
```
Here are the contents of the ova:

```
$ tar -tvf vm.ova
-rw-r--r-- nobody/nobody 133950 2022-08-26 10:26 vm-2.nvram
-rw-r--r-- nobody/nobody 1507931648 2022-08-26 10:26 vm-1.vmdk
-rw-r--r-- nobody/nobody       6435 2022-08-31 10:11 vm.ovf
-rw-r--r-- nobody/nobody        283 2022-08-31 11:57 vm.mf
```

Same error if I unpack the ova and use `https://myserver.com/vm.ovf` as the URL source.

Using govc from govmomi to deploy the same image from the same URL works (deploying the ova from the vsphere web interface also works). 

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`

### Terraform Configuration

```
{
  "provider": {
    "vsphere": {
      "allow_unverified_ssl": "true",
      "password": "redacted",
      "user": "redacted@redacted.com",
      "vsphere_server": "10.1.0.250"
    }
  },
  "resource": {
    "vsphere_virtual_machine": {
      "test-vm": {
        "boot_delay": 5,
        "datastore_id": "datastore-3009",
        "disk": [
          {
            "label": "disk0",
            "size": 20,
            "thin_provisioned": true
          }
        ],
        "enable_disk_uuid": true,
        "firmware": "efi",
        "guest_id": "centos8_64Guest",
        "host_system_id": "host-37",
        "memory": 2048,
        "name": "TESTVM",
        "num_cpus": 2,
        "ovf_deploy": [
          {
            "disk_provisioning": "thin",
            "ovf_network_map": {
              "MYNET": "network-3002"
            },
            "remote_ovf_url": "https://myserver.com/vm.ova"
          }
        ],
        "resource_pool_id": "resgroup-3008"
      }
    }
  },
  "terraform": {
    "required_providers": {
      "vsphere": {
        "source": "hashicorp/vsphere",
        "version": "2.2.0"
      }
    }
  }
}
```

### Debug Output

```
vsphere_virtual_machine.test-vm: Creating...
vsphere_virtual_machine.test-vm: Still creating... [10s elapsed]
vsphere_virtual_machine.test-vm: Still creating... [20s elapsed]
vsphere_virtual_machine.test-vm: Still creating... [30s elapsed]
vsphere_virtual_machine.test-vm: Still creating... [40s elapsed]
vsphere_virtual_machine.test-vm: Still creating... [50s elapsed]
vsphere_virtual_machine.test-vm: Still creating... [1m0s elapsed]
╷
│ Error: error while importing ovf/ova template, error while uploading the disk vm-2.nvram Put "https://10.1.0.2/nfc/52403efe-5044-eef5-28ec-ae066ac4d521/disk-1.nvram": net/http: HTTP/1.x transport connection broken: http: ContentLength=270840 with Body length 133950
│ 
│   with vsphere_virtual_machine.test-vm,
│   on main.tf.json line 1, in resource.vsphere_virtual_machine.test-vm:
│    1: {"provider":{"vsphere":{"allow_unverified_ssl":"true","password":"redacted","user":"redacted@redacted.com","vsphere_server":"10.1.0.250"}},"resource":{"vsphere_virtual_machine":{"test-vm":{"boot_delay":5,"datastore_id":"datastore-3009","disk":[{"label":"disk0","size":20,"thin_provisioned":true}],"enable_disk_uuid":true,"firmware":"efi","guest_id":"centos8_64Guest","host_system_id":"host-37","memory":2048,"name":"TESTVM","num_cpus":2,"ovf_deploy":[{"disk_provisioning":"thin","ovf_network_map":{"MYNET":"network-3002"},"remote_ovf_url":"https://myserver.com/vm.ova"}],"resource_pool_id":"resgroup-3008"}}},"terraform":{"required_providers":{"vsphere":{"source":"hashicorp/vsphere","version":"2.2.0"}}}}
```

### Expected Behavior

The VM should be created successfully.

### Actual Behavior

An error is produced, as per logs above.

### Steps to Reproduce

`terraform apply` of the above configuration.

**Comment by tenthirtyam** [comment]
Can you reproduce the error with a known public OVA? For example: [Nested_ESXi7.0u3_Appliance_Template_v1.ova](https://download3.vmware.com/software/vmw-tools/nested-esxi/Nested_ESXi7.0u3_Appliance_Template_v1.ova) or [ubuntu-22.04-server-cloudimg-amd64.ova](https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.ova).

[Example](https://github.com/tenthirtyam/terrafom-examples-vmware/blob/main/vsphere/vsphere-virtual-machine/clone-ovf-esxi-simple/main.tf)

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
