### ISSUE TITLE
Unable to find content library `datastore_id` for `r/virtual_machine` cdrom attributes

### ISSUE THREAD

**Issue by spyroot** [hashicorp/terraform-provider-vsphere#1746]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.3

### Terraform Provider

v2.2.0_x5

### VMware vSphere

v7.0.3

### Description

Hi Folks,

It looks like cdrom datastore_id can't resolve content_lib iso.  For example, when you are using center, it contentLib
<img width="919" alt="image" src="https://user-images.githubusercontent.com/11797329/188878583-5cac1d4f-05ea-40a5-aa8d-540d279c01f1.png">

I tried different options none of them worked.  In all cases, I see errors.

```hcl
  cdrom {
    datastore_id = "contentLib"
    path         = "/iso/ph4-rt-refresh"
  }
```

### Affected Resources or Data Sources
vsphere_content_library_item VM

```hcl
data "vsphere_content_library" "iso_library" {
  name = var.iso_library
}

resource "vsphere_virtual_machine" "vm" {
  name             = "foo"
  # skiped

  cdrom {
   # this should work
    datastore_id =  data.vsphere_content_library.iso_library.id
    # this should work
    datastore_id = "contentLib"
   # this technically should have  some sort of path attribute from content vsphere_content_library_item
    path         = "/iso/ph4-rt-refresh"
  }
}
```

### Terraform Configuration

```hcl
data "vsphere_content_library" "iso_library" {
  name = var.iso_library
}
resource "vsphere_content_library_item" "test_iso" {
  name        = "ph4-rt-refresh"
  description = "ph4-rt-refresh"
  file_url    = "http://httpd.mgmt.vmw-nfv.rocks/iso/photon/ph4-rt-refresh.iso"
  library_id  = data.vsphere_content_library.iso_library.id
  type        = "iso"
}

data "vsphere_content_library_item" "library_item_photon" {
  name       = "ph4-rt-refresh"
  type       = "iso"
  library_id = data.vsphere_content_library.iso_library.id
}
 
resource "vsphere_virtual_machine" "vm" {
  name             = "foo"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  num_cpus         = 4
  memory           = 8192
  guest_id         = "other3xLinux64Guest"

  cdrom {
    datastore_id = "contentLib"
    path         = "/iso/ph4-rt-refresh"
  }

  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label = "disk0"
    size  = 40
  }
}
```

### Debug Output

Trimmed.
https://gist.github.com/spyroot/ed35077a488caed8331754fbc8e827b1

### Expected Behavior

It should create VM and attach Cdrom with path to content lib iso.Cdrom

### Actual Behavior

Error

cdrom.0: cannot find datastore: ServerFaultCode: The object 'vim.Datastore:contentLib' has already been deleted or has not been completely created

if I use lib.id it indicates content.lib error

### Steps to Reproduce

Create VM with CDROM and attempt to use iso from the content library.

**Comment by tenthirtyam** [comment]
Hi @spyroot - can you please:

- Update the description. It's currently "REPLACE WITH A SHORT DESCRIPTION`
- Format the code blocks and move the debug output to a Gist per the issue template notes?

<img width="865" alt="image" src="https://user-images.githubusercontent.com/7771363/188881188-a15d4a0d-0620-49ab-aeb0-4b33ec2721c5.png">

Status: `pending-closure`

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by spyroot** [comment]
Sorry, I don't know why the description switched back to replace.

**Comment by tenthirtyam** [comment]
I've updated the formatting to use **```hcl**.

I'm confused by the following:

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "foo"
  # skiped

  cdrom {
   # this should work
    datastore_id =  data.vsphere_content_library.iso_library.id
    # this should work
    datastore_id = "contentLib"
   # this technically should have  some sort of path attribute from content vsphere_content_library_item
    path         = "/iso/ph4-rt-refresh"
  }
}
```

Hence the error, as there is no matching ID:

```console
│ Error: cdrom.0: cannot find datastore: ServerFaultCode: The object 'vim.Datastore:contentLib' has already been deleted or has not been completely created
```

Ideally, this should be:

```hcl
datasource "vsphere_datastore" {
   name = "contenLib"
}

resource "vsphere_virtual_machine" "vm" {
  #... brevity
  cdrom {
    datastore_id =  data.vsphere_datastore.id
    path         = "/path/to/the/file.iso"
  }
}
```

You can't use `data.vsphere_content_library.iso_library.id` as that's the content library's ID and the datastore for the library is not returned in the data source.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by spyroot** [comment]
It doesn't matter what you use in datastore_id.
Let's say I do following

data "vsphere_content_library" "iso_library" {
  name = var.iso_library
}

# uploaded IOS

```
resource "vsphere_content_library_item" "test_iso" {
  name        = "ph4-rt-refresh"
  description = "ph4-rt-refresh"
  file_url    = "some_url/ph4-rt-refresh.iso"
  library_id  = data.vsphere_content_library.iso_library.id
  type        = "iso"
}
```

Now I want to boot VM and attach CD with that ISO and it.
In my case content library name **iso**


If I use 

cdrom {
    datastore_id = data.vsphere_content_library_item.iso_library.id
    path         = "/iso/ph4-rt-refresh.iso"
  }

Notice data.vsphere_content_library_item.iso_library.id it doesn't work.

VC

By default, resolve the path for Content Library as [contentLib]

<img width="246" alt="image" src="https://user-images.githubusercontent.com/11797329/188961642-752af113-8eba-456d-887a-ef1387cfe290.png">

Notice it has three options.  I choose content lib.

VC automatically resolved that as content lib.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/11797329/188961794-8bf0d164-99cb-4a2a-89cf-359c598e2f90.png">

**Comment by tenthirtyam** [comment]
The resource does not support the Content Library ISO File method - this would require an enhancement for the provider.

If the datastore is known and the path is known, you can use:

```hcl
datasource "vsphere_datastore" {
   name = "contenLib"
}

resource "vsphere_virtual_machine" "vm" {
  #... brevity
  cdrom {
    datastore_id =  data.vsphere_datastore.id
    path         = "/path/to/the/file.iso"
  }
}
```

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by spyroot** [comment]
No, you can't use path because content lib upload uses backend storage, which always generates UUID for each item; neither resource nor data contains a full path for backend storage.

**Comment by tenthirtyam** [comment]
This issue would be an enhancement request - please resubmit using the enhancement request issue template.

**Comment by tenthirtyam** [comment]
If you have any concerns converting to an enhancement m, please feel free to DM me on Slack.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
https://github.com/hashicorp/terraform-provider-vsphere/issues/1750 has been created as an enhancement request and has been placed in the backlog for review.

- Vote on GH-1750 by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to that issue's original issue initial description to help the maintainers prioritize.
-   If you are interested in working on this issue or have submitted a pull request, please leave a comment on GH-1750.

**Comment by spyroot** [comment]
No, I see a pushed feature request. Thank you very much!  I flag it closed.
