### ISSUE TITLE
Error destroying `r/virtual_machine` with attached virtual disk

### ISSUE THREAD

**Issue by skupfer** [hashicorp/terraform-provider-vsphere#1753]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.8

### Terraform Provider

vSphere 2.0.2

### VMware vSphere

v7.0.3.00700

### Description

We have a case where we want to provide VMs with a persistent data disk which survives up/down-grading the template because the data is independent. The `r/vsphere_virtual_disk` data disk will get created first on `terraform apply` and attached afterwards in the `r/vsphere_virtual_machine` block.

If running `terraform destroy` the VM will get deleted but will throw the error:

```console
Error: Error caused by file ds:///vmfs/volumes/5eb0222d-0ef0f2c2-6110-e4434bce26d0/persistent_disk_storage/pdisks_persistent.vmdk attached to persistent_test

```
I need to run the command again to finally destroy the attached disk.

I hope the provided block is enough. I think the problem is that on destruction it is handled top-down, too and therefore it tries to delete the attached disk first without detaching it first.

### Affected Resources or Data Sources

- `resource/vsphere_virtual_machine`
- `resource/vsphere_virtual_disk`

### Terraform Configuration

```hcl
resource "vsphere_virtual_disk" "PersistentDataDisk" {
  count		        = var.persistent_data_disk == true ? length(var.vms) : 0
  size                  = var.vms[count.index].flavor.disks[1].size
  datacenter            = var.datacenter
  vmdk_path             = "${var.vms[count.index].flavor.persistent_vmdk_path}/${var.vms[count.index].general.host_name}_persistent.vmdk"
  datastore             = var.vms[count.index].general.datastore
  type                  = "thin"
  create_directories    = true
}

resource "vsphere_virtual_machine" "vms" {
[ ...]

  dynamic disk {
    for_each = [for i in var.vms[count.index].flavor.disks: { 
      size   = i.size
      number = i.number
      attach = var.persistent_data_disk == true ? true : false
      path   = "${var.vms[count.index].flavor.persistent_vmdk_path}/${var.vms[count.index].general.host_name}_persistent.vmdk"
    }]
    content {
      label = "disk${disk.value.number}"
      unit_number = disk.value.number
      size = disk.value.number != 1 ? disk.value.size : null
      thin_provisioned = disk.value.number != 1 ? true : null
      attach = disk.value.attach == true && disk.value.number == 1 ? disk.value.attach : null
      path = disk.value.attach == true && disk.value.number == 1 ? disk.value.path : null
      datastore_id = disk.value.attach == true && disk.value.number == 1 ? data.vsphere_datastore.datastores[count.index].id : null
    }
  }

[...]
}
```

### Debug Output

```console
vsphere_virtual_disk.PersistentDataDisk[0]: Destroying... [id=persistent_disk_storage/pdisks_persistent.vmdk]
vsphere_virtual_machine.vms[0]: Destroying... [id=42157a18-6f69-8984-0c1b-4b8601c4ea2a]
vsphere_virtual_machine.vms[0]: Destruction complete after 8s
╷
│ Error: Error caused by file ds:///vmfs/volumes/5eb0222d-0ef0f2c2-6110-e4434bce26d0/persistent_disk_storage/pdisks_persistent.vmdk attached to persistent_test 
│ 
│ 
╵
```

### Expected Behavior

First the VM will get destroyed, then the attached disk

### Actual Behavior

Tries destroying the attached disk, destroys the VM and  throws an error

### Steps to Reproduce

Run `terraform apply`, then `terraform destroy`

**Comment by tenthirtyam** [comment]
Reminds me of similar issue GH-1678.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Duplicate of #1678.

**Comment by skupfer** [comment]
It is indeed a duplicate but I haven't found this. I gave it a try and due to "A single static variable reference is required" i tried linking it to the first vm created

`  depends_on            = [vsphere_virtual_machine.vms[0]]`
or
`  depends_on            = [vsphere_virtual_machine.vms]`

but it does not create the virtual_disk and fails because it cannot find it. From the linked issue I got that I have to add the depends_on on the r/vsphere_virtual_disk.

```
  # vsphere_virtual_disk.PersistentDataDisk[0] will be created
  + resource "vsphere_virtual_disk" "PersistentDataDisk" {
      + adapter_type       = "lsiLogic"
      + create_directories = true
      + datacenter         = "LP"
      + datastore          = "S-LP11"
      + id                 = (known after apply)
      + size               = 10
      + type               = "thin"
      + vmdk_path          = "persistent_disk_storage/pdisks_persistent.vmdk"
    }

  # vsphere_virtual_machine.vms[0] will be created
  + resource "vsphere_virtual_machine" "vms" {

[...]
  Enter a value: yes

vsphere_virtual_machine.vms[0]: Creating...
vsphere_virtual_machine.vms[0]: Still creating... [10s elapsed]
vsphere_virtual_machine.vms[0]: Still creating... [20s elapsed]
vsphere_virtual_machine.vms[0]: Still creating... [30s elapsed]
vsphere_virtual_machine.vms[0]: Still creating... [40s elapsed]
```

Think I don't get the correct usage

**Comment by skupfer** [comment]
Ok, found it. I had to link it reverse.

`  depends_on       = [data.vsphere_virtual_machine.template, vsphere_virtual_disk.PersistentDataDisk]`

Thanks for your help!

**Comment by tenthirtyam** [comment]
You’re welcome! Have a good weekend!

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
