### ISSUE TITLE
 "Error: ServerFaultCode: NoPermission" when cloning `r/virtual_machine`

### ISSUE THREAD

**Issue by henryx** [hashicorp/terraform-provider-vsphere#1761]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.8

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.2.00400

### Description

According to https://github.com/hashicorp/terraform-provider-vsphere/issues/974#issuecomment-591956362 assignation of profile `Profile-driven storage view` to user permits cloning of VM from template, but this works only on `1.15.0`. From `1.16.0`, it doesn't work anymore

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`

### Terraform Configuration

Sample to reproduce the problem is the snippet in official documentation: https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#creating-a-virtual-machine-from-a-template

### Debug Output

https://gist.github.com/henryx/36ca98b3f1b95d98eb16c798f6e4b4ee

### Expected Behavior

Machine is cloned from template

### Actual Behavior

```console
vsphere_virtual_machine.vm-cloned: Refreshing state... [id=4215d500-2f37-711b-fd36-ad32754165db]
╷
│ Error: ServerFaultCode: NoPermission
│
│   with vsphere_virtual_machine.vm-cloned,
│   on main.tf line 56, in resource "vsphere_virtual_machine" "vm-cloned":
│   56: resource "vsphere_virtual_machine" "vm-cloned" {
│
╵
```

### Steps to Reproduce

 - Create a Vsphere user wich doesn't have administrative rights.
 - Assign it rights to manage VMs and templates.
 - Assign it  `Profile-driven storage view`  right.
 - Create (or load) a template in Vshpere
 - Execute a terraform file which clone the template

### References

#GH-974

**Comment by tenthirtyam** [comment]
Please provide a gist with the output from v2.2.0 as well as the specific privileges and scope assigned to the users context.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Also, please refer to https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs#notes-on-required-privileges to ensure that the additional required privileges are also provided.

**Comment by tenthirtyam** [comment]
For general questions, we recommend reaching out to the [community forum](https://discuss.hashicorp.com/tags/c/terraform-providers/31/vsphere) for greater visibility.  The GitHub issue tracker is only watched by a small group of maintainers and collaborators and is typically reserved for bug reports and enhancement request. You will typically have more success finding assistance on the forum.

If you find the forum to be more helpful or if you've found the answer to your question elsewhere, please comment and close the issue. If there is no further activity on this question within the next 30 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by henryx** [comment]
I'm sorry if I haven't replied before. This is the Gist with debug log using provider at `v2.2.0` : https://gist.github.com/henryx/c4ac6f3eeea5014a574b73fcb5735992

**Comment by tenthirtyam** [comment]
Have you enabled Storage Profile > View for the account at the vCenter Server root object?

**Comment by henryx** [comment]
Yes, is enabled

**Comment by tenthirtyam** [comment]
Do the privileges also apply nclide swap placement?

**Comment by henryx** [comment]
Yes, user have permission to locate swap placement

**Comment by tenthirtyam** [comment]
Could you provide the specific list of privileges provider to the account and the placement and propagation of the permissions. That would aid in any issue reproduction.

**Comment by henryx** [comment]
Sadly, I'm not able to view the list of permissions in VSphere cluster

**Comment by tenthirtyam** [comment]
Without this additional information it will be difficult to assist in investigating the root cause and reproduce the issue.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
