### ISSUE TITLE
Creating Resource Pool in Cluster with Scaleable Shares enabled causes error

### ISSUE THREAD

**Issue by jacksonwg** [hashicorp/terraform-provider-vsphere#1763]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.3.1

### Terraform Provider

2.2.

### VMware vSphere

7.0.3

### Description

Attempting to create a new child resource pool of an existing pool fails when the cluster is configured with scalable shares

### Affected Resources or Data Sources

resource/vsphere_resource_pool

### Terraform Configuration

```
terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "2.2.0"
    }
  }
}

provider "vsphere" {
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "Datacenter"
}

data "vsphere_resource_pool" "parent" {
  name = "Departments"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_resource_pool" "child" {
  name = "Child"
  parent_resource_pool_id = data.vsphere_resource_pool.parent.id
}

```

### Debug Output

https://gist.github.com/jacksonwg/4303057a118f4852c4dc3e89acdca2f1

### Expected Behavior

Resource pool is created without error.

### Actual Behavior

Looks like the vSphere API isn't allowing a value for the scalable shares attribute on the pool because it is set at the cluster level. The provider defaults to `disabled` but manually setting `scaleCpuAndMemoryShares` is also rejected.

Error from vCenter web console events is ` A specified parameter was not correct: ResourceConfigSpec Setting scaleDescendantsShares on the resource pool is not allowed because the descendants of resource pool 'Resources' are already scalable.`

### Steps to Reproduce

`terraform apply --auto-approve` with the above configuration after ensuring the names for the datacenter and parent resource pool objects match.

### References

https://github.com/hashicorp/terraform-provider-vsphere/issues/1622

**Comment by tenthirtyam** [comment]
@jacksonwg - can you test using the example as seen in the originating pull request?

https://github.com/hashicorp/terraform-provider-vsphere/pull/1634#issue-1177421836

**Comment by jacksonwg** [comment]
I tried with both examples.

The first, where the cluster is created with DRS and scalable shares, fails with an identical error to my example above when trying to create `resource.vsphere_resource_pool.this`

The second runs successfully.

But if I modify the second and add a third generation resource pool, setting the second generation as its parent then it fails with the same error. Modified second example here: https://gist.github.com/jacksonwg/f71535f61299b6587bb358bacc9e31b6

**Comment by tenthirtyam** [comment]
Thanks for confirming, @jacksonwg. 

I'll take action to address this item, but unlikely for v2.3.0 given my current and planned availability.

If you'd like to research and submit a pull request for the fix, please review the contributing guidelines and I'll bee happy to review.

Ryan

**Comment by coffmant** [comment]
Any update on this one?  Ran into it again today

**Comment by burnsjared0415** [comment]
so, i am getting the same error but i am trying to understand the ask on this, are you asking for a check if the parent Resource Pool is set to descendants is already scalable or what are you asking, i tested this with api and gui to the same result. So trying to figure out what we are trying to fix here.

**Comment by jacksonwg** [comment]
It has been almost two years so I'm basing this on what I've reviewed above.

Using the versions described in the initial report, the vSphere provider is unable to create Resource Pool objects when the parent object (either a vSphere Cluster Object or other Resource Pool object) has scalable shares enabled. 

From the debug output on the Resource Pool object when the parent object has scaleable shares enabled
>   `- .scale_descendants_shares: planned value cty.StringVal("disabled") for a non-computed attribute`
but I do not believe "disabled" is valid here per [the documentation](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-0F6C6709-A5DA-4D38-BE08-6CB1002DD13D.html)
> Shares are scaled at the parent level. All descendant resource pools created from a parent with scalable shares have scalable shares by default.

Once tenthirtyam confirmed the issue I didn't investigate further and implemented a workaround (manual object creation).

**Comment by burnsjared0415** [comment]
i got the error, i will see how i can work around this or come up with if there is a option here.
