### ISSUE TITLE
`r/virtual_machine` with a large disk fails with "context deadline exceeded"

### ISSUE THREAD

**Issue by rmestrum** [hashicorp/terraform-provider-vsphere#1764]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.9

### Terraform Provider

v2.2.0

### VMware vSphere

v6.7.0.51000

### Description

When I create a VM with a large disk the creation fails with the message "context deadline exceeded"

I noticed that there was already an issue for this #1134. In this issue the solution was to add the api_timeout parameter to the provider so I did this but I didn't notice any difference. The creation of the VM is aborted every time after approximately 5 minutes

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`

### Terraform Configuration

``` hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_user
  password             = var.vsphere_password
  allow_unverified_ssl = true
  api_timeout          = 130
}
```

### Debug Output

``` console
module.my_module.vsphere_virtual_machine.vm[2]: Creating...
module.my_module.vsphere_virtual_machine.vm[2]: Still creating... [10s elapsed]
... 
module.my_module.vsphere_virtual_machine.vm[2]: Still creating... [6m30s elapsed]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify
│ that no other changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵
╷
│ Error: error reconfiguring virtual machine: error reconfiguring virtual machine: Post "https://..../sdk": context deadline exceeded
│ 
│   with module.my_module.vsphere_virtual_machine.vm[2],
│   on .terraform/modules/my_module/main.tf line 46, in resource "vsphere_virtual_machine" "vm":
│   46: resource "vsphere_virtual_machine" "vm" {
│ 
```

### Expected Behavior

The machine and the disk are created

### Actual Behavior

The machine is not created.

### Steps to Reproduce

Create a VM with a very large disk.

**Comment by tenthirtyam** [comment]
This issue should be resolved in the upcoming release which includes the enhancement from https://github.com/hashicorp/terraform-provider-vsphere/pull/1645.

Could you build the provider and test locally to confirm?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Resolved in https://github.com/hashicorp/terraform-provider-vsphere/issues/1662.
