### ISSUE TITLE
Terraform detects change when there is no change due to file()

### ISSUE THREAD

**Issue by aSauerwein** [hashicorp/terraform-provider-vsphere#1765]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.3.1

### Terraform Provider

v2.2.0

### VMware vSphere

7.0.3

### Description

I use terraform to deploy Virtual Machines on VMware based on Ubuntu Cloud Image OVA with the ssh public key set as VMware vapp property. 

I've noticed that terraform changes the property `public-keys` everytime I hit terraform apply, and therefore restarting all the VMs even when nothing changed at all. 

the root cause to this issue is probably that i use file() to load a public key from file. Terraform shows the value as `<<-EOT --- file content EOT` but in the state file the property is shown without `<<-EOT`

Issue cannot be reproduced if a use a static string instead of file() function. 

### Affected Resources or Data Sources

`vsphere_virtual_machine`

### Terraform Configuration

main.tf

```hcl
resource "vsphere_virtual_machine" "vm1" {
.
.
  vapp {
    properties = {
      "public-keys" = file("~/.ssh/id_ed25519.pub")
    }
  }
.
.
 ```

terraform apply output

``` console
               ~ "public-keys" = <<-EOT
                    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5XXXXIESZnrJm6+WelABBFS5wnO8UKHXXprwJz6f2TXXw2wgT asauerwein@sautron.local
                EOT
```

### Debug Output

terraform plan output: https://gist.github.com/aSauerwein/a94f705f79d454c851114aa4b750c468

### Expected Behavior

nothing

### Actual Behavior

terraform updats the VM object with the exact same value and restarts the VM

### Steps to Reproduce

1. create `vsphere_virtual_machine` with vapp property loaded from a file
2. `terrafrom apply` - to create the vms
3. `terraform apply` - to reproduce the error.

### References

could be similar to https://github.com/hashicorp/terraform-provider-aws/issues/9042

**Comment by tenthirtyam** [comment]
Try:

```hcl
resource vsphere_virtual_machine "foo" {
 # ... excluded for brevity...
 vapp {
 # ... excluded for brevity...
 }
 lifecycle {
   ignore_changes = [
     vapp[0].properties,
   ]
 }
}
```

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by aSauerwein** [comment]
yes that is a workaround and I think it does not matter because public-keys are as far as i know public-keys are only read once during first boot. 

but that is not a wholesome solution. What if there is some property read from a file than can be changed during the lifetime of a VM ?

**Comment by tenthirtyam** [comment]
Thanks for the confirmation. 

This is the solution to address this scenario. If there's a particular use case in which you envision a vApp property needs to be read day-_n_, please open an enhancement issue and describe the use/case or scenario so that it can be tracked as an `enhancement`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
