### ISSUE TITLE
`r/vsphere_file` causes crash with incorrect configuration

### ISSUE THREAD

**Issue by springer268** [hashicorp/terraform-provider-vsphere#1779]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.3.3

### Terraform Provider

v2.2.0

### VMware vSphere

7.0.2.00500

### Description

I am trying to use vsphere_file to upload a file to a datastore. This causes a crash in the plugin 

### Affected Resources or Data Sources

`r/vsphere_file`

### Terraform Configuration

```hcl
provider "vsphere" {
  allow_unverified_ssl = true
  vsphere_server       = var.server
  user                 = var.user
  password             = var.password
}

resource "vsphere_file" "ubuntu_vmdk_upload2" {
  datacenter         = "dc"
  datastore          = "ds1"
  source_file        = "/Users/springern/Documents/hi.txt"
  destination_file   = "hi.txt"
  create_directories = true
}
```

### Debug Output

https://gist.github.com/springer268/3ac854675994b18aa2922c042791c8dc

### Panic Output

https://gist.github.com/springer268/3ac854675994b18aa2922c042791c8dc

(i dont see a crash.log)

### Expected Behavior

The file to upload to the specified datastore

### Actual Behavior

the file is not uploaded to the datastore and crashes the program

### Steps to Reproduce

1. Have vsphere, terraform, and provider with matching versions
2. Attempt to upload file to datastore with configuration as shown before
3. See output

### Environment Details

This error also occurs on a different vCenter.

The datastore is VMFS

**Comment by tenthirtyam** [comment]
At first glance the example seems incorrect as it's create directories but none are required.

```hcl
resource "vsphere_file" "ubuntu_vmdk_upload2" {
  datacenter         = "dc"
  datastore          = "ds1"
  source_file        = "/Users/springern/Documents/hi.txt"
  destination_file   = "hi.txt"
  create_directories = true
}
```

Try:

```hcl
resource "vsphere_file" "ubuntu_vmdk_upload2" {
  datacenter         = "dc"
  datastore          = "ds1"
  source_file        = "/Users/springern/Documents/hi.txt"
  destination_file   = "path/to/file/hi.txt"
  create_directories = true
}
```

or if in the datastore root:

```
resource "vsphere_file" "ubuntu_vmdk_upload2" {
  datacenter         = "dc"
  datastore          = "ds1"
  source_file        = "/Users/springern/Documents/hi.txt"
  destination_file   = "hi.txt"
  create_directories = false
}
```

**Comment by springer268** [comment]
Yes, this worked. I guess an error message should be added when this occurs, instead of a crash. Thanks.

**Comment by tenthirtyam** [comment]
I've updated the issue to track this item for an enhancement to the error handling.
