### ISSUE TITLE
Add support for configuring vApp properties where `ovf:userConfigurable="false"`

### ISSUE THREAD

**Issue by sohamcoder007** [hashicorp/terraform-provider-vsphere#1782]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
1.0.10

### vSphere Provider Version
`hashicorp/vsphere_2.0.2`

### Affected Resource(s)
`vsphere_virtual_machine`

### Overview
Currently the vapp properties which are set as `ovf:userConfigurable="false"` are unable to be configured when deploying to vSphere through Terraform.

Ovftool has an option `-X EnableHiddenProperties` which allows such properties to be edited, when deploying through PowerShell etc. Can there be a way to do the same with Terraform?

### Use Case(s)

Configuration in  `.tf` file

```hcl
vapp {
    properties = {
      "prop1 = "value1",
      "prop2" = "value2",
    }
}
```

Corresponding configuration in `.ovf` file

```xml
      <Property ovf:key="prop11" ovf:type="string" ovf:userConfigurable="false">
        <Label>Prop 1</Label>
        <Description> ... </Description>
      </Property>
      <Property ovf:key="prop2" ovf:type="string" ovf:userConfigurable="false">
        <Label>Prop 2</Label>
        <Description> ... </Description>
      </Property>
```

The following error is seen:

```console
Error: error while creating vapp properties config vApp property with userConfigurable=false specified in vapp.properties: [prop1]
```

**Comment by sohamcoder007** [comment]
Is there any timeline for this enhancement request to be applied in terraform code? VMware had a dependency on this issue for a feature release.

**Comment by tenthirtyam** [comment]
It’s placed in the backlog and has had no reactions. 

If you want to contribute an enhancement to this project, please review the [contributing guidelines](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/docs/CONTRIBUTING.md) and information on [submitting pull requests](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/docs/PULL_REQUESTS.md).

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
