### ISSUE TITLE
Add support for vSAN data-in-transit encryption and HCI mesh

### ISSUE THREAD

**Issue by SlimYang** [hashicorp/terraform-provider-vsphere#1783]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

vSAN has a rich set of features that are not yet supported by the terraform provider. The following two are well-known and widely used feature but are not yet supported.

* vSAN Data-in-transit Encryption. This ensures that the over-the-wire communication between vSAN nodes are properly encrypted. This feature has been supported in vSphere 7.0 release: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vsan.doc/GUID-10099331-92E7-41AF-BCAA-88DB4B4A4B7B.html. 
* vSAN HCI mesh feature: vSAN HCI mesh feature is also introduced with vSphere 7.0 release. It has the use case to export the current local vSAN datastore to other clusters such that other clusters can be compute only. Related documents are here: https://blogs.vmware.com/virtualblocks/2020/09/16/introducing-vmware-vsan-hci-mesh/. 

### Use Case(s)

See the above.

### Potential Terraform Provider Configuration

```hcl
resource "vsphere_compute_cluster" "compute_cluster" {
  name            = "terraform-compute-cluster-test"
  datacenter_id   = data.vsphere_datacenter.datacenter.id
  host_system_ids = [data.vsphere_host.host.*.id]

  drs_enabled          = true
  drs_automation_level = "fullyAutomated"

  ha_enabled = false

  vsan_enabled = true
  vsan_remote_datastore_ids   = [data.vsphere_datastore.datastore.id]
  vsan_dit_encryption_enabled = true
  vsan_dit_rekey_interval = 1800
  vsan_disk_group {
    cache = data.vsphere_vmfs_disks.cache_disks[0]
    storage = data.vsphere_vmfs_disks.storage_disks
  }
}
```

**Comment by tenthirtyam** [comment]
Enhancement added in GH-1820.

cc @appilon
