### ISSUE TITLE
Add support for searching for best matching VM in `d/vsphere_virtual_machine`

### ISSUE THREAD

**Issue by nneul** [hashicorp/terraform-provider-vsphere#1785]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Current data source for virtual machines doesn't include any ability to search for anything other than an exact match. This is very limiting if you're using tf in conjunction with packer to build templates that are datestamped. With the AWS AMI data source, you can use something like:

```hcl
data "aws_ami" "latest_baseline" {
  most_recent = true
...
  filter {
    name   = "tag:Name"
    values = ["template-name"]
  }
}
```

### Use Case(s)

Use case is being able to select a matching VM by pattern instead of just by name, such as if you have a template named something like "app-server-20221122-104759" by searching for virtual machine named "app-server-.*"

### Potential Terraform Provider Configuration

```hcl
data "vsphere_virtual_machine" "vm_tmpl" {
  search  = "^app-server-.*$"
  search_order = "descending"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
```

Would return the first virtual machine matching the pattern.

**Comment by nneul** [comment]
Example packer snippet that this could be used with:

```
locals {
  template_name     = "${local.name}-${local.timestamp}"
  ...
}

source "vsphere-clone" "build" {
   vm_name             = local.template_name
   convert_to_template = true
   ...
}
```

**Comment by nneul** [comment]
@tenthirtyam If you think this is something that syntactically you'd be willing to merge, I'm willing to take a crack at putting together a PR for it.

**Comment by UnixC0rn** [comment]
Looking for exactly that feature. could also be implemented to accept wildcards and return a list of vms matching the name, so you could further filter it with functions or regex.

**Comment by tenthirtyam** [comment]
Duplicate of #1500

**Comment by nneul** [comment]
@tenthirtyam - I would note that I wouldn't really consider a duplicate, as #1500 is asking for something quite a bit more complex. #1500 would certainly be a solution to this, but it's a much bigger solution. 

"Support for plural data sources" is quite a bit more advanced/encompassing than "Add capability in data source to return a singular 'best match'" - equivalent to what exists in packer when requesting "first best match for an AMI".
