### ISSUE TITLE
Add support to configure auto-start / power-on of virtual machine resources

### ISSUE THREAD

**Issue by holmesb** [hashicorp/terraform-provider-vsphere#1788]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Hi,

I can’t see any way to auto-boot VMs when host starts using this provider. [Apparently](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-5FE08AC7-4486-438E-AF88-80D6C7928810.html) it’s configured on the host as well as per-VM. But there’s nothing in [vsphere_host](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/host), nor [vsphere_virtual_machine](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine) resources.

I thought this might be done using [vsphere_vapp_entity](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/vapp_entity)’s poweron argument, but that seems to be just for manual poweron, not autostart whith host.

Any ideas, or is this an enhancement request?

Many thanks

### Use Case(s)

Improve uptime.

**Comment by Ashtonian** [comment]
This is needed. The go vsphere client already seems to support it https://github.com/vmware/govmomi/blob/aa3f6d6a6456547703ed40b0735cc0aaaf473724/govc/host/autostart/info.go#L17 already.

**Comment by ashtonian** [comment]
RIP, the go cli already does this, just need TF resources
