### ISSUE TITLE
Error: `POST https://myfavsrv.net/rest/com/vmware/cis/session: 401 Unauthorized`

### ISSUE THREAD

**Issue by realrubberduckdev** [hashicorp/terraform-provider-vsphere#1791]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.3.5

### Terraform Provider

2.2.0_x5

### VMware vSphere

7.0.3.19234570

### Description

I am getting 401 unauthorized when trying to run terraform plan. This is very similar to this issue which has been reported before
https://github.com/hashicorp/terraform-provider-vsphere/issues/756

```
terraform plan
╷
│ Error: POST https://myfavsrv.net/rest/com/vmware/cis/session: 401 Unauthorized
│
│   with provider["registry.terraform.io/hashicorp/vsphere"],
│   on main.tf line 1, in provider "vsphere":
│    1: provider "vsphere" {
```
As part of investigation:
Tried setting `VSPHERE_CLIENT_DEBUG` and gathered the call request url, authorization header, and other headers. Using those ran a `Invoke-RestMethod` via Powershell and it works fine and returns a session id.

I can login to vsphere client, create VMs using the credentials used in Terraform.

The comment in previous issue https://github.com/hashicorp/terraform-provider-vsphere/issues/756#issuecomment-490984241 says use no_proxy url, unsure what that means. Any pointers welcome.

Is there a fix for this or any ideas how to investigate further?

### Affected Resources or Data Sources

Fails at terraform plan itself so

```
provider "vsphere" {
```

### Terraform Configuration

```
provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}
```

### Debug Output

N/A

### Expected Behavior

Plan to succeed

### Actual Behavior

```
terraform plan
╷
│ Error: POST https://myfavsrv.net/rest/com/vmware/cis/session: 401 Unauthorized
│
│   with provider["registry.terraform.io/hashicorp/vsphere"],
│   on main.tf line 1, in provider "vsphere":
│    1: provider "vsphere" {
```

### Steps to Reproduce

Perform a terraform plan on the provided code

### Environment Details

Working from behind a proxy so had to setup proxy. Terraform init succeeds.

**Comment by tenthirtyam** [comment]
First, does it work with `administrator@vsphere.local`, if you are able to test with that.

Next, can you confirm that the name format is `user@foo.bar`?

For example:
- `administrator@vsphere.local` - SSO user
- `terraform@vsphere.local` - SSO user
- `terraform@rainpole.io` - AD user

**Comment by realrubberduckdev** [comment]
Hi @tenthirtyam 
Many thanks for your quick response and apologies for the delay. Took a bit of time to test these out.

The username formats I have tried are:
`user` (cannot logon to vsphere client and Terraform throws 401)
`user@domain-name.net` (can logon to vsphere client but Terraform throws 401)
`user@domain-name` (can logon to vsphere client but Terraform throws 401)
`administrator@vsphere.local` (can logon to vsphere client but Terraform throws 401)
All of these get the 401. 

**Further debugging - works outside of Terraform**
I tried using VSPHERE_CLIENT_DEBUG as described at https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs#debugging-options

In the logs folder, the request in 3-0001.req.headers file looks like:
```
POST /rest/com/vmware/cis/session HTTP/1.1
Host: myfavsrv.net
Accept: application/json
Authorization: Basic 01notreatokenhereatpresent=
Content-Type: application/json
Vmware-Use-Header-Authn: true
```

and response in 3-0001.res.headers file looks like
```
HTTP/1.1 401 Unauthorized
Transfer-Encoding: chunked
Age: 0
Cache-Control: proxy-revalidate
Connection: Keep-Alive
Content-Type: application/json
Date: Wed, 23 Nov 2022 14:01:01 GMT
Proxy-Connection: Keep-Alive
Proxy-Support: Session-based-authentication
Server: envoy
Set-Cookie: BCSI-CS-f450701b1f4aa64e=1; Path=/
Www-Authenticate: Basic realm="VAPI endpoint",SIGN realm=notrealrealmhereatpresent,service="VAPI endpoint",sts="https://myfavsrv.net/sts/STSService/vsphere.local"
X-Envoy-Upstream-Service-Time: 0
```

But if I take the headers from the request and do this in powershell
```
$EncodedAuth = "01notreatokenhereatpresent="
$Headers = @{
    "Host"= "myfavsrv.net";
    "Accept"= "application/json";
    "Authorization"="Basic $EncodedAuth";
    "Content-Type"= "application/json";
    "Vmware-Use-Header-Authn"="true"
}
$initSession=Invoke-RestMethod -Uri "https://myfavsrv.net/rest/com/vmware/cis/session" -Method Post -Headers $Headers
$SessionID=$initSession.Value
Write-Host "session-id: $SessionID"
```
Then there is no error. It returns a valid session id. And if I decode the base64 authorization header, I see my username:password in plain text. I suspect the provider is not passing these headers properly.

Any thoughts or ideas?

**Comment by realrubberduckdev** [comment]
Hi @tenthirtyam is there any ETA on the fix? It is a major blocker for a project we are working on :-(

**Comment by tenthirtyam** [comment]
Hi @realrubberduckdev - there's no assigned ETA for review and a fix, if required. It would be helpful if you can provide information on the environment such as OS and version for community repro. In the meantime, can you test against another environment as well?

**Comment by tenthirtyam** [comment]
>  In the meantime, can you test against another environment as well?

Marking as `pending-closure`, awaiting OP response since 2022-11-29.

**Comment by tenthirtyam** [comment]
Marking as closed. Issue awaiting OP response since 2022-11-29.
