### ISSUE TITLE
Incorrect `folder` argument reference for `r/vsphere_folder` and `r/vsphere_virtual_machine`

### ISSUE THREAD

**Issue by jacco32** [hashicorp/terraform-provider-vsphere#1793]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.4

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.3

### Description

the documentation of `vsphere_folder` is incorrect, it states: 1 argument path which should include datacenter and folder type, but that does not work. what does work is using 2 unmentioned arguments: `datacenter_id` and `type` + use path without including datacenter and folder type.

in `vsphere_virtual_machine` folder argument reference it mentions full path including datacenter and folder type, which should be without datacenter and folder type.

suggestion: mention in `vsphere_folder` documention a path with subfolders does not create the intermediate folders for you, so for path `some/vms` you need to first create folder `some` and then `some/vms`

### Affected Resources or Data Sources

resource/vsphere_folder
resource/vsphere_virtual_machine

### Terraform Configuration

according to documentation (for folder type vm):
```
resource "vsphere_folder" "example" {
  path = "/my_dc/vm/my_folder"
}
```

this throws error that datacenter_id and type is required

working example:
```
resource "vsphere_folder" "example" {
  datacenter_id = data.vsphere_datacenter.my_dc.id
  type          = "vm"
  path          = "my_folder"
}
```

### Debug Output

not relevant: documentation issue

### Expected Behavior

documentation should be correct

### Actual Behavior

documentation is incorrect

### Steps to Reproduce

see example terraform configuration

**Comment by tenthirtyam** [comment]
Could you kindly include links to where your seeing the issues in the **References** section?

Please note that the [current docs on the Terraform Registry](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/folder) do have the correct information regarding the `type` and `datacenter_id`.

**Comment by tenthirtyam** [comment]
> Could you kindly include links to where your seeing the issues in the **References** section?

Marking as `pending-closure`, awaiting OP response since 2022-12-08.

**Comment by tenthirtyam** [comment]
Marking this issue as closed: No OP response since 2022-12-08.

If you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. 

Thank you!
