### ISSUE TITLE
Cannot create a network and retrieve it as a "data" resource without applying twice

### ISSUE THREAD

**Issue by EggyJohn** [hashicorp/terraform-provider-vsphere#1794]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.3.5

### Terraform Provider

v2.2.0

### VMware vSphere

v6.7.0.42000

### Description

already closed off here:  https://github.com/hashicorp/terraform-provider-vsphere/issues/1608

but the suggested fix (using "depends_on" arguments) does not actually work, the issue was closed off with no reply from the OP

exact same issue as the linked one - I create a virtual switch and port group, which should then be able to be referenced as a data object of "vsphere_network"

however, after successfully making the port group, and setting the vsphere_network data object to depend on the creation of the port group first, terraform fails to apply saying the network cannot be found

running apply a second time works, since the port group had indeed been created - "depends_on" is supposed to be the fix, but it doesn't seem to work

### Affected Resources or Data Sources

data/vsphere_network

### Terraform Configuration

```
resource "vsphere_host_virtual_switch" "testswitch" {
  name = "vSwitchTerraform"
  host_system_id = data.vsphere_host.id

  ...
}

resource "vsphere_host_port_group" "testportgroup" {
  name = "PortGroupTerraform"
  host_system_id = data.vsphere_host.id
  virtual_switch_name = vsphere_host_virtual_switch.testswitch.name
}

data "vsphere_network" "testnetwork" {
  name = "PortGroupTerraform"
  datacenter_id = data.vsphere_datacenter.dc.id

  depends_on = [
    vsphere_host_port_group.testportgroup,
  ]
}
```

### Debug Output

(no access, working on private work server)

### Expected Behavior

Running "terraform apply" should create the vSwitch and port group resources, then successfully find the network data source

### Actual Behavior

Terraform deems that the network cannot be found, and will only find it if you run "terraform apply" a second time

`Error: error fetching network: network 'PortGroupTerraform' not found`

### Steps to Reproduce

1. Create a "vsphere_host_virtual_switch" resource and "vsphere_host_port_group" resource
2. Create a "vsphere_network" data source for the newly created network
3. Ensure the "vsphere_network" depends_on the switch
4. Run "terraform apply"

**Comment by tenthirtyam** [comment]
Did you try the example in https://github.com/hashicorp/terraform-provider-vsphere/issues/1608 to establish the dependencies? The example shows that there are multiple dependencies.

For example, there's no dependency set between the host switch and the port group.

```hcl
data "vsphere_network" "testnetwork" {
  name = "PortGroupTerraform"
  datacenter_id = data.vsphere_datacenter.dc.id

  depends_on = [
    vsphere_host_port_group.testportgroup,
  ]
}

resource "vsphere_host_virtual_switch" "testswitch" {
  name = "vSwitchTerraform"
  host_system_id = data.vsphere_host.id
  ...
}

resource "vsphere_host_port_group" "testportgroup" {
  name = "PortGroupTerraform"
  host_system_id = data.vsphere_host.id
  virtual_switch_name = vsphere_host_virtual_switch.testswitch.name

  depends_on = [
    vsphere_host_virtual_switch.testswitch,
  ]
}
```

**Comment by EggyJohn** [comment]
hi - yes i've just tried that (dependency is now network > port group > switch), same result

**Comment by tenthirtyam** [comment]
> I should point out that in the output, the port group is visibly created before we see `data.vsphere_network: Reading...` and it will still error

There are at time the need to put in a wait period. I often use `hashicorp/time` to do so while the API is realizing the config - it is typically seen more in the creation of storage policies; however.

```hcl
resource "time_sleep" "nap" {
  depends_on = [
    foo.bar
  ]
  create_duration = "120s"
}

data "vsphere_foo" "bar" {
  depends_on = [
   foo.baz,
    time_sleep.nap
  ]
  name       = var.vsphere_content_library_ovf
  type       = "ovf"
  library_id = data.vsphere_content_library.content_library.id
}

**Comment by EggyJohn** [comment]
it's the same as in my initial post, i just left out the data sources required to get it set up - regardless i'll copy it for you now with names and addrs obviously placeholdered (and by hand, as sadly it's on a secure VM without internet):

```
data "vsphere_datacenter" "dc" {
  name = <dc_name>
}

data "vsphere_host" "host" {
  name = <host_name>
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_host_virtual_switch" "testswitch" {
  name = "vSwitchTerraform"
  host_system_id = data.vsphere_host.id

  network_adapters = []
  active_nics = []
  standby_nics = []
}

resource "vsphere_host_port_group" "testportgroup" {
  name = "PortGroupTerraform"
  host_system_id = data.vsphere_host.id
  virtual_switch_name = vsphere_host_virtual_switch.testswitch.name

  depends_on = [
    vsphere_host_virtual_switch.testswitch,
  ]
}

data "vsphere_network" "testnetwork" {
  name = "PortGroupTerraform"
  datacenter_id = data.vsphere_datacenter.dc.id

  depends_on = [
    vsphere_host_port_group.testportgroup,
  ]
}
```

something I left out until now is the empty lists used when creating the virtual switch resource - I wonder if that's somehow causing a weird edge case situation

**Comment by EggyJohn** [comment]
> > I should point out that in the output, the port group is visibly created before we see `data.vsphere_network: Reading...` and it will still error
> 
> There are at time the need to put in a wait period. I often use `hashicorp/time` to do so while the API is realizing the config - it is typically seen more in the creation of storage policies; however.

I will also give this a go!

**Comment by tenthirtyam** [comment]
> something I left out until now is the empty lists used when creating the virtual switch resource - I wonder if that's somehow causing a weird edge case situation

Note that this empty list requirement for `standby_nics` will be removed in v2.3.0. See https://github.com/hashicorp/terraform-provider-vsphere/pull/1695.

**Comment by tenthirtyam** [comment]
Also worth nothing that there is another example for the use of the time provider in https://github.com/hashicorp/terraform-provider-vsphere/issues/1228.
