### ISSUE TITLE
Add support for [ctkEnabled]

### ISSUE THREAD

**Issue by dasmfm** [hashicorp/terraform-provider-vsphere#1797]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

It would be great to be able to configure ctkEnabled param of virtual machine.
In this case terraform-created VMs will avoid https://kb.vmware.com/s/article/88193 problem while using vsphere-csi-driver.

### Use Case(s)

VMs for Kubernetes cluster with vsphere-csi-driver.

**Comment by vasil-ivanov-vmw** [comment]
@dasmfm Can you use the extra_config property of the vm resource?

`
resource "vsphere_virtual_machine" "vm" {
  name             = "vm"
  extra_config = {
    "ctkEnabled": "TRUE",
    "scsi0:0.ctkEnabled": "TRUE"
  }    
}
`
