### ISSUE TITLE
re-using session from GOVC seems to be broken

### ISSUE THREAD

**Issue by ulrik-sysint** [hashicorp/terraform-provider-vsphere#1807]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.3.0

### Terraform Provider

2.2.0

### VMware vSphere

7.0.3

### Description

During "linter fixes" in commit [linter fixes](https://github.com/hashicorp/terraform-provider-vsphere/pull/1416/commits/b120f5b03bed9f7238c41b51c71164e3899e6ccf) the hash algorithm was changed from sha1 to sha256. This was probably an oversight, as the govmomi library still uses sha1 in its "create session file"-function. This provider no longer generates the same hash (file name) as govc/govmomi and the session can't be re used.

**GOVC/GOVMOMI:**
```go
// key is a digest of the URL scheme + username + host + Client.Path()
func (s *Session) key(path string) string {
	p := s.Endpoint()
	p.Path = path

	// Key session file off of full URI and insecure setting.
	// Hash key to get a predictable, canonical format.
	key := fmt.Sprintf("%s#insecure=%t", p.String(), s.Insecure)
	return fmt.Sprintf("%040x", sha1.Sum([]byte(key)))
}
```

**VSPHERE PROVIDER:**

```go
// sessionFile is a helper that generates a unique hash of the client's URL
// to use as the session file name.
//
// This is the same logic used as part of govmomi and is designed to be
// consistent so that sessions can be shared if possible between both tools.
func (c *Config) sessionFile() (string, error) {
	u, err := c.vimURLWithoutPassword()
	if err != nil {
		return "", err
	}

	// Key session file off of full URI and insecure setting.
	// Hash key to get a predictable, canonical format.
	key := fmt.Sprintf("%s#insecure=%t", u.String(), c.InsecureFlag)
	name := fmt.Sprintf("%040x", sha256.Sum256([]byte(key)))
	return name, nil
}
```

### Affected Resources or Data Sources

provider/vsphere

### Terraform Configuration

provider "vsphere" : {
             persist_session = true
}

### Debug Output

N/A

### Expected Behavior

When i authenticate with govc the session can be re-used by terraform/vsphere provider. My understanding from the documentation (and the code) is that this should work.

### Actual Behavior

Authenticating with terraform (or govc) creates valid session files, but they have different hash (file names). If i rename the, it works.

### Steps to Reproduce

Authenticate with either govc or terraform with the "persist session" options enabled. 

### References

Related #1416

**Comment by tenthirtyam** [comment]
I suggest that even though this could be an easy fix to revert to SHA-1, given its state this should instead be considered for an upstream enhancement for govc.

**Comment by ulrik-sysint** [comment]
I'm guessing the linter flagged the SHA-1 because of security concerns, but in this instance it is only used for generating a unique (ish) string (file name), right? 

I might be wrong, but is this really an upstream fix? (works for me either way, of course).

**Comment by tenthirtyam** [comment]
Give that if others expect `vmware/govmomi` to use SHA1 that it would break those consumers it'll be best to simply revert the changes in the provider. I'll create a pull request with this reversion / update.

**Comment by tenthirtyam** [comment]
There may be a future opportunity to enhance the provider to use `vmware/govmomi`'s session/cache package so that the provider doesn't need to care about the details of how cache files are named, etc. https://github.com/vmware/govmomi/pull/1898

cc @appilon
