### ISSUE TITLE
Add support for port mirroring on a vSphere Distributed Switch

### ISSUE THREAD

**Issue by sean1245780** [hashicorp/terraform-provider-vsphere#1828]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, the ~~module~~ provider doesn't have the option to add any port mirroring or any of vspan spec of the dvs, and I'd like to have the option.

I want to be able to add a resource of vmware-vspan-session and to connect it to ~~dvs~~ vDS.
I'd really love to see it in production as it has many useful features!
Thanks! :)

### Use Case(s)

``` terraform
data "vsphere_vspan_port" "my_source_port_received" {
  ipAddress = ["25.5.4.3", "3.4.5.2"]
  vlans     = [1, 5, 19]
  # Other possible variables ...
}

data "vsphere_vspan_port" "my_source_port_transmitted" {
  ipAddress = ["11.5.4.3", "3.6.5.2"]
  vlans     = [4, 2, 8]
  # Other possible variables ...
}

resource "vsphere_vspan_session" "my_vspan_session" {
  # ...
  dvs_id                = "${my_dvs.id}"
  name                  = "my_vspan_session"
  enabled               = true
  normalTrafficAllowed  = false
  stripOriginalVlan     = false
  sourcePortReceived    = data.vsphere_vspan_port.my_source_port_received
  sourcePortTransmitted = data.vsphere_vspan_port.my_source_port_transmitted
  # Other possible variables ...
}
```

**Comment by sean1245780** [comment]
Is there any progress here?
I'd really love to see progress as we really need it.
@tenthirtyam

**Comment by tenthirtyam** [comment]
> Is there any progress here?
> I'd really love to see progress as I really need it.

Hi @sean1245780 👋 - 

Please note that this is still in the backlog milestone as seen attached to the issue. 

I don't have availability to work on this enhancement and they are items in the 2.4.0 milestone that are prioritized.

Contributions from the community are, of course, welcome if you'd like to assist.

Ryan
