### ISSUE TITLE
Provider does not find a vSphere subfolder when setting it through data.vsphere_folder

### ISSUE THREAD

**Issue by ptx96** [hashicorp/terraform-provider-vsphere#1830]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.2

### Terraform Provider

v2.2.0

### VMware vSphere

v6.7 3o

### Description

I'm trying to pass a variable containing a "path" to the `vsphere_folder` datasource;
in particular, I'm pointing to a VM subfolder structured like this:

`DC/vm/Clients/foo/production/bar`

then, I'm setting the VM `folder` parameter to use that:

`folder           = data.vsphere_folder.folder.path`

and it works pretty well during the `plan` step.

Once I try the `apply` step (to create OR move VMs to another subfolder), it breaks like this:

```
vsphere_virtual_machine.vm[0]: Creating...
╷
│ Error: folder '/DC/vm/DC/vm/Clients/foo/production/bar' not found
│ 
│   with vsphere_virtual_machine.vm[0],
│   on main.tf line 19, in resource "vsphere_virtual_machine" "vm":
│   19: resource "vsphere_virtual_machine" "vm" {
│ 
╵

OR

Error: could not move virtual machine to folder DC/vm/Clients/foo/production/bar: folder '/DC/vm/DC/vm/Clients/foo/production/bar' not found
```

note: the `DC/vm` prefix has been doubled

---

Viceversa, if I set the `path` like this:

`Clients/foo/production/bar`

it breaks the datasource function.

To make it work, I have to directly pass the `var.vsphere_folder` to the `resource.virtual_machine.vm` 

`folder = var.vsphere_folder`

OR use different folder variables for resource and datasource.

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`
`datasource/vsphere_folder`

### Terraform Configuration

``` data.tf
data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

[...]

data "vsphere_folder" "folder" {
  path = var.vsphere_folder
}
```

``` main.tf
resource "vsphere_virtual_machine" "vm" {
  name             = "foo"
  resource_pool_id = data.vsphere_resource_pool.default.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = data.vsphere_folder.folder.path
  #folder = var.vsphere_folder

  num_cpus               = 2
  memory                 = 8192

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label            = "disk0"
    size             = 10
    unit_number      = 0
    thin_provisioned = false
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
}
```

``` vars.tf
variable "vsphere_datacenter" {
  default = "DC"
}

[...]

variable "vsphere_folder" {
  default = "DC/vm/Clients/foo/production/bar"
  type    = string
}

```

### Debug Output

https://gist.github.com/ptx96/afb694c9bb47a5c4edab5ae6cfaf41f0

### Expected Behavior

I would like to pass the `data.vsphere_folder.folder.path` without problems like the double prefix

### Actual Behavior

Using:

`DC/vm/Clients/foo/production/bar`

```
vsphere_virtual_machine.vm[0]: Creating...
╷
│ Error: folder '/DC/vm/DC/vm/Clients/foo/production/bar' not found
│ 
│   with vsphere_virtual_machine.vm[0],
│   on main.tf line 19, in resource "vsphere_virtual_machine" "vm":
│   19: resource "vsphere_virtual_machine" "vm" {
│ 
╵
```
---
Using:

`Clients/foo/production/bar`

```
╷
│ Error: cannot locate folder: folder 'Clients/foo/production/bar' not found
│ 
│   with data.vsphere_folder.folder,
│   on data.tf line 35, in data "vsphere_folder" "folder":
│   35: data "vsphere_folder" "folder" {
│ 
╵
```

### Steps to Reproduce

Create a code sample to deploy a simple VM on vSphere;
set the folder parameter with the path of a vSphere VM subfolder using a vsphere_folder datasource, 

terraform plan
terraform apply

**Comment by tenthirtyam** [comment]
You can use the `vsphere_folder` data source to drive placement, but you need to make some slight modifications as illustrated below:

```hcl
data "vsphere_folder" "folder" {
  path = "/${data.vsphere_datacenter.datacenter.name}/vm/terraform/services"
}
```
and...

```hcl

resource "vsphere_virtual_machine" "vm" {
  name = var.vm_name
  folder = trimprefix(data.vsphere_folder.folder.path, "/${data.vsphere_datacenter.datacenter.name}/vm") 

```

I've posted [an example here](https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine/clone-template-linux-nested-folder
).
