### ISSUE TITLE
 The operation is not supported on the object. com.vmware.vim.resourcePool.error.standaloneHostScalableSharesUnsupported

### ISSUE THREAD

**Issue by ba31** [hashicorp/terraform-provider-vsphere#1846]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.3.9

### Terraform Provider

2.3.1

### VMware vSphere

7.0u2 and 8.0

### Description

Resource pool not getting created and its report "The operation is not supported on the object. com.vmware.vim.resourcePool.error.standaloneHostScalableSharesUnsupported" . Can not create resource pool on standalone ESXi host.

### Affected Resources or Data Sources

'resource/vsphere_resource_pool'

### Terraform Configuration

```
 resource_pool             = {
          + site1-resource-pool = {
              + cpu_expandable           = true
              + cpu_limit                = -1
              + cpu_reservation          = 0
              + cpu_share_level          = "normal"
              + cpu_shares               = (known after apply)
              + custom_attributes        = null
              + id                       = (known after apply)
              + memory_expandable        = true
              + memory_limit             = -1
              + memory_reservation       = 0
              + memory_share_level       = "normal"
              + memory_shares            = (known after apply)
              + name                     = "site1-resource-pool"
              + parent_resource_pool_id  = (known after apply)
              + scale_descendants_shares = "disabled"
              + tags                     = null
            }
          + site2-resource-pool = {
              + cpu_expandable           = true
              + cpu_limit                = -1
              + cpu_reservation          = 0
              + cpu_share_level          = "normal"
              + cpu_shares               = (known after apply)
              + custom_attributes        = null
              + id                       = (known after apply)
              + memory_expandable        = true
              + memory_limit             = -1
              + memory_reservation       = 0
              + memory_share_level       = "normal"
              + memory_shares            = (known after apply)
              + name                     = "site2-resource-pool"
              + parent_resource_pool_id  = (known after apply)
              + scale_descendants_shares = "disabled"
              + tags                     = null
            }
```

### Debug Output

```
╷
│ Error: ServerFaultCode: The operation is not supported on the object.
│
│   with module.foundation.vsphere_resource_pool.resource_pool["site1-resource-pool"],
│   on ../../resource_pool.tf line 23, in resource "vsphere_resource_pool" "resource_pool":
│   23: resource "vsphere_resource_pool" "resource_pool" {
│
╵
╷
│ Error: ServerFaultCode: The operation is not supported on the object.
│
│   with module.foundation.vsphere_resource_pool.resource_pool["site2-resource-pool"],
│   on ../../resource_pool.tf line 23, in resource "vsphere_resource_pool" "resource_pool":
│   23: resource "vsphere_resource_pool" "resource_pool" {
│
```

![image](https://user-images.githubusercontent.com/41516771/220348218-26714b99-7c03-4739-90e5-2ddaaa751993.png)

### Expected Behavior

Should be able to create a resource pool on standalone ESXi host.

### Actual Behavior

create a resource pool on standalone ESXi host.

### Steps to Reproduce

```
data "vsphere_datacenter" "datacenter" {
  name = "dc-01"
}

data "vsphere_host_thumbprint" "thumbprint" {
  address = "esx-01.example.com"
  insecure = true
}

resource "vsphere_host" "esx-01" {
  hostname = "esx-01.example.com"
  username   = "root"
  password   = "password"
  license    = "00000-00000-00000-00000-00000"
  thumbprint = data.vsphere_host_thumbprint.thumbprint.id
  datacenter = data.vsphere_datacenter.datacenter.id
}

data "vsphere_host" "host" {
  name          = "esxi-01.example.com"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
resource "vsphere_resource_pool" "resource_pool" {
  name                    = "site1-resource-pool"
  parent_resource_pool_id = data.vsphere_host.host.resource_pool_id
}
```

**Comment by ba31** [comment]
Please confirm its consider to be fix in new release ?

**Comment by tenthirtyam** [comment]
> Please confirm its consider to be fix in new release ?

Please follow the labels and assigned release milestone attached to the issue to follow the status.

If you'd like to contribute a fix, please review the contributing guidelines and submit a pull request.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by olsson-s** [comment]
I have the same problem.  The only workaround I have is to go back to an old version.  For example, it works when I go back to terraform 0.13.2, with vsphere 1.24.0 and null 2.1.2.

Terraform **v0.13.2**
+ provider registry.terraform.io/hashicorp/null **v2.1.2**
+ provider registry.terraform.io/hashicorp/vsphere **v1.24.0**

**Comment by olsson-s** [comment]
Hello,

I was able to trace this down to the version which introduces this error.  Basically, I can use the current version of hashicorp/null and the current version of terraform itself without any issue.  I can then use vsphere provider anywhere from **1.24.0** (at least) until **2.1.1**.  If I try _**2.2.0**_, it stops working with the error mentioned above.  

### In summary, this does **work**:

Terraform **v1.4.5**
on linux_amd64
+ provider registry.terraform.io/hashicorp/null **v3.2.1**
+ provider registry.terraform.io/hashicorp/vsphere **_v2.1.1_**


### This does **not work**:

Terraform **v1.4.5**
on linux_amd64
+ provider registry.terraform.io/hashicorp/null **v3.2.1**
+ provider registry.terraform.io/hashicorp/vsphere **_v2.2.0_**

**Comment by olsson-s** [comment]
We use VMWare Essentials which doesn't have HA functions so that is why we never created a cluster.  I see that it's possible though... just wouldn't really do anything other than maybe make terraform-vsphere work.  I'll try.  

In theory, you should be able to use vsphere plugin without a cluster and have it works as the old version of the vsphere plugin allows, but I understand that would be low priority if simply creating a cluster works.  I'll let you know.

**Comment by burnsjared0415** [comment]
So i found a way to do this but it is not the way it is being shown here, you would do different steps.
```
data "vsphere_datacenter" "datacenter" {
  name = "dc-01"
}

data "vsphere_host_thumbprint" "thumbprint" {
  address = "esx-01.example.com"
  insecure = true
}

resource "vsphere_host" "esx-01" {
  hostname = "esx-01.example.com"
  username   = "root"
  password   = "password"
  license    = "00000-00000-00000-00000-00000"
  thumbprint = data.vsphere_host_thumbprint.thumbprint.id
  datacenter = data.vsphere_datacenter.datacenter.id
}
```
then you would run the apply one more time
```
data "vsphere_host" "host" {
  name          = "esxi-01.example.com"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
resource "vsphere_resource_pool" "resource_pool" {
  name                    = "site1-resource-pool"
  parent_resource_pool_id = data.vsphere_host.host.resource_pool_id
}
```

i can't get it to recognize the hosts in the second command with out running a second apply
