### ISSUE TITLE
Configure vSAN dedup and compression failed with context deadline exceeded error in 5 min

### ISSUE THREAD

**Issue by zxinyu08** [hashicorp/terraform-provider-vsphere#1851]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.1

### Terraform Provider

v2.3.0

### VMware vSphere

v8.0

### Description

After creating a vSAN cluster with diskgroup attached, we run another `terraform apply` cmd to enable vsan dedup and compression. It failed in 5 min with following err msg. But checked vSphere UI, tasks could be completed successfully and dedup and compression could be enabled.
```
Error: cannot apply vsan service on cluster 'cluster-1': Post "https://10.212.99.1/sdk": context deadline exceeded
│
│   with vsphere_compute_cluster.cluster,
│   on demo.tf line 136, in resource "vsphere_compute_cluster" "cluster":
│  136: resource "vsphere_compute_cluster" "cluster" {
```
Some complex vSAN service configurations in 8.0 usually takes more than 5 min, however vSAN reconfigure uses the default provider timeout, we need change it to a more reasonable value.

### Affected Resources or Data Sources

`resource/vsphere_compute_cluster`

### Terraform Configuration

```
variable "hosts" {
  default = [
    esx-0,
    esx-1,
    esx-2,
  ]
}

data "vsphere_host" "hosts" {
  count         = length(var.hosts)
  name          = var.hosts[count.index]
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datacenter" "dc" {
  name = "DataCenter"
}

resource "vsphere_compute_cluster" "cluster" {
  name          = "cluster-1"
  datacenter_id = data.vsphere_datacenter.dc.id
  drs_enabled              = false
  ha_enabled               = false
  host_system_ids = "${data.vsphere_host.hosts.*.id}"

  vsan_enabled       = true

  vsan_dedup_enabled = true
  vsan_compression_enabled = true
}
```

### Debug Output

```
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 4m0s elapsed]
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 4m10s elapsed]
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 4m20s elapsed]
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 4m30s elapsed]
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 4m40s elapsed]
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 4m50s elapsed]
vsphere_compute_cluster.cluster: Still modifying... [id=domain-c22, 5m0s elapsed]
╷
│ Error: cannot apply vsan service on cluster 'cluster-1': Post "https://10.212.99.1/sdk": context deadline exceeded
│
│   with vsphere_compute_cluster.cluster,
│   on demo.tf line 136, in resource "vsphere_compute_cluster" "cluster":
│  136: resource "vsphere_compute_cluster" "cluster" {
```

### Expected Behavior

terraform apply should succeed, vSAN cluster is configured with dedup and compression.

### Actual Behavior

vSAN cluster could be configured with dedup and compression, but terraform apply failed.

### Steps to Reproduce

1. Create a vSAN cluster with diskgroup attached.
2. Set vsan_dedup_enabled and vsan_compression_enabled fields to true.
3. Terraform apply.

**Comment by tenthirtyam** [comment]
HI @zxinyu08 - are you or @SlimYang submitting a pull request for this item?

**Comment by zxinyu08** [comment]
Yes @tenthirtyam , we'll fix this issue.
