### ISSUE TITLE
dns_suffix_list prepends to searchable domains instead of appending

### ISSUE THREAD

**Issue by nbamrah** [hashicorp/terraform-provider-vsphere#1854]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.3.6

### Terraform Provider

3.0

### VMware vSphere

7.0.3

### Description

Leveraging the VSphere terraform provider, and when creating a vm with the use of the "dns_suffix_list", we've noticed that this field prepends the specified domains to the search field within the resolv.conf file. We would expect the "dns_suffix_list" to append, so that the primary domain (upon vm creation) remains the main domain searched against first, before checking against the other dns suffixes.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

  clone {
    timeout       = 120
    template_uuid = data.vsphere_content_library_item.item.id
    dns_suffix_list = ["test2.com", "test3.com"]
}

### Debug Output

search test2.com test3.com.com test1.com

### Expected Behavior

Expected behavior is for the searchable domains to be in appended order:

search test1.com test2.com test3.com

### Actual Behavior

The actual behavior is that the searchable domains are in prepended order:

search test2.com test3.com test1.com

### Steps to Reproduce

1. define searchable domains as a tf list variable
2. configure vm with searchable domains variable as value for dens_suffix_list
3. create vm
4. log into vm and cat resolv.conf (primary domain will be last entry for "search")

**Comment by burnsjared0415** [comment]
i am not able to re-produce this, need more data, i am not seeing this behavior, it looks at the order of entry determines how entered example:
```
dns_suffix_list = ["google.com", "test.com", "test1.com"]
```

can you provide a little more information on the config
