### ISSUE TITLE
Network interface disconnected after cloning from an OVF template in a Content Library

### ISSUE THREAD

**Issue by lfc550** [hashicorp/terraform-provider-vsphere#1875]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.4.2

### Terraform Provider

v2.3.1

### VMware vSphere

v8.0.0.10200

### Description

So, I built a template and have it stored both in a datastore as a template and in a content library as an OVF template. I can deploy VMs using either template in the vSphere console with no problem. They launch with the network interface connected.

However, when trying the same deployment with Terraform, they always launch with the network interface not connected and the Connect at Power On option not checked. I also know that this is checked by default in the template that I made.

I need these VMs to deploy with the network interface connected. I have tried changing just about everything I could think of/find in my Terraform. Currently, the customize network_interface block is leveraging DHCP.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine.this

### Terraform Configuration

```
  resource "vsphere_virtual_machine" "this" {
  for_each         = local.database_server
  name             = each.key
  resource_pool_id = data.vsphere_compute_cluster.this["${each.key}"].resource_pool_id
  datastore_id     = data.vsphere_datastore.root["${each.key}"].id
  num_cpus         = each.value.num_cpus
  memory           = each.value.memory
  guest_id         = "ubuntu64Guest"
  firmware         = "efi"

  network_interface {
    network_id   = data.vsphere_network.this["${each.key}"].id
    adapter_type = try(each.value.network_adapter_type, "vmxnet3")
  }

  disk {
    label            = format("%s-%s", each.key, "disk0")
    size             = each.value.root_storage
    datastore_id     = data.vsphere_datastore.root["${each.key}"].id
    eagerly_scrub    = false
    thin_provisioned = true
  }

  clone {
    template_uuid = data.vsphere_content_library_item.this.id

    customize {
      linux_options {
        host_name = each.key
        domain    = var.domain_name
      }

      network_interface {}

    }
  }
}
```

### Debug Output

```
Error: 
│ Virtual machine customization failed on "/ABC/vm/ABC-postgres-foo":
│ 
│ An error occurred while customizing VM abc-postgres-foo. For details reference the log file /var/log/vmware-imc/toolsDeployPkg.log in the guest OS.
│ 
│ The virtual machine has not been deleted to assist with troubleshooting. If
│ corrective steps are taken without modifying the "customize" block of the
│ resource configuration, the resource will need to be tainted before trying
│ again. For more information on how to do this, see the following page:
│ https://www.terraform.io/docs/commands/taint.html
│ 
│ 
│   with vsphere_virtual_machine.this["abc-postgres-foo],
│   on main.tf line 3, in resource "vsphere_virtual_machine" "this":
│    3: resource "vsphere_virtual_machine" "this" {
```

### Expected Behavior

The VM should be deployed with the network interface in the connected state. This is not the case.

### Actual Behavior

The VM is deployed with the network interface not connected.

### Steps to Reproduce

terraform apply

### Environment Details

deploying an ubuntu 22.04 server OVF template

**Comment by tenthirtyam** [comment]
> _deploying an ubuntu 22.04 server OVF template_

Is cloud-init still enabled on the Ubuntu image? If so, you should use `extra_config`. [Example](https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine/clone-template-linux-cloud-init).

If cloud-init has been removed from the image and you wish to perform the customization using guest tools define your `customize` block.

```hcl
  clone {
    template_uuid = template_uuid = data.vsphere_content_library_item.this.id
    customize {
      linux_options {
        host_name = var.vm_hostname
        domain    = var.vm_domain
      }
      network_interface {
        ipv4_address = var.vm_ipv4_address
        ipv4_netmask = var.vm_ipv4_netmask
      }

      ipv4_gateway    = var.vm_ipv4_gateway
      dns_suffix_list = var.vm_dns_suffix_list
      dns_server_list = var.vm_dns_server_list
    }
  }
```

**Comment by tenthirtyam** [comment]
@lfc550 - If possible, please use the Markdown editor to format the hcl and console outputs in code blocks.

**Comment by lfc550** [comment]
@tenthirtyam sorry for the formatting. Thought I did that. I'll fix it when I am back at my computer.

However, I see you recommend defining my customize block if not using cloud-init but, maybe hard to read right now, I did define my customization block.

**Comment by lfc550** [comment]
@tenthirtyam I updated the formatting.

Also, the recommended extra_config does not scale well with terraform and I would prefer to use the customize block. However, it does not seem to be working for me. Any pointers as to where to look?

**Comment by tenthirtyam** [comment]
Is cloud-init in use on the Ubuntu image? It's there by default. If so, remove it.

**Comment by tenthirtyam** [comment]
Can you try the example I provided above?

**Comment by lfc550** [comment]
@tenthirtyam the customize block, I presume?

**Comment by lfc550** [comment]
Also, some errors from the VM

```
[2023-03-29T21:08:17.504Z] [   error] execv failed to run (/usr/bin/cloud-init), errno=(2), error message:(No such file or directory)
....
[2023-03-29T21:08:18.608Z] [   error] Deploy error: 'Deployment failed.The forked off process returned error code.'.
[2023-03-29T21:08:18.608Z] [   error] Package deploy failed in DeployPkg_DeployPackageFromFile
```

**Comment by tenthirtyam** [comment]
Looks like cloud-init is still installed or expected. This is an example for removing it from Ubuntu:

```console
apt-get purge cloud-init -y
rm -rf /etc/cloud/ && sudo rm -rf /var/lib/cloud/
rm -f /etc/netplan/00-installer-config.yaml
rm -f /etc/netplan/50-cloud-init.yaml
```

**Comment by lfc550** [comment]
@tenthirtyam same issue where the customization fails.

cloud-init is not on my system:

```
Unit cloud-init.service could not be found.
...
Package 'cloud-init' is not installed, so not removed
```

also, logs from the VM below

```
[2023-03-29T21:51:33.528Z] [   error] Customization command failed with exitcode: 127, stderr: ''.
[2023-03-29T21:51:33.528Z] [    info] cloud-init is not installed.
...
[2023-03-29T21:51:34.529Z] [   error] Customization process returned with error.
[2023-03-29T21:51:34.529Z] [   debug] Deployment result = -1.
[2023-03-29T21:51:34.529Z] [    info] Setting 'unknown' error status in vmx.
[2023-03-29T21:51:34.530Z] [    info] Transitioning from state 'INPROGRESS' to state 'ERRORED'.
[2023-03-29T21:51:34.530Z] [    info] ENTER STATE 'ERRORED'.
[2023-03-29T21:51:34.530Z] [    info] EXIT STATE 'INPROGRESS'.
[2023-03-29T21:51:34.531Z] [   debug] Setting deploy error: 'Deployment failed.The forked off process returned error code.'.
[2023-03-29T21:51:34.531Z] [   error] Deployment failed.The forked off process returned error code.
[2023-03-29T21:51:34.531Z] [    info] Launching cleanup.
[2023-03-29T21:51:34.531Z] [   debug] Command to exec : '/bin/rm'.
[2023-03-29T21:51:34.531Z] [    info] sizeof ProcessInternal is 56
[2023-03-29T21:51:34.531Z] [    info] Returning, pending output from stdout
[2023-03-29T21:51:34.531Z] [    info] Returning, pending output from stderr
[2023-03-29T21:51:34.631Z] [    info] Process exited normally after 0 seconds, returned 0
[2023-03-29T21:51:34.631Z] [    info] No more output from stdout
[2023-03-29T21:51:34.631Z] [    info] No more output from stderr
[2023-03-29T21:51:34.631Z] [    info] Customization command output:
''.
[2023-03-29T21:51:34.631Z] [    info] sSkipReboot: 'false', forceSkipReboot 'false'.
[2023-03-29T21:51:34.631Z] [   error] Deploy error: 'Deployment failed.The forked off process returned error code.'.
[2023-03-29T21:51:34.631Z] [   error] Package deploy failed in DeployPkg_DeployPackageFromFile
[2023-03-29T21:51:34.631Z] [   debug] ## Closing log
```

**Comment by lfc550** [comment]
@tenthirtyam also, I made sure all of those directories/files were removed. However, there is still one in /etc/netplan

```
99-netcfg-vmware.yaml
```

**Comment by tenthirtyam** [comment]
The issue seems guest OS specific versus being related to the provider.

**Comment by lfc550** [comment]
@tenthirtyam can you point me to an Ubuntu guest os image that would not run into this issue? I downloaded the official one from ubuntu for 22.04

**Comment by lfc550** [comment]
also, why would this only be an issue with terraform and not when using the same thing from the console? Shouldn't the provider be leveraging the same console specifications and commands through the API?

**Comment by lfc550** [comment]
issue was likely do to some corruption of the base image I was using. Using a fresh copy of the OS worked.
