### ISSUE TITLE
Add support for initial power state when created

### ISSUE THREAD

**Issue by IreshMM** [hashicorp/terraform-provider-vsphere#1877]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Ability to control whether to start or not start the VM after creation

### Use Case(s)

There are instances we just need terraform to create the VMs but not touch the power state.

### Potential Terraform Provider Configuration

```hcl
resource "vsphere_virtual_machine" "vm" {
  ......
  initial_power_state = "stopped"
  // initial_power_state = "started"
}

```

**Comment by tenthirtyam** [comment]
After previous deliberations with the maintainers, it was decided that at this time a similar capability would not be added to the provider as it tends to blur the lines between [mutable vs. immutable infrastructure](https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure).

If you take a look back to #327, the same enhancement was requested and the maintainer at the time [shared the reasoning](https://github.com/hashicorp/terraform-provider-vsphere/issues/327#issuecomment-352559036) at the time for not including the capability. 

 cc @appilon
