### ISSUE TITLE
Failed to add servers to an exist vm group in vsphere provider

### ISSUE THREAD

**Issue by ChaunceyZ36** [hashicorp/terraform-provider-vsphere#1878]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.4.2

### Terraform Provider

v2.3.1

### VMware vSphere

v7.0.3

### Description

If my cluster has a vm group named "test" and I want to add a new build server to the group, it will fail; but I use the name which do not exist, such as "test2", it will run successful and sever will be added to the group.

### Affected Resources or Data Sources

`resource\vsphere_compute_cluster_vm_group`

### Terraform Configuration

```
resource "vsphere_compute_cluster_vm_group" "cluster_vm_group" {
  name                = "test"
  compute_cluster_id  = "${data.vsphere_compute_cluster.cluster.id}"
  virtual_machine_ids = ["${vsphere_virtual_machine.vm.*.id}"]
}
```

### Debug Output

```console
Error: A specified parameter was not correct: groupSpec.info.name

on .terraform/modules/example-server-windowsvm/main.tf line 291, in resource
"vsphere_compute_cluster_vm_group" "cluster_vm_group":
291: resource "vsphere_compute_cluster_vm_group" "cluster_vm_group" {
```

### Expected Behavior

add new built server to exist vm group

### Actual Behavior

only new group can be created 

### Steps to Reproduce

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/compute_cluster_vm_group

use example also reproduce

**Comment by ChaunceyZ36** [comment]
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine, 
I have checked resource/vsphere_virtual_machine  , also do not have the parameter about vm group

**Comment by burnsjared0415** [comment]
i added some new code, but i do have a question, the new code works with 
```
terraform import vsphere_compute_cluster_vm_group.cluster_vm_group \
  '{"compute_cluster_path": "/dc1/host/cluster1", \
  "name": "terraform-test-cluster-vm-group"}'
 ```
 after importing the group to there terraform state the new code will just add any new VM's, the issue is that you would need to create new plan for any new groups. Please let me know if this will work.
