### ISSUE TITLE
Add support for Setting MTU in network_interface under clone customize for vsphere_virtual_machine

### ISSUE THREAD

**Issue by LargoUsagi** [hashicorp/terraform-provider-vsphere#1889]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently there is no way to set the MTU of a network interface in the clone section.  If any networks on a VM require a custom MTU you cannot use the customize section of the clone section for vsphere_virtual_machine

### Use Case(s)

Setting MTU to specific values without having to remove the customize block and rely on the userdata/meta data.  This would allow the generated netplan to sync  to the mac addresses generated during vm provisioning instead of relying on the network interfaces having consistent naming IE ens192/eth0.

This would also add to reliability if the interfaces are ever re arranged or modified as we should not expect the MAC addresses to change.

### Potential Terraform Provider Configuration

clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = "hello-world"
        domain    = "example.com"
      }
      network_interface {
        ipv4_address = "172.16.11.10"
        ipv4_netmask = 24
        mtu = 9000
      }
      ipv4_gateway = "172.16.11.1"
    }
  }

**Comment by hmahdiany** [comment]
We have also a similar need to set MTU via this provider.
