### ISSUE TITLE
Unsupported library item type: iso

### ISSUE THREAD

**Issue by Zheer09** [hashicorp/terraform-provider-vsphere#1904]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.4.6

### Terraform Provider

v2.4.0

### VMware vSphere

v8.0.0

### Description

I want to create a VM from a existing content library but it mentions that iso type is not supported , i am using local iso image 

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

```hcl

data "vsphere_datacenter" "dc" {
  name = "DCS"
}

data "vsphere_datastore_cluster" "datastore_cluster" {
  name          = "PROD-DSC"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = "datastore-prod3-3"
  datacenter_id = data.vsphere_datacenter.dc.id
}


data "vsphere_compute_cluster" "cluster" {
  name          = "PROD-CLUSTER"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "NETWORK"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "host" {
  name          = "hostName"
  datacenter_id = data.vsphere_datacenter.dc.id
}


data "vsphere_content_library" "existing_library" {
  name = "WSC-ContentLibrary-ProdHost-2"
}

data "vsphere_content_library_item" "item" {
  name       = "ubuntu-22.04.2-live-server-amd64"
  type       = "iso"
  library_id = data.vsphere_content_library.existing_library.id
}


resource "vsphere_virtual_machine" "vm" {
  name             = "be-09-prod-tf"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  host_system_id   = data.vsphere_host.host.id
  # scsi_controller_count = 0


  # only if you DO NOT want to wait for an IP address
  wait_for_guest_net_routable = false

  num_cpus = 4
  memory   = 16384
  # guest_id = "centos8_64Guest"

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label            = "disk0"
    size             = 150
    thin_provisioned = true
  }

  clone {
    template_uuid = data.vsphere_content_library_item.item.id
  }
}



### Debug Output

```hcl
╷
│ Error: unsupported library item type: iso
│ 
│   with vsphere_virtual_machine.vm,
│   on vm_machine.tf line 43, in resource "vsphere_virtual_machine" "vm":
│   43: resource "vsphere_virtual_machine" "vm" {
│ 
╵

### Panic Output

_No response_

### Expected Behavior

It should create the VM connected to CD/DVD with content library 

### Actual Behavior

As in the debug mentions ISO not supported even it in the doc ISO is allowed type of content library item i

### Steps to Reproduce

Using the configuration file you can get the issue 

### Environment Details

_No response_

### Screenshots

_No response_

### References

_No response_

**Comment by tenthirtyam** [comment]
Hi there! 👋🏻 You can not clone (or boot) a virtual machine resource from an ISO in the content library. You can only clone from a standard template or an OVF template in the content library.

**Comment by Zheer09** [comment]
@tenthirtyam Then Anyway to connect cdrom to content library?

**Comment by tenthirtyam** [comment]
Marking this issue as closed as this is an unsupported option for the provider.

if you are looking to build virtual
machine templates using IaC ai encourage you to look at Packer and the Packer Plugin for vSphere which you can this use the resulting images as as the clone element for a resource.
