### ISSUE TITLE
Add support for memoryReservationLockedToMax

### ISSUE THREAD

**Issue by ashtonian** [hashicorp/terraform-provider-vsphere#1920]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Missing the ability to set memoryReservationLockedToMax checkbox. Good first pr, may try it. 

Here is the field ->
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/97e6db01-d441-472e-ad53-b48c2bb0e1e4/45347fb1-052d-44b7-b3e9-cbefc34488e3/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.ConfigInfo.html memoryReservationLockedToMax

similar field ->
https://github.com/hashicorp/terraform-provider-vsphere/blob/fdea14a3f30ba99de578650d09693f49942bf44e/vsphere/virtual_machine_config_structure.go#L926

its already in the helper client -> 
https://github.com/search?q=repo%3Avmware%2Fgovmomi%20memoryReservationLockedToMax&type=code

### Use Case(s)

This setting is required when doing pcie passthrough. Additionally if you don't enable this, the vm will create a swap file for hot management. Just to note this will reserve all the guest mem on the host and it can't be shared.

**Comment by tenthirtyam** [comment]
Hello! This enhancement was added in v2.7.0 in https://github.com/hashicorp/terraform-provider-vsphere/pull/2093.
