### ISSUE TITLE
v1.22 tries to set hwVersion again, and fails

### ISSUE THREAD

**Issue by bish0polis** [hashicorp/terraform-provider-vsphere#1926]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

0.12.31

### Terraform Provider

v1.22

### VMware vSphere

6.5, 7.0.2

### Description

While updating the vSphere provider in prep for migrating off older vSphere (std) installations, the provider decided to add some benign in-place parameters:

    # vsphere_virtual_machine.atlvmhosts["triton"] will be updated in-place
    ~ resource "vsphere_virtual_machine" "atlvmhosts" {
          annotation                              = " "
      :
        + ide_controller_count                    = 2
      :
        + poweron_timeout                         = 300
      :
        + sata_controller_count                   = 0
          scsi_bus_sharing                        = "noSharing"
          scsi_controller_count                   = 4
          scsi_type                               = "pvscsi"
      :
    }

These are not a concern for us, as you may notice.

But during Apply, though, we get this:

    Error: The attempted operation cannot be performed in the current state (Powered on).
      on vms-atl.tf line 4, in resource "vsphere_virtual_machine" "atlvmhosts":
       4: resource "vsphere_virtual_machine" "atlvmhosts" {

.. for a powered-on host, and this for one that's dark:

    Error: The operation is not supported on the object.
      on vms-atl.tf line 4, in resource "vsphere_virtual_machine" "atlvmhosts":
       4: resource "vsphere_virtual_machine" "atlvmhosts" {

The error on the last one is the one I'm most interested in.  I can cope with having to power VMs off.  That's a small price to bill for not upgrading the toolchain yet (it's still jammed behind the supply-chain/airgap issue) but failing to mod even the dark VM is surprising.

If you can remind me how to get a debug of the state or process, I'll be happy to provide what I can.

```
# rpm -qa | grep -i terraform
golang-github-terraform-provider-esxi-1.9.1-0.1.x86_64
golang-github-terraform-provider-vsphere-1.22.0-0.1.x86_64
golang-github-terraform-provider-redfish-0.2.0-0.x86_64
terraform-0.12.31-1.el7.harbottle.x86_64
golang-github-terraform-provider-powerstore-1.0.0-1.x86_64
```

### Affected Resources or Data Sources

```
vsphere_virtual_machine
```

### Terraform Configuration

I'm worried that we're not very interested in debugging this, and I'm hoping this jogs someone's memory.

If not, and if we ARE interested, I can carve out a minimal setup, I think.  I'm leery that the setup is so old that interest in examining it *beyond* the "yeah I remember that" will be very low.  If you're game, though, I am too.

### Debug Output

as above.

### Expected Behavior

Of course the expected behaviour is hot reconfig of a VM to add in the missing benign bits.

### Actual Behavior

as far above, the actual behaviour is the `terraform apply` fails.

### Steps to Reproduce

As above, if there is enough interested to look into it beyond a quick brainstorm/brainw-wrack, then I'll cook up a Vagrant VM spec.

### Environment Details

- very recent gitlab (after the editor breakage)
- minimal VM working as gitlab-runner

```
# rpm -qa | grep -i terraform
golang-github-terraform-provider-esxi-1.9.1-0.1.x86_64
golang-github-terraform-provider-vsphere-1.22.0-0.1.x86_64
golang-github-terraform-provider-redfish-0.2.0-0.x86_64
terraform-0.12.31-1.el7.harbottle.x86_64
golang-github-terraform-provider-powerstore-1.0.0-1.x86_64
```

### Screenshots

![image](https://github.com/hashicorp/terraform-provider-vsphere/assets/13486046/12287f3e-3fad-4a0e-8cb3-5c27b2bea8a1)

### References

It smells like a reversion of https://github.com/hashicorp/terraform-provider-vsphere/pull/1055 but only because it's arbitrarily trying to update a hwVersion unecessarily again.

**Comment by tenthirtyam** [comment]
Please consider updating your provider to a newer version - e.g. v2.7.0.
