### ISSUE TITLE
Linux customisation running into timeout

### ISSUE THREAD

**Issue by tom-mes** [hashicorp/terraform-provider-vsphere#1932]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.5.0
v1.4.6

### Terraform Provider

v2.4.0

### VMware vSphere

v7.0.3

### Description

The create of a vm is running into a timeout when using customize linux_options for the setup of IP /dns etc.
The machine is already configured and in desired state - only the event pull is not working.

We have a high retention amount of events on our productive system. The terraform pulling of events does not use any filter so it is running into a timeout. Maybe it is a solution to use a filter and pull only the events of the last 10 minutes (depending on the defined timeout). 
Testing a similar manual query on the  event queue with a filter works, without it also runs into timeout.

Testing our config on a small test vsphere cluster works when there is only a small event retention.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

```hcl
  clone {
    template_uuid = data.vsphere_virtual_machine.template.uuid

    customize {
      linux_options {
        host_name = each.value.name
        domain    = "mytest.mygroup"
      }
      network_interface {
        ipv4_address = each.value.address
        ipv4_netmask = each.value.netmask
      }
      ipv4_gateway = each.value.asa_gateway
    }
  }
```

### Debug Output

```console
vsphere_virtual_machine.rocky_server["v-sax-e12-e-a"]: Still creating... [9m40s elapsed]
vsphere_virtual_machine.rocky_server["v-sax-e12-e-a"]: Still creating... [9m50s elapsed]
vsphere_virtual_machine.rocky_server["v-sax-e12-e-a"]: Still creating... [10m0s elapsed]
╷
│ Error: 
│ Virtual machine customization failed on "/Test/v-sax-e12-e-a":
│ 
│ timeout waiting for customization to complete
│ 
│ The virtual machine has not been deleted to assist with troubleshooting. If
│ corrective steps are taken without modifying the "customize" block of the
│ resource configuration, the resource will need to be tainted before trying
│ again. For more information on how to do this, see the following page:
│ https://www.terraform.io/docs/commands/taint.html
│ 
│ 
│   with vsphere_virtual_machine.rocky_server["v-sax-e12-e-a"],
│   on main.tf line 43, in resource "vsphere_virtual_machine" "rocky_server":
│   43: resource "vsphere_virtual_machine" "rocky_server" {
│ 
```

### Expected Behavior

Creating a vm without timeout

### Actual Behavior

timeout

### Steps to Reproduce

vsphere cluster with a high rentention / amount of log evnts

**Comment by tenthirtyam** [comment]
Hi @tom-mes 👋 - have you tried setting the API Timeout in the provider configuration to help resolve the issue due to the potential congestion?

Ryan

**Comment by burnsjared0415** [comment]
@tom-mes are you still seeing this? or did you try the timeout?
