### ISSUE TITLE
Updating tag category cardinality causes error 404

### ISSUE THREAD

**Issue by rippleFCL** [hashicorp/terraform-provider-vsphere#1959]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.5.3

### Terraform Provider

2.4.1

### VMware vSphere

8.0.1

### Description

When I modify the cardinality on a `vsphere_tag_category` resource, it replaces all tags under and including this category. 

If a tag is recreated, the reference to the old tag is invalid and causes a 404 when detaching it from an `vsphere_virtual_machine`

### Affected Resources or Data Sources

`resource\vsphere_tag_category`

### Terraform Configuration

https://github.com/ditrames/terraform-tag-catagory-bug

### Debug Output

```
vsphere_tag.test: Destroying... [id=urn:vmomi:InventoryServiceTag:3d059b86-e802-4744-bfc5-ec29804bf7bc:GLOBAL]
vsphere_tag.test: Destruction complete after 0s
vsphere_tag_category.default: Destroying... [id=urn:vmomi:InventoryServiceCategory:9cc1e538-0cfb-4852-92ca-4c160756c642:GLOBAL]
vsphere_tag_category.default: Destruction complete after 0s
vsphere_tag_category.default: Creating...
vsphere_tag_category.default: Creation complete after 0s [id=urn:vmomi:InventoryServiceCategory:1b59c10d-29e1-41fa-bee6-9236c54be4e1:GLOBAL]
vsphere_tag.test: Creating...
vsphere_tag.test: Creation complete after 0s [id=urn:vmomi:InventoryServiceTag:37edf48d-8cad-4d88-8b5d-7ea12246a69a:GLOBAL]
module.test[0].vsphere_virtual_machine.vm: Modifying... [id=420a7b94-b551-ed17-a9b6-b488f89f8edf]
╷
│ Error: error detaching tags to object ID "vm-7042": POST https://vcsa.home.lan/rest/com/vmware/cis/tagging/tag-association/id:urn:vmomi:InventoryServiceTag:3d059b86-e802-4744-bfc5-ec29804bf7bc:GLOBAL?~action=detach: 404 Not Found
│ 
│   with module.test[0].vsphere_virtual_machine.vm,
│   on modules/vsphere_vm/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
│    5: resource "vsphere_virtual_machine" "vm" {
```

### Expected Behavior

Detach the tag from the ```vsphere_virtual_machine```. 

Then recreate the tag and reassign 

### Actual Behavior

The tag is recreated, removing the tag in use by the ```vsphere_virtual_machine```

terraform then attempts to detach a tag that no longer exists and fails

### Steps to Reproduce

clone https://github.com/ditrames/terraform-tag-catagory-bug

run ```terraform init```
run ```terraform apply```
modify ```cardinality``` to ```"MULTIPLE"``` in ```./tags.tf```
run ```terraform apply```

**Comment by burnsjared0415** [comment]
So i ran through this, i did not get the same error, the issue i have is it recreates the tag and removes it from the VM themselves, so i will figure out how to make it just change the `cardinality`.

**Comment by burnsjared0415** [comment]
i figured out something, i will remove the forceNew from the `cardinality`
