### ISSUE TITLE
Unable to connect to v center via self signed ssl certifcate (allow_unverified_ssl == false is failing)  

### ISSUE THREAD

**Issue by pradeep-git23** [hashicorp/terraform-provider-vsphere#1994]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.4

### Terraform Provider

v2.4.1 

### VMware vSphere

7.0.3

### Description

When allow_unverified_ssl == false , Automation is failing 

### Affected Resources or Data Sources

provider "vsphere" {
             user = "{{vmware_user}}"
             password = "{{vmware_pass}}"
             vsphere_server = "{{vcenter}}"
             allow_unverified_ssl = false
}

### Terraform Configuration

automation is failing while             allow_unverified_ssl = false

### Debug Output

[31m│[0m [0m[1m[31mError: [0m[0m[1merror setting up new vSphere SOAP client: Post &quot;https://ip.of.vcenter/sdk&quot;: x509: certificate signed by unknown authority[0m

### Expected Behavior

It should execute terraform plan and apply 
.

### Actual Behavior

Failing with the error at terraform Plan. [31m│[0m [0m[1m[31mError: [0m[0m[1merror setting up new vSphere SOAP client: Post &quot;https://ip/sdk&quot;: x509: certificate signed by unknown authority[0m

### Steps to Reproduce

allow_unverified_ssl = false
while executing automation from awx to vcenter

### Screenshots

![error from awx](https://github.com/hashicorp/terraform-provider-vsphere/assets/65698353/106e2518-0692-4054-9e48-fa03242b6ca7)

**Comment by tenthirtyam** [comment]
Set it to `true` for self-signed or add the vCenter Server and VMCA certificates to your trust store if using `false`.

**Comment by pradeep-git23** [comment]
Hi @tenthirtyam thank you for your input i am using K8 cluster for running awx.

**Comment by tenthirtyam** [comment]
Are you still having an issue?

**Comment by tenthirtyam** [comment]
No reply from OP.
