### ISSUE TITLE
Add support for additional disks when creating a VM from a vsphere_ovf_vm_template

### ISSUE THREAD

**Issue by joaofeteira** [hashicorp/terraform-provider-vsphere#2000]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Hi,

Would it be possible to add additional disks when creating a VM from an OVF template?
Right now it seems it isn't since when explicitly adding the disks parameter inside the vsphere_virtual_machine resource it just replaces the existing ova included disk. Also the OVA template data doesn't have the disks parameter so we cannot access it.
BR

### Use Case(s)

Additional disks on existing ova image

**Comment by adeturner** [comment]
@joaofeteira, doesnt this do it? My vm has sda and sdb devices created correctly

```
data "vsphere_content_library_item" "MY_OVF" {
  name       = var.my_image_name
  type       = "ovf"
  library_id = data.vsphere_content_library.CL_PACKER_IMAGES.id
}

resource "vsphere_virtual_disk" "mydisk" {
  size               = 20
  type               = "thin"
  vmdk_path          = "/${local.hostname}/mydisk.vmdk"
  create_directories = true
  datacenter         = data.vsphere_datacenter.datacenter.name
  datastore          = data.vsphere_datastore.datastore.name
}

resource "vsphere_virtual_machine" "my_vm" {
...
  disk {
    # https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#disk-options
    label       = "disk0"
    size        = 40
    unit_number = 0 # must be unique (default 0)
  }

  disk {
    label        = "disk1"
    attach       = true
    datastore_id = data.vsphere_datastore.datastore.id
    path         = vsphere_virtual_disk.mydisk.vmdk_path
    unit_number  = 1 # must be unique
  }

  clone {
    template_uuid = data.vsphere_content_library_item.MY_OVF.id
    customize { ... }
  }
}
```

```
# fdisk -l /dev/sda
Disk /dev/sda: 40 GiB, 42949672960 bytes, 83886080 sectors
Disk model: Virtual disk
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 721EE3FF-179F-4B3F-8391-A13AA3C60164

Device       Start      End  Sectors Size Type
/dev/sda1     2048  2099199  2097152   1G EFI System
/dev/sda2  2099200  4196351  2097152   1G Linux filesystem
/dev/sda3  4196352 83884031 79687680  38G Linux filesystem

# fdisk -l /dev/sdb
Disk /dev/sdb: 20 GiB, 21474836480 bytes, 41943040 sectors
Disk model: Virtual disk
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

```

**Comment by joaofeteira** [comment]
Hi,

I think I have tested it like you have described and it didn't work. In my use case I am not using content library but instead the vsphere_ovf_vm_template data and the vsphere_virtual_machine resource with the ovf_deploy option. That might be the difference.
I will close this for now and test it again when I have some more time. 
Thanks for the help.
