### ISSUE TITLE
error sending customization spec

### ISSUE THREAD

**Issue by antwacky** [hashicorp/terraform-provider-vsphere#2006]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.5.6

### Terraform Provider

2.4.2

### VMware vSphere

7.0.3 build 21958406

### Description

I'm getting an error when trying to apply customization following cloning of a Debian 12 template.

The template guest is set to Ubuntu64, as there is not option for Debian 12 yet, assume this is ok.

The error shown in vsphere is:

```
Customization of the guest operating system is not supported due to the given reason: Tools is not installed in the GuestOS. Please install the latest version of open-vm-tools or VMware Tools to enable GuestCustomization.
```

However, if I remove the customization from the terraform configuration and apply, once the VM boots, vsphere shows that the guest tools are running (as they should be, I installed and verified the tools prior).

The terraform apply seems to exit very quickly before the VM has booted, should it not wait for the VM to boot before determining whether tools is running?

### Affected Resources or Data Sources

```resource/vsphere_virtual_machine```

### Terraform Configuration

```
data "vsphere_virtual_machine" "template" {
  name          = local.template_name
  datacenter_id = data.vsphere_datacenter.this.id
}

resource "vsphere_virtual_machine" "this" {
  name                   = var.hostname
  folder                 = local.vm_folder
  resource_pool_id       = data.vsphere_resource_pool.this.id
  datastore_id           = data.vsphere_datastore.this.id
  num_cpus               = var.cpu
  memory                 = var.memory
  cpu_hot_add_enabled    = true
  memory_hot_add_enabled = true

  guest_id = data.vsphere_virtual_machine.template.guest_id

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = var.hostname
        domain    = local.domain
      }
      network_interface {
        ipv4_address = netbox_available_ip_address.this.ip_address
        ipv4_netmask = 24
      }
      ipv4_gateway = local.network_gateway
    }
  }

  network_interface {
    network_id = data.vsphere_network.this.id
  }

  disk {
    label            = "root_disk"
    size             = var.root_disk_size
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  dynamic "disk" {
    for_each = toset(var.additional_disks)
    content {
      label = disk.value.name
      size  = disk.value.size
    }
  }

}
```

### Debug Output

Debug output does not provide any further context.

### Panic Output

```
Error: error sending customization spec: Customization of the guest operating system is not supported due to the given reason:
```

### Expected Behavior

I expected it to wait for the VM to boot, determine tools are running, and proceed with customization.

### Actual Behavior

Exits immediately after creating VM.

### Steps to Reproduce

Use the terraform configuration provided above.

**Comment by antwacky** [comment]
I saw that issue, tried 2.4.1 and got the same error.

**Comment by appilon** [comment]
Are you certain you managed to roll back to 2.4.1?

**Comment by antwacky** [comment]
Absolutely certain, I changed the version to 2.4.1, terraform init -upgrade and saw the version being installed.

**Comment by antwacky** [comment]
Trying via the UI (create VM from template, customize operating system) I get an error: "You do not have "Read customization specifications" privilege assigned to view and manage customization specifications on the vCentre Server system".

I guess this is related, but the error doesn't mention permissions. I'll get this assigned and try again in the morning.

**Comment by antwacky** [comment]
I got the permissions so I can customize via the UI now, although there's no customization options, there's no complaint in the UI about permissions now.

However, I'm still getting the same error via Terraform (both 2.4.1 and 2.4.2).

**Comment by antwacky** [comment]
Found it, I had to convert my template back to a VM, start it, shut it down, convert back to template.

I created the VMDK from scratch on Debian, and made modifications (such as installing open-vm-tools) within a chroot environment with the image mounted via nbd.

I assume it's something to do with systemctl.
