### ISSUE TITLE
VSphere Linux hostname does not contain the FQDN upon creation

### ISSUE THREAD

**Issue by kolojoe** [hashicorp/terraform-provider-vsphere#2007]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.4.5

### Terraform Provider

v2.2.0

### VMware vSphere

v7.0.3.01400

### Description

Upon creation of a virtual machine the hostname that is set is just the value of `host_name` in the Linux customization options:

```
    customize {
      linux_options {
        host_name = "hello-world"
        domain    = "example.com"
      }
```

and not the FQDN.

i.e. 
```
$ hostname
hello-world
```

vs

```
$ hostname
hello-world.example.com
```

I believe the proper behavior should be to set the entire FQDN.

I think the section of code that would change would be here:

[HostName: types.CustomizationFixedName](https://github.com/hashicorp/terraform-provider-vsphere/blob/5ca39fa7e5d44d45d1bf977b5aa9b2593995f0a1/vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go#L298-L301)

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

Any Linux host creation via vsphere. This is the example from your docs:

```
data "vsphere_datacenter" "datacenter" {
  name = "dc-01"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore-01"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = "cluster-01"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = "ubuntu-server-template"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = "hello-world"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  num_cpus         = 1
  memory           = 1024
  guest_id         = data.vsphere_virtual_machine.template.guest_id
  scsi_type        = data.vsphere_virtual_machine.template.scsi_type
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }
  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = "hello-world"
        domain    = "example.com"
      }
      network_interface {
        ipv4_address = "172.16.11.10"
        ipv4_netmask = 24
      }
      ipv4_gateway = "172.16.11.1"
    }
  }
}
```

### Debug Output

No debug output, the hostname in VSphere shows only the `host_name` value.

### Expected Behavior

VSphere should show the FQDN (host_name + domain) instead of just host_name.

### Actual Behavior

VSphere shows just host_name.

### Steps to Reproduce

Create a VM with the VSphere provider.

**Comment by tenthirtyam** [comment]
Hi @kolojoe 👋🏻 

This is the same behavior that you would see if using a customization specification in vSphere using the UI or PowerCLI and is the expected result - all of which are calling the vmtools unless you use cloud-init.

Here's a good [RHEL bug](https://bugzilla.redhat.com/show_bug.cgi?id=2056891) on a similar issue. 

Ryan
