### ISSUE TITLE
resource vsphere_folder  in datastore is impossible to create

### ISSUE THREAD

**Issue by jStrider** [hashicorp/terraform-provider-vsphere#2020]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.5.4

### Terraform Provider

2.4.3

### VMware vSphere

 vSphere 7

### Description

I'm trying to create a folder on my datastore on my standalone esxi.

I tried to troubleshoot as far as I could.

vsphere_folder call the govmoni api call (folder.create).

I can reproduce the same errors i get with terraform but with govc ( I tried a lot of different way to give the folder path)

```
## govc folder.create -k /ha-datacenter/datastore/myDatastore/myFolder
govc: folder '/ha-datacenter/datastore/myDatastore' not found

## govc folder.create -k /ha-datacenter/datastore/myDatastore/
govc: folder '/ha-datacenter/datastore/myDatastore' not found

## govc folder.create -k /ha-datacenter/datastore/myDatastore
govc: ServerFaultCode: The operation is not supported on the object.

## govc folder.create -k /ha-datacenter/datastore/myFolder
govc: ServerFaultCode: The operation is not supported on the object.

```

Maybe you can think "the datastore does not exist but : 

```
## govc ls -k /ha-datacenter/datastore/
/ha-datacenter/datastore/myDatastore
```

I can create folders using govc : 

`govc datastore.mkdir -p -k --ds MyDatastore MyFolder`

output return nothing but I can see the folder on my esxi so, for me it works.

Tell me if I'm doing something wrong.

### Affected Resources or Data Sources

`resource/vsphere_folder`

### Terraform Configuration

```
resource "vsphere_folder" "myFolder" {
  path          = "MyDatastore/myFolder"
  type          = "datastore"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
```

### Debug Output

.

### Expected Behavior

a folder `myFolder` should be created on the datastore `MyDatastore`

### Actual Behavior

an error

### Steps to Reproduce

terraform apply the terraform configuration referenced on a standalone esxi.

**Comment by tenthirtyam** [comment]
This resource is only for creating folders in the vSphere inventory, not in the datastore itself.

The resource supports creating folders of the 5 major types - datacenter folders, host and cluster folders, virtual machine folders, storage folders, and network folders.

I think the docs need to specify "storage" vs "datastore" for accuracy.
