### ISSUE TITLE
Unable to execute a terraform plan

### ISSUE THREAD

**Issue by T0myC** [hashicorp/terraform-provider-vsphere#2057]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.6.3

### Terraform Provider

v2.5.1

### VMware vSphere

v7.0

### Description

I try to create VM on a vSphere server using terraform.
In order to test my connection with my server, I try to get the content of the datacenter by using the vsphere_datacenter DataSource but it doesn't work.

### Affected Resources or Data Sources

data/vsphere_datacenter

### Terraform Configuration

```
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "2.5.1"
    }
  }
}

provider "vsphere" {
  user                         = var.user
  password                 = var.passwd
  vsphere_server        = var.server
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = var.datacenter
}
```

### Debug Output

│ Error: invalid character '<' looking for beginning of value
│ 
│   with provider["registry.terraform.io/hashicorp/vsphere"],
│   on main.tf line 10, in provider "vsphere":
│   10: provider "vsphere" {

### Expected Behavior

Get the informations about cluster

### Actual Behavior

Get the error : "invalid character '<' looking for beginning of value"

### Steps to Reproduce

Copy the code above and execute a terraform plan.

### Environment Details

The vSphere server is in OVH private cloud secure by 2FA.

**Comment by tenthirtyam** [comment]
A redacted. but similar example of the datacenter name would need to be provided.

```bash
│ Error: invalid character '<' looking for beginning of value
│
│ with provider["registry.terraform.io/hashicorp/vsphere"],
│ on main.tf line 10, in provider "vsphere":
│ 10: provider "vsphere" {
```

Looks like an issue in your variable name.

**Comment by T0myC** [comment]
My variable var.server is "nameserver.ovh.com".
There IS not '<' caracter.

**Comment by tenthirtyam** [comment]
More details are ideal for assistance.

Here are some examples of mine that may help in case it's syntax related.

https://github.com/tenthirtyam/terrafom-examples-vmware/tree/main/vsphere/vsphere-virtual-machine

**Comment by T0myC** [comment]
Sorry but I don't know which details I vould add because of the simplicity of the test ...
I just want to do what you have done at the beggining of each of your terraform file.

It seems like the connection with the vSphere is OK because when I enter a wrong password a wrong server name, I have the error saying : error setting up new vSphere SOAP client : Incorrect password/username and no such host.

It's like the API return HTML (so beginning by '<') and terraform was expecting something else.

**Comment by tenthirtyam** [comment]
Try the same connection with govc in govmomi.

**Comment by T0myC** [comment]
I try to connect to my vSphere server but I can't access to my datacenter (datacenter not found) but the command govc about return the following :
```
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      7.0.3
Build:        19234570
OS type:      linux-x64
API type:     VirtualCenter
API version:  7.0.3.0
Product ID:   xxx
UUID:         xxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by T0myC** [comment]
Anyone has an idea please ?

**Comment by louisquentinjoucla** [comment]
Hey!

All routes are not whitelisted with ovh 2FA! You need to setup a whitelist. Please read:
[[https://help.ovhcloud.com/csm/en-gb-vmware-use-2fa?id=kb_article_view&sysparm_article=KB0046140](https://help.ovhcloud.com/csm/en-gb-vmware-use-2fa?id=kb_article_view&sysparm_article=KB0046140#application-access-permission)
