### ISSUE TITLE
Add support to specify OU Path in guest customization

### ISSUE THREAD

**Issue by shettys-ops** [hashicorp/terraform-provider-vsphere#2130]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Hi Team,

I'm currently working on provisioning using the vsphere_virtual_machine resource with a customized template (created using Packer). When Using terraform for creating the machine With the customize - windows_options option, I'm able to add the newly provisioned VM to the domain, but it lacks the OU Path argument.

Could you please assist me in finding a way to add the machines to the correct OU? Any workarounds would also be appreciated

### Use Case(s)

OU path

**Comment by tenthirtyam** [comment]
Today, this would need to be done by using the `run_once_command_list` option in `windows_options`.

Seems that [vSphere 8.0 U2 added the option to target an OU](https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/api/vcenter/vm/vm/guest/customization/put/), but it's not been added to the provider in the guest customization helper. e.g. `flattenWindowsOptions`

**Comment by tenthirtyam** [comment]
Added to the backlog.

**Comment by shettys-ops** [comment]
thank you so much for your prompt response @tenthirtyam 
I will test this and report back if i need any further support 👍

**Comment by ultral** [comment]
it looks like my PR https://github.com/hashicorp/terraform-provider-vsphere/pull/2181 implements  that functionality

**Comment by tenthirtyam** [comment]
Yes, I've already linked the PR to the existing issue.
