### ISSUE TITLE
sync_time_with_host behavior chanhe in v2.7.0

### ISSUE THREAD

**Issue by ryan-peterson3** [hashicorp/terraform-provider-vsphere#2148]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

latest

### Terraform Provider

latest

### VMware vSphere

v8

### Description

The new version of the vSphere Provider 2.7.0 made a change to the default setting.  See this link:
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#sync_time_with_host

Old Default: sync_time_with_host = False
New Default: sync_time_with_host = True

I do not see this change documented in the change notes.  What is the reason for changing this default behavior?
https://github.com/hashicorp/terraform-provider-vsphere/releases/tag/v2.7.0

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

N/A

### Debug Output

N/A

### Expected Behavior

sync_time_with_host = False

### Actual Behavior

sync_time_with_host = True

### Steps to Reproduce

Run a Terraform Plan after upgrading vSphere Provider

**Comment by tenthirtyam** [comment]
Third item in the CHANGELOG.md.

https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md

**Comment by tenthirtyam** [comment]
See https://github.com/hashicorp/terraform-provider-vsphere/issues/1443.

**Comment by ryan-peterson3** [comment]
Thank you,  it would seem that I am blind.
