### ISSUE TITLE
Configuration for import target does not exist

### ISSUE THREAD

**Issue by Amonlol** [hashicorp/terraform-provider-vsphere#2158]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.5 on linux_amd64

### Terraform Provider

registry.terraform.io/hashicorp/vsphere v2.7.0

### VMware vSphere

6.7.0 Update 3 (Build 16773714)

### Description

I have a problem with importing existing vm's into my state. When I try to do 
```
terraform import vsphere_virtual_machine.vm /depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-01
```

govc output:
```
# govc find -u=************* | grep test
/depo_datacenter/vm/Nodes/test
/depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-01
```

### Affected Resources or Data Sources

resource vsphere_virtual_machine

### Terraform Configuration

My tf project structure:
```
.
├── main.tf
├── terraform.tfstate
└── variables.tf
```

main.tf: https://gist.github.com/Amonlol/8810fde6be99546c181004b53a11e127

variables.tf: https://gist.github.com/Amonlol/13147494384b3f407c0a6b0d94f8fdb0

### Debug Output

```
terraform import vsphere_virtual_machine.vm /depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-01
```
https://gist.github.com/Amonlol/3938d6fa4d9f8608f2d03b0b6c405169

However importing an existing folder works fine:
```
terraform import vsphere_folder.folder /depo_datacenter/vm/Nodes/test
```
https://gist.github.com/Amonlol/484ec07a41ccb87c1a6e0e3dec385549

### Expected Behavior

Terraform should import my existing vm into it's state

### Actual Behavior

Error

### Steps to Reproduce

```
terraform import vsphere_virtual_machine.vm
```

**Comment by Amonlol** [comment]
Should set index for my vm as
```
terraform import vsphere_virtual_machine.vm[0] /depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-01
```

But if I need to import more than 1 vm? I need to manually\script set index for each import?
```
terraform import vsphere_virtual_machine.vm[0] /depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-01
terraform import vsphere_virtual_machine.vm[1] /depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-02
terraform import vsphere_virtual_machine.vm[2] /depo_datacenter/vm/Nodes/test/ubuntu-nodes-test-03
...
```

**Comment by tenthirtyam** [comment]
Hi @Amonlol 👋 ,

Could you please verify if this issue exists on vSphere 7.0 and later since vSphere 6.7 is no longer supported.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom
