### ISSUE TITLE
Add support to fetch datastores within a datastore cluster in `d/datastore_stats`

### ISSUE THREAD

**Issue by mrdevops100** [hashicorp/terraform-provider-vsphere#2159]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.5

### Terraform Provider

v2.7.0

### VMware vSphere

v7.0

### Description

When I use the "vsphere_datastore_stats" datasource it only fetches the top level datastores in a DC. It doesn't list the datastores under a datastore cluster.

### Affected Resources or Data Sources

`d/vsphere_datastore_stats`

### Terraform Configuration

```hcl
data "vsphere_datacenter" "datacenter" {
  name = "dc-01"
}

data "vsphere_datastore_stats" "datastore_stats" {
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

locals {
  free_space_values   = { for k, v in data.vsphere_datastore_stats.datastore_stats.free_space : k => tonumber(v) }
  filtered_values     = { for k, v in local.free_space_values : k => tonumber(v) if v != null }
  numeric_values      = [for v in values(local.filtered_values) : tonumber(v)]
  max_free_space      = max(local.numeric_values...)
  max_free_space_name = [for k, v in local.filtered_values : k if v == local.max_free_space][0]
}

output "max_free_space_name" {
  value = local.max_free_space_name
}

output "max_free_space" {
  value = local.max_free_space
}
```

### Debug Output

Not available

### Panic Output

Not available

### Expected Behavior

Show all the datastores including the ones under datastore cluster

### Actual Behavior

Datasource only fetches the top level datastores in a DC

### Steps to Reproduce

```hcl
data "vsphere_datacenter" "datacenter" {
  name = "dc-01"
}

data "vsphere_datastore_stats" "datastore_stats" {
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

locals {
  free_space_values   = { for k, v in data.vsphere_datastore_stats.datastore_stats.free_space : k => tonumber(v) }
  filtered_values     = { for k, v in local.free_space_values : k => tonumber(v) if v != null }
  numeric_values      = [for v in values(local.filtered_values) : tonumber(v)]
  max_free_space      = max(local.numeric_values...)
  max_free_space_name = [for k, v in local.filtered_values : k if v == local.max_free_space][0]
}

output "max_free_space_name" {
  value = local.max_free_space_name
}

output "max_free_space" {
  value = local.max_free_space
}
```

### Screenshots

n/a

### References

n/a

**Comment by tenthirtyam** [comment]
Hi @nikfot 👋 - would you like to pick this item up to enhance your addition in #1896?

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom

**Comment by nikfot** [comment]
Hello @tenthirtyam ! I'm glad you notified me on that! sure!
