### ISSUE TITLE
vsphere_virtual_disk created on v2.6.1 errors when running terraform plan with v2.7.0

### ISSUE THREAD

**Issue by Jusaa** [hashicorp/terraform-provider-vsphere#2162]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.6.6

### Terraform Provider

v2.7.0

### VMware vSphere

v7.0.3.01700

### Description

Upgrading to terraform-provider-vsphere v2.7.0 introduced a breaking bug for vsphere_virtual_disks created with older versions.

This happens as the vmdk_path variable is now correctly set after this fix: https://github.com/hashicorp/terraform-provider-vsphere/pull/1762

I tried changing the vmdk_path to match the actual old value from vsphere but it doesn't work, and it shouldn't work if I understand the code change correctly. What would be the proper steps to be able to upgrade to latest provider version?

### Affected Resources or Data Sources

resource/vsphere_virtual_disk

### Terraform Configuration

```
resource "vsphere_virtual_disk" "main" {
  size               = var.size
  vmdk_path          = "${var.path}/${var.name}.vmdk"
  datastore          = var.datastore
  datacenter         = var.datacenter
  type               = "thin"
  create_directories = false
}
```

### Debug Output

Planning failed. Terraform encountered an error while generating this plan.
│ Error: Failed to query disk type
│ 
│   with module.example-data.vsphere_virtual_disk.main,
│   on ../../modules/disk/main.tf line 5, in resource "vsphere_virtual_disk" "main":
│    5: resource "vsphere_virtual_disk" "main" {
│ 

### Expected Behavior

Plan after update to provider v2.7.0 passes with either no changes or possible change to the vsphere_virtual_disk configuration

### Actual Behavior

Plan after update to provider v2.7.0 errors out

### Steps to Reproduce

1. Create vsphere_virtual_disk with vsphere provider v2.6.1
2. Update provider to v2.7.0
3. Run terraform plan

**Comment by algofol** [comment]
Same for me:

**Terraform**
v1.7.2

**Terraform Provider**
v2.7.0

**VMware vSphere**
v8.0.1.00000

When changed vsphere provider version to 2.2.0 or even 2.6.1 it worked

**Comment by spacegospod** [comment]
We've picked up govmomi 0.37.1

**Comment by Jusaa** [comment]
Can confirm it works, we successfully updated to v2.8.1 without any problems!
