### ISSUE TITLE
vsphere guest os customization not applying

### ISSUE THREAD

**Issue by lsmokm** [hashicorp/terraform-provider-vsphere#2167]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.5

### Terraform Provider

v2.7.0

### VMware vSphere

v7.0.3

### Description

vm customization spec is created as expected in vcenter but the spec does not apply to windows vm during deployment

### Affected Resources or Data Sources

resource/vsphere_guest_os_customization

### Terraform Configuration

```
resource "vsphere_guest_os_customization" "windows_customization" {
  name = "windows-spec"
  type = "Windows"
  spec {
    windows_options {
      computer_name = "vm-basic-01"
      workgroup     = "lab-wg"
      time_zone     = 085
    }
  }
}
```

### Debug Output

<script src="https://gist.github.com/lsmokm/31f17a59ce06df8f4008a3411a14c708.js"></script>

### Expected Behavior

The vm customization spec should be created and applied to vm(s) during deployment

### Actual Behavior

The vm customization spec is created but not applied to vm(s) during deployment

### Steps to Reproduce

terraform apply

**Comment by stoyanzhelyazkov** [comment]
@lsmokm I tried applying your customization on a Windows Server 2019 VM and it works.

Is it possible that you forgot to sysprep your OS before customizing?
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--system-preparation--overview?view=windows-11

If system preparation isn't performed the customization task passes but has no effect.

**Comment by tenthirtyam** [comment]
Unfortunately, no response from OP. Closing.
