### ISSUE TITLE
 ept_rvi_mode and hv_mode Changing Value after v2.8.0 update

### ISSUE THREAD

**Issue by zachary-plencner** [hashicorp/terraform-provider-vsphere#2193]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.8.2

### Terraform Provider

v2.8.0

### VMware vSphere

v7.0.3

### Description

Probably related to: 
https://github.com/hashicorp/terraform-provider-vsphere/issues/1902
and
https://github.com/hashicorp/terraform-provider-vsphere/pull/2172

After this provider was updated today our pipelines that utilize this are having issues. Terraform wants to reset the value of  ept_rvi_mode and hv_mode to null, when they were previously being detected as something else:
![image](https://github.com/hashicorp/terraform-provider-vsphere/assets/116110992/05e5cc57-9d19-4c77-ad2c-ebd0d1007ac8)

These properties are not being set anywhere in our .tf files. It is creating issues since in order for Terraform to change this value (to "null" apparently) it wants to power off the VM, which is not desirable since it manages systems that are in production.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Detect the infrastructure as matching the Terraform state configuration and continuing.

### Actual Behavior

Terraform wants to power off VM in order to reset these unmanaged properties

### Steps to Reproduce

Do not set the above properties in .tf file
Deploy a machine using provider <=v2.7.0
Rerun Terraform using provider v2.8.0

**Comment by tenthirtyam** [comment]
@stoyan-hristov - can you please take a look into this one based on the prior changes?

**Comment by randomitguylv** [comment]
same issue here

**Comment by stoyan-hristov** [comment]
@spacegospod - can you take a look?

**Comment by spacegospod** [comment]
@tenthirtyam @zachary-plencner This is caused by https://github.com/hashicorp/terraform-provider-vsphere/pull/2172

Prior to 2.8.0 the provider used to always override the values for these properties which caused it to run in-place updates on VMs even when nothing had changed.

The in-place update that you're observing on your pipeline should only occur once.
In my opinion 2.8.0 behaves correctly and 2.7.0 is faulty.

I will revert PR 2172 until I figure out how we can apply it without causing VM power ops events

**Comment by tenthirtyam** [comment]
This has been reverted in v2.8.1.
