### ISSUE TITLE
Issue with disks upon restore/snapshot revert

### ISSUE THREAD

**Issue by mvandriessen** [hashicorp/terraform-provider-vsphere#2199]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.8.2

### Terraform Provider

v2.7.0

### VMware vSphere

v7.0.3

### Description

We've created a module for rolling out our VMs and we had used the following logic..
```
  disk {
    label       = "OS-disk"
    size        = 60
    unit_number = 0
  }
  dynamic "disk" {
    for_each = var.data_disks
    content {
      label       = disk.key
      size        = disk.value.size
      unit_number = index(keys(var.data_disks), disk.key) + 1
    }
  }
```

This resulted in all our disks after the OS-Disk to be named disk1, disk2, etc - this is the recommended disk naming scheme according to the [documentation.](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#disk-options)

Turns out that when you restore a VM from backup or revert from a snapshot, vSphere defaults to setting the labels like "Hard disk 1" , "Hard disk 2", ...  Since label is an immutable attribute, Terraform will destroy the disk and create a new one upon the next plan/apply.

The documentation should be changed to reflect this.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

```
  disk {
    label       = "OS-disk"
    size        = 60
    unit_number = 0
  }
  dynamic "disk" {
    for_each = var.data_disks
    content {
      label       = disk.key
      size        = disk.value.size
      unit_number = index(keys(var.data_disks), disk.key) + 1
    }
  }
```

In our tfvars file, the data_disks block looks like
```
   data_disks = {
      disk1 = {
        size = 200
      }
    }
```

### Debug Output

https://gist.github.com/mvandriessen/4cdd48205c44ee8dcf05283ede551d67

### Expected Behavior

We expect labels to follow the naming convention as outlined in the documentation (disk0, disk1, disk2), in all scenarios.

### Actual Behavior

Upon snapshot revert or backup restore, all hard disks receive the label "Hard disk 1", "Hard disk 2", ...

### Steps to Reproduce

* Create a virtual machine
* Create a vSphere snapshot
* Revert to snapshot
* Trigger a plan

**Comment by tenthirtyam** [comment]
Ref: #363 (Related to import requirements.)

Will add an update to the docs.

**Comment by xtala** [comment]
I think this isn't necessarily a documentation issue. The current requirements of disk label names (diskN), clash with vSpheres snapshot mechanism (which sets to label to Hard Disk N).

**Comment by rdrgporto** [comment]
Hi,

Any updates on this bug? The only way to fix it is by changing the label value to `Hard Disk N`. For example:

````
disk {
  label            = "Hard disk 1"
  size             = 20
  eagerly_scrub    = false
  thin_provisioned = true
  unit_number      = 0
}
````

Regards

**Comment by burnsjared0415** [comment]
starting to look at this

**Comment by rdrgporto** [comment]
Hi, @burnsjared0415 

I am facing a problem when importing the Terraform state from vSphere, as the disk label indicates that it has changed.

````
~ disk {
  ~ label             = "Hard disk 1" -> "<deleted>"
   # (20 unchanged attributes hidden)
}
````

The virtual machine was deployed with the following disk configuration:

````
disk {
  label            = "disk0"
  size             = "40"
  eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
  thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
}
````

I conducted another test, deploying a machine with the following disk configuration:

````
disk {
  label            = "Hard disk 1"
  size             = "40"
  eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
  thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
}
````

I deleted its state and imported it again (using the `terraform import` command). After running a `terraform plan`, the error no longer appears. Does vSphere needs `Hard Disk 1` label?

It seems that something has changed, either in vSphere, Terraform, or the provider. This was not happening a few months ago.

Lastly, there is a related issue on this problem (https://github.com/hashicorp/terraform-provider-vsphere/issues/1944).

**Comment by burnsjared0415** [comment]
What i am notices now, is that on import, if you lets say deployed the vm with a configuration like this:
```
  disk {
    label       = "OS-disk"
    size        = 60
    unit_number = 0
  }
    disk {
    label       = "APP-disk"
    size        = 5
    unit_number = 1
  }
    disk {
    label       = "test-disk"
    size        = 5
    unit_number = 2
  }
  ```
  and then you import and then try to plan on that import it will delete the disk, if you change your tf config before import and to have 
  ```
  disk {
    label       = "Hard disk 1"
    size        = 60
    unit_number = 0
  }
    disk {
    label       = "Hard disk 2"
    size        = 5
    unit_number = 1
  }
    disk {
    label       = "Hard disk 3"
    size        = 5
    unit_number = 2
  }
  So when import runs it will change the disk labels what they where deployed with to what it is expecting which is Hard disk x, i will see if i can figure out why it will not import differently but it looks like the default behavior might have changed if this was working a couple months ago, i will look at the related issue to see how they related.

**Comment by rdrgporto** [comment]
Hi @burnsjared0415,

Exactly, when running `terraform plan`, it indicates that the disk will be deleted. This behavior is a bit strange, as a few months ago I imported the state of a virtual machine without any issues.

From the beginning, I've always used with `disk.label = "disk0"` as per [recommendations](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#additional-importing-requirements). It seems that the recommendation should be changed to using "`Hard Disk 1`" from now on.

Thank you very much for your help!

Regards

**Comment by burnsjared0415** [comment]
so what is interesting is when the import goes out it is not getting a label, i need to figure out where the label is being storage

```
2024-10-02T08:43:53.819-0400 [INFO]  provider.terraform-provider-vsphere: 2024/10/02 08:43:53 [INFO] device description: &{{} Hard disk 1 62,914,560 KB}: timestamp=2024-10-02T08:43:53.819-0400
2024-10-02T08:43:53.819-0400 [INFO]  provider.terraform-provider-vsphere: 2024/10/02 08:43:53 [INFO] device label: Hard disk 1: timestamp=2024-10-02T08:43:53.819-0400
2024-10-02T08:43:53.819-0400 [INFO]  provider.terraform-provider-vsphere: 2024/10/02 08:43:53 [INFO] device description: &{{} Hard disk 2 5,242,880 KB}: timestamp=2024-10-02T08:43:53.819-0400
2024-10-02T08:43:53.819-0400 [INFO]  provider.terraform-provider-vsphere: 2024/10/02 08:43:53 [INFO] device label: Hard disk 2: timestamp=2024-10-02T08:43:53.819-0400
2024-10-02T08:43:53.819-0400 [INFO]  provider.terraform-provider-vsphere: 2024/10/02 08:43:53 [INFO] device description: &{{} Hard disk 3 5,242,880 KB}: timestamp=2024-10-02T08:43:53.819-0400
2024-10-02T08:43:53.819-0400 [INFO]  provider.terraform-provider-vsphere: 2024/10/02 08:43:53 [INFO] device label: Hard disk 3: timestamp=2024-10-02T08:43:53.819-0400
```

**Comment by burnsjared0415** [comment]
i will update the documentation to reflect this change, not sure if it is a bug at this point, looks like just a change in the provider, if documentation change will work, i will make the updates and close out this Issue, please let me know if that will work.

**Comment by mvandriessen** [comment]
An update in the docs would work for us. Changing the behavior again would make it so that a lot of people would potentially have to refactor their code and update their environment again.

Thanks for the investigation!

**Comment by rdrgporto** [comment]
Hi @burnsjared0415 

I noticed that a pull request has been created ([#2772](https://github.com/hashicorp/terraform-provider-vsphere/pull/2272)).

Quick question: Do we know where the issue originates from? Is it on the vSphere side, the provider, or perhaps the version of Terraform?

Regards

**Comment by burnsjared0415** [comment]
i will do some more digging to see if it is terraform or vSphere that makes this change

**Comment by rdrgporto** [comment]
Hi @burnsjared0415,

Thank you very much for your help.

Regards

**Comment by burnsjared0415** [comment]
it looks like it is vSphere that makes the change

**Comment by rdrgporto** [comment]
Hi @burnsjared0415,

Thank you for the information. So, can we start fix our deployments and applying `Hard Disk 1` label?

Regards
