### ISSUE TITLE
Add support for [or cluster for 3 zone Deployments

### ISSUE THREAD

**Issue by haferch** [hashicorp/terraform-provider-vsphere#2204]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Could you add the following vCenter REST Call: 
https://{api_host}/api/vcenter/namespace-management/supervisors__action=enable_on_zones
to the vSphere Provider

See here for details: https://developer.broadcom.com/xapis/vsphere-automation-api/latest/vcenter/api/vcenter/namespace-management/supervisors__action=enable_on_zones/post/

### Use Case(s)

We want to deploy a 3 Zone Supervisor Cluster (WPC)

**Comment by tenthirtyam** [comment]
Closing in favor of #2185.
