### ISSUE TITLE
custom_attributes are not applying to vsphere_vapp_container resource

### ISSUE THREAD

**Issue by hae-andrew-young** [hashicorp/terraform-provider-vsphere#2225]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.8.1

### Terraform Provider

2.7.0

### VMware vSphere

don't know

### Description

I'm trying to add custom attributes to a resource like vApp but the value is not being added.

### Affected Resources or Data Sources

resource/vsphere_vapp_container

### Terraform Configuration

```
data "vsphere_custom_attribute" "build_attr" {
  name = "build"
}

resource "vsphere_vapp_container" "vapp_container" {
  name                    = local.vapp_name
  parent_resource_pool_id = var.resource_pool_cluster.resource_pool_id
  parent_folder_id        = var.folder.id
  custom_attributes = tomap({
    "${data.vsphere_custom_attribute.build_attr.id}" = "this no worky"
  })
}
```

### Debug Output

No error occurs. The provider executes as if nothing is wrong.

### Expected Behavior

The value of the custom attribute applied to the vApp resource.

### Actual Behavior

Custom attribute's value remains empty in the vSphere console

### Steps to Reproduce

Manually create a custom_attribute called `build` in the vSphere console.

`terraform apply`

### Screenshots

![Screenshot 2024-06-20 at 4 59 16 PM](https://github.com/hashicorp/terraform-provider-vsphere/assets/146012589/2e8591d5-7753-4ae6-b82d-0dfdfe183624)

**Comment by tenthirtyam** [comment]
Try

```hcl

data "vsphere_custom_attribute" "build_attr" {
  name = "build"
}

resource "vsphere_vapp_container" "vapp_container" {
  name                    = local.vapp_name
  parent_resource_pool_id = var.resource_pool_cluster.resource_pool_id
  parent_folder_id        = var.folder.id
  custom_attributes = tomap({
    data.vsphere_custom_attribute.build_attr.id = "this"
  })
}

```

**Comment by hae-andrew-young** [comment]
@tenthirtyam, What you suggested isn't valid TF syntax.

To be clear, with my original example, `terraform apply` does not error out. Everything else applies just fine. The custom attribute is even recorded into the state the the vApp. i.e. if I do a `terraform state show 'vsphere_vapp_container.vapp_container'`, the custom attribute will show up there with the correct value. Its just that it does not appear to be actually manifesting in vSphere.

**Comment by hae-andrew-young** [comment]
FYI. I just modified the description and title of the issue. It only appears to be happening with the `vsphere_vapp_container` resource.

**Comment by tenthirtyam** [comment]
Sorry, just noticed that this is specially for [`r/vapp_container`](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/vapp_container), which is not provided in the resource.

Please open a separate enhancement request to track this as an enhancement item and not a bug.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom
