### ISSUE TITLE
add a disk on a exists vm will recreate this VM

### ISSUE THREAD

**Issue by johng521888** [hashicorp/terraform-provider-vsphere#2233]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.7.1

### Terraform Provider

2.6.1

### VMware vSphere

7.0.3

### Description

I modified main.tf and tried to add a disk to an existing VM. Terraform apply will recreate my VM, which will cause data loss. Is there any way to avoid the re-creation?

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

1、create vsphere vm from template with only one disk first
2、add another disk to the vsphere_virtual_machine resource

### Debug Output

vsphere_virtual_machine.vm：Destroying... [id=422de896-1dbe-6669-d019-fa8e69afd15f]

### Expected Behavior

when I add a new disk to an existing VM, I want to avoid recreating the VM after executing terraform apply.

### Actual Behavior

add new disk will recreate VM

### Steps to Reproduce

1、use terraform create an VM with only one disk instance
2、use terraform create an disk
3、Modify the main.tf file of the virtual machine and bind the disk created in the second step to the virtual machine
4、apply this VM will destroy and recreate this VM

### References

https://github.com/hashicorp/terraform-provider-vsphere/issues/434

**Comment by spacegospod** [comment]
Hey @johng521888 I tried this myself, I added both a simple `disk` block and one with a path to an existing vmdk.
Neither of these destroy the VM, they just reconfigure it.
I ran this experiment on a basic VM and on one that I created from a template.

Can you try updating your provider to the latest version?
If you continue to encounter this problem please share your configuration and the output from `terraform plan` so that we can see the diff

**Comment by johng521888** [comment]
> Hey @johng521888 I tried this myself, I added both a simple `disk` block and one with a path to an existing vmdk. Neither of these destroy the VM, they just reconfigure it. I ran this experiment on a basic VM and on one that I created from a template.
> 
> Can you try updating your provider to the latest version? If you continue to encounter this problem please share your configuration and the output from `terraform plan` so that we can see the diff

Hi spacegospod,
i have tried today. but have same issue in version 2.8.2 vsphere provider. i have two modules as below
1、vshereVM（to create a machine）
resource "vsphere_virtual_machine" "vm" {
    name=var.hostname
    num_cpus = var.vcpu
    memory = var.memory
    datastore_id = xxx
    resource_pool_id = xxx
    guest_id = xxx
    scsi_type = xxx

    disk {
        lable = "disk0"
        size = var.disk_size
        eagerly_scrub = xxx
        thin_provisioned = xxx
    }
    #disk {
        #attach = true
        #path = "xxxx/thisistestdisk.vmdk"
        #label = "disk1"
        #datastore_id = xxx
        #unit_number = 1
        #io_limit = 3000 
   #}
   ......
   ......
}
first time i create this machine with one disk use terraform apply

2、create another disk use below tf
resource "vsphere_virtual_disk" "virtual_disk" {
    size = 100
    vmdk_path = first_create_machine_UUID/thisistestdisk.vmdk
    datacenter = same_machine_datacenter
    datasotore = same_machine_datastore
}

3、Uncomment virtual machine second disk in main.tf  and execute terraform apply in virtual machine module

resource "vsphere_virtual_machine" "vm" {
    name=var.hostname
    num_cpus = var.vcpu
    memory = var.memory
    datastore_id = xxx
    resource_pool_id = xxx
    guest_id = xxx
    scsi_type = xxx

    disk {
        lable = "disk0"
        size = var.disk_size
        eagerly_scrub = xxx
        thin_provisioned = xxx
    }
    disk {
        attach = true
        path = first_create_machine_UUID/thisistestdisk.vmdk
        label = "disk1"
        datastore_id = xxx
        unit_number = 1
        io_limit = 3000 
   }
   ......
   ......
}

plan：1 to add, 0 to change, 1 to destroy.

I don't know why this happens, can I avoid destroying my virtual machine? Because not everyone knows at the beginning whether they want to add a second disk

**Comment by spacegospod** [comment]
Adding a disk shouldn't just by itself be able to force a VM to get re-created.
Have any changes been made to this VM outside of Terraform?

I'd be curious to see the output just above `1 to add, 0 to change, 1 to destroy.`
Terraform should display the configuration diff.
It would also be useful to run the provider with `TF_LOG` set to `TRACE` and share the detailed logs, just make sure to obfuscate any potentially sensitive data.

**Comment by johng521888** [comment]
Thank you @spacegospod.
i have solved this problem. the reason is that the instance lifycycle has not been completed. so each apply operation will also recreate the vm.

My VM network name contains special symbols, and terraform cannot recognize this symbol "/", which causes the life cycle of the created VM to fail to complete normally.

**Comment by spacegospod** [comment]
Thank you for the update, I'm going to close the ticket now.
Feel free to re-open if you need assistance
