### ISSUE TITLE
Error: Error while installing hashicorp/vsphere v2.9.0: checksum list has no SHA-256 hash(...)

### ISSUE THREAD

**Issue by batchenr** [hashicorp/terraform-provider-vsphere#2258]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.5.7

### Terraform Provider

2.9.0

### VMware vSphere

vSphere Client version 7.0.3.00000

### Description

Hello, i am unable to install the vsphere source i have tried all releases but i get the same error.
main.tf:
```
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "2.9.0"
    }
  }
}

provider "vsphere" {}

resource "vsphere_virtual_machine" "vm" {
  name             = "foo"
}
```

when i run terraform init: 
```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/vsphere versions matching "2.9.0"...
- Installing hashicorp/vsphere v2.9.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/vsphere v2.9.0: checksum list has no SHA-256 hash for
│ "terraform-provider-vsphere_2.9.0_darwin_arm64.zip"
```
I have tried also to run 
`terraform providers lock` but it doesnt work also.

```
│ Error: Could not retrieve providers for locking
│ 
│ Terraform failed to fetch the requested providers for darwin_arm64 in order to calculate their checksums:
│ some providers could not be installed:
│ - registry.terraform.io/hashicorp/vsphere: checksum list has no SHA-256 hash for
│ "terraform-provider-vsphere_2.9.0_darwin_arm64.zip".
```

I have tried a different provider which worked fine so im gussing the issue is with vsphere and mac m1 ?
thanks!

### Affected Resources or Data Sources

vsphere

### Terraform Configuration

brew install terraform

### Debug Output

added in description

### Expected Behavior

to install the resource via terraform init

### Actual Behavior

│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/vsphere v2.9.0: checksum list has no SHA-256 hash for
│ "terraform-provider-vsphere_2.9.0_darwin_arm64.zip"

### Steps to Reproduce

terraform init

### Environment Details

mac Apple M1 Max

**Comment by tenthirtyam** [comment]
Seems rather odd. The checksum is included in the [terraform-provider-vsphere_2.9.0_SHA256SUMS](https://releases.hashicorp.com/terraform-provider-vsphere/2.9.0/terraform-provider-vsphere_2.9.0_SHA256SUMS) file from `releases.hashicorp.com`.

```text
38ccf8110bf0a5f13e7b4bf922c0cdae4391436c8815a9f2e2303e93f3cee898  terraform-provider-vsphere_2.9.0_darwin_amd64.zip
b25a77a04328163a330ba77260fe6dd9958e430e83a62a65844338e32d24ec83  terraform-provider-vsphere_2.9.0_darwin_arm64.zip
a00ea30204d23b61395f9742ed025114b7cf38da2c501fca8c21fd8d65db287f  terraform-provider-vsphere_2.9.0_freebsd_386.zip
18c1377f0ae294afe2ef537f9d2ea908d254ceccb57b9b59ea534bbb0faaacdf  terraform-provider-vsphere_2.9.0_freebsd_amd64.zip
9406a0e8c186060a835d4ae3dead270c1f0bf240c059446d1e3b3780d0e4e2cd  terraform-provider-vsphere_2.9.0_freebsd_arm.zip
a3f8616337ffcf9d33afe34f1196265a4707b4d9cc138649b3524c4b3d931cad  terraform-provider-vsphere_2.9.0_linux_386.zip
b32ba97602e1ac5c009cd581e9c0dae101522f705181a71439415f76256a1d57  terraform-provider-vsphere_2.9.0_linux_amd64.zip
4940f6bda21930c9023b9102115c31e6314fe79c7e5a049e7904d51012bc4f95  terraform-provider-vsphere_2.9.0_linux_arm.zip
83ebb7543b6a66d7020ee205debcee3f393caf67fe22d3de0e262449be5fe6b1  terraform-provider-vsphere_2.9.0_linux_arm64.zip
0fa82a384b25a58b65523e0ea4768fa1212b1f5cfc0c9379d31162454fedcc9d  terraform-provider-vsphere_2.9.0_manifest.json
888398456c7cf1a98112bc09f7ab1ad785e250605ec4b8d9774278f85bf1d79f  terraform-provider-vsphere_2.9.0_windows_386.zip
c7b0007d2fdd50f88d1fc2c378f3e1b8618b2acaad7760dc090593bc90734bde  terraform-provider-vsphere_2.9.0_windows_amd64.zip
```

**Comment by batchenr** [comment]
Hey problem solved by opening this links:
releases.hashicorp.com

We have opened only registry.terraform.io so maybe that was the issue,
thanks anyways for the response!
