### ISSUE TITLE
VM is recreated after changing non-destructive resources

### ISSUE THREAD

**Issue by svg-mn** [hashicorp/terraform-provider-vsphere#2267]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.9.6

### Terraform Provider

2.9.2

### VMware vSphere

8.0.2

### Description

When using the vSphere Terraform provider, certain resource changes that should not require the destruction and recreation of the virtual machine (such as changing the VM name or adjusting CPU count) are causing the provider to unnecessarily destroy and recreate the VM. This behavior leads to service disruption and increased downtime, which is not expected for these types of changes.

### Affected Resources or Data Sources

resource/vm

### Terraform Configuration

resource "vsphere_virtual_machine" "example" {
  name             = "example-vm"
  num_cpus         = 2
  memory           = 4096
  resource_pool_id = "resgroup-123"
  datastore_id     = "datastore-123"

  network_interface {
    network_id   = "network-123"
    adapter_type = "vmxnet3"
  }

  disk {
    label            = "disk0"
    size             = 50
  }
}

### Debug Output

I can't link the debug GitHub log since it's not connected to the internet

### Expected Behavior

Changes to non-destructive fields (like the VM name, CPU count) should be applied in place without triggering a VM destruction and recreation.

### Actual Behavior

When modifying resources like the VM name or CPU count Terraform plans to destroy the existing VM and recreate a new one. These changes should instead be updated without needing to delete and recreate the virtual machine.

### Steps to Reproduce

1. Deploy a VM using the vsphere_virtual_machine resource.

2. Change the name, CPU, or memory allocation in the Terraform configuration.

3. Run terraform plan and observe that it plans to destroy and recreate the VM instead of updating the resources in place.

**Comment by burnsjared0415** [comment]
i am not able to re-produce this, i have tested each setting one by one and get change for each, please provide info of output.
```
  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
      - enable_disk_uuid                        = true -> null
        id                                      = "4228e427-62e8-ccc2-3fb6-015d66766146"
      ~ memory                                  = 2048 -> 4098
        name                                    = "foo-win-1"
        tags                                    = []
        # (67 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
```
      - enable_disk_uuid                        = true -> null
        id                                      = "4228e427-62e8-ccc2-3fb6-015d66766146"
        name                                    = "foo-win-1"
      ~ num_cpus                                = 2 -> 4
        tags                                    = []
        # (67 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
```
  ~ resource "vsphere_virtual_machine" "vm" {
      - enable_disk_uuid                        = true -> null
        id                                      = "4228e427-62e8-ccc2-3fb6-015d66766146"
      ~ name                                    = "foo-win-1" -> "foo-win-2"
        tags                                    = []
        # (68 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by tenthirtyam** [comment]
Marking as closed. Please open a new issue and reference #2267 is the problem persists.
