### ISSUE TITLE
vsphere_virtual_machine disk: duplicate unit_number 0 during template cloning

### ISSUE THREAD

**Issue by lbrigman124** [hashicorp/terraform-provider-vsphere#529]
Terraform v0.11.7
+ provider.vsphere v1.5.0

Arch linux_amd64

During plan execution:.....

data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_compute_cluster.cluster: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:
* vsphere_virtual_machine.gsm1: 3 error(s) occurred:

* vsphere_virtual_machine.gsm1[2]: disk: duplicate unit_number 0
* vsphere_virtual_machine.gsm1[0]: disk: duplicate unit_number 0
* vsphere_virtual_machine.gsm1[1]: disk: duplicate unit_number 0

### Affected Resource(s)
- `vsphere_virtual_machine disk`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
# Configure the VMware vSphere Provider
provider "vsphere" {
  vsphere_server       = "${var.vsphere_vcenter}"
  user                 = "${var.vsphere_user}"
  password             = "${var.vsphere_password}"
  allow_unverified_ssl = true
}

# this is for the newer provider
data "vsphere_datacenter" "dc" {}

data "vsphere_datastore" "datastore" {
  name          = "${var.datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "${var.vsphere_cluster}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.netname}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "Centos7-base-rev1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_folder" "openshift-cluster" {
  path          = "${var.dir_name}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
  type          = "vm"

  #  datacenter = "${var.vsphere_datacenter}"
}

# Build CentOS - vsphere provider cannot import
resource "vsphere_virtual_machine" "gsm1" {
  # this is the vsphere name
  count = "${var.instance_count}"
  name  = "${var.host}-${count.index + 1}.${var.domain}"

  num_cpus = 4

  memory = 16384

  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"

  guest_id         = "centos64Guest"
  folder           = "${vsphere_folder.openshift-cluster.path}"
  enable_disk_uuid = true

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  # Define the Disks and resources. The first disk should include the template.
  disk {
    label = "disk0"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
  }

  # second disk - docker base container storage
  disk {
    size  = 30
    label = "docker"
  }

  # third disk - registry
  disk {
    size  = 20
    label = "registry"
  }

  # 4th disk - etcd
  disk {
    size  = 10
    label = "etcd"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.host}-${count.index + 1}"
        domain    = "${var.domain}"

        # Define Time Zone
        time_zone = "America/Los_Angeles"
      }
    }
  }

}

```
### Expected Behavior

What should have happened?
Plan should complete or identify the error with correction information

### Actual Behavior

What actually happened?
Received an error message without any details on how to correct:
* vsphere_virtual_machine.gsm1[2]: disk: duplicate unit_number 0

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by lbrigman124** [comment]
Adding the unit_number just moves from one bug to another.
* vsphere_virtual_machine.gsm1.1: error reconfiguring virtual machine:
error processing disk changes post-clone: disk.1: error creating disk:
ServerFaultCode: The object has already been deleted or has not been
completely created

**Comment by vancluever** [comment]
@lbrigman124 can you open a new issue for this one? Please include the full logs of the Terraform run.

Thanks!
