### ISSUE TITLE
DirectPath I/O support

### ISSUE THREAD

**Issue by johnjelinek** [hashicorp/terraform-provider-vsphere#552]
### Terraform Version

`Terraform v0.11.7`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Expected Behavior

I expected to be able to configure the network adapter setting for DirectPath I/O.

### Actual Behavior

I didn't see anywhere to configure this.

### References

This is how it's configured in vCenter: ![image 2018-06-13 at 12 43 29 pm](https://user-images.githubusercontent.com/873610/41369061-6c4715a2-6f09-11e8-80c7-4d349fc840e7.png)

**Comment by redi-dangeloj** [comment]
Im seeing the same issue with Terraform v0.11.11 and vsphere v1.9.1 where DirectPath I/O VM's that were created from a template are having DirectPath I/O enabled, which doesn't seem like anything that is even tracked in the tfstate.   It's caused network forwarding issues after a vMotion on linux guests for us.

**Comment by gowthamakanthan** [comment]
Any update on this?

**Comment by christopherdraper** [comment]
If I'm not mistaken, the API has a different name for this internally on the NIC properties.

https://vmware.github.io/vsphere-automation-sdk-java/vsphere/6.5.0/vsphereautomation-client-sdk/com/vmware/vcenter/vm/hardware/EthernetTypes.CreateSpec.html#setUptCompatibilityEnabled(java.lang.Boolean)

**Comment by christopherdraper** [comment]
vendor/github.com/vmware/govmomi/vim25/types/types.go

```go
type VirtualEthernetCardOption struct {
        VirtualDeviceOption

        SupportedOUI              ChoiceOption `xml:"supportedOUI"`
        MacType                   ChoiceOption `xml:"macType"`
        WakeOnLanEnabled          BoolOption   `xml:"wakeOnLanEnabled"`
        VmDirectPathGen2Supported *bool        `xml:"vmDirectPathGen2Supported"`
        UptCompatibilityEnabled   *BoolOption  `xml:"uptCompatibilityEnabled,omitempty"`
}

```

**Comment by awslovato** [comment]
Still not seeing a way to enable/disable this on 0.12.12.  Any update on this?

Thanks.

**Comment by johnjelinek** [comment]
They call it `passthrough` in packer now. Any update on this in `terraform`?

**Comment by bill-rich** [comment]
This was added in #1099
