### ISSUE TITLE
Add support for VM Encryption 

### ISSUE THREAD

**Issue by surajsub** [hashicorp/terraform-provider-vsphere#584]
### Terraform Version
0.11.7

### vSphere Provider Version

1.5

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

More of a question
Is there any plan to support vmware encryption in the future releases.  We have a requirement to support PCI based workloads . Since vmware already offers this capability , i prefer using that rather than a custom solution. Any thoughts

**Comment by bill-rich** [comment]
Hi @surajsub! We don't currently have it on the road map, but I believe it is a feature we will likely implement in the future. I'll leave this issue open to keep track of the request and I will update here when more information is available.

**Comment by bill-rich** [comment]
This will likely be implemented along with VBS in #677

**Comment by pezhore** [comment]
Any updates on this? I'm particularly interested in getting vm encryption handled through Terraform.
