### ISSUE TITLE
error reconfiguring virtual machine: A general system error occurred: Error creating disk Function not implemented

### ISSUE THREAD

**Issue by masavanu** [hashicorp/terraform-provider-vsphere#817]
Hi,

we are trying to add disk from VSAN datastore in vcenter, but getting error like creating disk function not implemented.  
This is the main.tf file code i am using to create/attach disk in VM.

disk {
    name             = "TESTG1TierBVM21.vmdk"
    size             = "10"
    thin_provisioned = "true"
    unit_number      = 1
  }

vsphere_virtual_machine.TierB1: Creating...
  boot_retry_delay:                          "" => "10000"
  change_version:                            "" => "<computed>"
  clone.#:                                   "" => "1"
  clone.0.template_uuid:                     "" => "4229d322-08ca-1d33-0c27-c812b7d36288"
  clone.0.timeout:                           "" => "30"
  cpu_limit:                                 "" => "-1"
  cpu_share_count:                           "" => "<computed>"
  cpu_share_level:                           "" => "normal"
  datastore_id:                              "" => "datastore-1565"
  default_ip_address:                        "" => "<computed>"
  disk.#:                                    "" => "2"
  disk.0.attach:                             "" => "false"
  disk.0.device_address:                     "" => "<computed>"
  disk.0.disk_mode:                          "" => "persistent"
  disk.0.disk_sharing:                       "" => "sharingNone"
  disk.0.eagerly_scrub:                      "" => "false"
  disk.0.io_limit:                           "" => "-1"
  disk.0.io_reservation:                     "" => "0"
  disk.0.io_share_count:                     "" => "0"
  disk.0.io_share_level:                     "" => "normal"
  disk.0.keep_on_remove:                     "" => "false"
  disk.0.key:                                "" => "0"
  disk.0.name:                               "" => "TPCCT1G1TierBVM2.vmdk"
  disk.0.size:                               "" => "6"
  disk.0.thin_provisioned:                   "" => "true"
  disk.0.unit_number:                        "" => "0"
  disk.0.write_through:                      "" => "false"
  disk.1.attach:                             "" => "false"
  disk.1.device_address:                     "" => "<computed>"
  disk.1.disk_mode:                          "" => "persistent"
  disk.1.disk_sharing:                       "" => "sharingNone"
  disk.1.eagerly_scrub:                      "" => "false"
  disk.1.io_limit:                           "" => "-1"
  disk.1.io_reservation:                     "" => "0"
  disk.1.io_share_count:                     "" => "0"
  disk.1.io_share_level:                     "" => "normal"
  disk.1.keep_on_remove:                     "" => "false"
  disk.1.key:                                "" => "0"
  disk.1.name:                               "" => "TPCCT1G1TierBVM21.vmdk"
  disk.1.size:                               "" => "10"
  disk.1.thin_provisioned:                   "" => "true"
  disk.1.unit_number:                        "" => "1"
  disk.1.write_through:                      "" => "false"
  ept_rvi_mode:                              "" => "automatic"
  firmware:                                  "" => "bios"
  force_power_off:                           "" => "true"
  guest_id:                                  "" => "otherGuest"
  guest_ip_addresses.#:                      "" => "<computed>"
  host_system_id:                            "" => "host-31"
  hv_mode:                                   "" => "hvAuto"
  imported:                                  "" => "<computed>"
  memory:                                    "" => "4096"
  memory_limit:                              "" => "-1"
  memory_share_count:                        "" => "<computed>"
  memory_share_level:                        "" => "normal"
  migrate_wait_timeout:                      "" => "30"
  name:                                      "" => "TPCCT1G1TierBVM2"
  network_interface.#:                       "" => "1"
  network_interface.0.adapter_type:          "" => "vmxnet3"
  network_interface.0.bandwidth_limit:       "" => "-1"
  network_interface.0.bandwidth_reservation: "" => "0"
  network_interface.0.bandwidth_share_count: "" => "<computed>"
  network_interface.0.bandwidth_share_level: "" => "normal"
  network_interface.0.device_address:        "" => "<computed>"
  network_interface.0.key:                   "" => "<computed>"
  network_interface.0.mac_address:           "" => "<computed>"
  network_interface.0.network_id:            "" => "network-53"
  num_cores_per_socket:                      "" => "1"
  num_cpus:                                  "" => "2"
  reboot_required:                           "" => "<computed>"
  resource_pool_id:                          "" => "resgroup-27"
  run_tools_scripts_after_power_on:          "" => "true"
  run_tools_scripts_after_resume:            "" => "true"
  run_tools_scripts_before_guest_shutdown:   "" => "true"
  run_tools_scripts_before_guest_standby:    "" => "true"
  scsi_controller_count:                     "" => "1"
  scsi_type:                                 "" => "pvscsi"
  shutdown_wait_timeout:                     "" => "3"
  swap_placement_policy:                     "" => "inherit"
  uuid:                                      "" => "<computed>"
  vmware_tools_status:                       "" => "<computed>"
  vmx_path:                                  "" => "<computed>"
  wait_for_guest_net_timeout:                "" => "5"
vsphere_virtual_machine.TierB1: Still creating... (10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.TierB1: 1 error(s) occurred:

* vsphere_virtual_machine.TierB1: error reconfiguring virtual machine: A general system error occurred: Error creating disk Function not implemented

Please Help.

**Comment by SamyCoenen** [comment]
I received the same error message and the reason was a datastore using VMware vSAN.
The solution was using another datastore without vSAN.

**Comment by stgrace** [comment]
You can create a disk on vSAN but not at the top level. It needs to be created in a folder.
See this issue: https://github.com/vmware/govmomi/issues/654
