### ISSUE TITLE
The object 'vim.ResourcePool' has already been deleted or has not been completely created

### ISSUE THREAD

**Issue by thiagolmo** [hashicorp/terraform-provider-vsphere#923]
### Terraform Version

Terraform v0.11

### vSphere Provider Version

provider.vsphere ~> 1.9.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```
resource "vsphere_virtual_machine" "virtual_machine" {
  name             = "${var.hostname["${var.environment}"]}${random_string.random.result}v-${var.environment}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  wait_for_guest_net_timeout = 0

  num_cpus  = "${var.cpu[var.value]}"
  memory    = "${var.memory[var.value]}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label             = "terraform_clone_0.vmdk"
    size              = "${var.disk[var.value]}"
    eagerly_scrub     = true
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }
}
```

### Debug Output

vsphere_virtual_machine. virtual_machine: 1 error(s) ocorred: *vsphere_virtual_machine. virtual_machine: could not find resource pool ID "xxx": ServerFaultCode: The object 'vim.ResourcePool:xxx' has already been deleted or has not been completely created

### Expected Behavior

That the template clone was successfully performed

### Actual Behavior

vsphere_virtual_machine. virtual_machine: 1 error(s) ocorred: *vsphere_virtual_machine. virtual_machine: could not find resource pool ID "xxx": ServerFaultCode: The object 'vim.ResourcePool:xxx' has already been deleted or has not been completely created

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I have already tried to provide the pool name as well as the pool id.

**Comment by bill-rich** [comment]
Hi @thiagolmo! Can you provide some additional information about the resource pool being used? Is it a standard resource pool, and is it nested in any other objects? 

Also, if possible, please provide the full debug output log, as there could be helpful information about why the pool cannot be found.

Thanks!

**Comment by ikkaro** [comment]
Hi,

I'm using the latest version.
My resource pool name is RANCHER_K8S_POOL and is not nested. Is bellow a compute cluster.

´
data "vsphere_datacenter" "dc" {
  name = "vdc_XX"
}

data "vsphere_datastore" "datastore" {
  name          = "DS01"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "vcl_ZZ"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "dpg-002"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "RANCHER_K8S_POOL"
  # also tried "vcl_XX/Resources/RANCHER_K8S_POOL"
 # also tried  "/vdc_XX/host/vcl_ZZ/Resources/RANCHER_K8S_POOL"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
 resource_pool_id = "data.vsphere_resource_pool.pool.id"
  datastore_id     = "data.vsphere_datastore.datastore.id"

  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "data.vsphere_network.network.id"
  }

  disk {
    label = "disk0"
    size  = 20
  }

}
´

**Comment by canit00** [comment]
Also having this same issue on Terraform version `0.12.20` Go runtime version: `go1.12.13` plugin: `vsphere, 1.16.1`

main.tf
```
provider "vsphere" {
  user = var.vsphere_user
  password = var.vsphere_password
  vsphere_server = var.vsphere_server

  # Allow to connect to self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "ocp4"
}

data "vsphere_datastore" "datastore" {
  name = "datastore_esx1"
  datacenter_id = "$${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_resource_pool" "pool" {
  name = "Compute-ResourcePool"
  datacenter_id = "$${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_network" "network" {
  name = "segment"
  datacenter_id = "$${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_virtual_machine" "template" {
  name = "RHCOST"
  datacenter_id = "$${data.vsphere_datacenter.datacenter.id}"
}

resource "vsphere_virtual_machine" "vm" {
    name             = "server.domain.us"
    folder           = "ocp4"
    resource_pool_id = "$${data.vsphere_compute_cluster.cluster.resource_pool_id}"
    datastore_id     = "$${data.vsphere_datastore.datastore.id}"
    firmware         = "bios"
    num_cpus = 4
    memory   = 16384
    guest_id = "$${data.vsphere_virtual_machine.template.guest_id}"
    network_interface {
        network_id   = "$${data.vsphere_network.network.id}"
        adapter_type = "vmxnet3"
    }
    disk {
        label            = "disk0"
        size             = 120
        eagerly_scrub    = "true"
        thin_provisioned = "true"
    }
    scsi_type = "pvscsi"
}
```

Also attaching debug log
[tdbug.log](https://github.com/terraform-providers/terraform-provider-vsphere/files/4214721/tdbug.log)

**Comment by bill-rich** [comment]
Hi All! It looks like the issues here are around HCL syntax. Please see below for an example:

```
data "vsphere_datacenter" "datacenter" {
  name = "dc-name"
}

data "vsphere_resource_pool" "pool" {
  name = "rp-name"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
...
    resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
...
}
```
