### ISSUE TITLE
vsphere_network fails when PortGroup names used on multiple DVS

### ISSUE THREAD

**Issue by tvigneron** [hashicorp/terraform-provider-vsphere#925]
Hello,

The vsphere_network network resource fails when multiple PortGroup with the same name are created in the environment with the following error:
terraform data.vsphere_network.network: error fetching network: path resolves to multiple networks
This is restrictive in an environment with multiple clusters with their own DVS but the same networks (as PortGroup is a DVS object, names can be repeated across DVS).  It blocks the usage of the Terraform Provider in those environments. 

Would it be possible to solve this by allowing the user to pick his DVS as an optional argument   of the vsphere_network resource?

Thank you

**Comment by sumitAgrawal007** [comment]
Hi @tvigneron 
Can you mention the VC version.
Also I tried to reproduce the issue, from the vsphere UI, one can't create PortGroup with the same name under different DVS switches. It will throw an error that a port group with the same name already exists unless you have put the DVS switches under different directories.

Can you tell me more about your vsphere  structure, as to how did you create the duplicate port groups.
