### ISSUE TITLE
vcsim Terraform support

### ISSUE THREAD

**Issue by Satak** [hashicorp/terraform-provider-vsphere#940]
Does Terraform vSphere provider support VMware **vcsim** simulator? I'm having hard time getting Terraform working against vcsim. Opened a issue here for VMware: https://github.com/vmware/govmomi/issues/1779

It would really speed up Terraform development if one could run templates against vcsim instead of an actual vSphere. Are there any other alternatives for rapid Terraform development for vSphere?

**Status June 2020**: Terraform can provision VMs against vcsim but only without clone block. Clone block will cause Terraform crash!
Crash log here: https://gist.github.com/Satak/ec149546617397bc41f70291d64fe030

**Comment by bill-rich** [comment]
Hi @Satak! We haven't done much in the area of testing with vcsim. Based on the error in you govmomi issue, it looks like vcsim is probably missing a few attributes required by the Terraform provider, but it is possible it is a configuration issue also. 

As you said in the other issue, I think the first step would be defining a simple working configuration to see if we could get that working, and then expand from there to see what does or does not work.

**Comment by Satak** [comment]
So I have been playing around with this vcsim and govc and managed to pinpoint the problem to this `customize {}` block. This tf config works fine against vcsim but only if you don't use customize. If you use customize block it will give you an error:
`Error: cannot find OS family for guest ID "otherGuest": could not find guest ID "otherGuest"`

## `main.tf`

```terraform
provider "vsphere" {
  user                 = "username"
  password             = "password"
  vsphere_server       = "localhost"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "DC0"
}
data "vsphere_datastore" "datastore" {
  name          = "datastore/LocalDS_0"
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_resource_pool" "pool" {
  name          = "DC0_H0/Resources"
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_network" "network" {
  name          = "network/VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_virtual_machine" "template" {
  name          = "DC0_H0_VM0"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  num_cpus         = 2
  memory           = 4096
  guest_id         = data.vsphere_virtual_machine.template.guest_id

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    label = "disk0"
    size  = 50
  }
  /*
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      network_interface {
        ipv4_address = "10.134.3.162"
        ipv4_netmask = "24"
      }
    }
  }
  */
  scsi_type                  = data.vsphere_virtual_machine.template.scsi_type
  wait_for_guest_net_timeout = "-1"
}
```

**Comment by Satak** [comment]
Terraform log here: <https://gist.github.com/Satak/1745368ebc694b4430c795293b27b472>

**Comment by virt-ninja** [comment]
Hi Satak,

Your issue is due to the simulator not actually creating a real vm - so there's no OS to customize. Though I suppose someone could create a pull request to mock the responses from vmware tools as if there were, though it would be very limited. 

The quickest route to getting your main.tf to run would be to remove the customize section within the clone block. It should then work :)

**Comment by Satak** [comment]
vcsim now works with Terraform but only without a clone block. If you add this block to the main.tf Terraform will crash:

```tf
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
```

Crash log here: https://gist.github.com/Satak/ec149546617397bc41f70291d64fe030

Maybe something to do with this:

> 2020-06-16T10:19:01.177+0300 [DEBUG] plugin.terraform-provider-vsphere_v1.18.3_x4.exe: panic: runtime error: invalid memory address or nil pointer dereference

**Comment by Satak** [comment]
See this: https://github.com/vmware/govmomi/issues/1779#issuecomment-653078095

**Comment by Satak** [comment]
This is now working since vcsim fixed this issue: https://github.com/vmware/govmomi/issues/1779

This was the root problem: https://github.com/vmware/govmomi/issues/1779#issuecomment-757514623

> **Terraform** could also use a fix to avoid that crash and a change **tolerate the product name suffix**.
