### ISSUE TITLE
Creating vapp_entity fails with: "vim.VirtualApp:vsphere_vapp_container.vapp_container.id' has already been deleted or has not been completely created"

### ISSUE THREAD

**Issue by mikaheikkinen** [hashicorp/terraform-provider-vsphere#943]
### Terraform Version
0.12.6

### vSphere Provider Version
provider.null 2.1.2
provider.vsphere 1.13.0

### Affected Resource(s)
- vsphere_vapp_entity

### Terraform Configuration Files

resource "vsphere_folder" "folder" {
  path = var.vsphere_resource_pool
  type= "vm"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"

}
resource "vsphere_vapp_container" "vapp_container" {
    name= var.vsphere_resource_pool 
    parent_resource_pool_id = "${data.vsphere_resource_pool.resource_pool.id}"
    parent_folder_id = "${vsphere_folder.folder.id}"
}
resource "vsphere_vapp_entity" "vapp_entity_gw" {
    target_id = "vsphere_virtual_machine.gw.id"
    container_id = "vsphere_vapp_container.vapp_container.id"
    start_order=2
    depends_on = [
      "vsphere_virtual_machine.gw",
      "vsphere_vapp_container.vapp_container"
    ]
}

### Debug Output
I can't provide full debug.

### Expected Behavior
vsphere_vapp_entity should be created

### Actual Behavior
vsphere_vapp_container is created and vm is added to vapp, but with vsphere_vapp_entity Terraform throws an error.

### Steps to Reproduce
1. `terraform apply`

**Comment by aareet** [comment]
Perhaps related to #941

**Comment by mikaheikkinen** [comment]
> Perhaps related to #941

Hi, 
with this change I can now create Vapp without vsphere_folder, so I think it did fix one problem. But I'm still having same problem  when trying to create vsphere_vapp_entity resource.

**Comment by koikonom** [comment]
Can you please reproduce the issue but this time set the TF_LOG environment variable to DEBUG when you run the `apply` operation (like TF_LOG=DEBUG terraform apply <planfile>) and post the debug output in a github gist?

**Comment by mikaheikkinen** [comment]
Yes I can if debug don't share too much details about our env. I try do it next week, right now i don't have access to vsphere.

**Comment by mikaheikkinen** [comment]
> Can you please reproduce the issue but this time set the TF_LOG environment variable to DEBUG when you run the `apply` operation (like TF_LOG=DEBUG terraform apply ) and post the debug output in a github gist?

https://gist.github.com/mikaheikkinen/ceef4c38ff5233fa7e846cbc5ae2272c

**Comment by bill-rich** [comment]
Hi @mikaheikkinen! The issue your running into is that your attributes are values that need to be interpolated, but they are in quotes.

For example, rather than:
```
container_id = "vsphere_vapp_container.vapp_container.id"
```
you'll need:
```
container_id = vsphere_vapp_container.vapp_container.id
```
