### ISSUE TITLE
The object 'vim.ResourcePool:bat-cave' has already been deleted or has not been completely created

### ISSUE THREAD

**Issue by jasonwilliams14** [hashicorp/terraform-provider-vsphere#949]
Hello there.
This may be similar to issue [Issue #923 ](https://github.com/terraform-providers/terraform-provider-vsphere/issues/923)

But basically, trying to build a new vm off an existing clone in vsphere.    

### Terraform Version

> Terraform v0.12.19       
> provider.vsphere v1.14.0

### vSphere Provider Version

Run `terraform providers` to show the list of providers in use and locate the     

`provider.vsphere`

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`
.

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_vcenter
  allow_unverified_ssl = var.vsphere_unverified_ssl
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_vm_template
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = var.vsphere_vm_name
  folder           = var.vsphere_vm_folder
  resource_pool_id = var.vsphere_vm_resource_pool
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = 1
  memory   = 1024
  guest_id = data.vsphere_virtual_machine.template.guest_id

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks[0].size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks[0].eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }

  connection {
    type = "ssh"
    user = "singleuser"
    password = "whatchamacallit"
}

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    
```

### Debug Output

[Debug Output](https://gist.github.com/jasonwilliams14/ed5ab16f3d7644a3e1ccbd7972ad0523)

### Expected Behavior

What should have happened?

A VM should have been created from an existing template

### Actual Behavior

`terraform apply`
Failed with resource pool ID error (in subject line)

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

This is just a test lab as I learn terraform. (2) ESXi hosts, connected via vsphere 6.5 host. Please let me know if you need more information. Happy to oblige.

### References

[Issue #923 ](https://github.com/terraform-providers/terraform-provider-vsphere/issues/923)

**Comment by koikonom** [comment]
Hello, 

Can you tell us if the value of `var.vsphere_vm_resource_pool` is `bat-cave`? If that is the case then the issue is that the `virtual_machine` resource needs the ID of a resource pool, and not it's name.

In your case for example you could use `data.vsphere_compute_cluster.cluster.resource_pool_id` as a value for the resource's `resource_pool_id` attribute.

**Comment by jasonwilliams14** [comment]
@koikonom Thanks for the reply. Here is the contents of my additional files. hopefully this will shed some light. i did see that error, made sure it did exist in my files as well as vcenter:


```
variable "vsphere_user" {
  description = "vSphere username"
}

variable "vsphere_password" {
  description = "vSphere password"
}

variable "vsphere_vcenter" {
  description = "vCenter server FQDN or IP"
}

variable "vsphere_unverified_ssl" {
  description = "get through signed ssl cert"
}

variable "vsphere_datacenter" {
  description = "which datacenter"
}

variable "vsphere_vm_name" {
  description = "name of the VM"
}

variable "vsphere_vm_template" {
  description = "VM template located"
}

variable "vsphere_vm_folder" {
  description = "folder VM will be store"
}

variable "vsphere_vm_resource_pool" {
  description = "bat-cave"
}

variable "vsphere_cluster" {
  description = "In which cluster the VM will be deployed"
}


variable "vsphere_datastore" {
  description = " name of the VM datastore"
}

variable "vsphere_network" {
  description = "port group the VM NIC will be configured"
}
```
and my terraform.tfvars file:    

```
vsphere_vm_resource_pool = "Bat-cave"
vsphere_network = "vDEV-PG"
vsphere_vm_name = "terraform-var-test"
vsphere_vm_template = "_Templates/p-ubuntu1804_temp"
```

I did not put everything in there, but i can add more if it helps narrow down/find the issue.
Much appreciated.

**Comment by ikkaro** [comment]
This setup is also failing:


`
data "vsphere_datacenter" "dc" {
  name = "vdc_XXX"
}

data "vsphere_datastore" "datastore" {
  name          = "ds_YYY"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "vcl_ZZZ"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "dpg-002"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "vcl_CLARA_002_IFR/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "data.vsphere_compute_cluster.resource_pool_id"
  datastore_id     = "data.vsphere_datastore.datastore.id"

  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "data.vsphere_network.network.id"
  }

  disk {
    label = "disk0"
    size  = 20
  }

}`

**Comment by bill-rich** [comment]
The issue your running into @jasonwilliams14  is that you must look up the resource pool by name using the resource pool data source first, and then use ID in the virtual machine.

@ikkaro, you'll need to remove the quotes around `resource_pool_id` and `datastore_id`, otherwise the literal string value will be used.
