### ISSUE TITLE
 error fetching resource pool for host in cluster:  resource pool not found

### ISSUE THREAD

**Issue by bish0polis** [hashicorp/terraform-provider-vsphere#962]
### Terraform Version

Terraform v0.12.20

### vSphere Provider Version

+ provider.vsphere v1.15.0

### Affected Resource(s)

Please list the resources as a list, for example:
- "vsphere_resource_pool"

### Terraform Configuration Files

All other resources refresh SO happily.  This is the current state of the config file, showing all the permutations I've tried.  No luck.

```hcl
data "vsphere_resource_pool" "Cluster1" {
  provider = vsphere.dc
#  name = "Cluster1/Resources"
#   name          = "host.fq.dn"
#   name          = "host"
#  name = "Cluster1/host.fq.dn"
#  name = "Cluster1/host.fq.dn/Resources"
#  name = "host.fq.dn/Resources"
#  name = "host/Resources"
#  name = "Cluster1/host/Resources"
#  name = "Cluster1/host"

#  name = "Cluster1/host.fq.dn"
#  name = "Cluster1/host.fq.dn/Resources"
#  name = "Cluster1/host/Resources"
#  name = "Cluster1/host"
#  name = "/host.fq.dn"
#  name = "/host.fq.dn/Resources"
#  name = "/host.fq.dn"
#  name = "root/host.fq.dn"
#  name = "root/host.fq.dn/Resources"

#  name = "dc1/Cluster1/host.fq.dn"
#  name = "dc1/Cluster1/host.fq.dn/Resources"

#  name = "dc1/Cluster1/host/Resources"
#  name = "dc1/Cluster1/host"

#  name = "dc1/Cluster1/host.fq.dn"
#  name = "dc1/Cluster1/host.fq.dn/Resources"

#  name = "dc1/Cluster1/host/Resources"
#  name = "Cluster1/host"

#  name = "Cluster1/Resources/host.fq.dn"
  name = "Cluster1/Resources/host"

  datacenter_id = data.vsphere_datacenter.dc.id
}
```

### Debug Output

https://gist.github.com/bish0polis/cde7fdfbc215cb3eae1a7bcba13612e5

### Expected Behavior

data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_host.host: Refreshing state...
data.vsphere_resource_pool.Cluster1: Refreshing state...
data.vsphere_datastore.iscsi12: Refreshing state...
data.vsphere_network.dmz2: Refreshing state...
data.vsphere_virtual_machine.othervm: Refreshing state...
data.vsphere_network.internal: Refreshing state...

### Actual Behavior

Error: error fetching resource pool: resource pool 'Cluster/Resources/host' not found

  on rp-Cluster.tf line 9, in data "vsphere_resource_pool" "Cluster1":
   9: data "vsphere_resource_pool" "Cluster1" {

### Steps to Reproduce

1. `terraform refresh`

### Important Factoids

 - I have no resources defined; just whatever pseudo-settings are available
 - the cluster is a minimal two-host essentials-plus managed cluster

**Comment by aareet** [comment]
Recent resource pool issues #923 #949

**Comment by koikonom** [comment]
Hi @bish0polis, in order to retrieve the resource pool of a cluster you can use the `resource_pool_id` attribute of the compute cluster data source. 

```
data "vsphere_compute_cluster" "cluster" {
  name          = "hashi-cluster1"
  datacenter_id = data.vsphere_datacenter.dc.id
}
```

and then in the virtual machine resource (or any other resource you need the ID of a resource pool):

```
resource "vsphere_virtual_machine" "v" {
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  [.... other attributes ....]
}
```

**Comment by bish0polis** [comment]
That's what I eventually went with, but I notice that targeting a resource which is a cluster used to be the same construct as targeting a standalone, managed host;  or, the same as targeting a specific host within a cluster.  No longer?  

It seems if we can eventually get to where we can use interpolation in resource names, that needing to specify the type of resource (cluster node, cluster, or standalone, managed node) using one of 2-3 resource code types would limit the versatility.

Is there truly no way of targeting a cluster's Resources using the older syntax?

I'm sorry I left this for so long without updating.  It doesn't feel like it was only three weeks, but  I was beating my head against interpolation issues already, and that took up SO much time.

(I don't blame the add-on for any of that;  and I hope mushycore forgot to remove the older code as they hot-glued the new stuff on !)

**Comment by bill-rich** [comment]
Hi @bish0polis! Unfortunately, the provider doesn't support using the path for most attributes now. Sorry for the inconvenience.
