### ISSUE TITLE
Error applying plan: "ServerFaultCode: SecurityError"?

### ISSUE THREAD

**Issue by mattthehearn** [hashicorp/terraform-provider-vsphere#971]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.0 (Jenkins Plugin)

### vSphere Provider Version
1.16.1

This seemed to work fine with 1.14.  The Jenkins plugin seems to download the latest version by default, and I haven't yet figured out how to force it to use a specific version, so I don't know if the issue was introduce in 1.15, 1.16, etc.

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files
terraform.tfstate:
https://gist.github.com/mattthehearn/221ef2ea91b36c1de693d0a3d358ff04
vars.tf:
https://gist.github.com/mattthehearn/7b1d163267159cc550df2af5d10947f5
main.tf:
https://gist.github.com/mattthehearn/bafe8ac6bda01767c830982eba7af048

I've obscured some identifying data, but none of these files have changed since the last time we had good builds with 1.14.

### Debug Output
https://gist.github.com/mattthehearn/52939c504d8ad029de06299158af0003

### Expected Behavior

It should have built the VM and powered it on.

### Actual Behavior

It seems to build the VM, but then attempts to do some kind of operation on the boot disk and throws this:

```
Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.terraform_vm: 1 error(s) occurred:

* vsphere_virtual_machine.terraform_vm: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: SecurityError: RESOURCE (vm-740985:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-740985), ACTION (PolicyIDByVirtualDisk)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

The changelog for v1.16 mentions this:
"Add storage policy to virtual_machine resource. ** Requires profile-driven storage permissions for Terraform user."

Did this put some additional security around disk operations that we need to configure within vCenter?  I temporarily tried putting our terraform user in the Administrator role, so in theory it should be allowed to do whatever it wants, but got the same error.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform validate` - successful
2. `terraform plan` - successful
3. `terraform apply` - throws the error

### References
Looks like this *may* be related to https://github.com/terraform-providers/terraform-provider-vsphere/issues/966, though they're throwing a different error.

**Comment by mattthehearn** [comment]
Update; tried using a later Terraform Jenkins Plugin version (0.12.17) and it threw the same error, along with this:

```
  on main.tf line 42, in resource "vsphere_virtual_machine" "terraform_vm":
  42: resource "vsphere_virtual_machine" "terraform_vm" {
```

That section in full:
https://gist.github.com/mattthehearn/3bc1c5eee08056912a61f74e6a9b135d

Relevant disk section:
  # Disk config
  disk {
    label = "${trimspace(var.vsphere_vm_name[count.index])}.vmdk"
    size = "40"
  }

Looks like maybe it's trying to shrink down a thin-provisioned disk, and it's not allowed to?

**Comment by mattthehearn** [comment]
Further update: figured out how to use provider 1.14 and that worked fine.

**Comment by clayvan** [comment]
Agreed, seeing the same thing.

**Comment by bill-rich** [comment]
Hi All! In order to use v1.16+, you'll need to enable the permissions described in #974.
