### ISSUE TITLE
Inconsistency in terraform stages between two versions (terraform-provider-vsphere_1.15 and terraform-provider-vsphere_1.16)

### ISSUE THREAD

**Issue by Nitheesh89** [hashicorp/terraform-provider-vsphere#972]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.13

### vSphere Provider Version
terraform-provider-vsphere_1.16 - This is the version provided as part of terraform 11.13 where I faced issue.
While it seemed to work fine when i specify version as 1.15 in main.tf file.

**AffectedResource(s)**
vsphere_virtual_machine

### Terraform Configuration Files

main.tf:
[https://github.com/Nitheesh-cmd/Terraform-Single/blob/master/main.tf](https://github.com/Nitheesh-cmd/Terraform-Single/blob/master/main.tf)

variable.tf:
[https://github.com/Nitheesh-cmd/Terraform-Single/blob/master/variable.tf](https://github.com/Nitheesh-cmd/Terraform-Single/blob/master/variable.tf)

### Expected Behavior

VM should be created and deployed

### Actual Behavior

Issue when we use vsphere 1.16 version.

<img width="512" alt="Issue_Vsphere" src="https://user-images.githubusercontent.com/50433885/74543543-8c2bd800-4f6b-11ea-848f-caee4288fdba.png">

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example: - terraform-provider-vsphere_1.16

terraform validate - successful
terraform init- successful
terraform plan- Error as in screenshot above

### Important Fact
In Vsphere version - 1.15 - All stages - init, plan & apply goes through and able to deploy
In Vsphere version - 1.16 - In stage of plan, received the above error in the screenshot

**Comment by aareet** [comment]
@Nitheesh89 can you reproduce the issue with vSphere version 1.16.1? We have resolved some permissions issues in that minor version

**Comment by Nitheesh89** [comment]
Tried with version 16.1.1. IT goes through the plan stage.
While getting same sort of error in the apply stage. Attached the snap below

Steps:
terraform validate - successful
terraform init- successful
terraform plan- successful
terraform apply- Error

![image](https://user-images.githubusercontent.com/50433885/74625577-cfa46300-5172-11ea-84f2-c9c7fe409f77.png)

**Comment by koikonom** [comment]
Hi @Nitheesh89, 

can you please check you have all the necessary permissions, as described in the Changelog for 1.16.1 ? 

```
Add storage policy to virtual_machine resource. ** Requires profile-driven storage permissions for Terraform user. (#881)```

**Comment by Nitheesh89** [comment]
> Hi @Nitheesh89,
> 
> can you please check you have all the necessary permissions, as described in the Changelog for 1.16.1 ?
> 
> ```
> Add storage policy to virtual_machine resource. ** Requires profile-driven storage permissions for Terraform user. (#881)```
> ```

Yeah definitely can check on that.. Curious on that with the same permission i could possibly apply and spin up a  machine successfully with older version(1.15)?

**Comment by koikonom** [comment]
This is a new requirement introduced by version 1.16.

**Comment by bill-rich** [comment]
Please see #974 for details on the required permissions.
