### ISSUE TITLE
Disk Size is int and only works with GBs

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform-provider-vsphere#977]
I am using vCenter for Kubernetes cluster with dynamic disk provisioning. 

Virtual machines are created with Terraform, but then K8S creates and attaches disks as it pleases - this is why we have `ignore_changes = [disk]` set for virtual machines.

Despite this setting, Terraform of course still pulls disks from vCenter API and saves them as orphaned disks in a state file.

Problem arises when someone creates a volume that has is less than 1 Gigabyte (which probably should not happen, but hey, people do different things when they use K8S cluster).

Terraform pulls this disk, sees the size of, let's say, 0.2 Gigabytes and makes it 0, then saves to statefile like this:

```
              {
                "attach": false,
                "datastore_id": "datastore-46",
                "device_address": "scsi:0:1",
                "disk_mode": "independent_persistent",
                "disk_sharing": "sharingNone",
                "eagerly_scrub": false,
                "io_limit": -1,
                "io_reservation": 0,
                "io_share_count": 1000,
                "io_share_level": "normal",
                "keep_on_remove": true,
                "key": 2001,
                "label": "orphaned_disk_0",
                "name": "",
                "path": "kubevols/kubernetes-dynamic-pvc-6111b8f7-cb22-11e9-84d9-005056a3f246.vmdk",
                "size": 0,
                "storage_policy_id": "",
                "thin_provisioned": true,
                "unit_number": 1,
                "uuid": "6000C29a-9381-30ed-ebf5-9ec8e115088e",
                "write_through": false
              }
```

There size of 0 is invalid and Terraform throws an error:

```
Error: disk.1: size for disk "orphaned_disk_0": required option not set
```

I would suggest to use megabytes so that this issue happens only when someone creates a disk of less than 1mb :-)

Relevant lines of code:

https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_disk.go#L21

https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_disk.go#L292

I would love to provide pull request, but no time as of now, so feel free to pick this one up. Change itself should be easy, but it will be a breaking change for sure.

### Terraform Version

```
Terraform v0.12.20
+ provider.vsphere v1.16.1
```
### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`
- `vsphere_virtual_disk`

### Error

```
Error: disk.1: size for disk "orphaned_disk_0": required option not set
```

### Expected Behavior

Disk size is saved in at least megabytes

### Actual Behavior

Disk size is always gigabytes

**Comment by Fodoj** [comment]
After looking into it a bit more, problem is even worse. If disk dise is 100 500mb, bug will also happen. With thin provisioned volumes this becomes a real headache.

**Comment by siwyroot** [comment]
Hello, I have faced exact issue, the only workaround I found was to add all disks to lifecycle like this, all or disk will not work.

        lifecycle {
          ignore_changes = [
            disk.0,
            disk.1,
            disk.2,
            disk.3,
            disk.4,
            disk.5,
            disk.6,
            disk.7,
            disk.8,
            disk.9,
            disk.10,
            disk.11,
            disk.12,
            disk.13,
            disk.14,
            disk.15,
            sata_controller_count,
            ide_controller_count,
          ]
        }

**Comment by noroutine** [comment]
Hit this bug as well, makes it real pain with PVC served by vSphere

Workaround worked, just in my case I still prefer to be able to resize root disk with terraform, so narrowed above a bit

```
    ignore_changes = [
      clone,
      extra_config,
      network_interface,
      datastore_id,
      datastore_cluster_id,
      # https://github.com/hashicorp/terraform-provider-vsphere/issues/977
      # disk.0,
      disk.1,
      disk.2,
      disk.3,
      disk.4,
      disk.5,
      disk.6,
      disk.7,
      disk.8,
      disk.9,
      disk.10,
      disk.11,
      disk.12,
      disk.13,
      disk.14,
      disk.15,
      sata_controller_count,
      ide_controller_count,
    ]
```

**Comment by zuzzas** [comment]
@Fodoj 
Does [this](https://github.com/hashicorp/terraform-provider-vsphere/pull/1397) fix your problem?

**Comment by arizvisa** [comment]
Just curious, is there some particular reason (technical) that `terraform-provider-vsphere` uses gigabytes instead of megabytes for the denomination of the disk size?

**Comment by tenthirtyam** [comment]
@Fodoj , 

This appears to have been addresses in #1397. Could you please confirm?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
