### ISSUE TITLE
How to use storage_policy_id ?

### ISSUE THREAD

**Issue by neogen19** [hashicorp/terraform-provider-vsphere#978]
Hello Everyone,

Need some help to understand how to use "storage_policy_id" released under version 1.16.1?
I am deploying a VM in a new datastore from a template stored in an NFS share and need to assign the default storage policy of the target datastore.

### Terraform Version

v12.20

### vSphere Provider Version

v 1.16.1

**Comment by Satak** [comment]
What I understand you can pass `storage_policy_id` to VM resource level and it's disk sub level. You can either get the UUID from vCenter and hardcode it there, or pass it as a variable. You can also compute the UUID from storage policy name that you pass to the data block documented here: https://www.terraform.io/docs/providers/vsphere/d/storage_policy.html

First define the datablock for your storage policy
```hcl
data "vsphere_storage_policy" "policy" {
  name = "policy1" // or from var: name = var.storage_policy_name
}
```

and then you can pass that to your VM resource:

```hcl
resource "vsphere_virtual_machine" "template" {
  storage_policy_id = data.vsphere_storage_policy.policy.id

  disk {
    label             = "disk0"
    size              = 50
    storage_policy_id = data.vsphere_storage_policy.policy.id
  }

}

I think this whole storage policy needs better documentation and confirmation that it really works. I for example have not make it to work in my vCenter environment with Terraform. Can we get some dev input on this?

**Comment by remoe** [comment]
Any update for this? Need to know which permission is needed on VCenter.

**Comment by bill-rich** [comment]
Hi @Satak! Sorry about the delay in responding. Can you provide more information on what isn't working for you with storage policies? Your configuration looks correct, but if it is giving you problems, I'd be happy to take a look.

**Comment by tenthirtyam** [comment]
No response from @Satak in >1 year. 

Recommend to consider an update to the `vsphere_storage_policy` with an quality example as it's rather sparse.

Ryan

cc @tenthirtyam
