### ISSUE TITLE
vMotion from one cluster/datastore to another succeeds but fails in vCenter Server with a specified parameter was not correct spec.pool

### ISSUE THREAD

**Issue by BraddMPiontek** [hashicorp/terraform-provider-vsphere#980]
Attempting to use Terraform to vmotion VMs from one Cluster and Datastore to another. terraform plan and terraform apply all look good. Terraform apply succeeds but the VM is not successfully relocated in VSphere. The message is "specified parameter was not correct spec.pool" Subsequent plans show the state with the VM is on the old cluster and datastore and applys attempt to move it again. (which makes sense as it failed in VCenter)

### Terraform Version

Terraform v0.11.10

### vSphere Provider Version

v1.16.1

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "linux_dhcp_vm" {
  provider = "vsphere.module_vm"

  # Number of VMs
  # Checking vm_os_family to see if we should build that kind of VM
  count = "${var.vm_os_family == "linux" && var.static == "false" ? var.vm_count : 0}"

  # Basics
  name              = "${local.vm_host_base_name}${format("%01s",var.application_leg)}${format("%02d", count.index + 1)}"
  resource_pool_id  = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id      = "${data.vsphere_datastore.datastore.id}"
  folder            = "${vsphere_folder.application_vms.path}"
  annotation        = "${var.application_name}-${var.application_environment}"
  custom_attributes = "${zipmap(local.custom_attribute_keys, local.custom_attribute_vals)}"

  # CPU
  num_cpus             = "${var.vm_num_cpus}"
  num_cores_per_socket = "${var.vm_num_cores_per_socket}"
  cpu_hot_add_enabled  = true

  # Memory
  memory                 = "${var.vm_memory}"
  memory_hot_add_enabled = true

  # Storage
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  disk {
    # /dev/sda
    label       = "disk0"
    size        = "${var.vm_disk0_size == "DERIVED_DEFAULT" ? lookup(local.vm_os_family_defaults[var.vm_os_family], "disk0_size") : var.vm_disk0_size}"
    unit_number = 0
  }

  disk {
    # /dev/sdb
    label       = "disk1"
    size        = "${var.vm_disk1_size == "DERIVED_DEFAULT" ? lookup(local.vm_os_family_defaults[var.vm_os_family], "disk1_size") : var.vm_disk1_size}"
    unit_number = 1
  }

  # Network
  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  #
  # Clone configurations
  #
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  clone {
    # Longer waits for VM builds during heavy periods
    timeout = 120

    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      # This needs to be initialized to use DHCP
      network_interface {}

      linux_options {
        host_name = "${local.vm_host_base_name}${format("%01s",var.application_leg)}${format("%02d", count.index + 1)}"
        domain    = "${var.vm_domain == "DERIVED_DEFAULT" ? lookup(local.vm_domain_defaults,"${var.vm_os_family}-${var.vsphere_environment}") : var.vm_domain}"
        time_zone = "${var.vm_time_zone == "DERIVED_DEFAULT" ? lookup(local.vm_os_family_defaults[var.vm_os_family], "timezone") : var.vm_time_zone}"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/piontekdd/0b32d7cb9cb8630bc53ce6dacad6a565.js

### Panic Output

N/A

### Expected Behavior

Successfully relocated the VM to the new cluster and datastore.

### Actual Behavior

Terraform says the apply was successful but the VM remains on the old cluster and datastore.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

**Comment by koikonom** [comment]
Hi @piontekdd, thanks for taking the time to file this issue. 

I noticed the VM you're trying to migrate has two disks. Out of curiosity, can you confirm you're also seeing the same issue with VMs that have a single disk?

Also would it be possible to run the the `apply` operation again, but this time set the `TF_LOG` environment variable to `DEBUG` (like `TF_LOG=DEBUG terraform apply <planfile>`) and post the debug output to another github gist?

**Comment by piontekdd** [comment]
We do not have any VMs with single disks nor is our Terraform coded in a manner where I can easily create such a VM.

**Comment by tenthirtyam** [comment]
To confirm, this issue is seen when moving between clusters, not just between datastores, correct?

**Ryan Johnson**
Staff II Solutions Architect, VMware Inc.

**Comment by sonman** [comment]
Also happens in our lab. Does a workaround exists ?

**Comment by sonman** [comment]
I tested again with vSphere Provider 2.4.3. I can not reproduce the issue anymore. Yay

**Comment by quantm241** [comment]
Hello, I'm also facing this issue when migrating vSphere VM between host
```
Terraform v1.6.0
vSphere provider v2.5.0
```

I'd tried migrating with govc client which also based on govmomi and got these results:
- govc vm.migrate -host <hostname> -ds <datastore> vm ✅ 
- govc vm.migrate -host <hostname> -pool <hostname>/Resources  -ds <datastore> vm ✅ 
- govc vm.migrate -pool <hostname>/Resources -ds <datastore> vm ❌ 

Digging to terraform-vsphere-provider code and found this line:
https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/resource_vsphere_virtual_machine.go#L638

I have built a local provider version with the above line commented out and my vm could migrate successfully.
Please take a look.

**Comment by cuongdevzinza** [comment]
Hello, I'm also facing this issue when migrating vSphere VM between host

```
Terraform v1.6.0
vSphere provider v2.5.0

```
I'd tried migrating with govc client which also based on govmomi and got these results:

govc vm.migrate -host -ds vm ✅
govc vm.migrate -host -pool /Resources -ds vm ✅
govc vm.migrate -pool /Resources -ds vm ❌
Digging to terraform-vsphere-provider code and found this line:
https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/resource_vsphere_virtual_machine.go#L638

I have built a local provider version with the above line commented out and my vm could migrate successfully.
Please take a look.

**Comment by burnsjared0415** [comment]
Is this still a Issue? Or can it be closed based on newer Terraform version?
