### ISSUE TITLE
Add resource for VM Storage Policy for tag based placement rules

### ISSUE THREAD

**Issue by nvpnathan** [hashicorp/terraform-provider-vsphere#993]
Hi there,

Working to automate the requirements around VM Storage Polices based on tags and tag category for enabling Workload Management. 

### Terraform Version
Terraform v0.12.23
+ provider.vsphere v1.16.1

### vSphere Provider Version
provider.vsphere 1.16.1

### Affected Resource(s)
vsphere_tag_category
vsphere_tag

**Comment by sumitAgrawal007** [comment]
Hi @nvpnathan ,
Can you please provide some more details on what is the improvement here. I understand from the description that the requirement is to add a resource for VM storage policy. 
Can you please elaborate on what is expected from this resource.

Thanks.
