### ISSUE TITLE
Terraform plan/apply keeps changing storage_policy_id

### ISSUE THREAD

**Issue by gchek** [hashicorp/terraform-provider-vsphere#995]
### Terraform Version
0.12.23

### vSphere Provider Version
1.16.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "Blue" {
  count = var.demo_count
  name   = "Blue-VM-${count.index + 1}"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = "Workloads"


  num_cpus = 2
  memory   = 1024
  guest_id = "other26xLinuxGuest"

  network_interface {
    network_id = data.vsphere_network.network12.id
  }

  disk {
    label = "disk0"
    size  = 20
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.demo.id
  }
}
```
### Expected Behavior
Once the VMs are created, a subsequent `terraform apply` should not modify anything.
`storage_policy_id` keeps changing

### Actual Behavior

terraform apply wants to modify 
`storage_policy_id = "aa6d5a82-1c88-45da-85d3-3d74b91a5bad" -> null`

### Steps to Reproduce

1. `terraform plan or apply`

**Comment by pvlltvk** [comment]
Having the same issue, i had to rollback to the previous version (1.15.0) because of this.

**Comment by gchek** [comment]
good tip @pvlltvk. my version.tf is now
`terraform {
  required_version = ">= 0.12"
  required_providers {vsphere = "= 1.15"}
}`

Thanks

**Comment by FlorianLaunay** [comment]
@pvlltvk thanks for the tip !

**Comment by vterdunov** [comment]
@pvlltvk how you managed with? These attributes came from newer version of the provider.
```
unsupported attribute "distributed_virtual_switch_uuid"
unsupported attribute "ovf_network_map"
```

**Comment by rothman857** [comment]
Any updates here?  I can't use an up-to-date vsphere provider until this is fixed.

Terraform v0.12.25
+ provider.vsphere v1.18.2

**Comment by KevDBG** [comment]
Hello,

I don't have the problem in v1.18.3

Maybe fix here -> https://github.com/terraform-providers/terraform-provider-vsphere/commit/4971a0d855284d23c5d932d0667aa6383fdca103

**Comment by gchek** [comment]
Not fixed. After VM is created, if i do a 'terraform apply' again NOTHING should change but provider keeps changing storage policy

**Comment by LennertMertens** [comment]
I do have the same issue when I apply more than once.

**Comment by gchek** [comment]
`Terraform v0.12.29
+ provider.nsxt v2.1.1
+ provider.vsphere v1.21.1
`
Problem still here. 
no change in code - doing terraform apply twice will change the storage policy and toggle VMs state (off-on)

**Comment by gchek** [comment]
Terraform v0.12.29
+ provider.nsxt v2.1.1
+ provider.vsphere v1.20.0

vSphere provider is not IDEMPOTENT since 1.15
after deploying VMs without any issues, launching a `terraform apply` again keeps changing the storage policy.  
    - storage_policy_id                       = "aa6d5a82-1c88-45da-85d3-3d74b91a5bad" -> null
This shuts down all VMs deployed by Terraform !!

please have a look at it. It's been 5 months !!!

**Comment by isometry** [comment]
Expanding upon the initial bug report, this issue manifests when deploying VMs to datastores that implement a default storage policy (i.e. VVols and vSAN).

A non-scalable workaround is to ignore changes to the `storage_policy_id` attributes:

```terraform
resource vsphere_virtual_machine example {
  # …elided…

  lifecycle {
    ignore_changes = [storage_policy_id, disk.0.storage_policy_id]
  }
}
```

**Comment by bill-rich** [comment]
Thanks for the reports on this everybody. I'll be looking into this soon. @sumitAgrawal007 Any ideas?
