### ISSUE TITLE
Add support to create a `vsphere_virtual_machine` without powering it on

### ISSUE THREAD

**Issue by mooperd** [hashicorp/terraform-provider-vsphere#999]
Hi there - I need to clone some VMs into a folder but leave them powered off - is this possible with terraform? I cannot find a way of controlling the power state with the documentation. 

Thanks,

Andrew

**Comment by eizedev** [comment]
As mentioned in #916 I also need the ability to keep VMs powered off until they are needed.
Therefore it would be great if it would be possible to change the power state of a VM (off to on, on to off...).
With 2.1.1 (only) the check for the power state was implemented.
@tenthirtyam Would it be possible to implement this?

As mentioned in the documentation and #1407 the powerstate will only be exported but cannot be changed at the moment:

[power_state](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#power_state) - A computed value for the current power state of the virtual machine. One of `on`, `off`, or `suspended`.

Thanks

**Comment by tenthirtyam** [comment]
Hi @eizedev,

It was decided not to implement control over the power operations in #1394.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
After previous deliberations with the maintainers, it was decided that at this time this capability would not be added to the provider as it tends to blur the lines between [mutable vs. immutable infrastructure](https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure).

If you take a look back to #327, the same enhancement was requested and the maintainer at the time [shared the reasoning](https://github.com/hashicorp/terraform-provider-vsphere/issues/327#issuecomment-352559036) at the time for not including the capability. 

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
